### ISSUE TITLE
· (middle dot) doesn’t become \cdot

### ISSUE THREAD

**Issue by flying-sheep** [arnog/mathlive#10]
Hi, awesome project, thanks for making it!

My keyboard has a way to input [“·” (Middle dot)](http://graphemica.com/·), but not [“⋅” (Dot operator)](http://graphemica.com/⋅).

It would be great if both could be converted to `\cdot`.

**Comment by arnog** [comment]
Thanks! Fixed now. For my own curiosity, what kind of keyboard is it?

**Comment by flying-sheep** [comment]
thank you!

i should have said “input method” – it’s a regular keyboard, but under linux, the default keyboard layout has the ellipsis and mathematical operators on <kbd>AltGr</kbd>[<kbd>Shift</kbd>]<kbd>,</kbd> and <kbd>AltGr</kbd>[<kbd>Shift</kbd>]<kbd>.</kbd>:

<span></span> | – | <kbd>Shift</kbd>
--|--|--
<kbd>,</kbd> | · | ×
<kbd>.</kbd> | … | ÷
