### ISSUE TITLE
Definite Integral limits in wrong order in LaTeX

### ISSUE THREAD

**Issue by phcreery** [arnog/mathlive#1000]
## Description

SubSup (Subscript Superscript) being parsed in the wrong order. The definite integral is an example.

![image](https://user-images.githubusercontent.com/44987569/121441373-47416700-c94f-11eb-8b21-edd7eade209a.png)
http://mathlive.io/examples/latex/index.html

Some LaTeX parsers are not able to understand this orientation.

### Actual Behavior

```
\int ^{\infty}_0
```

### Expected Behavior
Subscript then Superscript
```
\int_0^{\infinty}
```

Like that found on these resources:
https://www.onemathematicalcat.org/MathJaxDocumentation/TeXSyntax.htm
http://math.hws.edu/gassert/LaTeX_Guide_Title.pdf
https://latex.wikia.org/wiki/Int_(LaTeX_symbol)

### Environment

MathLive 0.68.1
Windows 10
Chrome (latest as of date)

**Comment by phcreery** [comment]
I tried attempting to resolve this myself, but the codebase was much too intimidating. Especially with my lack of TypeScript knowledge.

**Comment by arnog** [comment]
Thanks for pointing this out!

**Comment by phcreery** [comment]
I am impressed with the sheer speed of resolving this. 👏
