### ISSUE TITLE
bigger version parentheses do not work

### ISSUE THREAD

**Issue by faxinwang** [arnog/mathlive#1015]
## Description

```
\bigl  \Bigl \biggl \Biggl  \bigr  \Bigr

\biggr \Biggr

\bigm \Bigm \biggm \Biggm

\big  \Big  \bigg  \Bigg
```
Those bigger version parentheses do not work. The parentheses donot appear in the mathlive editor when those command typed in the editor. Is this a bug?

**Comment by arnog** [comment]
It depends what you typed. If you just type `\Bigl` for example, nothing will be rendered. The command should be followed by a delimiter, for example `\Bigl(` or `\Bigl\lbrack`. When I do this, it seems to work for me. Let me know if this answers your question.

**Comment by faxinwang** [comment]
Oh it's my fault, It works fines. Thanks.
