### ISSUE TITLE
Clearing style

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#1016]
## Description

Mathlive has a quite convenient `applyStyle` function. I was wondering if an 'inverse' of that would be something that mathlive could have, something like `clearStyle({ color: true })`. This would make it possible to implement a decent styling function in a mathematics editor

![image](https://user-images.githubusercontent.com/10220080/122213730-8a4c8e80-cea9-11eb-943a-3445f6198d33.png)

### Environment

**MathLive version** 0.69.3 

**Operating System** Windows 10

**Browser** Firefox

**Comment by stefnotch** [comment]
It turns out that `applyStyle({ color: "" })` effectively clears the color. That works for me and as such, feel free to close this issue.

**Comment by arnog** [comment]
I believe setting it to 'none' should also work. Let's keep this issue open to remind me to document this somewhere...

**Comment by arnog** [comment]
Added to doc.
