### ISSUE TITLE
synhesized spoken math doesn't always quote single letter variables

### ISSUE THREAD

**Issue by zoranpopovic** [arnog/mathlive#1018]
## Description

ideally all math variables should be quoted, to enable right pronunciation.  however, `x \cdot a` generates `'X' times a` instead of `'X' times 'A'`

## Steps to Reproduce

using all default settings for speech, convertLatexToSpeakableText or executeCommand "speak" produce `'X' times a`  which makes 'a' almost unaudible.

### Environment

**MathLive version**
latest

**Operating System** 
windows

**Browser** 
any

**Comment by arnog** [comment]
Fixed now.
