### ISSUE TITLE
\ne ,\neq and \not= are not working.

### ISSUE THREAD

**Issue by faxinwang** [arnog/mathlive#1024]
## Description

\ne ,\neq and \not= are not working. 

input: A\ne B
output: AB
expected:A\ne B

input: A\neq B
output: AB
expected: A\neq B

input A\not=B
output: A=B
expected:A\not= B

Note that the editor dispalying the right content, only the output latex value is not as expected.

### Environment

**MathLive version** 0.69.3

**Operating System** [Windows 10]

**Browser** [ Chrome]

**Comment by stefnotch** [comment]
Additional Info:
If one types `A \ne B`, the copied MathJson ends up being: `["Multiply","A","B"]`. This seems to be related to the issue

**Comment by arnog** [comment]
Ah, yes, that's probably the problem...

**Comment by faxinwang** [comment]
Do you mean I just need to upgrade mathlive to 0.69.4 ?

I have upgraded to 0.69.4, but the problem still exists.

**Comment by faxinwang** [comment]
Hi, is there any progress on this problem? I have tried typing A \ne B on this page(https://cortexjs.io/mathlive/demo/), the output is still AB。

**Comment by arnog** [comment]
I believe this was a duplicate of #1222, which is now fixed.
