### ISSUE TITLE
Removing math-field from page brokes elements already rendered by renderMathInElement

### ISSUE THREAD

**Issue by parus95** [arnog/mathlive#1035]
## Description

Removing `math-field` from page brokes elements rendered by renderMathInElement

Can be reproduced with this code:
``` html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Mathlive test</title>
        <style>
            body {
                max-width: 800px;
                margin: 20px auto;
            }
            math-field {
                border: 1px solid;
            }
        </style>
    </head>
    <body>
        <script src="https://unpkg.com/mathlive/dist/mathlive.js"></script>

        <script>
            function test() {
                var paragraph = document.getElementById('el');
                var mathfield = new MathLive.MathfieldElement();
                mathfield.id = 'me';
                paragraph.appendChild(mathfield);

                var formulaSpan = document.createElement('span');
                formulaSpan.innerHTML =
                    '<script type="math/tex">f(x)=5*x<' + '/script>';
                MathLive.renderMathInElement(formulaSpan);
                paragraph.appendChild(formulaSpan);
                setTimeout(() => {
                    //  after it formulaSpan is broken
                    paragraph.removeChild(mathfield);
                }, 1000);
            }
        </script>

        <button onclick="test()">Test</button>
        <p id="el"></p>
    </body>
</html>

```

![image](https://user-images.githubusercontent.com/632680/122773772-4c88a500-d2b1-11eb-902a-cd72c224ab7e.png)

## Steps to Reproduce

1. Add math-field to page
2. Call renderMathInElement for page element
3. Remove math-field from page

### Actual Behavior

Elements rendered by renderMathInElement broken

### Expected Behavior

Elements rendered by renderMathInElement not broken

### Possible solution

before https://github.com/arnog/mathlive/blob/aa079aeda566c74508ed031c0a38543ddc1599cc/src/common/stylesheet.ts#L39-L55
add lines:
``` javascript
      if (root !== document.head) {
          return {
              release: () => {}
          }
      }
```
because release is needed (and works) only to globally added stylesheets. Mathfield(1) uses local stylesheet(2), but releases global(3):
![image](https://user-images.githubusercontent.com/632680/122775847-3a0f6b00-d2b3-11eb-9cc5-1f869b65961a.png)

### Environment

**MathLive version** 0.69.3

**Operating System** Windows 10

**Browser** Google Chrome

**Comment by brianlukoff** [comment]
I'm running into the same issue -- has anyone found a workaround?

**Comment by arnog** [comment]
The workaround is to explicitly inject the necessary stylesheet:

```html
    <link rel="stylesheet" href="https://unpkg.com/mathlive/dist/mathlive-static.css" />
```

**Comment by arnog** [comment]
A complete fix is to change the implementation of `release()` from:
```ts
    release: (): void => {
      const element_ = document.head.querySelector<HTMLElement>(
        `style[data-id="${id}"]`
      );
```
to
```
    release: (): void => {
      const element_ = (root as HTMLElement).querySelector<HTMLElement>(
        `style[data-id="${id}"]`
      );
```

**Comment by brianlukoff** [comment]
Thanks @arnog! Would you be able to push this in a release to npm?

**Comment by arnog** [comment]
@brianlukoff yes, but give me a few days: I want to include more fixes in the release.

**Comment by brianlukoff** [comment]
Great -- thanks @arnog!

**Comment by arnog** [comment]
MathLive 0.87.0 has the fix

**Comment by brianlukoff** [comment]
Thanks!
