### ISSUE TITLE
Typing / on numpad does not trigger fraction input

### ISSUE THREAD

**Issue by nickgravelyn** [arnog/mathlive#104]
## Prerequisites

* [x] Did you check the [issue tracker](https://github.com/arnog/mathlive/issues) to see if this issue has already been reported?

For more information, see the `CONTRIBUTING` guide.

## Description
Typing / on the question mark key triggers a fraction whereas the numpad one does not.

## Steps to Reproduce
1. Go to http://mathlive.io/0.24f/index.html
2. Type 3/5 using the /? key.
3. Notice you get a fraction.
4. Delete everything and type 3/5 using the / key on the numpad.
5. Notice you don't get a fraction.

### Actual behavior
Typing / on the numpad does not give me a fraction.

### Expected Behavior 
I expect that typing / works consistently regardless of which key entered it. People using a number pad should have the same experience as those typing on non-numpads.

### Environment
**Operating System** Windows 10

**Browser** Firefox Developer Edition

**URL** http://mathlive.io/0.24f/index.html

**Comment by arnog** [comment]
I suspect this is a simple fix. The keycode for the numpad keys is either ignored or mapped incorrectly somewhere in editor-keyboard.js.
