### ISSUE TITLE
Deleting set brackets leads to \lbrace

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#1055]
## Description

Deleting a bracket from a set `{a}` results in the text `\lbracea`

## Steps to Reproduce

Can be reproduced on https://cortexjs.io/mathlive/

1. Type `{a}`
2. Hit the `Backspace` key

### Actual Behavior

![image](https://user-images.githubusercontent.com/10220080/123539839-f5188800-d73b-11eb-8467-829e725fd079.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/10220080/123539848-fcd82c80-d73b-11eb-87f4-17aec57fe718.png)
### Environment

**MathLive version** v0.69.4

**Operating System** Windows 10

**Browser** Firefox

**Comment by arnog** [comment]
This is working correctly now.
