### ISSUE TITLE
Font issue with Firefox?

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#11]
## Description
The attached page renders the sqrts and big parens fine in Chrome but has problems in Firefox V54.0.1

Here is a snapshot of a test page in Firefox:
![image](https://user-images.githubusercontent.com/1545836/28335788-6b734a0a-6bb4-11e7-8ec1-9f3afb409d0f.png)

Same page in Chrome:
![image](https://user-images.githubusercontent.com/1545836/28335756-4cb60ab2-6bb4-11e7-9fa3-2f1e0ffa3a98.png)

Here is the test page:
```
<!DOCTYPE html><html lang="en-US">
<head>
    <meta charset="utf-8">
    <title>MathLive Sample</title>

    <link rel="stylesheet" href="../dist/mathlive.core.css">
    <link rel="stylesheet" href="../dist/mathlive.css">
    <script src="../dist/mathlive.js"></script>
</head>
<body>
<p> Here a test of font rendering with sqrts and large parens: <br>
    $$\Biggl(\sqrt{ \sqrt{ \sqrt{2} } } \Biggr)$$<br>
In Firefox, they don't display well, but do display fine in Chrome.
</p>

<script>
	MathLive.renderMathInDocument();
</script>
</body>
</html>
```

## Same problem on mathlive.io?
I see the some issues for the mathlive reference page in Firefox that may be font related:
![image](https://user-images.githubusercontent.com/1545836/28336017-3cc1fe4e-6bb5-11e7-93f3-6403253d1298.png)

**Comment by arnog** [comment]
I can't reproduce this. From the screenshot, it would appear that the font is not loaded at all.

Try this:
1. In Firefox, bring up the network panel by typing ctrl+shift+Q or menu > Developer > Network
2. Click the gear icon (left of the close panel X)
3. In Advanced Settings, turn on "Disable HTTP Cache (when toolbox is open)"
4. Click on the "Networking" tab
5. Reload the page

Watch the network resources being pulled and the status code. In particular you should have 200 status codes for the font files KaTeX_Main-regular.woff2

![screenshot 2017-07-21 10 59 57](https://user-images.githubusercontent.com/760798/28476156-d1798a3e-6e03-11e7-9ec7-87b777e816bb.png)

**Comment by NSoiffer** [comment]
Here's a screen shot:

![image](https://user-images.githubusercontent.com/1545836/28592055-b02023fc-713c-11e7-9bdf-213ac64dbabe.png)

All the status codes look good, but I still get the "undefined"s. The one "interesting" thing I see is that the size4 font (the one I think is the problem), just says "font", not "JS Font" next to it.

**Comment by NSoiffer** [comment]
Probably a different issue, but maybe related, so I'll comment on it here...

On a local file and local setup, I noticed in my console log lots of font errors like this for Firefox:
> downloadable font: download failed (font-family: "KaTeX_Main" style:normal weight:normal stretch:normal src index:0): bad URI or cross-site access not allowed source: file:///C:/Dev/mathlive/dist/fonts/KaTeX_Main-Regular.woff2

The path and font exist on my machine.

**Comment by arnog** [comment]
Assuming this is a stale issue. Closing.

**Comment by NSoiffer** [comment]
I checked and it is fixed for me.
