### ISSUE TITLE
Virtual Keyboard doesn't appear on Firefox or Microsoft Edge

### ISSUE THREAD

**Issue by LinGrin** [arnog/mathlive#110]
## Prerequisites

* [x] Did you check the [issue tracker](https://github.com/arnog/mathlive/issues) to see if this issue has already been reported?

For more information, see the `CONTRIBUTING` guide.

## Description
Virtual Keyboard doesn't open on Firefox or Microsoft Edge

## Steps to Reproduce
1. For example go to: http://mathlive.io/0.24f/index.html
2. Try to toggle open the virtual keyboard in Firefox or Edge

### Actual behavior
 the keyboard doesn't appear, instead there's thin gray bar at the bottom of the screen.
There are no error messages

### Expected Behavior 
The keyboard should toggle open just like it does in chrome or safari

### Environment
**Operating System** macOS, Windows 10 (via browserstack)

**Browser** Firefox 62.0, Edge 17 (via browserstack)

**URL** http://mathlive.io/0.24f/index.html

**Comment by arnog** [comment]
Thanks for reporting this issue.
A closing </svg> tag was missing, and previous versions of Firefox (and current versions of Chrome and Safari) were more stringent. Fixed now.
