### ISSUE TITLE
Not reading TeX notation for both sub/supscript properly

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#111]
## Description
The TeX notation for including both sub and super scripts is `x_i^n` or `x^n_i`. MathLive will use the later when generating TeX from an expression, but doesn't read it properly, resulting in super/supscript added to the whole expression
## Steps to Reproduce
To get the right notation to show up, I need to do the following when typing to MathLive:
1. Type `x_i`
2. Select the expression (with the mouse, shift-arrow doesn't work, but that's a different issue)
3. Type `^n`

### Actual behavior
Now the notation looks right as pictured below:
![image](https://user-images.githubusercontent.com/1545836/45973928-ae2e5e80-bff4-11e8-8b66-6a30af2751bc.png)

If I copy it out, I get `x^n_i`. The result of pasting it in is shown below:
![image](https://user-images.githubusercontent.com/1545836/45974070-1f6e1180-bff5-11e8-8ea3-111e26adc948.png)

Copying that back out is `x^n_i` (i.e, the same as before).

**Comment by rpdiss** [comment]
@arnog any progress on this seems to be high priority i can be wrong ; p
