### ISSUE TITLE
Clicking on formula when virtual keyboard is displayed closes the keyboard

### ISSUE THREAD

**Issue by prem17299** [arnog/mathlive#1115]
## Description
I want the keyboard to stay on the screen when I click anywhere in the math field area but It should disappear if clicked anywhere else . Now generally the focus property of the math field stays attached  before toggling the keyboard but once it gets toggled it loses its own focus property  depending on the keyboard .If clicked on the keyboard it stays otherwise it loses its focus . Ideally the keyboard should not disappear if clicked in the math field area .

In this demo video you can see if we go to cortex.js website and in demo section i toggle the keyboard ,it is focussed but when i click on the mathfield ,keyboard and mathfield both losses its focus and keyboard disappers which should nt be the case as when click on the mathfield area keyboard should stay on screen 

https://user-images.githubusercontent.com/55232029/128643872-259b4907-9791-4608-8e10-da1d6753bae5.mp4

## Steps to Reproduce

1. visit https://cortexjs.io/mathlive/demo/" 
2. Click the Virtual Keyboard button"
3. click on the Mathfield area 

### Actual Behavior

keyboard disapperas after clicking on mathfield area.

### Expected Behavior

keyboard show stay toggled and on while clicking inside the mathfield and only disappear when clicked outside the mathfield and keyboard area.

### Environment

**MathLive version** 0.69.4

**Operating System** macOS Big Sur version 11.3.1

**Browser**  Chrome

**Comment by prem17299** [comment]
by what time can i expect this bug to be fix ? actually i want to use the keyboard for my project in the startup @arnog  ?

**Comment by arnog** [comment]
@prem17299 hard to say. I'll have a look at it when I get some time. However, anyone is welcome to submit a Pull Request with a fix. Let me know if you want to work on it.

**Comment by arnog** [comment]
It seems to work correctly now.
