### ISSUE TITLE
Allow images in math expressions

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#112]
## Description
Math sometimes has images as part of a problem description or solution. It was be useful if mathlive allowed someone to insert (and resize) an image.

Given that images are fixed sizes boxes and are supported in browsers, it seems like this would not be too hard to support (famous last words :-).

**Comment by Alzy** [comment]
I would like to argue that handling images is beyond the scope of what a math editor like mathlive should do. While handling images is something you'd normally do in a rich text editor environment, a component like mathlive should stick to handling math expressions. Images, unlike symbols, are never used inside of math expressions.

**Comment by NSoiffer** [comment]
I admit it is not common to use images directly as part of an expression, but that does happen. E.g., from a [Wikipedia page on knot theory](https://en.wikipedia.org/wiki/Knot_theory):
![image](https://user-images.githubusercontent.com/1545836/46555343-d4c38380-c897-11e8-821f-9fc91bece92a.png)


The more common case is when describing a problem, figures show up. mathlive allows one to mix text and math (although the UI is kind of clunky), and as part of that, including images would be useful. For example, one might have something like 'In this figure [image], f(x) is bounded by [math] and has a minimum when x=...'.

**Comment by arnog** [comment]
It might make sense to implement the `\inputgraphics` command: https://en.wikibooks.org/wiki/LaTeX/Importing_Graphics and https://www.kwasan.kyoto-u.ac.jp/solarb6/usinggraphicx.pdf

**Comment by SushantGautam** [comment]
> It might make sense to implement the `\inputgraphics` command: https://en.wikibooks.org/wiki/LaTeX/Importing_Graphics and https://www.kwasan.kyoto-u.ac.jp/solarb6/usinggraphicx.pdf

Although, handling images is beyond the scope of a math editor like MathLive, I believe this will be a valuable addition to let a user add graphics with \inputgraphics. It could be helpful to insert symbols/ strange formulas that LATEX doesn't support natively.

**Comment by arnog** [comment]
No additional interest expressed in a few years. Closing.
