### ISSUE TITLE
onCommit hook fails after moving mathfield

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#1120]
## Description
The `onCommit` hook stops working after moving the mathfield using `.appendChild`. This is probably because `.appendChild` first *removes* an element and then adds it again.

## Steps to Reproduce
1. Use the following script
2. Open the developer tools (browser console)
3. Click into the mathfield and hit `Enter`. Notice how something gets logged in the browser console
4. Click the `test` button, which moves the mathfield
3. Click into the mathfield and hit `Enter`. Nothing will get logged in the browser console.

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Mathlive test</title>
        <style>
            body {
                max-width: 800px;
                margin: 20px auto;
            }
            math-field {
                border: 1px solid;
            }
        </style>
    </head>
    <body>
        <script src="https://unpkg.com/mathlive/dist/mathlive.js"></script>


        <button onclick="test()">Test</button>
        <div id="el"></div>
		separator
        <div id="el2"></div>
		
		<script>
			var paragraph = document.getElementById('el');
			var mathfield = new MathLive.MathfieldElement({
			  onMoveOutOf: (mathfield, direction) => {
				console.log("move out")
				return false
			  },
			  onTabOutOf: (mathfield, direction) => {
				console.log("tab out")
				return true
			  },
			  onCommit: (mathfield) => {
				console.log("commit")
				mathfield.blur?.()
			  },
		  });
			mathfield.id = 'me';
			mathfield.value = "cat";
			paragraph.appendChild(mathfield);
			
			// Move the mathfield
			function test() {
				var paragraph2 = document.getElementById('el2');
				paragraph2.appendChild(mathfield);
				
			}
        </script>
    </body>
</html>

```
### Actual Behavior

`onCommit` hook does not get called anymore

### Expected Behavior

I expected the Mathfield to continue working

### Environment

**MathLive version** v0.69.5

**Operating System** Windows 10

**Browser** Firefox 90

**Comment by arnog** [comment]
This is fixed now. However, I would recommend using events (i.e. `addEventListener`) rather than the `onCommit`, etc.. hooks.
