### ISSUE TITLE
[Question] How to always show keyboard?

### ISSUE THREAD

**Issue by doiya46** [arnog/mathlive#1121]
Some time we need to debug, for example: Change some css of layout when customize keyboard.

How can I do that?

**Comment by arnog** [comment]
You can try to trap the blur event and cancel it.

**Comment by arnog** [comment]
You can now set the `virtualKeyboardMode` to `"off"` and control the keyboard programmatically with `mf.virtualKeyboardState = "visible"`  and `mf.virtualKeyboardState = "hidden"`
