### ISSUE TITLE
How to not smart to convert to symbols

### ISSUE THREAD

**Issue by li741938507** [arnog/mathlive#1122]
when I enter ‘in’,it always change to '∈'.How to ban the situation?Thank you.

**Comment by arnog** [comment]
See "Inline Shortcuts" in https://cortexjs.io/mathlive/guides/shortcuts/

**Comment by li741938507** [comment]
How to use undo?Thank you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arnog/mathlive"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 下午2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arnog/mathlive] How to not smart to convert to symbols (#1122)





 
See "Inline Shortcuts" in https://cortexjs.io/mathlive/guides/shortcuts/
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
