### ISSUE TITLE
[high priority] module can not use at Vue cli (vue 2.x)

### ISSUE THREAD

**Issue by niceplugin** [arnog/mathlive#1123]
## Description

[Description of the bug or feature.]

Last version 0.69.5 doesn't work with vue cli (vue 2.x).
An error occurs when importing a module.
In version 0.69.4 it works fine.

[Include screenshots, screen recordings, code fragments or CodePen if
applicable]

```
import * as MathLive from "mathlive/dist/mathlive.min.mjs"
import VueMathfield from "mathlive/dist/vue-mathlive.mjs"
Vue.use(VueMathfield, MathLive)
```

```
npm run serve
```

**Comment by arnog** [comment]
`vue-cli` does not support optional chaining (see  https://github.com/vuejs/vue-loader/issues/1697) There are workarounds for  this, but debugging and fixing this is too difficult for many users.  Therefore, sadly, the workaround is to roll back emitting code including optional  chaining, despite the fact it's supported in every targeted browser, until the  `vue` toolchain gets its act together. To be clear MathLive does not use or  depend on `Vue`, but some users are integrating MathLive in projects that do  use it, and this is sufficient to break MathLive.
