### ISSUE TITLE
what does the 'undo' mean?

### ISSUE THREAD

**Issue by li741938507** [arnog/mathlive#1124]
![1628666887(1)](https://user-images.githubusercontent.com/40060960/128988012-3e227e1f-9e84-40ed-b83e-3c901b9fb451.png)

**Comment by arnog** [comment]
Press command/control + Z.

**Comment by li741938507** [comment]
> Press command/control + Z.

It's too much trouble.How to revert to all the raw input?

**Comment by li741938507** [comment]
> If you don't want shortcuts, use `mf.setOptions({ inlineShortcuts:{} })`.

It doesn't work

**Comment by li741938507** [comment]
But it works. `mf.setOptions({
        inlineShortcuts: {
          in: {
            mode: 'math',
            value: 'in',
          },
        },
      });` What's the reason?

**Comment by arnog** [comment]
Ah. It turns out there is a bug and the default inlineshorcuts are used even if the `inlineShortcuts` option is set to empty.

**Comment by li741938507** [comment]
> Ah. It turns out there is a bug and the default inline shorcuts are used even if the `inlineShortcuts` option is set to empty.

Yep.I use ` inline-shortcut-timeout="1"`.It works.

**Comment by li741938507** [comment]
> Ah. It turns out there is a bug and the default inline shorcuts are used even if the `inlineShortcuts` option is set to empty.

Yep.I use` inline-shortcut-timeout="1"`.It works.

**Comment by li741938507** [comment]
> Ah. It turns out there is a bug and the default inline shorcuts are used even if the `inlineShortcuts` option is set to empty.

Yep.So I use `inline-shortcut-timeout="1"`. It works.
