### ISSUE TITLE
No space character when pressing space bar in text mode (only on macOS)

### ISSUE THREAD

**Issue by ashayp22** [arnog/mathlive#1126]
## Description

While in text mode, pressing space bar with your actual keyboard doesn't add anything to the math field. 

This only seems to happen on macOS with an actual keyboard. On Windows, it added an actual space. Using the virtual keyboard on macOS also adds a space while in text mode.

## Steps to Reproduce

1. Switch the math field to text mode (I did this by setting mathfield.mode = "text").
2. Press space bar

### Actual Behavior

Nothing happens. No errors in the console as well.

### Expected Behavior

A space character should have been added.

### Environment

**MathLive version**: 0.69.5 

**Operating System** macOS, Big Sur

**Browser**: Safari and Google Chrome

**Comment by arnog** [comment]
I can't reproduce this. Could there be something else in your project configuration that's capturing the spacebar?

**Comment by ashayp22** [comment]
Yup, there was something capturing the spacebar. For space key presses on the math field, I was doing "e.preventDefault()." This prevented the math field from adding the space character.
