### ISSUE TITLE
Contents of curly brackets wind up outside it

### ISSUE THREAD

**Issue by Koiane** [arnog/mathlive#1137]
## Description
When typing in curly brackets, the contents is placed outside rather than inside it. 

![image](https://user-images.githubusercontent.com/23076893/129695407-f543d412-c5f4-4e43-9665-7875ee3302f8.png)

## To reproduce:
1. Open https://cortexjs.io/mathlive/demo/
2. Remove everything from the first box.
3. Type "{", "1", "}"

## Actual behavior:
See picture above. "{}1" in the first box, "\left\lbrace\right\rbrace1" in the second. 

## Expected behavior: 
"{1}" in the first box, "\left\lbrace 1\right\rbrace" in the second. 

### Environment
**MathLive version:** The current version on https://cortexjs.io/mathlive/demo/, but the issue is also present in our own modified version of MathLive based on 0.69.4
**Operating System:** Ubuntu 18.04.5 LTS 
**Browser:** Tested with Firefox 91.0 (64-bit) and Chrome Version 92.0.4515.131 (Official Build) (64-bit)

### Additional notes
In our own version of MathLive, parentheses use the latex "\left(...\right)", the scaling parentheses. In https://cortexjs.io/mathlive/demo/, parentheses are added as "(...)", the standard non-scaling parentheses in latex. The same with hard brackets ("\left\lbrack ...\right\rbrack" vs "[...]"). In our own version, the same problem described above also occur with parentheses and hard brackets. They do not occur with the non-scaling parentheses and hard brackets.

From our simple test page:
![MathLive-bug-parentheses](https://user-images.githubusercontent.com/23076893/129699199-09bc7d6b-115b-4b4e-9970-78d643bba60d.jpg)
![MathLive-bug-brackets](https://user-images.githubusercontent.com/23076893/129699188-d5bf2378-0b81-4daa-a3ce-f96d46da2bd9.jpg)

This issue is also reported at https://github.com/cortex-js/cortexjs.io/issues/8

**Comment by arnog** [comment]
This seems to work now. Might have been related to #1375
