### ISSUE TITLE
liminf and limsup are not serialized correctly

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#1148]
## Description

The probably rarely used `liminf` and `limsup` shortcuts don't quite seem to work.

![image](https://user-images.githubusercontent.com/10220080/130982024-09f6acaf-4235-4b51-8bef-df24cb4b1cbc.png)

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. Go to https://cortexjs.io/compute-engine/demo/
2. Type `liminf`
3. Look at the output or try copying it

### Actual Behavior

![image](https://user-images.githubusercontent.com/10220080/130982024-09f6acaf-4235-4b51-8bef-df24cb4b1cbc.png)

### Expected Behavior

`\liminf`

### Environment

**MathLive version** v0.69.5

**Operating System** Windows 10

**Browser** Firefox 91, Microsoft Edge

**Comment by arnog** [comment]
This is working now.
