### ISSUE TITLE
Backspace in numerator deletes character before fraction

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#115]
## Description
When the insertion cursor is at the start of the numerator, backspace deletes the character before fraction.

## Steps to Reproduce
[Provide steps that are specific and repeatable, if possible]
1. Create the expression `a+\frac {b}{c}` 
2. Click in the numerator before the `b` so the insertion cursor is in front of the `b`
3. Hit `backspace`

The `+` is deleted.

## Expected Behavior
There are many possibilities of what should happen, but deleting the character before the fraction is one that I do not think is a good one. If you think of a touch typist, it probably took a keystroke to create the fraction (if created in a prefix manner), so backspace can be thought of as destroying the fraction but leaving the contents. Desmos and Learnosity which are both based on MathQuill do this. That seems drastic and unintuitive. MathType and the MS Word math editor select the fraction. Wiris selects all but the numerator. Mathematica moves the insertion point to before the fraction (it consistently treats backspace like a left arrow at the edge of 2d notations because it 'undoes' the key stroke it took to move to that point).

I personally prefer the Mathematica solution (I wrote it, so I am biased). The current behavior seems like a mistake.

## Related Behavior
The symmetric case is `delete` at the end of the denominator. Again mathlive deletes the character after the fraction. MathQuill is also symmetric (delete fraction line), but Mathematica and MathType do nothing. The MS editor selects the fraction and WIRIS selects all but the denominator. Another possibility is to move the insertion cursor to after the fraction.

Two other related cases are backspace at start of denominator and delete at the end of the numerator. In this case, MathQuill deletes the fraction line/fraction, as does mathlive. This seems overly destructive. Selection, doing nothing, or moving the insertion cursor are all other reasonable possibilities.

**Comment by arnog** [comment]
Thanks for filing this and for the thorough review of what various editors do. 

I'm not sure of what the right answer is. An argument can be made that consistency with other editors could be valuable, but there doesn't seem to be much consistency between each editors.

The delete and backspace key currently have a consistent behavior in that if you press them something will get deleted. Pressing one of those keys and having something get selected or the insertion point move seems like users might get surprised when they press these keys.

**Comment by dominique-unruh** [comment]
I think two expectations of backspace are:
* If I type a character, I can immediately undo it using backspace.
* When I type backspace, it deletes something my cursor touches.

With these expectations, the current behavior is confusing. If I type `a + / <backspace>`, the + vanishes and the fraction remains. My expectation would have been to have `a+` remain. In the example from the issue, deleting + is also confusing because + is not touching the cursor.

(Selecting the fraction, or moving to the left do not following this idea exactly, but they avoid negative surprises: Nothing unexpected gets deleted, and the cursor/selection is changed in a way that the next backspace deletes something, and it is visually obvious what will be deleted.)

**Comment by stefnotch** [comment]
For the record, MathCad does it a bit differently again. After typing `a + /`, it simply does nothing when you hit `[Backspace]`. Instead you have to press the `[Delete]` key to delete the fraction when the cursor is in the numerator. 

I personally am also in favor of changing the current behavior. May I suggest a bit of an odd middle ground: 
- When the fraction is empty, backspace deletes the fraction. This means that typing `/<backspace>` results in the expected outcome.
- (???) When either the numerator or denominator are empty, backspace could delete the fraction but leave the numerator/denominator. I don't know if this would be nice though, I'd have to play around with it first.
- And when the fraction has both a numerator and denominator, either select the fraction (MathType) or move the cursor to before the fraction (Mathematica)

**Comment by arnog** [comment]
With bcb807d the behavior has changed to implement what @stefnotch described. Play with it and feel free to try different things. The changes would be in the `onDelete()` function in `delete.ts` for `genfrac` and `overunder` case.

**Comment by arnog** [comment]
Inactive issue, and I believe it has been resolved with bcb807d. Closing.
