### ISSUE TITLE
Unintuitive Fraction Focus Behavior

### ISSUE THREAD

**Issue by saivan** [arnog/mathlive#1150]
## Description

The fraction focus behaviour is quite unintuitive, see the little movie below:

https://user-images.githubusercontent.com/8543370/131054570-bcd3a2b5-3a3e-4b64-ab3c-e1dfe98ee49e.mp4

## Steps to Reproduce

The key sequence was
- 1
- /
- /
- backspace
- backspace
- ...

### Expected Behavior

I would expect backspacing inside a fraction to select the outer fraction, instead of putting the caret in front of the fraction as it currently does. Just for reference, here's mathquills behavior with the same key sequence

https://user-images.githubusercontent.com/8543370/131055007-184904f2-92ef-41aa-82ef-e40d4ca93a0d.mp4

**Comment by saivan** [comment]
Sorry I should clarify, I don't mean that it should select anything, I mean that backspacing should effectively undo any action you do. The behaviour I'd expect is the behaviour mathquill has implemented. This seems to be the behavior on every math editor I've used in the past too. I tried quite aa few.

**Comment by Temez1** [comment]
+1 for this. This happens only with an empty fraction. It only removes the upper placeholder, not the whole fraction.

**Comment by zkorz** [comment]
I agree with this. In the simplest case you write "5" then "/" then "backspace" it should undo the fraction and leave with plain "5". If a person types an errant fraction, there is no way to delete the fraction without deleting the numerator as well.

**Comment by arnog** [comment]
The behavior when deleting an empty numerator/denominator now matches the behavior of the Desmos graphing calculator.
