### ISSUE TITLE
sounds-directory attribute not used

### ISSUE THREAD

**Issue by Smef** [arnog/mathlive#1154]
## Description

When defining a <math-field> element the sounds-directory attribute is not read

## Steps to Reproduce

Create an element with a sounds-directory attribute:

`<math-field sounds-directory="https://mysite.com/sounds"></math-field>
`
### Actual Behavior

Sounds are still loaded from the default directory

### Expected Behavior

Sounds are loaded from the directory specified by the sounds-directory attribute

### Environment

**MathLive version**
0.69.5

**Comment by arnog** [comment]
I believe this has been fixed with PR#1228
