### ISSUE TITLE
[Question] Mathfield Dimensions

### ISSUE THREAD

**Issue by rowhitter** [arnog/mathlive#1155]
How can one access the dimensions of the mathfield element in JavaScript? Using the usual HTML Element offset properties or trying to access dimensions through the computed style does not yield accurate values.

**Comment by arnog** [comment]
I would expect the regular properties of a HTML element to work with a `math-field` element. Do you have a test case demonstrating the problem?

**Comment by rowhitter** [comment]
**Test**
[MathfieldDimensionsTest.zip](https://github.com/arnog/mathlive/files/7083511/MathfieldDimensionsTest.zip)
Safari 15.0
MathLive 0.69.5 via mathlive.min.js

**Expected**
<img width="177" alt="expected" src="https://user-images.githubusercontent.com/76398340/131495372-cb6d6596-b23f-4cb5-8eb4-c194560a0617.png">

**Actual**
<img width="817" alt="console" src="https://user-images.githubusercontent.com/76398340/131495381-3d83736f-26b5-4576-9aeb-423a152c0d22.png">

Only the width seems to be inaccurate.

**Test Page Code**
```html
<!DOCTYPE html>
<html>
    <head>
        <script src="mathlive.min.js"></script>
    </head>
    <body>
        <script>
            const mathfield = new MathfieldElement();
            mathfield.readOnly = true;
            mathfield.setAttribute("style", "display: inline-block;");
            mathfield.defaultMode = "inline-math";
            mathfield.value = "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}";
            document.body.appendChild(mathfield);
            console.log("OFFSET");
            console.log("offsetWidth: " + mathfield.offsetWidth);
            console.log("offsetHeight: " + mathfield.offsetHeight);
            console.log("CLIENT");
            console.log("clientWidth: " + mathfield.clientWidth);
            console.log("clientHeight: " + mathfield.clientHeight);
            console.log("CONTENT");
            console.log("contentWidth: " + mathfield.scrollWidth);
            console.log("contentHeight: " + mathfield.scrollHeight);
            console.log("ACTUAL");
            console.log("style.width: " + mathfield.style.width);
            console.log("style.height: " + mathfield.style.height);
            console.log("MIN");
            console.log("style.minWidth: " + mathfield.style.minWidth);
            console.log("style.minHeight: " + mathfield.style.minHeight);
            console.log("MAX");
            console.log("style.maxWidth: " + mathfield.style.maxWidth);
            console.log("style.maxHeight: " + mathfield.style.maxHeight);
        </script>
    </body>
</html>
```

**Comment by arnog** [comment]
By the time you call `console.log(mathfield.offsetWidth)` the browser has not completed calculating the layout of the element that you added. The values for its dimension/position are therefore not up to date. To work around this, you can call `setTimeout` which will defer the call until after the layout has been completed, i.e. 

```
setTimeout(() => {
      console.log(mathfield.offsetWidth)
    }, 0);
```

Even better would be to use `requestAnimationFrame()` (in some cases `setTimeout` may be called before the layout has been completed). You could also use a `ResizeObserver`.

Finally, to get up to date computed CSS style, you should call `window.getComputeStyle()` to ensure the style information you get account for layout changes as well.

**Comment by rowhitter** [comment]
I can confirm that the approaches you mentioned work as you say.

Thank you for the quick, clear, and thorough responses.
