### ISSUE TITLE
Delete at end of sqrt and root deletes char after root

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#116]
## Description
This is similar to #115 except for square roots and radicals.

Note that backspace at the start of the root deletes the root, not the character before it. A backspace at the start of the index deletes the char in front of the root.

Delete at the end of the index or radicand deletes the character after the root.

Examples to try are `a+\sqrt{b}+c` and `a+\sqrt[3]{b}+c`

Better alternatives are to move the insertion cursor, do nothing, or select the root.

**Comment by arnog** [comment]
With bcb807d:
- Deleting at the end of the index moves to the body of the root. 
- Deleting at the end of the body of the root moves outside the root.
