### ISSUE TITLE
Delete and backspace around scripts

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#117]
## Description
This is like #115, but for scripts...

mathlive stands alone among 9 editors for how it handles delete/backspace around scripts:
1. if the insertion cursor is before/after the script, then delete/backspace deletes the entire script.
2.  if the insertion cursor is at the start of the script, backspace changes it to a linear notation (all parts are still there, but it is no longer a sub or superscript).
3. if the insertion cursor is at the end of the script, delete deletes the character following the script.

Among editors, there is not a lot of agreement as to what should happen. Some select the script in the first case, some select the entire expressions, some move the insertion cursor into the script, some do nothing. Desmos deletes just the first/last character of the script. In the other cases, again, there is little agreement. Moving the insertion cursor or doing nothing are some things that are done. Word selects the base and script, MathType selects the script (backspace), and MathQuill does '2' for both '2' and '3'.

I prefer just moving the cursor into/out of the script.

If both scripts are present, mathlive is in good company (Learnosity but not Desmos, MathType, WIRIS) in selecting both scripts. This is very different from '1' when there is a single script and that seems wrong. Another option is to move to start of subscript/end of superscript.

Being at the start/end of a sub or superscript results in different behavior that is not predictable:
1. Start of subscript/superscript: backspace deletes the subscript/superscript operator so that subscript/superscript is directly follows the base and the super/subscript is on the last character of what was the other script.
2. End of subscript: deletes the first character of the superscript
3. End of superscript: deletes the character following the sub/superscript

Again, there are lots of options for what can be done. Consistency is important. I favor moving the insertion cursor.

## Steps to Reproduce
1. Start with this `a+b_{n-1}+c^{n-1}+a^{n+1}_{i-1}+1`
2. Fix up sub/superscript (bug #111) by deleting subscript and selecting `a^{n+1}` and typing `_i-1` 
3. Now try various backspace and delete keys

**Comment by arnog** [comment]
With bcb807d, the behavior matches Mathematica (i.e. move the cursor when at the edge of superscript/subscript) and the delete/backspace key is pressed)
