### ISSUE TITLE
Compile error using MathfieldElement

### ISSUE THREAD

**Issue by Temez1** [arnog/mathlive#1172]
## Description

See [CodeSandbox](https://codesandbox.io/s/unruffled-resonance-k3tl8?file=/src/App.tsx)

When trying to compile the project to build it, tsc throws error 

```bash
node_modules/mathlive/dist/public/options.d.ts:5:53 - error TS7016: Could not find a declaration file for module'@cortex-js/compute-engine/dist/math-json.min.esm.js'.
```

## Steps to Reproduce

1. Open [the CodeSandbox](https://codesandbox.io/s/unruffled-resonance-k3tl8?file=/src/App.tsx)
2. Open new terminal by clicking the + icon next to yarn start terminal
3. run command `npx tsc` in terminal

### Actual Behavior

Throws the error when trying to compile the project

### Expected Behavior

Project compiles

### Environment

See the CodeSandbox

**Comment by Temez1** [comment]
I traced down the issue to compiler settings. This is caused by the strict mode being on (which is a good thing IMO).

I forked the mathlive, and removed `"noImplicitAny": false,` from tsconfig.json and run `npx tsc --strict` and it found 441 errors from the current repo.

That's a long way to go fix each implicit any + other related typing issues, even though they would be a nice improvement when using TS. I think using TS with implicitAny and without strict removes a huge portion of the point using TS in a project. Would love to see this project at least use `"noImplicitAny": true,` if not strict mode. Changing this leaves 294 errors in the current repo, which is a lot, but a lot less than with strict.

As a workaround for this issue without disabling strict mode from my own project, I added this declaration file for my project under src/.

```typescript
// src/global.d.ts
declare module "@cortex-js/compute-engine/dist/math-json.min.esm.js" {
  type ErrorCode = any
}
```

If there is something that I have missed or have a better workaround, please let me know.

**Comment by arnog** [comment]
A workaround I'd suggest is to replace `from '@cortex-js/compute-engine/dist/math-json.min.esm.js';` with `from '@cortex-js/compute-engine';` in line 42 and 56 of `mathlive.ts`. This will allow the correct definition file to be imported.

As for the use of `noImplicitAny`, yes that would be nice, but the project was converted from JavaScript to TypeScript and making TypeScript accept some JavaScript idioms can be extremely tedious with little to no benefit. The conversion to TS was overall worthwhile, though as it did find a few bugs, and more importantly, makes the overall codebase much easier to maintain and extend.
