### ISSUE TITLE
Mathfield does not scroll into view when virtual keyboard hides it

### ISSUE THREAD

**Issue by Temez1** [arnog/mathlive#1173]
## Description

When using a virtual keyboard, it doesn't scroll into view when you start typing. This means you can't see what you are typing.

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. Go to mathlive [website](https://cortexjs.io/mathlive/)
2. Scroll down so that the math input is at the bottom of the page
3. Toggle virtual keyboard
4. It covers the mathfield, even when you input something.

### Actual Behavior

You don't see the input if you don't scroll down manually.

### Expected Behavior

When the virtual keyboard is visible if some input is made in a mathfield that mathfield should scroll into view. 

### Environment

Happens in my local env, as well as in the browser (Chrome version 93.0.4577.82)

**Comment by zwz** [comment]
@arnog Even worse is when the page has a mathfield at the bottom.
It can not scroll up at all, and the virtual keyboard just hides the mathfield.

I wonder is it possible to set an 'parent dom node' option to tell where the virtual keyborad should go.

**Comment by Temez1** [comment]
@zwz As a workaround, I calculated the position of the mathfield and added a margin-bottom to my wrapper (box) for the mathfield and it scrolls to the bottom of the screen when it's touched. A bit dirty but works. This doesn't work if you want to click it to open (or use it on a non-touch device), but I disabled the default behavior as it was not necessary for me. `"virtualKeyboardMode: "off"`

```typescript
 const handleTouch = () => {
    let viewportHeight = document.getElementById("root")?.clientHeight

    if (viewportHeight === undefined) {
      console.error("Can't find root element")
      viewportHeight = window.innerHeight
    }

    const distanceFromBottomOfScreenInPx =
      viewportHeight - mfe.getBoundingClientRect().bottom

    const heightOfVirtualKeyboardMobileInPx = 270
    const heightOfVirtualKeyboardInPx = 330

    const marginMobile = `${
      heightOfVirtualKeyboardMobileInPx - distanceFromBottomOfScreenInPx
    }px`
    const margin = `${
      heightOfVirtualKeyboardInPx - distanceFromBottomOfScreenInPx
    }px`

    setInputOffsetOnVirtualKeyboardVisible({ base: marginMobile, md: margin })
    window.scrollTo(0, document.body.scrollHeight)
    mfe.virtualKeyboardState = "visible"
  }

```

**Comment by zwz** [comment]
@Temez1 
Thanks for the workaround.
I hope there is a clean way.

**Comment by arnog** [comment]
This should now work.
