### ISSUE TITLE
Not able to import sounds using own asset pipeline

### ISSUE THREAD

**Issue by Temez1** [arnog/mathlive#1175]
## Description

When using your own asset pipeline, the sounds are imported with the wrong path. The [docs](https://cortexjs.io/mathlive/guides/integration/#:~:text=Integrating%20with%20an%20Asset%20Pipeline) have a guide to handle fonts doing this, but the sounds are not supported.

I have tried to set the `soundsDirectory` to the path that the sounds are imported from and it's working as supposed, changing the path to correct **folder** but the file name is wrong.

`GET http://localhost:5000/assets/keypress-spacebar.wav 404 (Not Found)`

The actual path would be in this case

`http://localhost:5000/assets/keypress-spacebar.b4e698a8.wav`

**Comment by Temez1** [comment]
As a workaround, I moved the sounds to the `public` folder so that they are not hashed in the build and can be imported with the default naming.

**Comment by arnog** [comment]
If your asset bundler is renaming the sound files, you can specify the new names by setting the `keypressSound` and `plonkSound` properties of the math-field element.

**Comment by Temez1** [comment]
Okay, thanks for the info. I'm happy with the public folder solution. Naming them directly would lead me to specify different names in development and build, which is possible, but unnecessary.
