### ISSUE TITLE
Text mode doesn't allow spaces between words if both braces are typed before typing text

### ISSUE THREAD

**Issue by Temez1** [arnog/mathlive#1178]
## Description

When using text mode and typing both brackets before starting to write the text, you can't use space to separate words.

## Steps to Reproduce

1. In editor type `\text{}`
2. Move the caret inside the brackets
3. try to type `if and`

### Actual Behavior

When you use space inside brackets it will "jump out" to outside the brackets

### Expected Behavior

You would be able to type `\text{if and}`

**Comment by arnog** [comment]
I can't reproduce this.
