### ISSUE TITLE
Arrow key/backspace/delete problems with limits

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#118]
## Description
This is like #115, but for limits... Maybe for the other issues (#115, #116, and #117), there could be an argument that what mathlive does makes sense (I would disagree), but in the case of limits, there are clearly bugs.

Cases which seem clearly buggy with a single limit:
1. Cursor before base/limit: right arrow/delete both move cursor to _after_ first char in base -- you can't get insertion point before first char in base. Move left takes you out of the base/limit.
1. Cursor at end of limit: right arrow moves cursor to _after_ first char after base/limit.
1. Cursor at end of limit: delete deletes _second_ char after base/limit.

Cases which seem clearly buggy when both limits are present:
1. Insertion cursor at front of lower limit: left arrow and the insertion cursor disappears. A second left arrow and it is in front of the limit.

Cases that seem wrong to me:
1. Insertion cursor at front of lower/upper limit:  backspace -- lower/upper limit moves to before sum and there is no longer a lower/upper limit.
1. Insertion cursor at end of lower limit: delete deletes first character of upper limit.
1. Insertion cursor at end of upper limit: delete deletes first character after base & limits.
 
## Examples used
1. Just one limit: `1+\underset{under}{base}+\overset{over}{base}+2`
2. Two limits (only allowed on sum, etc): `2\sum ^n_{i=0}f(i)`

**Comment by Nifdee** [comment]
I also just ran into the issue with both limits (cursor disappearing) and noticed that this even crashes the whole browser tab. To reproduce, enter a sum and navigate to the front of the lower limit so that the cursor disappears. After a couple of seconds, the tab is frozen and won't recover.

**Comment by arnog** [comment]
I've fixed the navigation for the inferior limit, although I wasn't able to reproduce the hang. The other issues seem to be fixed as well. Let me know if you still see some problems.
