### ISSUE TITLE
Disable default inline shortcuts

### ISSUE THREAD

**Issue by cyrillbrito** [arnog/mathlive#1183]
## Description

In my use case the input will be used with only a few functionalities and I want to be able to remove the shortcuts that don't make sense for the project.

## Potential Solution

1. Add a flag on the options to disable default shortcuts
2. Use the same logic as the Macros. When you set `inlineShortcuts` option it overrides all existing shortcuts.

---

I am willing to code this as long as I know each solution makes more sense.

**Comment by arnog** [comment]
Setting `inlineShortcuts` should override all existing shortcuts. Are you saying that it doesn't? Do you have an example you could share?

**Comment by cyrillbrito** [comment]
I was using a older version by accident, in the current version it works fine. Thanks!

**Comment by SahilPatel2349** [comment]
How can I disables all shortcut?

**Comment by arnog** [comment]
By setting `mf.inlineShortcuts = {}`
