### ISSUE TITLE
mathlive running in chrome 69 , with error /\p{Letter}/: Invalid property name

### ISSUE THREAD

**Issue by ginkosen** [arnog/mathlive#1184]
## Description

mathlive running in chrome 69 , with error **/\p{Letter}/: Invalid property name**

![image](https://user-images.githubusercontent.com/2233819/134655431-7f439551-d8b1-41cd-9687-b520ea3318e9.png)

[To quickly build a demo project, consider

- (https://github.com/mindreframer/mathlive-bug-issue-templates)
- (https://github.com/mindreframer/mathlive-create-app) ]

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. [First Step]
2. [Second Step]
3. [And so on...]

### Actual Behavior

![image](https://user-images.githubusercontent.com/2233819/134636646-919aeb5b-bb26-40fc-a74e-359ed0692598.png)

### Expected Behavior

fix

### Environment

**MathLive version**
0.35.1+

**Operating System** [macOS, Windows, iOS. Include the version]

android 11

**Browser** [Safari, Chrome, IE, Firefox, etc... Try several browsers and note
chrome 69

**Comment by arnog** [comment]
The current version of MathLive is 0.69.7. Check if 
The current version of Chrome is 94, version 69 is no longer supported.

**Comment by ginkosen** [comment]
yes, i know 
the newest MathLive version have same issues

newest chrome is 94, unfortunately some users android chrome version is very low .
