### ISSUE TITLE
mathlive reference page for large fences is blank

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#119]
## Description
On the [mathlive reference page](http://mathlive.io/0.24f/reference.html), even if you click on "all 700+" (for 'compact', 'details' does work [see #82]), you can't see how to create large fences. There is a button at the bottom of the page to take you to a [page that supposedly lists them](http://mathlive.io/0.24f/reference.html?format=compact&cat=Large%20Fences). However, that page is basically blank:
![image](https://user-images.githubusercontent.com/1545836/47130729-dbff6f80-d24f-11e8-9051-9153813c98b4.png)

There is nothing about large fences on the page.

**Comment by arnog** [comment]
Fixed.

**Comment by arnog** [comment]
Oh, I see. Yes, "Large Fences" is an empty category. All the fences are in the "Fences" category. I'll remove it.

**Comment by NSoiffer** [comment]
Thanks. But note that the large versions of the fences under fences doesn't display correctly:

![image](https://user-images.githubusercontent.com/1545836/47596903-b43e9480-d93e-11e8-98be-d7c7b0a01e8b.png)

**Comment by arnog** [comment]
Fixed. They display under the "Sizing" category.
