### ISSUE TITLE
\overset & \underset don't allow editing of annotation

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#12]
## Description
The notation for underset and overset is:
\overset{annotation}{base}

In the editor, you can not select or move the cursor into the annotation part of the construct.

## Steps to Reproduce
1. In a math editor instance, type `1+\overset{x-1}{ax+by+c}` followed by enter
2. The \overset is properly display
3. Try to arrow backwards -- you can't get to the 'x-1'
4. Try to select 'x-1' -- you can't

I tried this in both Chrome and Firefox.

**Comment by NSoiffer** [comment]
Related to this:  if you select the entire expression, the `x-1` it seems to be in some quantum selection state :-)
1. If you type delete or a character, the entire expr is deleted or replaced.
2. If you type `/`, only base is part of the fraction as shown below (selected the fraction)
![image](https://user-images.githubusercontent.com/1545836/36701992-3181e44a-1b0a-11e8-9f77-49941c9110c5.png)

**Comment by arnog** [comment]
Selection should work now.
