### ISSUE TITLE
Scrim element z-index problem

### ISSUE THREAD

**Issue by Stenli79** [arnog/mathlive#1201]
##  Scrim z-index problem

I try to integrate matlive lib into bootstrap modal. But bootstrap modal overlay  has z-index: 10050 and the virtual keyboard appear under  modal overlay. I found this solution for keyboard 
```
.ML__keyboard{
  z-index: 10100;
}
```
but i don't have control under scrim popup.

![Screenshot from 2021-09-30 16-48-41](https://user-images.githubusercontent.com/81822353/135473430-7ba7b867-f7af-4e29-ac7e-c0e63edab13a.png)

![Screenshot from 2021-09-30 16-49-59](https://user-images.githubusercontent.com/81822353/135473476-8ec827a9-e58b-438b-a46b-fe05375b95e8.png)

## Steps to Reproduce
Add some modal overlay with z-index 10000

### Actual Behavior
I can't control the z-index of scrim popup.

### Expected Behavior
Solution: Add in **_mathlive/src/editor/scrim.ts_** in line 41

`element.setAttribute('class', 'some-class-to-overwrite');`

### Environment

**MathLive version**
- MathLive 0.69.

**Operating System** 
- [macOS, Windows, iOS. Include the version]

**Browser** 
- not specific

**Comment by arnog** [comment]
I've added a `--scrim-zindex` CSS variable, but I've also changed the default to 10099.
