### ISSUE TITLE
Question about transition of virtual keyboard

### ISSUE THREAD

**Issue by hhabakuk** [arnog/mathlive#1227]
Hello!

I'm using math-live to create a multi-line equasion solving component as seen below
![image](https://user-images.githubusercontent.com/13555621/140072655-eed7d193-3b4b-459a-9d5c-7fa5d1046e60.png)

Under the hood each line is a separate input.

Now I am trying to make better UX for showing virtual keyboard with `virtualKeyboardMode="onfocus"`. 
Current behavior is that the keyboard keeps transitioning on every line change.

My questions: 
Is it somehow possible to remove keyboard animation?

**Comment by arnog** [comment]
Have you considered using `makeSharedVirtualKeyboard()`? This allows you to have a single virtual keyboard shared by multiple mathfield instances. See https://cortexjs.io/mathlive/guides/virtual-keyboards/ "Sharing Virtual Keyboards Amongst Multiple Instances"

**Comment by hhabakuk** [comment]
Thanks for the quick reply, `makeSharedVirtualKeyboard ` should indeed do what I need, I am having trouble making it work though. Could you have a look at either of the sandboxes to see what's the problem?

[With React](https://codesandbox.io/s/priceless-marco-l9ohc?file=/src/App.js)
[Without React](https://codesandbox.io/s/mathlive-forked-y7vzo?file=/App.svelte)

Thanks in advance!

**Comment by hhabakuk** [comment]
Hi again - perhaps there is an existing codesandbox example for using `makeSharedVirtualKeyboard` ? Just having a working example with whatever stack would help a bunch with debugging the issue.

**Comment by arnog** [comment]
Thanks for the additional info and the sandboxes. I'm going to have a look at them, but the earliest I can do that is next week. It is possible that what you are trying to do is in fact not possible, but I think it's a valid use case and I'd be happy to add a solution for it. Thanks for your patience!
