### ISSUE TITLE
documentation about how mathlive.io compares

### ISSUE THREAD

**Issue by johanneswilm** [arnog/mathlive#123]
Hey,
this looks like a promising piece of software. With **fiduswriter** we have hitherto used **Mathquill** for editing and **katex** for rendering and I just spent a considerable amount of time trying to bundle Mathquill together with jQuery (to avoid having a global jQuery). The reason I didn't use **Mathlive** instead was that I had not found it despite searching for something similar. Now that I have been pointed to it, some questions come up that I think also others will have who are considering using Mathlive so it would be good if they could be addressed in some way:

* Based on the documentation, it seems you suggest to use Mathlive for both formula editing and rendering. While your demos can show some impressive examples of really complex formulas, I am sure you are aware of limitations of Mathlive as well. So I wonder: how does it (roughly) compare with other libraries such as **katex** or **Mathjax**? Can it just about as many formulas, or is it more restricted? Is speed an issue? Should one  for example stick to katex to render more complex formulas and use Mathlive mainly for WYSIWYG editing of relatively simple formulas? Or does that not make sense at all?

* The documentation also shows how your engine automatically can find formulas in text, similarly to how Mathjax does it (or at least used to do it a few years back). You also have some examples of how to use the library functions more directly, but it sounds a bit like you are against using it as a dependency in an ES2015+ type project where it's being bundled with everything else and you prefer using it like one we used to with jQuery, loading it apart from the rest of the project. Also, you seem to have put everything into one global object, similarly to jQuery. So before I start trying to use this, let me ask: Is it possible to use it in a ES2015 type project?  

If answers to these questions can be found somewhere in your documentation - please excuse my bad search skills, but I just did not see it mentioned anywhere.

**Comment by arnog** [comment]
Thanks for taking the time to write. Great questions. I'll try to answer them:

If you have some suggestions on where I can advertise MathLive, let me know (i.e. where did you search initially and not find it?)

MathLive has been designed in a modular fashion. So, if you're only interested in rendering math, you can omit all the modules related to editing.

As far as the capabilities of MathLive, last time I looked it was more comprehensive than Katex (in particular support for LaTeX environments), but not as comprehensive than MathJax (which supports a number of non-standard LaTeX commands for improved integration with web content. MathLive supports only a subset of those). I've tried to optimize MathLive for speed of rendering, so whether to just display formulas, or to edit them, speed should not be an issue.

MathLive can indeed be used with an 'auto-render' add-on which will scan a web page and automatically converts math notations (using some of the same conventions used by MathJax to tag that content). The intent of that functionality is to make it very easy to author math content without having to write Javascript to have it displayed. While this is usually sufficient if you only need to display content, realistically for any editing, you will want to write some Javascript and use the MathLive API to do so. The current release is recommending to use an AMD-compatible loader such as requirejs to load the necessary modules. However, I am in the process of finalizing a conversion to native ES6 JavaScript modules that will make it unnecessary to use a third-party loader.

When loading MathLive you do get back an object, `MathLive`, which is the entry point to the public API. There is no dependency on the `window` object (although MathLive is also added to the `window` object if it exists). It is perfectly possible to use MathLive in non-browser environments that don't have a `window` object, such as NodeJS. In fact, the MathLive automated test suite runs in NodeJS.

**Comment by johanneswilm** [comment]
First I looked at the overview page at mathjax [1]. It seems you have updated this since. I was also searching on npmjs.com and other than that just googling for terms like "JavaScript LaTeX editor". I have been searching for about 1.5 years after it became apparent that mathquill is not been developed any more.

> As far as the capabilities of MathLive, last time I looked it was more comprehensive than Katex (in particular support for LaTeX environments), but not as comprehensive than MathJax (which supports a number of non-standard LaTeX commands for improved integration with web content. MathLive supports only a subset of those). I've tried to optimize MathLive for speed of rendering, so whether to just display formulas, or to edit them, speed should not be an issue.

OK, this is very useful information. It seems we should be able to use it as a drop-in replacement for katex and Mathquill. If users complain that they need to render more complex math, we will have to add mathjax in a way where it takes over if formulas are very complex and users then don't get WYSIWYG input controls. It may not be an issue for our users at all.

> I am in the process of finalizing a conversion to native ES6 JavaScript modules that will make it unnecessary to use a third-party loader.

Ok, it sounds like we should wait for that then to finish.

> When loading MathLive you do get back an object, MathLive, which is the entry point to the public API. There is no dependency on the window object (although MathLive is also added to the window object if it exists). It is perfectly possible to use MathLive in non-browser environments that don't have a window object, such as NodeJS. In fact, the MathLive automated test suite runs in NodeJS.

This seems like an OK setup. Given that it is automatically added to window, there could be situations where a developer forgets to import it in a particular ES6 file (as it's still working) and then get confused because it's not working in nodejs testing. But those should be fairly limited cases. As long as one will be able to do something like this in an ES6 file:

```js
import {MathLive} from "mathlive"
```

And it is then accessible within that file, I think we should be good. 

Thanks for your fast response and it sounds like we should go ahead with trying to switch to MathLive.


[1] https://github.com/mathjax/MathJax-docs/wiki/List-of-web-based-math-editors

**Comment by arnog** [comment]
MathLive 0.24 is now available in GitHub and npm. This version includes full support for JavaScript native modules. To import MathLive:
```javascript 
import MathLive from "dist/mathlive.mjs"
```
This version is a pure module, so it doesn't make any assumption or modifications to other scopes (`window`, etc...). The old UMD-style version is still available in `dist/mathlive.js` (note the different file extensions) and can be used with requirejs, for example.

I will close this issue for now, but feel free to open a new one if you run into any problems.
