### ISSUE TITLE
Select all (CMD+A) in latex mode breaks rendering

### ISSUE THREAD

**Issue by mklilley** [arnog/mathlive#1240]
## Description

When you select all using CMD+A in latex mode, the equations you type next do not render when you try to get out of latex editing mode

I made a loom video where I take you through exactly what this means and how to reproduce https://www.loom.com/share/ffe787ef0e8e49f492e955d9340b75b4

## Steps to Reproduce

1. Hit escape to get into latex editing mode
2. Select all using CMD+A
3. Start typing latex
4. Hit escape to get out of latex

### Actual Behavior

Equations not rendered and even virtual keyboard input no longer works to render stuff. No console errors.

### Expected Behavior

Equations should still render

### Environment

Using mathlive demo on https://cortexjs.io/mathlive/.

Using Mac, using brave browser. Also happens on Chrome

**Comment by arnog** [comment]
Thanks Matt, for the video and the clear reproducible steps. I've been able to reproduce it, and there is indeed a bug.

**Comment by mklilley** [comment]
Happy I could help. Thanks for fixing it so quickly. 🙏
