### ISSUE TITLE
Feature Request: geometry \overgroup \overrightarrow \overleftrightarrow

### ISSUE THREAD

**Issue by jasoncable** [arnog/mathlive#126]
## Description
I'm creating multiple virtual keyboards and need one for geometry.  I'm not sure how to implement these symbols.  I kind of hacked it in, but I can't figure out how to extend the characters to fit what is underneath them.  My javascript knowledge is not very good or else I would love to help.

The symbols I'm referring to are here: https://katex.org/docs/support_table.html

\overgroup - represents an arc in geometry
\overrightarrow - represents a ray in geometry
\overleftrightarrow - represents a line in geometry

Thanks!

**Comment by arnog** [comment]
You can use something like `\overset{\leftrightarrow }{AB}` as a workaround, but those stretchy operators are indeed not currently supported.
