### ISSUE TITLE
Mathfield scrolls to top when you input

### ISSUE THREAD

**Issue by kingnare** [arnog/mathlive#1310]
## Description
Source Code:
```
<!DOCTYPE html>
<html>
<head>
  <script defer src="//unpkg.com/mathlive/dist/mathlive.min.js"></script>
</head>
<body>
  <math-field id="formula" style="height:100px; overflow:auto;">
    \begin{align*}y & = \\  & a \\  & b \\  & c \\  & d \\  & e \\  & f \\  & g\end{align*}
  </math-field>
</body>
</html>
```

- Scroll to bottom first, lost focus, focus in the mathfield, the mathfield will scroll to the top.
- Scroll to bottom, the mathfield will scroll to the top when you input.

[Video](https://kingnare.github.io/mf-demo.mp4)

[Demo](https://kingnare.github.io/f.html)

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. CSS: overflow:auto
2. mathlive: multiline content
3. input or lost focus->focus

### Environment

**MathLive version** 0.69.9

**Operating System** [Windows 10]

**Browser** [Chrome 96.0]

**Comment by arnog** [comment]
This should now work. Furthermore, you no longer need to add the `overflow: auto` CSS property.

**Comment by 2arch** [comment]
still doesn't work
