### ISSUE TITLE
[Question] Convert the equation to an image tag

### ISSUE THREAD

**Issue by Nebojsa-B** [arnog/mathlive#1312]
Dear mathlovers,

I just want to ask you if there is a possibility to convert the equation to an image tag via mathlive library. The current presentation is in the span tag.

![convert-to-image](https://user-images.githubusercontent.com/48208164/150240911-ac233a39-8c63-4f88-8ce7-ef91f170e458.PNG)

Best regards,
NebojsaB

**Comment by arnog** [comment]
You can convert the mathfield to an image using some third-party library. Have a look at `https://github.com/arnog/mathlive/tree/master/examples/latex` for an example (look for the `htmlToImage` function)

**Comment by Nebojsa-B** [comment]
Dear arnog, 
Thank you for your fast answer. It is helpful
 I will research that link.
