### ISSUE TITLE
[Question] Is there a option to make draggable virtual keyboard?

### ISSUE THREAD

**Issue by Nebojsa-B** [arnog/mathlive#1337]
Hi arnog!

We are working to implement your library in editor and we need to make draggable. Is there any option to do that?

Also great work!! :)

Kind regards,
Nebojsa B

**Comment by arnog** [comment]
Thank you!

There is no direct support for a draggable keyboard, however, you should be able to put the keyboard in an `iframe` and make the `iframe` draggable. Alternatively, you could try to set the appropriate CSS and JavaScript handlers on the keyboard container, but I have a feeling that the `ifram` route would be easier.

See the section about "Sharing Virtual Keyboards" in this page: https://cortexjs.io/mathlive/guides/virtual-keyboards/

**Comment by Nebojsa-B** [comment]
Can you send me some an example with iframe if you have or something similiar?

**Comment by arnog** [comment]
You can find an example here: https://github.com/arnog/mathlive/tree/master/examples/iframe

**Comment by Nebojsa-B** [comment]
This is helpful. Thank you!
