### ISSUE TITLE
Clicking on virtual keyboard plate hides virtual keyboard on >=0.69.6

### ISSUE THREAD

**Issue by wb-joona** [arnog/mathlive#1347]
## Description

When clicking on the gray area between the virtual keyboard's keys, the keyboard gets hidden.
This behavior was introduced in 0.69.6. On 0.69.5, the keyboard does not close when clicking on the gray area.

![PowerToys_1CD7e755Xe](https://user-images.githubusercontent.com/85222502/154271362-0f6f8268-31ff-4d28-9aa6-a2794daef173.gif)

## Steps to Reproduce

1. Go to https://cortexjs.io/mathlive/demo/
2. Open up the virtual keyboard
3. Click on the gray area between the virtual keyboard's keys
4. Notice that the keyboard gets hidden

### Actual Behavior

The keyboard is hidden when clicking on the gray area.

### Expected Behavior

I would expect the keyboard not to get hidden, as this makes it rather awkward if you miss the key by just a few pixels (e.g. on a small mobile screen).

[Is this a regression: did it use to work in a previous version?]
Regression or just different behavior before 0.69.6. Possibly from https://github.com/arnog/mathlive/commit/5e981259f74b0e36347b83c034d762e4ac84c463

### Environment

**MathLive version**
`>=0.69.6`

**Operating System** [macOS, Windows, iOS. Include the version]
Windows 10

**Browser**
Chrome 98.0.4758.102
Firefox 97.0

**Comment by hengsok** [comment]
@arnog yes I can confirm this bug. Is there a fix soon? Many thanks for this great library.

**Comment by xing38** [comment]
@arnog Hi Arnog, thanks for the amazing library. I have helped to fix the issue above. Hope you can merge my request and push to NPM so I can get this changes to my project. Thanks again. 

@wb-joona pls try this fix

**Comment by arnog** [comment]
Fixed
