### ISSUE TITLE
Inline math spacing is incorrect

### ISSUE THREAD

**Issue by zeyad-ahmad-aql** [arnog/mathlive#1356]
## Description

There are some incorrect spacings in **inline-math** mode.

<img width="251" alt="Screen Shot 2022-02-23 at 11 40 31 AM" src="https://user-images.githubusercontent.com/46978227/155294163-ecd4ae85-6049-4c82-a593-79f20b3ea75e.png">

## Steps to Reproduce

1. Create an empty .html file anywhere
2. Copy the following snippet
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Inline Math Test</title>
  </head>
  <body>
    <h3>Inline</h3>
    <math-field
      default-mode="inline-math"
      value="\mathrm \frac{X_L}{\left(X_C\right)_1}"
    ></math-field>

    <h3>Block</h3>
    <math-field value="\mathrm{\frac{X_L}{\left(X_C\right)_1}}"></math-field>

    <script src="https://unpkg.com/mathlive/dist/mathlive.min.js"></script>
  </body>
</html>
```
3. Open the html file in the browser

### Actual Behavior

The numerator intersects with the frac.

### Expected Behavior

The spacing of the numerator should be increased so the letters do not intersect with the frac.

## Environment

**MathLive version**: 0.69.9

**Operating System**: macOS Version 12.2.1 (21D62)

**Browser**: Chrome Version 98.0.4758.102 (Official Build) (arm64)

**Comment by arnog** [comment]
I'm having some difficulties reproducing this. Do you have a zoom level applied in your browser? This is what I'm getting

<img width="71" alt="Screen Shot 2022-04-12 at 21 13 42" src="https://user-images.githubusercontent.com/760798/163098976-d1c53b05-16c8-4201-aa09-0c60e3706021.png">

For reference, this is what TeX is producing

<img width="89" alt="Screen Shot 2022-04-12 at 21 13 50" src="https://user-images.githubusercontent.com/760798/163099011-f5ec42e2-d66e-4d3b-a224-c6fd3d664515.png">

**Comment by zeyad-ahmad-aql** [comment]
No, nothin at all. I even tried it now using the demo on [https://cortexjs.io/mathlive/demo/](https://cortexjs.io/mathlive/demo/)  by setting the default mode, and it produces the same result with me.

**Comment by arnog** [comment]
OK, I've tried to adjust the position of the fraction bar by half the height of the bar. I'm not sure if this was the problem, since I couldn't reproduce it, but let me know if you still see something off.

**Comment by zeyad-ahmad-aql** [comment]
> How did you get you original screenshot? The text doesn't appear to be 16px tall, so you have something applied to enlarge it. Did you change the font-size? Did you scale it?

Nop, I don't have anything applied. I event tried testing it using [https://cortexjs.io/mathlive/demo](https://cortexjs.io/mathlive/demo) on other devices to check if something is wrong with mine, but still the same result, even after the changes you did.

**Comment by zeyad-ahmad-aql** [comment]
> > How did you get you original screenshot? The text doesn't appear to be 16px tall, so you have something applied to enlarge it. Did you change the font-size? Did you scale it?
> 
> Nop, I don't have anything applied. I event tried testing it using https://cortexjs.io/mathlive/demo on other devices to check if something is wrong with mine, but still the same result, even after the changes you did.

On [https://cortexjs.io/mathlive/demo](https://cortexjs.io/mathlive/demo) even after you released, nothing has changed. But after merging your changes in my forked repo, It is fixed. Thank you @arnog.
