### ISSUE TITLE
How to "shift" between custom virtual keyboard layers

### ISSUE THREAD

**Issue by wlewis-formative** [arnog/mathlive#1357]
A colleague and I are attempting to add a custom virtual keyboard similar to the default "roman" keyboard.
We'd like the `Shift` key to behave identically: that is, the "lower" layer should be visible by default, and when
a user clicks `Shift`, the keyboard should switch to the "upper" layer (and remain there until they click `Shift`
again). We've tried adding various `class`es to the `Shift` key, but to no avail. We've also considered the
possibility that a custom "shift handler" is required, but don't know where to install it.

Is it possible to produce this effect in a custom keyboard at this time, and if so, could you provide a brief example
or pointers on how to do so?

PS Thanks for this great package.

**Comment by arnog** [comment]
Thank you, glad you enjoy MathLive.

It's possible, but it's a bit involved and I have written only limited documentation about this. Here are a few tips...

To have a key that triggers a "shift", use something like this:
```json
{
   "label": "&#x21e7;", 
   "class": "layer-switch shift modifier font-glyph bottom left w15'"
},
```

The `&#x21e7` is the Unicode glyph for the shift-key, but you can use whatever is appropriate for your use case. 

The set of classes are mostly decorative, except for the `layer-switch` class and the `shift` class. The `layer-switch` class is the the one that indicates that this keycap triggers a layer switch.

Now, there are two "modes" of keyboard shifting. 

The first is a temporary state, which you get if you press and hold the shift key. When you release the shift key after this press and hold, you revert to the original state. In this temporary state the label (and commands) associated with the keycaps on the current layer are modified. The label of the keycaps with a `shifted` property are changed to the content of the `shifted` property. If they have a `shiftedCommand` property, that is the command that will be executed if the keycap is pressed in this state. If the label of the keycap is a single lowercase letter (`a-z`), it is automatically turned to its uppercase counterpart,  even if there is no `shifted` property.

This first state is triggered by the `shift` class. If you don't want this behavior, but simply want to switch to another layer, include the `shift-layer` class, but not the `shift` class.


 Incidentally, while testing this I discovered an issue: the keycap doesn't properly revert to its original state if it has a `shifted` property and content other than a single "a-z" character. I'll push a fix for this shortly.


The second state is a permanent switch to another layer. To trigger this, include a `layer` property with the name of the layer you want to switch to. You should declare the layers associated with this keyboard in the `layers` property of your keyboard descriptor, i.e., assuming the name of the layer you want to switch to is `secondary-custom-layer`:

```json
      "custom-keyboard": {
        "label": "Custom Keyboard",
        "tooltip": "This is my very own keyboard",
        "layer": "primary-custom-layer",
        "layers": ["primary-custom-layer", "secondary-custom-layer"] 
        }
```

Now, while testing this I ran into another issue where they `layer` property is ignored when specifying the keyboard with an  object literal (you can also describe a keyboard with HTML (which works) and that's what MathLive uses internally, but it's even less documented). I will also shortly push a fix for this.

If those two shift states are confusing, have a look at the greek virtual keyboard. It makes use of both. You'll notice that if you press and hold the shift key, the keycaps shift to their corresponding capital version. That's the first mode. If you let go of the shift key, the keys rearrange themselves (the spacebar becomes larger for example). That's a secondary capital-greek layer that has been activated.

**Comment by arnog** [comment]
Reopening in case you have any further questions...

**Comment by wlewis-formative** [comment]
@arnog you are the man 🙏 
Thank you for the quick and detailed response, and again for such a great tool!

**Comment by boompikachu** [comment]
Using class `layer-switch shift-layer ...` to make permanent shift layer (second state) does not work

Did both adding `layer-switch shift-layer` to the shift key cap class and add the shifted layer in `layers`

```tsx
"custom-keyboard": {
        "label": "Custom Keyboard",
        "layer": "primary-custom-layer",
        "layers": ["primary-custom-layer", "secondary-custom-layer"] 
        }
```

Note that the first state does work (need to hold down shift key)

**Comment by boompikachu** [comment]
Solution as of `0.89.1`

In keyboard add the following

```tsx
"custom-keyboard": {
        "label": "KB",
        "layer": "base-layer",
        "layers": ["base-layer", "shifted-layer"] 
}
```
create the following function
```tsx
export const shiftKeyCap = (shiftToLayer: string) => ({
  label: "<svg class='svg-glyph'><use xlink:href='#svg-shift' /></svg>",
  class: 'svg-glyph modifier bottom left w15',
  layer: shiftToLayer,
});
```
In layer add the following

```tsx
...
'base-layer': {
    rows: [
      [
        shiftKeyCap('shifted-layer'),
        { key: 'z', label: 'z' },
        { key: 'x', label: 'x' },
        { key: 'c', label: 'c' },
        { key: 'v', label: 'v' },
        { key: 'b', label: 'b' },
        { key: 'n', label: 'n' },
        { key: 'm', label: 'm' },
      ],
    ],
  },
'shifted-layer': {
    rows: [
      [
        shiftKeyCap('base-layer'),
        { key: 'Z', label: 'Z' },
        { key: 'X', label: 'X' },
        { key: 'C', label: 'C' },
        { key: 'V', label: 'V' },
        { key: 'B', label: 'B' },
        { key: 'N', label: 'N' },
        { key: 'M', label: 'M' },
      ],
    ],
  },
...
```

**Comment by eagleoflqj** [comment]
@arnog Is there a solution for mathlive>=0.90? I like the refactor but now that layers are not identified by name, @boompikachu 's solution doesn't work.

**Comment by eagleoflqj** [comment]
I figured it out. There's a bug in `switchKeyboardLayer`. Will make a PR.
