### ISSUE TITLE
typing 'space' causes right paren to disappear

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#136]
## Description
If I have a parenthesis to the left of the insertion point, typing ` ` (space) causes it to disappear.

## Steps to Reproduce
1. Open `mathlive/examples/basic/index.html`. It initializes the input field with f(x)=
2. Click after the `=` and type a space.

This is what I see:
![image](https://user-images.githubusercontent.com/1545836/52590881-53f13700-2df7-11e9-8f00-082a317492d5.png)

Notice that the right paren has disappeared, although it is still in the latex interpretation below

**Comment by arnog** [comment]
This is the intended behavior. When at the border of a fence, typing spacebar will close the fence. This was a feature request. What behavior would you want?

**Comment by NSoiffer** [comment]
This appears to be an undocumented feature. The [documentation](https://mathlive.io/deploy/reference_shortcuts.html), says space moves to the end of the parent and shift-space moves to the beginning. It does not seem like typing a space to close a fence fits in well with this. Plus, I think that is a useful movement command and I'd hate to see it go away.

Be that as it may, if a fence is already closed, it seems very wrong to delete an existing closing fence (which may be quite far to the left) away. E.g, if you are at the end of `f(x)=a-b-c-d-e-f` and type space, you end up with `f(x=a-b-c-d-e-f`. That seems really strange. Also, note that there is no closing fence, either in the LaTeX field below on that page of when I copy the expression to a text editor (which should show the LaTeX), so even if it was suppose to add a closing fence, it doesn't.

Another bug (no matter whether you agree that it should close a fence or not), is that if you type a space and there is no open fence, then a `.` shows up (both display and LaTeX). E.g., start with `a+b` and type a space. Were you trying to get it to be `\right.`?
