### ISSUE TITLE
Cursor position jumps to start on backspace after completion

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#137]
## Description
The insertion cursor jumps to the start of an expression after deleting some latex substitutions. I might have seen this for other substitutions, but this is a reproducible case to work on.

## Steps to Reproduce
1. Open `mathlive/examples/basic/index.html` and click after the `=`
2. Type `\alpha` followed by a space. Great -- the Greek letter appears and insertion point is good.
3. Type a backspace. The alpha goes away but the insertion point is at the start of the line as shown below:

![image](https://user-images.githubusercontent.com/1545836/52591246-4f794e00-2df8-11e9-809d-02eaf14d0a73.png)

**Comment by arnog** [comment]
Fixed with 46c9140
