### ISSUE TITLE
Modify / Custom popover

### ISSUE THREAD

**Issue by aldoblack** [arnog/mathlive#1377]
## Description

Is there any way to modify the popover list? For example when I type `\sqr` it suggests Square Root. Is there any way that when creating new macros, it is added to Popover list as well?

## Steps to Reproduce

![ezgif-1-40da840f22](https://user-images.githubusercontent.com/7981133/157993490-78ab47be-dc9b-448c-9bea-dd580385841e.gif)

### Actual Behavior

The popover does not work for custom macros.

### Expected Behavior

Suggest a custom text. Example, when typing `\square_roo`, it should suggest to custom configurable text.

**Comment by arnog** [comment]
The popover list is not currently customizable.

However, I've pushed a change so that macros will now be eligible as an option in  the popover. Let me know if that works for you.
