### ISSUE TITLE
Use keyboard without mathfield

### ISSUE THREAD

**Issue by melvinotieno** [arnog/mathlive#1388]
## Description

The situation that I am in is I have a contenteditable div which functions as a Rich Text Editor. I also need to include mathematical expressions in it hence where mathlive comes in. So my question is, is it possible to use the keyboard without the mathfield and display the information on the editor as the keys are pressed on the virtual keyboard?

**Comment by melvinotieno** [comment]
I am using CKEditor as a Rich Text Editor. I would like to use it directly with the mathlive keyboard instead of the mathfield

**Comment by arnog** [comment]
I'm afraid this is not possible. The mathfield implements the layout algorithms, so without the mathfield it would not be possible to display the math correctly.

**Comment by melvinotieno** [comment]
Okay thanks. I'll think of a different kind of way to incorporate the two.

**Comment by jeroenhabets** [comment]
> Okay thanks. I'll think of a different kind of way to incorporate the two.

@melvinotieno I just started looking for the same; an affordable Math keyboard for CKEditor and stumbled upon your issue here. 
Did you ended up getting Mathlive to work with CKEditor? Happy Easter, Jeroen

**Comment by melvinotieno** [comment]
Hello @jeroenhabets, sorry for the late reply and thank you for the Happy Easter wishes. How I went on to implement this is by adding a custom button on the editor, which opens up a modal dialog. This dialog has the mathfield element and keyboard. Once an equation is entered to satisfaction and the dialog is closed, the equation is appended on the editor depending on where the cursor was.

**Comment by jeroenhabets** [comment]
Hello @melvinotieno, that sounds interesting. Though the idea is clear, do you have a demo somewhere per chance? Cheers!

**Comment by melvinotieno** [comment]
@jeroenhabets again, apologies for the late reply. Did you have it figured out? With the implementation that I made, no you cannot edit the injected equation.

Sending an implementation demo you requested however, it is not for ckeditor

file:///home/melvin/Videos/Screencasts/Screencast%20from%2005-20-2022%2002:26:50%20PM.webm

**Comment by melvinotieno** [comment]
@jeroenhabets How I would implement the edit functionality, I would check for text selection in the text area and pass the content (latex) to the dialog that displays math-field element. After editing, I would replace the selection with the new latex from the math-field element

**Comment by jeroenhabets** [comment]
@melvinotieno Thanks and definitely no apologies needed (grateful for reply). My team hasn't dived into it yet. I was just surveying the possibilities. Decision has been postponed until later this year.

Regarding the editing; it would need some kind of smart selection; potentially enlarging it (to contain the full expression) or shrinking it (down to the expression).

**Comment by melvinotieno** [comment]
@jeroenhabets you could do it your way and I can see that working but I meant using the javascript getSelection api. After getting the text (latext), I would then pass it as default value to math-field element then edit the equation.
