### ISSUE TITLE
Angular13 npm install giving error.

### ISSUE THREAD

**Issue by k2rta** [arnog/mathlive#1397]
Could not find a declaration file for module '@cortex-js/compute-engine/dist/math-json.min.esm.js'. 'math-client-angular/node_modules/@cortex-js/compute-engine/dist/math-json.min.esm.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/cortex-js__compute-engine` if it exists or add a new declaration (.d.ts) file containing `declare module '@cortex-js/compute-engine/dist/math-json.min.esm.js';`

installing cortex did nothing,

Does anyone have any ideas how to fix this?

**Comment by k2rta** [comment]
Also accepting solutions for Vue or React apps

**Comment by arnog** [comment]
This sounds like this may be a problem with an Angular wrapper, not with MathLive. Perhaps you could file an issue with that project? Also, it might be helpful if you included a project that can be used to reproduce/debug this issue.

**Comment by anisabboud** [comment]
This error was fixed in [`0.73.7`](https://github.com/arnog/mathlive/blob/master/CHANGELOG.md#0737-2022-05-29) - see https://github.com/arnog/mathlive/issues/1467.
