### ISSUE TITLE
Suggestion for getOriginalContent

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#14]
## Description
`getOriginalContent` is very useful for extracting the math content from the page after mathlive has turned it into pretty math.

However, it is "fragile" because it only works for a single piece of math in an element, and if there is any whitespace inside the element, `getOriginalContent` won't find it. E.g, calling `getOriginalContent` on the following `div` works:
```xml
    <div>$$x^2+1$$</div>
```
but calling it on this div will not work due to the whitespace:
```xml
    <div> $$x^2+1$$ </div>
```
Potentially, there could be multiple pieces of math inside the `div`

## Suggestion
`getOriginalContent` currently returns a string. It can be generalized to return an array of strings, one for each piece of math inside of the element. This would allow it work for several pieces of math in an element. More importantly for my usage, it would mean that whitespace would not be the difference between working correctly and failing to return an answer.

**Comment by arnog** [comment]
`getOriginalContent()` has been deprecated.
