### ISSUE TITLE
Trying to install mathlive but getting a node version error

### ISSUE THREAD

**Issue by melvinotieno** [arnog/mathlive#1406]
## Description

I am using node 16.14.0. When trying to install mathlive, I get the following error

`error @cortex-js/compute-engine@0.4.4: The engine "node" is incompatible with this module. Expected version ">=17.8.0". Got "16.14.0"`

**Comment by arnog** [comment]
Hmmm... the message seems to be pretty clear...

**Comment by melvinotieno** [comment]
But why would the library force usage of a version of node that is higher than the LTS version?

**Comment by arnog** [comment]
I've tested with the LTS version `16.14.2` and it works with it, so I've adjusted the requirements to this version instead of `17.8.0`.

**Comment by melvinotieno** [comment]
Great thanks
