### ISSUE TITLE
Documentation difficult to navigate

### ISSUE THREAD

**Issue by johanneswilm** [arnog/mathlive#1418]
I am trying to upgrade MathLive from 0.59 to 0.70. For now I just want the same features as earlier but with any bugfixes that have come since. So I'm looking for an option to turn off all the sounds. Browsing here: https://cortexjs.io/docs/mathlive/ it says "See MathfieldOptions for more details about these options." but then I don't see how I can get to that part of the documentation. Using the search feature to look for "MathfieldOptions" I don't find anything either.

**Comment by arnog** [comment]
Thanks for reporting this. Most public data structures were incorrectly not exported, and therefore did not appear in the documentation. This should be fixed now (it may take a few minutes for the cached cortexjs.io to update).
