### ISSUE TITLE
MathML generation error involving sin^2

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#142]
## Description
$text('mathML') returns incorrect MathML for `\sin ^2\left(x\right)`. It returns
```<mrow><msup><mo>sin</mo><mn>2</mn></msup><mrow><mo>(</mo><mi>x</mi><mo>)</mo></mrow></mrow>```

## Steps to Reproduce
I have attached a file that reproduces the problem:
[sinbug.zip](https://github.com/arnog/mathlive/files/2873676/sinbug.zip)

Unzip this to get an HTML file (can't attach HTML files directly) and that will show the error. This is a clone of examples/basic/index.html and the file references are relative to that location.

**Comment by arnog** [comment]
What mathML do you expect? This appears to be valid mathML and it displays correctly in Safari.

<img width="847" alt="screen shot 2019-02-17 at 6 42 29 pm" src="https://user-images.githubusercontent.com/760798/52924974-e2782380-32e3-11e9-84cb-3bf99a02117c.png">

**Comment by NSoiffer** [comment]
That is indeed the correct MathML, but if you type `sin^2  (x)` ('space' to get out of exponent), you see different MathML:
```<mrow><mo extid="phcusk">sin</mo><mo> &ApplyFunction; </mo><mrow><mo extid="phcuso">(</mo><mi extid="phcusm">x</mi><mo extid="phcuso">)</mo></mrow></mrow>```
(apologies, I apparently pasted the correct in the initial bug report). Notice that there is no `msup`.

If you have trouble reproducing it, open the attached file in the initial bug report -- perhaps one of the config settings is causing the bug.

**Comment by arnog** [comment]
OK, got it. This happens only when typing the formula, not if pasting it.
