### ISSUE TITLE
Bigger grouping symbols (like parentheses) don't seem to render

### ISSUE THREAD

**Issue by lunchbreak22** [arnog/mathlive#1420]
A picture (screenshot) worth thousand words [here](https://i.ibb.co/fMnqH9C/screen.png).

The original input at https://cortexjs.io/mathlive/ is

` <script src="//unpkg.com/mathlive"></script>`
` <math-field virtual-keyboard-mode=manual>`
`  x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}`
` </math-field>`

Placing the formula (after the equals sign) between `\left(` and `\right)`, or between `\bigl(` and `\bigr)`, or other similar commands, produces regular-sized parentheses.

Is it the same for you? How to enlarge the parentheses around the formula?

Thank you

**Comment by arnog** [comment]
Hmm... that's really interesting.

It is working for me:

<img width="382" alt="Screen Shot 2022-04-11 at 15 59 46" src="https://user-images.githubusercontent.com/760798/162846872-2e2fd66c-7f63-4dbe-9c84-22a2a21a1055.png">

However, I noticed a few things from your screenshot. You appear to be using a high-contrast theme. I assume this is on Windows (the high-contrast theme on Mac looks different)? I doubt this would affect the rendering of the brackets, though.

On the other hand, the font also  appears to be different (the shape of the `x` is very noticeably different).  Do you have some settings that modify the fonts being used? This could explain the difference with the appearance of the brackets.

I assume you are seeing this when looking at it on `cortexjs.io`. If you are seeing this in your own site, note that you must ensure that the custom fonts are accessible (see https://cortexjs.io/mathlive/guides/integration/ for some details).

**Comment by lunchbreak22** [comment]
...
