### ISSUE TITLE
The script uri "https://unpkg.com/mathlive" produces errors and warnings

### ISSUE THREAD

**Issue by lunchbreak22** [arnog/mathlive#1421]
I'm currently trying to load mathlive into a page using this code:

`<p>$$\frac{\pi}{2}$$</p>`
`<script src="https://unpkg.com/mathlive"></script>`
`<script>`
`window.addEventListener('DOMContentLoaded',`
`() => MathLive.renderMathInDocument()`
`);`
`</script>`
`<math-field>\sqrt[2]{5}\frac{2}{5}</math-field>`

but I get a bunch of errors and warnings:

`HTTP load failed with status 404. Load of media resource https://unpkg.com/sounds/plonk.wav failed.`
`HTTP load failed with status 404. Load of media resource https://unpkg.com/sounds/keypress-standard.wav failed.`
`HTTP load failed with status 404. Load of media resource https://unpkg.com/sounds/keypress-delete.wav failed.`
`HTTP load failed with status 404. Load of media resource https://unpkg.com/sounds/keypress-return.wav failed.`
`HTTP load failed with status 404. Load of media resource https://unpkg.com/sounds/keypress-spacebar.wav failed.`

`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Main-Regular.woff2 [HTTP/2 404 Not Found 43ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Main-BoldItalic.woff2 [HTTP/2 404 Not Found 66ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Main-Bold.woff2 [HTTP/2 404 Not Found 54ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Main-Italic.woff2 [HTTP/2 404 Not Found 48ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Math-Italic.woff2 [HTTP/2 404 Not Found 37ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_AMS-Regular.woff2 [HTTP/2 404 Not Found 37ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Math-BoldItalic.woff2 [HTTP/2 404 Not Found 31ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Caligraphic-Regular.woff2 [HTTP/2 404 Not Found 40ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Caligraphic-Bold.woff2 [HTTP/2 404 Not Found 48ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Fraktur-Regular.woff2 [HTTP/2 404 Not Found 43ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Fraktur-Bold.woff2 [HTTP/2 404 Not Found 28ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_SansSerif-Regular.woff2 [HTTP/2 404 Not Found 38ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_SansSerif-Bold.woff2 [HTTP/2 404 Not Found 64ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_SansSerif-Italic.woff2 [HTTP/2 404 Not Found 56ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Script-Regular.woff2 [HTTP/2 404 Not Found 53ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Typewriter-Regular.woff2 [HTTP/2 404 Not Found 46ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Size1-Regular.woff2 [HTTP/2 404 Not Found 38ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Size2-Regular.woff2 [HTTP/2 404 Not Found 75ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Size3-Regular.woff2 [HTTP/2 404 Not Found 67ms]`
`GEThttps://unpkg.com/fonts@0.0.2/KaTeX_Size4-Regular.woff2 [HTTP/2 404 Not Found 59ms]`
`GEThttps://unpkg.com/sounds@1.0.2/plonk.wav [HTTP/2 404 Not Found 27ms]`
`GEThttps://unpkg.com/sounds@1.0.2/keypress-standard.wav [HTTP/2 404 Not Found 52ms]`
`GEThttps://unpkg.com/sounds@1.0.2/keypress-delete.wav [HTTP/2 404 Not Found 31ms]`
`GEThttps://unpkg.com/sounds@1.0.2/keypress-return.wav [HTTP/2 404 Not Found 40ms]`
`GEThttps://unpkg.com/sounds@1.0.2/keypress-spacebar.wav [HTTP/2 404 Not Found 36ms]`
`downloadable font: download failed (font-family: "KaTeX_Main" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Main-Regular.woff2`
`downloadable font: download failed (font-family: "KaTeX_Main" style:italic weight:700 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Main-BoldItalic.woff2`
`downloadable font: download failed (font-family: "KaTeX_Main" style:normal weight:700 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Main-Bold.woff2`
`downloadable font: download failed (font-family: "KaTeX_Main" style:italic weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Main-Italic.woff2`
`downloadable font: download failed (font-family: "KaTeX_Math" style:italic weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Math-Italic.woff2`
`downloadable font: download failed (font-family: "KaTeX_AMS" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_AMS-Regular.woff2`
`downloadable font: download failed (font-family: "KaTeX_Math" style:italic weight:700 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Math-BoldItalic.woff2`
`downloadable font: download failed (font-family: "KaTeX_Caligraphic" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Caligraphic-Regular.woff2`
`downloadable font: download failed (font-family: "KaTeX_Caligraphic" style:normal weight:700 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Caligraphic-Bold.woff2`
`downloadable font: download failed (font-family: "KaTeX_Fraktur" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Fraktur-Regular.woff2`
`downloadable font: download failed (font-family: "KaTeX_Fraktur" style:normal weight:700 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Fraktur-Bold.woff2`
`downloadable font: download failed (font-family: "KaTeX_SansSerif" style:italic weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_SansSerif-Regular.woff2`
`downloadable font: download failed (font-family: "KaTeX_SansSerif" style:normal weight:700 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_SansSerif-Bold.woff2`
`downloadable font: download failed (font-family: "KaTeX_SansSerif" style:italic weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_SansSerif-Italic.woff2`
`downloadable font: download failed (font-family: "KaTeX_Script" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Script-Regular.woff2`
`downloadable font: download failed (font-family: "KaTeX_Typewriter" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Typewriter-Regular.woff2`
`downloadable font: download failed (font-family: "KaTeX_Size1" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Size1-Regular.woff2`
`downloadable font: download failed (font-family: "KaTeX_Size2" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Size2-Regular.woff2`
`downloadable font: download failed (font-family: "KaTeX_Size3" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Size3-Regular.woff2`
`downloadable font: download failed (font-family: "KaTeX_Size4" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://unpkg.com/fonts/KaTeX_Size4-Regular.woff2`

And [this](https://i.ibb.co/QJt96mR/new-screen-1.png) is the output (the index of radical sign is in the wrong place, other than that it looks fine).

But replacing `<script src="https://unpkg.com/mathlive"></script>` with `<script src="https://unpkg.com/mathlive/dist/mathlive.min.js"></script>` makes everything work. [Here](https://i.ibb.co/kD3M3Gb/new-screen-2.png)'s the output.

I suspect this is somehow related to the previous issue I had with the parentheses.

What could be the problem?

Thank you, and sorry for the wall of text this message turned out to be.

**Comment by arnog** [comment]
Fixed in `0.71.0`
