### ISSUE TITLE
Removing/Disabling Macros

### ISSUE THREAD

**Issue by jakeoeding** [arnog/mathlive#1422]
## Description
I'm using a math field, but would like to remove/disable all the default macros. 

The documentation hints this is possible when it says, "To add or **remove** macros use `setOptions({macros: ...})`." However, I don't see any specific examples showing how to do this.

I've tried a few of things, namely:
1. Simply passing an empty object to setOptions like: `setOptions({macros: {}})`
2. Fetching all the default macros with `getOption('macros')`, stubbing them out with empty objects, and then passing that back to setOptions

Perhaps I'm misunderstanding something. If there is an already established way to remove or disable the default macros, please let me know! 

### Actual Behavior
After taking either of the approaches above, macros still work as before, i.e. they are not disabled.

Perplexingly, if I call `getOption('macros')` after each of the approaches above, the results suggest to me that it should have worked. For example, after method 1 above, `getOption('macros')` yields  an empty object: `Object { }`.

### Expected Behavior
Removing all default macros by overwriting them permanently disables them for the lifetime of the math field

### Environment
Note: I'm using the math field inside a React component

**MathLive version**
0.69.8

**Browser**
I'm seeing this across multiple browsers, specifically Chrome and Firefox

**Comment by arnog** [comment]
The correct way to do this is indeed `setOptions({macros: {}})`. However, there was a problem where the default macros would still be used in some cases. This has now been fixed.

**Comment by jakeoeding** [comment]
Thanks for the quick resolution! May I ask when the next planned npm release will be?
