### ISSUE TITLE
Error : Cannot read properties of undefined (reading 'treeBranch')

### ISSUE THREAD

**Issue by jongjunpark** [arnog/mathlive#1425]
## Description
This error does not exist a specific pattern. It occurs frequently if I just keep writing any text.
![image](https://user-images.githubusercontent.com/60080679/163762860-a6c8bac9-b0d3-473e-96e4-8f3ac22b41be.png)
```
TypeError: Cannot read properties of undefined (reading 'treeBranch')
(anonymous function)
http://unpkg.com/mathlive:2:572724
Na
http://unpkg.com/mathlive:2:573525
moveDown [as fn]
http://unpkg.com/mathlive:2:582005
(anonymous function)
http://unpkg.com/mathlive:2:901269
$c.executeCommand
http://unpkg.com/mathlive:2:901800
Ja
http://unpkg.com/mathlive:2:603421
keystroke
http://unpkg.com/mathlive:2:890607
HTMLTextAreaElement.<anonymous>
http://unpkg.com/mathlive:2:888646
HTMLTextAreaElement.sentryWrapped
```
## Steps to Reproduce

1. Load CDN in **React base html file**
```
<script src="//unpkg.com/mathlive"></script>
```
2. add math-field tag as below
```
<math-field virtual-keyboard-mode=manual>
  x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}
</math-field>
```
3. just constantly Typing anything. 
4. error (it occur certain situations but there is no exact pattern)

### Actual Behavior

Error occurs like attached screenshot.

### Environment

**MathLive version** recently

**Operating System** [macOS]

**Browser** [Chrome]

**Comment by jongjunpark** [comment]
I found pattern. Pressing multiple keys at the same time, error occurs. (I tried left-arrow key + up-arrow key + another key)
but this web(https://cortexjs.io/mathlive/) not found this error.

**Comment by arnog** [comment]
Can you try to load the debug library in order to get a better stack trace?

```html
<script src="//unpkg.com/mathlive/dist/mathlive.js"></script>
```
