### ISSUE TITLE
parsing rationnal reduce this rationnal automatically... a bad idea.

### ISSUE THREAD

**Issue by lhotejc** [arnog/mathlive#1426]
## Description

ce.parse('\\frac{8}{10}').json return  ["rationnal", 4, 5] and it is a bad choice for me.
Why it is not ["rationnal", 8, 10] ?
in fact ce.parse('\\frac{8}{10}').canonical.json is ["rationnal", 4, 5] and it's correct, but I can't use ce.parse() to look if a student knows the reduced form... If his response is 8/10 in mathField, and I parse it, I can't see 8/10 but only 4/5 that is the good answer he don't type.

![image](https://user-images.githubusercontent.com/59118750/163870150-2cb09461-d573-49b7-a358-77dd5ac9707b.png)

### Expected Behavior

Why do not keep ["rationnal", 8, 10] for json translation and ["rationnal", 4, 5] for the canoncal form ?

**MathLive version**
0.4.4

**Comment by arnog** [comment]
Maybe not so much a bad idea as a bug. Thanks for reporting the issue!

**Comment by arnog** [comment]
Fixed in ComputeEngine 0609cc3fa6c207649a75a79522fb5ff23f79bb4a

**Comment by arnog** [comment]
Published in `mathlive@0.72.0`

**Comment by lhotejc** [comment]
Sorry. I will update my module.
Thanks for this quick answer and for all work.


Le mar. 19 avr. 2022 à 02:41, Arno Gourdol ***@***.***> a
écrit :
