### ISSUE TITLE
LaTeX and MathML not updated on close paren

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#143]
## Description
mathlive provides a grayed out closing bracket after typing an opening bracket. It appears that `\right?` is used to represent the potential matching bracket. However, when the closing bracket is typed, it doesn't go away until after another character is typed.

## Steps to Reproduce
1. Type `(x)`

Here's a screen shot showing the result:
![image](https://user-images.githubusercontent.com/1545836/52922804-d63a9900-32d8-11e9-9e05-beb0bbabb381.png)

This is shown via `contentDidChange`, so it is possible that  `contentDidChange` is firing at the wrong time, but that seems unlikely.

## A Second Bug
Note there is also a second bug here: The MathML for the `\right?` is just `?`. I suppose that there isn't anything really good to use, but I suspect it would be better to not generate anything for that grayed out character because it hasn't been typed. Second best option would be to include the proper character. A third option would be to use some special Unicode character, possibly in private space, to represent the `\right?`.

**Comment by arnog** [comment]
I can't reproduce this. There was a bug fixed recently when `onContentDidChange` would not always fire it. You may be running into this. Make sure you have the latest version.

**Comment by NSoiffer** [comment]
I did a pull before filling the bug report. I do see you just did an
update, and that does fix the problem.
