### ISSUE TITLE
Change the default equation in all latex output

### ISSUE THREAD

**Issue by michelmar** [arnog/mathlive#1445]
## Can we change the output format
The output of mathlive is rendered by katex, because of this I'm having some issues, I can't control the output to be in \begin{equation} mode, because I want to have numbered equations as well. Another question is how I change the default delimiters, I could only see something close in the Auto render Options.

**Comment by arnog** [comment]
You can customize the format exported to the clipboard using the [`onExport`](https://cortexjs.io/docs/mathlive/?q=onExport) hook.

I don't understand your question about delimiters.

**Comment by michelmar** [comment]
Thanks a lot ! That's exactly what I was looking for.

**Comment by michelmar** [comment]
About the delimiters, I'm having some issues with the output compatibility between katex and mathlive. Is there a major difference between them?

**Comment by arnog** [comment]
Could you give me an example?

**Comment by michelmar** [comment]
\begin{equation*} \sum_{n=1}^{\infty}\frac{1}{n^2}=\frac{\pi^2}{6}\colorbox{yellow}{\[ asdfasdfa \]}\,\colorbox{yellow}{\[ sdfasd \]} \end{equation*}

is giving some error with the \[ 

![example](https://i.imgur.com/fD1pnot.png)

**Comment by arnog** [comment]
OK, I'm a bit confused. The equation you provided has a `[` inside the `\colorbox` command, but the error message from KaTeX would seem to indicate there was a `\[` command before the `\colorbox` command? Not sure what's going on. Maybe KaTeX is getting confused?

Anyway, KaTeX is sorta right. The equation you provided is not really valid LaTex. If you want a bracket inside the `\colorbox` command, it should be `\lbrack`'. Also, the argument f a `\colorbox` command is in text mode, if you want it displayed in math mode you need to include some `$$...$$`. I don't know what `asdfasdfa` are supposed to be. If you want it to be text, than you can leave out the `$$...$$`. I'm not sure how you got the `[` in there, though.

**Comment by michelmar** [comment]
I used the default keyboard to get this expression. I was only giving an example for you of how the output was.

**Comment by arnog** [comment]
Do you remember what keys you pressed to get this formula? I can get a formula that as a `\[`, but not the isolated `[`.
