### ISSUE TITLE
Empty subscript and superscript serialization

### ISSUE THREAD

**Issue by timmckague** [arnog/mathlive#1446]
## Description

When an empty subscript or superscript exists the latex returned from the mathfield does not necessarily "match" what I would expect based on what I visually see in the mathfield.

## Steps to Reproduce

If I type "x" , "^", "right arrow (to leave the superscript)", "2" as a user I see "x2". But then if I ask the mathfield to give me the latex, it returns "x^2", which if I were to put that back into mathlive, it would render something different than the "x2" I was intending/expecting.

<img width="836" alt="Screen Shot 2022-05-11 at 10 05 38 AM" src="https://user-images.githubusercontent.com/5762072/167869327-d65f28ab-2c81-437a-92be-2ab93d55d89d.png">

### Expected Behavior

I think I would be happy if the exported latex was either 
"x2"
or
"x^{\placeholder{box}}2"

### Environment

https://cortexjs.io/mathlive/demo/

Chrome, on Mac OSX

**Comment by arnog** [comment]
The serialized LaTeX in this case is now `x^{}2`
