### ISSUE TITLE
How can we centralize the text in the text area?

### ISSUE THREAD

**Issue by michelmar** [arnog/mathlive#1447]
I'm having some difficult time to override the default css of the textarea, I think this is happening because of ShadowRoot,
Could we pass an option in the math-live component to make something like this possible?
![](https://i.imgur.com/sbxcuwT.png)
For this result above I manually added  ` justify-content: center;`  in the element  `<span class='ML__fieldcontainer__field'>`,
Is there another option?

**Comment by arnog** [comment]
No, there is currently no option to control the alignment of the expression inside the mathfield.

**Comment by michelmar** [comment]
Do you have any interest in giving this possibility in the near future?

**Comment by arnog** [comment]
This is not a priority at the moment.

**Comment by michelmar** [comment]
Thanks, I  used the code bellow to achieve this:
`const style = document.createElement("style");
      style.innerHTML = `
        .ML__fieldcontainer__field {
        justify-content: center;
  }`;
      shadowroot.appendChild(style);`
