### ISSUE TITLE
Typing close paren after a close paren deletes earlier close paren

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#145]
## Description
If I have a close parenthesis to the left of the insertion point, typing `) ` (space) causes it to disappear.

## Steps to Reproduce
1. Open `mathlive/examples/basic/index.html`. It initializes the input field with f(x)=
2. Click after the `=` and type a `)`.

You get `f(x=)` -- the close paren has caused the earlier close paren to go away. If this is a feature, I think it is one that would surprise most users. I would expect it to be `f(x)=)`

Notice that in the latex interpretation below, it is different than what is displayed: it is `f(x)=`

**Comment by arnog** [comment]
That's the expected behavior with smartFence. You can turn off smartFence with `setConfig({smartFence: false})`

**Comment by NSoiffer** [comment]
I'll turn it off in MathShare, but you might want to rethink this,
especially as a default being on. I'd be surprised is the vast majority of
users weren't surprised, and more importantly, would not want this to
happen.
