### ISSUE TITLE
can't use array shortcuts

### ISSUE THREAD

**Issue by michelmar** [arnog/mathlive#1455]
The shortcuts definied in #225, are working? I can't use them even with execCommand. Can you help me?

**Comment by arnog** [comment]
Could you provide some code of what you tried and describe what happened?

**Comment by michelmar** [comment]
I'm trying to add more rows and colums in matrix, multiline, and in environments as equation, aligned, etc. But none of the shortcuts are working. So I tried to listen to the keystroke event, and manually add the command, but even this way I couldn't get this to work.
Do I have to make a specific configuration to the shortcuts defined in #225  work?

**Comment by arnog** [comment]
no

**Comment by michelmar** [comment]
I'm using a pc but I  already tested these shortcuts in a mac, and I have the same results. I'm trying directly in the demo page

**Comment by michelmar** [comment]
Sorry, I think this is a duplicate of #736 . I'll be closing this issue.
