### ISSUE TITLE
Extra keyboard animations when changing focus between math fields

### ISSUE THREAD

**Issue by dannygreg** [arnog/mathlive#1456]
## Description

Virtual keyboard animates out and back in when changing focus from one `math-field` to another. We've run into this in a few different ways in Brilliant lessons and it's causing a noticeable amount of disorientation if we have 2 or 3 inputs for a given problem. 

## Steps to Reproduce

1. Create a demo page with two `math-field`s with `onFocus` as their `virtual-keyboard-mode`
3. Focus one of the fields
4. Focus the other, either by clicking on it or tabbing

### Actual Behavior

As you change from one field to the other the keyboard slides out and then back in.

### Expected Behavior

The keyboard (assuming the same layout), should stay visually persistent.  

### Environment

**MathLive version** `master` (e259559b)

**Operating System** macOS 12.3.1

**Browser** Reproduced on both Safari and Brave

### Suggested Fix

Instead of directly fixing the bug, I think what's really missing here is a `virtual-keyboard-mode` that allows the caller ultimate control of whether the keyboard is hidden or shown. We have `showVirtualKeyboard` and `hideVirtualKeyboard`, however regardless of mode the keyboard will be hidden due to the `onBlur` in `mathfield-private.ts`

Instead of always disabling it, allowing it to be left up to the caller would allow them to handle the hiding and showing as relevant to their application.

I'm happy to open a PR to that effect if that sounds reasonable.

**Comment by arnog** [comment]
Yes, that makes sense, and that has been suggested before. See related issues #1345, #1227, #1121.

A PR to address this would be welcome.

I would suggest adding a new `virtual-keyboard-mode`, perhaps `"persistent"`? When this mode is set, the keyboard would not appear automatically on focus, and  not be dismissed on blur, but instead would be entirely under programmatic control. Maybe need a `"manual-persisten"` mode as well that would show the virtual keyboard toggle, but otherwise be like persistent?

There are a few interesting cases that need to be handled: 
- two mathfields with different keyboard layouts: the keyboard layout should update to reflect the applicable layout for the focused mathfield
- a key pressed on the virtual keyboard when no mathfield is focused, or when an input element other than a mathfield is focused (a text area or input field). Not sure what the right behavior is. Perhaps generate a synthetic keyboard event and send it to the focused element?

**Comment by hhabakuk** [comment]
Glad to see some progress for #1227 solution!  Having full control over keyboard would be perfect. I have the use-case where  `manual-persistent` mode should be used but I think the case would be very easy to handle with `persistent` mode so not sure if adding this mode is worth the effort.

**Comment by dannygreg** [comment]
I believe we can close this out with my recent PRs now merged. It's now possible to use a shared keyboard, with the mode set to `off` to achieve complete control of when the keyboard is shown and hidden.

**Comment by dannygreg** [comment]
Hey @hanshs - the trick is to use a shared keyboard. You can then use a blur event (with the help of a short timeout) to decide whether to hide the keyboard based on which element has focus. 

We have this working in production. We found that this was more effective than handling it automatically in MathLive as we could use our own DOM elements as part of the opening/closing decision.

**Comment by arnog** [comment]
OK, I think I've improved the behavior of the virtual keyboard with multiple mathfields on a page.

All you need to do now is to call `makeSharedVirtualKeyboard()` at some point before the user interacts with a mathfield. Note that the property `virtualKeyboardMode` is specific to a mathfield, not to the shared virtual keyboard (i.e. it's not a valid property when passed to `makeSharedVirtualKeyboard()`).

You do not need to set the `useSharedVirtualKeyboard` property (this property is now only necessary when using mathfields in an iframe).

You should set the `virtualKeyboadMode` property on the mathfields to `auto`, `onfocus` or `manual`, depending on the desired behavior.

You do not need to intercept the `onFocus` or `onBlur` events, or change the virtual keyboard visibility manually. The shared virtual keyboard will now automatically do the right thing, that is, stay visible if changing focus from one mathfield to another,  or hiding itself if changing focus to an element that's not a mathfield (after a 300ms delay).

**Comment by hanshs** [comment]
Thanks all for the helps! Is there a way for me to test the unreleased version via npm?

**Comment by arnog** [comment]
`mathlive@0.74.0` on npm includes those changes

**Comment by arnog** [comment]
I think this is an interaction with stackblitz. Could you try in a regular web page?

**Comment by hanshs** [comment]
While creating an example in a vanilla/no-framework type of setup, I managed to reproduce the faulty behavious I described previously, heres the example repo - https://github.com/hanshs/mathlive-vite-vanilla-ts 
In `/src/main.ts` there are instructions on how to toggle between the faulty and correct behaviour.

Looks like calling `setOptions` for a math-field instance, causes the behaviour to break.

**Comment by arnog** [comment]
Yes, `makeSharedVirtualKeyboard()` should be called as early as possible. I'll look into it to see if that constraint can be relaxed...

**Comment by arnog** [comment]
OK, I looked into it, but it's not a trivial change. Any mathfield elements that have been connected to the DOM before `makeSharedVirtualKeyboard()` has been called have been setup to *not* use a shared virtual keyboard instance (i.e. they have created their own virtual keyboard instance). If they would expect to be changed *after* `makeSharedVirtualKeyboard()` is changed they would have to be unmounted from the DOM, then remounted.

I'll clarify in the documentation that `makeSharedVirtualKeyboard()` should be called as early as possible, and before mathfield elements are connected to the DOM.
