### ISSUE TITLE
Integral (and summation) bounds deleted when more than one char is entered

### ISSUE THREAD

**Issue by picodeflank** [arnog/mathlive#1465]
## Description

When entering an integral (or sum) if you enter more that one character in the upper/lower bound the, bounds will disappear and you will now be editing what is inside of the integral. The same thing happens when entering a sum. I have found that the only way to circumvent this is by pasting the bounds into the editor. However, this is not ideal. I don't recall it being like this in the past, so I assume that this is not an intended feature.

![bug-1-1](https://user-images.githubusercontent.com/64933569/170145828-91de57b7-764b-486e-bb4e-b296ec71786d.PNG)
->
![bug-1-2](https://user-images.githubusercontent.com/64933569/170145846-e1696460-35c5-4d8d-8710-f0d8ccde42b5.PNG)
->
![bug-1-3](https://user-images.githubusercontent.com/64933569/170145857-c3440255-c56f-4afb-a242-9c0e0c452864.PNG)

what was typed: int -> 1 -> 2

## Steps to Reproduce

for integral
1. focus on the equation editor
2. type "int"
3. begin entering the upper bound, note: the bug occurs when the bound is more than one character

for sum
1. focus on the equation editor
2. type "sum"
3. begin entering the upper bound, note: the bug occurs when the bound is more than one character
### Actual Behavior

The bounds are deleted and you are now editing what is inside the integral/sum.

### Expected Behavior

You should be able to enter more than one character for the bounds. The bounds should not be deleted when more than one character is typed.

### Environment

**MathLive 2022-05-24**

**Operating System** windows

**Browser** chrome

**Comment by arnog** [comment]
Fixed in `0.73.3`
