### ISSUE TITLE
Copying equations with matrix in them freezes the browser

### ISSUE THREAD

**Issue by ImGelu** [arnog/mathlive#1475]
## Description

If you copy (via keyboard shortcuts or the virtual keyboard) an equation containing a matrix, the content will not be copied in the clipboard and the whole browser freezes

## Steps to Reproduce

1. Insert a matrix
2. Open the virtual keyboard
3. Press the copy to clipboard button

### Actual Behavior

The browser file freezes and you can't do anything

### Expected Behavior

The content is copied to the clipboard, without the browser crashing

### Environment

**MathLive version**: latest (0.73.6), worked fine in previous versions (at least in 0.73.4)

**Operating System**: Windows 10

**Browser**: Chrome

**Comment by arnog** [comment]
I think this was a configuration error which I hope to have fixed in `mathlive@0.73.7`. Let me know if you still encounter this issue with this version, though.

**Comment by ImGelu** [comment]
> I think this was a configuration error which I hope to have fixed in `mathlive@0.73.7`. Let me know if you still encounter this issue with this version, though.

Works perfectly now (and the #1462 is also fixed again). Thanks a lot!
