### ISSUE TITLE
onContentDidChange not catching placeholder change(?)

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#148]
## Description
Some MathML is not getting updated properly after a placeholder is replaced (I think that is the critical item).

## Steps to Reproduce
Either change `example/basic/index.html` to include
```
        generateID: true,
	onContentDidChange: mf => {
            document.getElementById('mml').textContent = mf.$text('mathML');
            document.getElementById('latex').textContent = mf.$latex();
        },
```
or use this file: [mathml.zip](https://github.com/arnog/mathlive/files/2877419/mathml.zip) (unzip first).

1. Delete the existing expression and type `3/`
The MathML is
```<mfrac><mn extid="1f">3</mn><mi>&nbsp;</mi></mfrac>```
Note that the `&nbsp;` doesn't have an `id`

2. Type `4`.
The MathML is
```<mfrac><mn extid="1a6gi6">3</mn><mn>4</mn></mfrac>```
Again, no `id` on the denominator.

If you type another char, you'll get the id and it will be there if you use backspace to delete the extra char. 

That's not the case if you delete all the way to get the placeholder -- so maybe that's a separate bug.

**Comment by arnog** [comment]
When `onContentDidChange` is invoked the formula has not been rendered yet, and therefore the ID has not been assigned to the new atom. Instead, you could watch for changes to the DOM representing the formula:
```
const observer = new MutationObserver(mathfieldMutationHandler);
observer.observe(document.getElementById('math-editor'), { 
    attributes: true, 
    childList: true, 
    characterData: true, 
    subtree: true 
});
```
