### ISSUE TITLE
Unexpected '$$' in output latex when using `colorbox`

### ISSUE THREAD

**Issue by kvas-damian** [arnog/mathlive#1489]
## Description

Virtual keyboard add `$$` in unexpected places in latex when using a `colorbox` button and interacting with both: virtual keyboard and latex textarea

## Steps to Reproduce

1. Open https://cortexjs.io/mathlive/demo/
2. erase the equation
3. turn on `colorbox` (yellow circle on virtual keyboard) and type in something using virtual keyboard
4. add any character using latex textarea
5. add any character using virtual keyboard

### Actual Behavior

Additional, unexpected `$$` are added to latex textarea

Example:
`$$ \colorbox{yellow}{$$25$$} $$a9`

### Expected Behavior

No additional `$$` are injected into latex:

`\colorbox{yellow}{$$25$$}a9`

### Environment

**MathLive version**: 0.73.7

**Operating System** Ubuntu

**Browser** Chrome 101

**Comment by arnog** [comment]
The second argument of the `\colorbox` command is in text mode by default. In order to display mathematical content correctly the `$$` are necessary.

**Comment by kvas-damian** [comment]
I understand that we need `$$` inside `{}`, but in the example output I got `$$` before and after `\colorbox` command. In my case, such latex code breaks rendering in KaTeX

**Comment by arnog** [comment]
How did you get the additional `$$`? What did you type? I couldn't reproduce this using step (4) and (5).

**Comment by arnog** [comment]
OK,  I've found a combination that triggers this: `1+2/3`
