### ISSUE TITLE
Style ML__fieldcontainer

### ISSUE THREAD

**Issue by benbro** [arnog/mathlive#1500]
## Description

Is there a way to style the ML__fieldcontainer element? I'm trying to set ```.ML__fieldcontainer {min-height: auto;}```
Is it possible to add part="fieldcontainer" similar to part="virtual-keyboard-toggle"?

### Environment

**MathLive version**
v0.72.3

**Comment by arnog** [comment]
I've added the `container` (for `.ML__fieldcontainer`) and `content` (for `.ML__fieldcontainer__field`) parts.

**Comment by Tony2** [comment]
What is recommended way to get the above changes into my project? It seems it's not in the latest npm release (0.77.0) yet?
