### ISSUE TITLE
Not expected output for \ne (≠) symbol

### ISSUE THREAD

**Issue by michelmar** [arnog/mathlive#1503]
## Description

![](https://i.imgur.com/U97ELeM.png)

## Steps to Reproduce

- Go to the demo page [Demo](https://cortexjs.io/mathlive/demo/)
-  Try to put \ne in the math field, 
-  Observe that the output is receveing an equal symbol

### Actual Behavior
 \ne =

**Operating System** [ Windows]

**Browser** [ Chrome]

**Comment by arnog** [comment]
I was not able to reproduce this. I went to the demo page, typed `\ne` + `RETURN` and the output field displayed `\ne`, as expected. I tried it on Chrome on macOS, Edge on Windows and Chrome on Windows.

**Comment by michelmar** [comment]
I think you have to type something more, here is a link for a video showing how I get this result:
[URL](https://imgur.com/Mg3OIum)

**Comment by arnog** [comment]
Thank you. That seems to be an important detail, indeed.

**Comment by michelmar** [comment]
Really nice that I could help somehow. Another thing that would be helpful is add the \ne symbol with the = group. I think this kind makes sense. 
![Screenshot_20220614-175335_Chrome.jpg](https://user-images.githubusercontent.com/60835138/173686870-31bd5bd4-1a8e-4362-9894-a2fb926f57f4.jpg)

**Comment by arnog** [comment]
You can set the `theme` attribute on the `<body>` tag to `dark` or `light`, i.e. `<body theme=dark>`
