### ISSUE TITLE
A problem with whitespace in the generated LaTeX encoding

### ISSUE THREAD

**Issue by sjzgit** [arnog/mathlive#1505]
## Description

For example,  π² ；
The standard LaTeX encoding should be：\pi ^2；
However, MathLive is missing whitespace. Same thing with a lot of other symbols.
![image](https://user-images.githubusercontent.com/26371424/173973955-18a3661c-ff6c-48d9-8a44-cc406702a4b6.png)

## Steps to Reproduce

1. Input π². [The Url](https://cortexjs.io/mathlive/demo/)
2. Check the code
3. Compare standard LaTeX encoding. [The Url](https://www.latexlive.com/)

### Actual Behavior

\pi^2

### Expected Behavior

\pi ^2

### Environment

**MathLive version** 0.73.7

**Operating System** [Windows]

**Browser** [Chrome]

**Comment by arnog** [comment]
In math mode TeX ignores whitespace. A space if only necessary when a command is immediately followed by an alphabetic variable, e.g. `\sin x`.

But `\pi^2` and `\pi ^ 2` are equivalent.

I don't know why latexlive.com adds whitespaces. They're not harmful, but they're not necessary either, and they are definitely not standard.

You can convince yourself of this  by looking at [this other Latex editor](https://www.codecogs.com/eqnedit.php), or [this page](https://en.wikibooks.org/wiki/LaTeX/Mathematics) about authoring math content for Wikipedia.

**Comment by sjzgit** [comment]
> 
Thank you for your answer.
The problem we ran into was that there was a lot of white space in the code for the formulas parsed out in the Office Word file, which didn't compare properly with the code for the MathLive output.
