### ISSUE TITLE
We want to use it with Quilljs editor 

### ISSUE THREAD

**Issue by ngcgolf11** [arnog/mathlive#152]
We want to implement this math editor with quilljs editor and we can use this with add another module and show button on quilljs but can it is possible. or suggest me any other editor in which we can use normal text along with mathfunctions for teacher who are not friendly with latex code

**Comment by arnog** [comment]
It should certainly be possible to write a plug-in for QuillJS that uses MathLive, but I don't know of one yet. That does sound like an interesting project, though.

**Comment by arnog** [comment]
I suggest you open an issue with QuillJS, similar to #2563, they may be able to help you on how to write a module for QuillJS.
