### ISSUE TITLE
[bug] body bottom padding doesn't get removed when using shared virtual keyboard

### ISSUE THREAD

**Issue by hanshs** [arnog/mathlive#1525]
## Description

Bottom padding CSS gets added to the HTML body element, when opening a virtual keyboard and is removed when closing the keyboard. However, when using a shared keyboard across multiple fields, it doesn't seem to detect the keyboard being closed and keeps adding to the padding each time a keyboard is opened.

## Steps to Reproduce

Can be reproduced with basic implementation of shared keyboard:
```
import * as Mathlive from 'mathlive'

const app = document.querySelector('#app')

const mathfields = [
  new Mathlive.MathfieldElement({ keyboardMode: 'onfocus' }),
  new Mathlive.MathfieldElement({ keyboardMode: 'onfocus' }),
  new Mathlive.MathfieldElement({ keyboardMode: 'onfocus' })
]

mathfields.forEach(f => app.appendChild(f))

Mathlive.makeSharedVirtualKeyboard({})
```

OR

1. Go to https://mathlive-shared-keyboard.vercel.app/
2. Focus on fields a couple of times to open keyboard
3. Inspect the HTML body style attribute

### Actual Behavior

The padding style in HTML body piles up.

![image](https://user-images.githubusercontent.com/19611757/176849123-4522c11e-866e-437e-a3b0-896883c8de6b.png)

### Expected Behavior

It should not pile up, padding should be removed each time a keyboard is closed.

### Environment

**0.76.1**

**Browser** [Chrome}

**Comment by sbondaryev** [comment]
@arnog I think that the fix for [1523](https://github.com/arnog/mathlive/issues/1523) won't catch the case of multiple instances.
So, finally we need some kind of check that padding is already set in `showVirtualKeyboard` method
```javascript
if (!/--keyboard-height/.test(padding)) {
  keyboard.originalContainerBottomPadding = padding;
  keyboard.options.virtualKeyboardContainer.style.paddingBottom = padding
    ? `calc(${padding} + var(--keyboard-height, 276px) - 1px)`
    : 'calc(var(--keyboard-height, 276px) - 1px)';
}
```

**Comment by arnog** [comment]
@hanshs note that you are not in fact using a shared virtual keyboard in the example you provide: the call to `makeSharedVirtualKeyboard()` only applies to mathfield instances created *after* the call is made, not retroactively to previously created instances. Perhaps I should have it `throw` if there are already instances on the page?

**Comment by arnog** [comment]
@hanshs ok, it's complicated. 

The inline example you have may work (use a shared keyboard), but this one (https://mathlive-shared-keyboard.vercel.app/) doesn't (doesn't use a shared keyboard). 

The constraint is not that `makeSharedVirtualKeyboard()` should be called before any mathfield instances have been connected to the page, it's that it should be called before any virtual keyboard instance have been instantiated by any mathfield instance. 

What triggers the instantiation of a virtual keyboard instance is not easy to enumerate, but amongst other things, calling `setOptions()` will.

So, my previous guidance is still valid, but the reality is more complicated than it seemed. I will add a `console.error` message if `makeSharedVirtualKeyboard()` detects it has been called too late, though.

**Comment by sbondaryev** [comment]
@arnog I think there is a general issue with changing the padding of the container?

For example the command `hideVirtualKeyboard` will erase the style of the container if the keyboard was never opened
https://github.com/arnog/mathlive/blob/eb0da9a1000463abc532ee85c3d8e3d72a7f6b8c/src/editor/virtual-keyboard-commands.ts#L242-L243
since `originalContainerBottomPadding` was never set in 
https://github.com/arnog/mathlive/blob/eb0da9a1000463abc532ee85c3d8e3d72a7f6b8c/src/editor/virtual-keyboard-commands.ts#L205

Maybe it is better to `appendChild/removeChild` to the container with the height of the keyboard?

**Comment by arnog** [comment]
@sbondaryev you're right, although hiding the keyboard before showing is not too likely, but that can also be guarded against. I'm not sure what you are suggesting instead...

**Comment by sbondaryev** [comment]
@arnog the idea was to add add remove a `div` placeholder in `virtualKeyboardContainer` instead of changing the its `padding-button` but I realized that the content  of `virtualKeyboardContainer` can be also changed - so, not a good idea.

**Comment by sbondaryev** [comment]
@arnog Ok, here is my attempt to toggle the padding by analyzing the container style using a regexp.

see PR https://github.com/arnog/mathlive/pull/1526

**Comment by arnog** [comment]
That's going in the right direction, but there's still a problem. If you have two mathfields (`mf1` and `mf2`) (without a shared virtual keyboard), and you show the keyboard on `mf1`, then on `mf2`, you will get a `mf2.showVirtualKeyboard()`, followed by `mf1.hideVirtualKeyboard()` (because `mf2` is focused, and a result of  that `mf1` is blurred), so the padding ends up removed when it shouldn't...

**Comment by arnog** [comment]
OK, I think I have a fix. It involves globally keeping track (in `window.mathlive.visibleVirtualKeyboard`) if there is a virtual keyboard being displayed, even if it is not shared, and hiding it explicitly if another virtual keyboard tries to show itself. Thanks @sbondaryev for the help in trying to get this sorted. Let me know if you still see some problems with this approach.

**Comment by sbondaryev** [comment]
@arnog Great I will close the PR then. Thank you!
