### ISSUE TITLE
Improve text in math

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#153]
## Description
When writing about math, it is not uncommon to need to add some text. For example, "When x<0, x^{2n+1} <0". mathlive has a `\text` command to indicate text, but in the editor, this is a very clumsy way of adding text.

For working out a solution to a problem, being able to easily mix text and math is very common. For students, being able to do this in a manner that isn't distracting or hard to figure out is very important.

## Suggestion
[based on discussions between @NSoiffer and @arnog]

mathlive should auto detect when something is math and something is text and automatically create the `\text`. Some ideas of triggers
* math operators such as `+` and `=` indicate that the operands should be math
* runs of characters (especially ones that form words that aren't known functions) are indications of text
* spaces and punctuation are potential switch points (space is also used to move out of superscripts, etc., so how do we know to insert a space versus move somewhere?)
* space could be considered an operator that means either "implied times" or "text space" and it's meaning is determined by it's operands. Because you don't know the right operand fully during typing, it's meaning may change as more characters are typed. Another example would be typing the sequence `i`, `if`, `if `, where the interpretation is sqrt(-1), sqrt(-1) times f, "if " (i.e,, text).
* text is more likely in some places (e.g, on the baseline) than in others (e.g, in a superscript). 
* shortcuts interact with interpreting text ("something" should include the shortcut for "in")

## Intermediate Solution
I think auto detection is hard. An intermediate solution and/or forcing text solution would make `"` as in in `"this is text"` force text mode.  `"`s would always show up in pairs. When the insertion cursor is moved outside of a quote, they disapear. Clicking in the text would make them reappear.

**Comment by NSoiffer** [comment]
A few examples/tests:
* When x<0, x^{2n+1} <0
* Find the product 28\times75.
* Graph x^2 -x+3 =0 for 0<=x<=5
* Divide by x-3 and then add x^2-1 to both sides
* Integrate f(x,y)=x^2+y^2 over the triangle with vertices (0,0), (0,1) and (1,0)
* Let D be the set {(x,y)|0≤x≤1 and 0≤y≤x}
* \int_{the unit square} f(x,y) dx dy
* slope = \frac{rise}{run}
* Given g(x) = 4x – 3, when does g(x)=0?

**Comment by arnog** [comment]
Status update: in the current build, typing a " (straight quote) will initiate text mode. Typing another one will close it and resume math mode. The text/math mode can also be toggled using the alt+= shortcut. If there is a selection, it will be converted and should roundtrip most of the time (via ASCIIMath). The default mode can also be set in config (`defaultMode`). It’s `math` by default.

**Comment by Khazuar** [comment]
Will the mode be visually indicated to the user in any way? Can we (as devs) automatically switch/remove the virtual keyboard when switching modes? In our application, we have both math-inputs (via mathlive) and text-inputs. The visual distinction for users generally is, that they do not get a virtual keyboard when focussing the input. That's supposed to tell them "you're not supposed to use anything but what you can type on your normal keyboard here!". I'd be really interested in seeing this feature realized.

**Comment by arnog** [comment]
For now (in the branch I'm using to work on this), the text mode is indicated in two ways:
- a slightly different insertion cursor (it's a bit thinner). It's a bit of a subtle change, but might be useful if you press the keyboard shortcut to switch mode (alt/option+=). It gives you a visual confirmation you are in this new mode.
- a light grey background for text zones.

I'm very interested on feedback if this works or if other feedback mechanism would be desirable.

Right now, the keyboard status does not change when the mode changes. I could add a notification when the mode changes, which would allow you to hide the keyboard if desired. Would that be useful?

And thank you for your interest in this feature. You can help by providing feedback, as well as examples of "mixed mode" equations you would see your users enter. This would help me fine tune the smart mode heuristics. 

Also, if you have some expertise in languages other than english, what natural language text you expect mixed in with your equations. In particular, I would need to know any short words (one or two letters) that could appear mixed in with an equation (in english, that would be "a", "I', "an", "be"...)

**Comment by Khazuar** [comment]
The notification option sounds useful, yes please. I imagine in other usecases than ours this might be valuable as well.

I'd love to share feedback on this feature as soon as I have some. 

Examples:

Users might type stuff like `a \equiv b \text{ mod } 3` (because they don't know there's `\mod`, but I wouldn't want to encourage that one anyway), `a \text{ is even}`, `\mid \text{Devisors of } n \mid > 3`, `n \text{ coprime to } k`, `(a_n)_{n \mathop{\in} \mathbb{N}_0} \text{ diverges}` ... at least in our case there's a lot of math that cannot be expressed without short words. For certain audiences, using words is preferable over mathematical symbols like `\forall n \in \mathbb{N}`/`\text{for all } n \text{ in } \mathbb{N}`. So it'd be great to have that option.

My first language is German, and I don't think there's that many "short words" in German to begin with. The only one I can think of right now that might appear in maths is `in`. There's plenty of "longer" words like "aus", "für", "mit", "ohne", ... that will frequently appear though. I imagine `ab` *could* appear, but I think in this context it's far more likely it's actually meant to be math ("a times b") than text.

**Comment by panoschal** [comment]
Is it possible to make smartMode work for Greek text? In the same way that when you type 3 consecutive English letters, they are automatically converted to text mode.
I think it can be solved with some regex here:
https://github.com/arnog/mathlive/blob/a0794d8631b859f358cb9148f15341c51732a590/src/editor/editor-mathfield.js#L1448
I think the only exception is "αβγ" where α, β, and γ are meant as variables and should be in math mode.

If you think this should not be addressed for the whole project (as it impacts only Greek users), I could fork Mathlive and try to implement it. I stumbled upon some difficulties using API's `onKeystroke` to handle mode changes on my project.

**Comment by NSoiffer** [comment]
The tests for text mode are pretty complex. I know I've talked with Arno about several tweaks, so changing them can be tough because of various interactions. I do agree that at some point, longer runs of Greek letters are almost certainly text, so the change at the point you suggested seems safe. There are other text/math tests though and they may need to change (someone [@arnog] would need to look in detail at all the cases). I'm sure when someone is Greek, some shorter runs make sense.  With that in mind, here are two thoughts:
1. The regular expressions that check for a letter could be made configurable so that in your case or the case of someone using a different alphabet could provide a regular expression to match their alphabet. I don't know enough about Asian languages (and others) that are character-based as opposed to alphabetic to know whether that is a help to them.
2. There is a callback `onModeChange` -- maybe it can be used in your case to "repair" a problem. However, if you are looking for something to switch to textmode and it doesn't switch, that function won't help.

**Comment by arnog** [comment]
WhenI implemented smart mode I thought about Greek (and other non-roman scripts) but I wasn't sure there was a use case for it. If you are a Greek user and believe it would be useful I'll look at it. Like Neil said, that's a tricky area so I'll need to think it through to make sure it doesn't break anything. Two questions
1/ would you want to mix Greek and English (i.e. have some words in Greek and some in Roman script?)
2/ Any other exceptions other than alpha/beta/gamma? Are there any common single letter Greek word that should be accounted for?

**Comment by itsUndefined** [comment]
π (pi) is also used in maths but if three letters have to be typed in order to switch from math to text I think that such exceptions are not an issue.

**Comment by panoschal** [comment]
> 1\. The regular expressions that check for a letter could be made configurable so that in your case or the case of someone using a different alphabet could provide a regular expression to match their alphabet. I don't know enough about Asian languages (and others) that are character-based as opposed to alphabetic to know whether that is a help to them.

This would be nice, I think. A quick search showed that a regex for Asian characters exists (probably).

> 2\. There is a callback `onModeChange` -- maybe it can be used in your case to "repair" a problem. However, if you are looking for something to switch to textmode and it doesn't switch, that function won't help.

I will try to use `onModeChange` + `onKeystroke` + `mf.perform(['switchMode', 'text'])` again and see if I can find a workaround.

> 1/ would you want to mix Greek and English (i.e. have some words in Greek and some in Roman script?)

No, we probably would not need to mix Greek and English.

> 2/ Any other exceptions other than alpha/beta/gamma? Are there any common single letter Greek word that should be accounted for?

The exceptions are:

- "αβγ" like I said before
- One or two letter words are in this space separated list `ο η το τα θα να αν οι τι με σε μα` and some variants of them
- Also there is π that currently switches to math mode automatically when pressed.
