### ISSUE TITLE
[FEATURE] Custom callback function when a keycap is pressed

### ISSUE THREAD

**Issue by Chrisb0606** [arnog/mathlive#1536]
Hi,
This feature may already exist and I potentially miss although I spent few hours in the code source and doc :-) My objective is to trigger a function (kind of submit function to assess the answer given in a mathfield) when the user clicks on a keycap on virtualkeyboard. In terms of UX, it prevent user to have to exit the mathfield to validate his answer.

Therefore, the idea is to link a callback function when a virtualKeyboard keycap is pressed.
Today, I can implement a keycap that triggers action : 
`{
          class: "action",
          label: "Next",
          command: ["performWithFeedback", "moveToNextPlaceholder"],
        },`
and it could be interesting to extend this feature to implement custom behaviour to trigger. Thanks to a callback function, I think we could achieve that.

In a simplistic view, one way to implement in a virtualkeyboard could be :
`{
          class: "action",
          label: "Submit",
          event: ["submit"],
  }`

To catch this kind of event we could use the existing method with a specific type
  answerMathField.addEventListener("action", (ev) => { //event named "submit" can be caught here }

Thanks,

Chris

**Comment by arnog** [comment]
The command you are looking for is `commit`. It will trigger a `change` event.

```js
{ class: "action", label: "Next", command: ["performWithFeedback", "commit"] }
```

```js
answerMathField.addEventListener("change", (ev) => { //event named "change" can be caught here }
```

I've updated the documentation, hopefully to make it easier to find.

This is not quite the feature request you are suggesting, but hopefully this addresses your need.

**Comment by boompikachu** [comment]
How do I differentiate between 2 commit commands?
