### ISSUE TITLE
blur not working on Firefox

### ISSUE THREAD

**Issue by eagleoflqj** [arnog/mathlive#1537]
## Description
```html
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <script src="https://unpkg.com/mathlive"></script>
    <math-field>x</math-field>
    </script>
  </body>
</html>
```
## Steps to Reproduce

1. Click input
2. Execute `document.activeElement` in console
3. `document.activeElement.blur()`
4. `document.activeElement `
### Actual Behavior

Console outputs `math-field`, `undefined`, `math-field`

### Expected Behavior

Console outputs `math-field`, `undefined`, `body`

### Environment

**MathLive version** Latest

**Operating System** Ubuntu 22.04 x64 or macOS 12.4 x64

**Browser** Firefox 102.0

Brave and Safari don't have this issue.

P.S: Great project! I'm integrating it in [SymPy Beta](https://github.com/eagleoflqj/sympy_beta).

**Comment by arnog** [comment]
Fixed now.
> P.S: Great project! I'm integrating it in [SymPy Beta](https://github.com/eagleoflqj/sympy_beta).
@eagleoflqj thank you! And that sound cool! Are you using MathJSON (i.e. `mf.expression`) to convert the input to Python? If so, would you be interested in contributing a MathJSON to Python/SymPy converter? I started working on one, but I had to put it on the backburner for now.

**Comment by eagleoflqj** [comment]
Thanks for the fix!
I use latex from `mfe.value` and call SymPy's built-in latex parser like this
```py
from sympy.parsing.latex import parse_latex
parse_latex(R'\frac{1}{2}')
```
I'll release that as soon as I finish customizing mathlive virtual keyboard.

> would you be interested in contributing a MathJSON to Python/SymPy converter?

If there's a skeleton and test that tells expected input and output I'd be happy to do that.
BTW I'm currently maintaining SymPy's latex parser (based on ANTLR).

**Comment by eagleoflqj** [comment]
It's online! https://sympy-beta.vercel.app/ under `LaTeX input`.
I customize keyboard to fit what SymPy can handle.
