### ISSUE TITLE
[QUESTION] SVG on keycap : an official list or adding custom one

### ISSUE THREAD

**Issue by Chrisb0606** [arnog/mathlive#1539]
Hi,
Is there any place to list existing svg icon I can use in keycaps.
I've found by myself by exploring sources : svg-tab , svg-angle-double-right  , svg-commit ...
,and for instance, I use them like that :
```
 {
          class: "action w10",
          label: `
            <svg class="svg-glyph"><use xlink:href='#svg-angle-double-right' /></svg>Validate`,
          command: ["performWithFeedback", "commit"],
        },
```
But is there an "official" list of svgs I could use in keycaps, or may I add a custom one and how ?

Thanks
Chris

**Comment by arnog** [comment]
I've added the list of built-in SVG glyphs here: https://cortexjs.io/mathlive/guides/virtual-keyboards/#keycap-examples

To use a custom one, just replace the `<use>` command with the appropriate SVG command (i.e. `<path>, etc...`) and set the viewBox and any other relevant attribute on the`<svg>` element.

**Comment by Chrisb0606** [comment]
Nice, that works great with <path  ... > to include few custom svg icons. Moreover I can also use some LaTeX characters that fit my needs.

**Comment by arnog** [comment]
Answered. Closing.
