### ISSUE TITLE
Suggestion: get ASCIImath out of mathfield

### ISSUE THREAD

**Issue by Kreijstal** [arnog/mathlive#154]
You can get latex out of the mathfield.
And you can convert the latex to html markup, you can convert it to mathml, and you can even get it spoken and with an AST.
But is there a way to get it as on as ASCII math?

**Comment by arnog** [comment]
There isn't direct support for ASCIIMath output right now. The easiest way to go about it would be to get the AST and to generate the ASCIIMath from that.

**Comment by arnog** [comment]
`mf.$text('ASCIIMath')` and `mf.$selectedText('ASCIIMath')` are now supported.
