### ISSUE TITLE
When using `makeSharedVirtualKeyboard()`, no `virtual-keyboard-toggle` dispatched

### ISSUE THREAD

**Issue by Chrisb0606** [arnog/mathlive#1541]
I've faced a issue. I've isolated the code there :
https://codesandbox.io/s/mathfield-test-listener-mgd36r?file=/src/index.js

Actually this issue is maybe linked to the #1535 .

In this issue, the use of customkeyboard and the makeSharedVIrtualKeyboard() makes events inactive. Try to comment the   makeSharedVirtualKeyboard(); line and you'll see the events emit in the console again.
Thanks

**Comment by Chrisb0606** [comment]
Hi, I still face this issue and didn't find any workaround. The makeSharedVIrtualKeyboard() makes events silent.
Anyone has an idea ?

Chris

**Comment by arnog** [comment]
When you say "makes events silent", you mean that the `virtual-keyboard-toggle` event is not dispatched? Which events are not dispatched?

**Comment by Chrisb0606** [comment]
You're right, I thought that all events were concerned but only virtual-keyboard-toggle isn't dispatched.
Tx.

**Comment by arnog** [comment]
Since the virtual keyboard is shared, and not attached to any mathfield, the `virtual-keyboard-toggle` is not dispatched by a mathfield.
I've enhanced the object returned by `makeSharedVirtualKeyboard()` to be an `EventE` that can be listened for `virtual-keyboard-toggle`:

```ts
      const k = makeSharedVirtualKeyboard();
      k.addEventListener('virtual-keyboard-toggle', (ev) =>
        console.log('toggling ', ev)
      );
```

**Comment by Chrisb0606** [comment]
It works great
Tx.
