### ISSUE TITLE
Only allow input via the virtual keyboard

### ISSUE THREAD

**Issue by patrickdavey** [arnog/mathlive#1544]
## Description
Firstly - thank you so much for a simply incredible library. Amazing work.

I have been trying to disable regular keyboard entry, and _only_ allow entry via the virtual keyboard. This is so that I can restrict what type of characters are allowed. I cannot see if this is possible, so, I thought I'd ask.

My best attempt so far was:

```javascript
        mfe.addEventListener('keydown',(ev, a) => {
          ev.preventDefault();
          return false;
        });
```

However, there are certain keypresses which _still get through_ . These ones

```
%
*
\
/
{
}
backspace
escape
+ followed by - with become a +- symbol
```
There are probably others I haven't discovered. Anyway, I was wondering if it is at all possible to just disable all keyboard input?

Thanks again for an excellent library.

**Comment by arnog** [comment]
Yes, that should work. There was a bug where the `defaultPrevented` state of the event was not respected. It is fixed now.

FYI, a workaround is to listen (and `preventDefault()`) the`"keystroke"` event.

**Comment by votrungnam456** [comment]
@arnog I updated lastest version, but it still get though with these key above, is this bug fixed ?

**Comment by arnog** [comment]
Which version are you using?

**Comment by shidel-dev** [comment]
@arnog I am testing something similar. I can confirm that the latest version has this issue. handling the "keydown" event, and calling `preventDefault()` does not prevent fractions from being created.

**Comment by arnog** [comment]
You must be careful to intercept the event during the capture phase:
```
      mf.addEventListener('keydown', (ev) => ev.preventDefault(), {
        capture: true,
      });
```

**Comment by shidel-dev** [comment]
Thank you @arnog! this was the missing piece. Probably the docs should reference this detail https://cortexjs.io/mathlive/guides/virtual-keyboards/#preventing-input-from-the-physical-keyboard.

**Comment by arnog** [comment]
Thanks. The doc has been updated
