### ISSUE TITLE
Mathfield lose focus on nav-tab changing

### ISSUE THREAD

**Issue by sbondaryev** [arnog/mathlive#1545]
## Description
Mathfield lose the focus while one switches between the tabs of the navigator (or virtual screens on mac)

![focus](https://user-images.githubusercontent.com/2843147/179347096-e2609d4b-1f1e-4002-9259-07773e684be8.gif)

## Steps to Reproduce

1. Go to the demo page 
2. Open two different tabs in the navigator
3. Focus the mathfield in one tab
4. Switch between the tabs

### Actual Behavior

Mathfield lose the focus

### Expected Behavior

Mathfield should stay focused

### Environment

**MathLive version**
0.77.0

**Operating System**
macOS

**Browser**
Chrome

**Comment by arnog** [comment]
Interesting... That appears to be a browser behavior. When changing tab, the document loses focus, and any focused element on the page loses focus as well.

When refocusing a page that had a focused textarea, the browsers refocus the textarea. However, they don't appear to do that for custom elements, such as `<math-field>`.

**Comment by arnog** [comment]
I have implemented a workaround that mimics the browser behavior for textarea.
