### ISSUE TITLE
[Question] How to distinguish onChange event from a commit button than a lost keyboard focus ?

### ISSUE THREAD

**Issue by Chrisb0606** [arnog/mathlive#1555]
Hi,
I use a custom Keyboard with virtualKeyboardMode: "onfocus" and with a keycap 
{ class: "action", label: "Submit", command: ["performWithFeedback", "commit"] }

When the user click on this later keycap a change event is trigerred and allow me to validate the form. Unfortunately a change event is also triggered when the math-field has lost focus and the form is validated as well in this condition. Is there any means to distinguish a change event coming from a click on commit keycap than and lost keyboard focus ?

Thanks

**Comment by arnog** [comment]
When you receive the `"change"` event, you can check if the mathfield has focus. If it does not, the "change" was triggered by a blur: ``mf.hasFocus() === false`

**Comment by Chrisb0606** [comment]
Thanks it works well.
