### ISSUE TITLE
[FEATURE] Support East-Asian cursor order in fraction

### ISSUE THREAD

**Issue by Milkaru** [arnog/mathlive#1556]
Thank you for making an amazing library.

## Description

When writing or speaking fractions in East-Asia(Korea, China, Japan etc.), the denominator comes first.

For example,
When Koreans say fraction 1/2:
We say ee(2) beun-ui(/) il(1).
We write like this:
![cursor-order-fraction-write](https://user-images.githubusercontent.com/102509765/180342964-9d6a7f71-c9ef-4f50-8445-107a1c8e9a6d.gif)

same as Chinese, Japanese. (You can check on Youtube)

It feels unnatural when the cursor points numerator first. (same as not East-Asians If the cursor points denominator first)

If I can put cursor order type in fraction to `setOptions`, It would be amazing.

|current|wish|
|:--:|:--:|
|![cursor-order-fraction](https://user-images.githubusercontent.com/102509765/180341893-7c8682e2-8b97-419f-a1f4-95944c63017f.gif)|<img width="48" alt="스크린샷 2022-07-22 오전 10 27 57" src="https://user-images.githubusercontent.com/102509765/180342230-e2667ab7-a58d-4614-a7d4-4221cfe9c3ee.png">|

Thank you.

**Comment by arnog** [comment]
Very interesting, thank you. I've learned something.

I've added a `fractionNavigationOrder` option. To use East Asian fraction navigation, set the option `fractionNavigationOrder` to `"denominator-numerator"`.

**Comment by Milkaru** [comment]
Wow, thank you very much.
I didn't expect that you to develop this option very quickly.
I'm looking forward to the next release!
