### ISSUE TITLE
window click event not firing on mathfields

### ISSUE THREAD

**Issue by ChristopherChudzicki** [arnog/mathlive#1558]
## Description

Window "click" events seem not to be firing on MathFields the way I would expect (and possibly other window events, too).

I came across this in a react project when a popover was open and clicking outside the popover on MathFields did not close the popover, whereas clicking anywhere else outside the popover did close it. But, seems reproducible without any framework, as described below.

## Steps to Reproduce

1. At https://cortexjs.io/mathlive/ in the developer console, run:
    ```ts
    window.addEventListener('click', (e) => {
      console.log("click!", e);
    });
    ```
2. Then click on the mathfield on the mathfield:

    <img width="1345" alt="Screen Shot 2022-07-24 at 9 15 16 PM" src="https://user-images.githubusercontent.com/9010790/180675616-ebcb21bc-f8a1-4bd4-a94a-c9ddd3991d34.png">

### Actual Behavior

Window Event handler not called

### Expected Behavior

Window Event handler should be called

### Environment

**MathLive version**: https://cortexjs.io/mathlive/ was using 0.77 when I tested this

**Operating System** macOS Monterey 12.3 on an M1 chip

**Browser** Chrome

_Thank you for this great library! It's been a joy to use!_

**Comment by arnog** [comment]
Glad you like MathLive.

Unfortunately, this is a duplicate of #1439 .

AFAICT it's not fixable, but there are workarounds. I should document this better, though.

**Comment by ChristopherChudzicki** [comment]
Thanks, I'll close this in favor of #1439 !
