### ISSUE TITLE
setting keybindings options breaks other keybindings

### ISSUE THREAD

**Issue by LinGrin** [arnog/mathlive#1560]
## Description
Attempting to set the `keybindings` options for a math-field causes (at least) the arrow keys and backspace key on the keyboard to no longer function as expected. The arrow keys will no longer scroll between the characters and pressing delete (I'm on a mac) no longer backspaces.

## Steps to Reproduce

Add the following:
```
mf.setOptions({
  keybindings: [],
});
```
to line 57 of the basic example: https://github.com/arnog/mathlive/blob/master/examples/basic/index.html#L57
and run the example.
Now use the arrow keys to try to navigate to the beginning of the field.

### Actual Behavior

Usually the first press of the arrow key or backspace will work as expected, but afterwards, the keys no longer do anything.

### Expected Behavior

setting the keybindings shouldn't affect any existing keybindings I'm not explicitly overriding.

### Environment
I'm using mathlive as an npm package, but I did test this out in just the basic example provided

**MathLive version**
I'm using 0.77.0 in my project (this is via npm) but it seems like this exists on master as well

**Operating System** macOS 12.4

**Browser** Firefox and Chrome

**Comment by arnog** [comment]
The keybindings specified in `setOptions()` are indeed replacing the existing keybindings. To add to the existing keybindings, use:
```
mf.setOptions({keybindings:[
   ...mf.getOptions('keybindings'),
  { key: 'alt+[KeyK]', command: ['insert', '\\kappa'] },
]});
```

**Comment by LinGrin** [comment]
Ah I see, I didn’t understand the API then, thanks for the clarification
