### ISSUE TITLE
Uncaught TypeError while typing ° symbol

### ISSUE THREAD

**Issue by sbondaryev** [arnog/mathlive#1576]
## Description
Mathlive throws `Uncaught TypeError: Cannot read properties of undefined (reading 'definitionType')`
while a user tries to input ° symbol

![input](https://user-images.githubusercontent.com/2843147/184272175-f11e5ae4-3fba-41df-ae25-fa0a2f16dca4.gif)

## Steps to Reproduce
1. Go to the demo page 
2. Try to input the ° symbol in the mathfield

### Actual Behavior
Symbol ° is not shown. Error is thrown.

### Expected Behavior
Sybol ° appears in the mathfield  

### Environment
**MathLive version**
0.78.0

**Operating System** 
macOS

**Browser** 
Chrome

**Comment by sbondaryev** [comment]
Probably related to the breaking change?
```
invalid-keybinding: A message is output to the console if a keybinding includes a combination of keys which cannot be performed with the current keyboard layout
```

**Comment by arnog** [comment]
Good idea, but it was a different problem. The ° character has no special keybinding or definition. Unicode characters without a special definition would trigger this crash. Fixed in `mathlive@0.78.1`

**Comment by sbondaryev** [comment]
@arnog FYI, the latest version is still 0.78.0 on the npm repo and on the demo page.

**Comment by arnog** [comment]
@sbondaryev oops... there was a problem in the publishing process. Should be fixed now.
