### ISSUE TITLE
Incorrect output with `decimalSeparator` option set to ","

### ISSUE THREAD

**Issue by hanshs** [arnog/mathlive#1582]
## Description

When setting the `decimalSeparator: ","` option, the field produces incorrect output for numbers < 10

## Steps to Reproduce

1. Go to https://mathlive-vite-vanilla-ts.vercel.app/
2. Type "1,5" into the mathfield
3. Check console output

Code for the repro - https://github.com/hanshs/mathlive-vite-vanilla-ts/blob/main/src/decimal-separator-example.ts

### Actual Behavior
The output is `1,5`

### Expected Behavior
The output should be `1{,}5`

### Environment

**MathLive version** 0.77.0

**Operating System** [Windows]

**Browser** [Chrome, Firefox]

**Comment by arnog** [comment]
This has been fixed in `mathlive@0.78.1` via a fix for another unrelated bug.
