### ISSUE TITLE
[Bug] Inserting into placeholder with keyboard 

### ISSUE THREAD

**Issue by nesh325** [arnog/mathlive#1583]
Creating custom buttons that inserts latex into the editor and came across this bug. 

![Screen Shot 2022-08-14 at 21 41 43 PM](https://user-images.githubusercontent.com/70300148/184638894-f4774c36-8775-4012-8bf5-c0f6b51a7fd1.png)
![Screen Shot 2022-08-15 at 08 44 57 AM](https://user-images.githubusercontent.com/70300148/184638899-9364c6d4-2782-4f78-9b88-5e2e8aa2097d.png)

It's only when I try and use the keyboard that this happens. But if I were to use numbered buttons to insert numbers it works fine.

Edit - Work around is to move curser after inserting. It's only an issue when the placeholder has focus after being inserted

Edit2 - The above work around only works if I move back to placeholder with keyboard but if I use buttons to move cursor back to placeholder and type it produces the same issue

**Comment by arnog** [comment]
Could you provide more details regarding this issue?
- what code did you run? what LaTeX did you try to insert?
- could you describe in more details what happens vs. what you expect to happen?

**Comment by nesh325** [comment]
First image

```
mf.insert("\\sqrt[#0]{#0}");
mf.focus();
```

This focuses on the 2nd placeholder on focus. When I type 2 it inserts "\placeholder{}" followed by the 2. 
![Screen Shot 2022-08-14 at 21 41 43 PM](https://user-images.githubusercontent.com/70300148/184672155-9f810cd1-4d9c-46db-8699-2c36748ed1ba.png)

Expected behaviour is that typing into the placeholder after insert and focus should not insert "\placeholder{}" before

The other time this happens is the following

```
mf.insert("\\sqrt[#0]{#0}");
mf.executeCommand("moveAfterParent");
mf.focus();
```
Cursor button to move back to placeholder
```
mf.executeCommand("moveToPreviousChar");
```
Then I use keyboard to type 2 and the same issue as above image occurs

If I use button to insert 2
``` 
mf.insert("2");
mf.focus();
```
No issues
