### ISSUE TITLE
Roadmap: deprecate the following add-ons: maston, outputSpokenText, outputMathML

### ISSUE THREAD

**Issue by arnog** [arnog/mathlive#159]
MathLive currently includes some "add-ons" that provide extra functionality, mostly to output the content of the mathfield to various formats, including MathJSON/Maston, spoken text and MathML.

Those three add-ons rely on a parsing of the atoms that make up the user input, and apply heuristics to determine the semantics in order to provide the output in the desired format. 

For example, each digits (and the decimal point) in "1234.56" is a separate atom, but it needs to be perceived as a single "number" in order to be conveyed correctly to speech, MathML or an AST.

Each of the add-ons have their own way of doing this, and they each have a set of different bugs. The most complete and robust is Maston.

Furthermore, some customers prefer to use alternate solutions, such as using SRE to generate spoken text. SRE support is currently baked in MathLive, but then the built-in spoken text module is redundant.

**Proposal**
- Remove the files "outputSpokenText", "outputMathML" and "maston" from the project.
- Create a new project that will provide similar functionality (i.e. conversion from LaTeX to spoken text, MathML and MathJSON, perhaps expending it to others such as MathASCII) but based on a single parser and set of heuristics to improve its robustness and consistency.

**Benefits**
- A smaller, less complex, MathLive
- More consistent and higher quality output for alternative representations, including spoken text and MathML.

**Impact**
- Calls to the `$text()` and `$selectedText()` functions with a format of `spoken`, `spoken-ssml`, `mathML` or `json` would have to be changed to make a call to `$text('latex')` followed by a call to this future project that would convert the latex into the desired format
- The "accessible node" that is wrapped around the mathfield would not be generated by default. Currently it wraps some MathML, but it's unclear if this is actually helpful or even desirable (for example, the spoken text version might be more useful or even better might be to be able to navigate and read aloud the expression). However, a callback would be provided that would give an option to do this wrapping if desired.
- A callback in config would provide an option to speak some LaTeX, which would be used during navigation of the expression. Alternatively, a more generic `announce` callback would offer the option to output to other modalities (braille readers, for example)
- Two implementation of the text output will be provided, once using the web speech API and the other using Amazon Polly. These will be provided as separate files that will have to be included in your project and connected to MathLive using `config()`.

**Timeline**
June to September 2019

**Comment by Kreijstal** [comment]
so now you only get latex as output?

**Comment by arnog** [comment]
If we proceed with this proposal the calls to `$text()` and `$selectedText()` will accept as format `latex`, `latex-expanded` and `asciimath` (even though ASCIIMath is not currently supported as an output format, it turns out that I have to add it in order to support mixing of text and math which I'm currently working on).

It will be possible to get (at least) the following formats with the future, separate project:
- `latex` → `math json` (MASTON)
- `math json` → `latex`
- `math json` → `MathML`
- `math json` → `spoken text`
- `math json` → `SSML`
I may also add `math json` → `ascii math` and `ascii math` -> `math json`

Let me know if this would work for you. Now is the time to provide feedback!

**Comment by NSoiffer** [comment]
I'd also like to see at some point in the future allowing MathML as input
via API or paste.

**Comment by Kreijstal** [comment]
I wonder if the maston syntax is extensible, for example I want to implement the `==` operator.

One could also implement asciiart math which is basically what some CASes use to display on the terminal. 

>I'd also like to see at some point in the future allowing MathML as input via API or paste.

Math as paste would be great.

**Comment by arnog** [comment]
@NSoiffer I'm sure that if someone knowledgable in MathML submitted a PR it would be given serious consideration. ;-)
@Kreijstal The MASTON/MathJSON syntax itself is extensible (as a reminder, it is documented [here](http://docs.mathlive.io/tutorial-MASTON.html)). The parser that transforms the LaTeX input into MASTON recognize a specific LaTeX notation, which could be extended if necessary.
