### ISSUE TITLE
\textcolor gets replaced with \mathcolor

### ISSUE THREAD

**Issue by IBastawisi** [arnog/mathlive#1592]
## Description

![image](https://user-images.githubusercontent.com/13211445/186231943-c451f9e4-bf3d-4e13-82ee-1d34a5c806ea.png)

**MathLive version**
0.78.0

**Comment by huzailhassan** [comment]
do you have an approximate time to have the virtual keyboard's applyStyle command fix this issue? use textcolor instead of mathcolor

**Comment by arnog** [comment]
This is fixed in the main branch, as per above. I will have a new build on npm in a few days.
