### ISSUE TITLE
Suggestion: add interface to allow specifying action for a key event

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#16]
## Description
I'd like to capture some key events and do some action with them. E.g., I'd like to capture shift-delete/backspace and bind those keys to an action that will cross out the item that would have been deleted. Ideally, I'd like the scheme to support multiple keystrokes, but potentially that is something that is handled by the callback (i.e, the callback records state).

Currently, there is no public interface to do this. However, there is a private interface in editor/keyboard that includes:
```
delegateKeyboardEvents(textarea: Element, handlers: Object)
```

Exposing something like this would like let me do what I want, at least for single key events.

Control of passing on the event to let another handler take it should probably be left up to the handler, but that needs to be thought about and maybe the answer is dependent upon the specific key event.

**Comment by arnog** [comment]
Done. Added onKeystroke handler to config of MathField.
