### ISSUE TITLE
Clicking on Mathfield will not always position caret correctly

### ISSUE THREAD

**Issue by gunnarmein-ts** [arnog/mathlive#1605]
## Description

As the title says, sometimes after a click the caret ends up at the front or end of the mathfield instead of closer to where the click happened.

I have a one-line fix for this (problem is in nearestAtomFromPointRecursive()), will submit PR as soon as I am done writing up the bug.

## Steps to Reproduce

Type " 2 + 3 + 4" in mathfield demo. Spaces matter. Click on spaces.

### Actual Behavior

Depending on where you click between characters, the caret will not move

### Expected Behavior

Caret should move pretty close to where it was clicked. I don't think this is a regression.

### Environment

Most recent version as of today (synced fork), MacOS, Chrome up to date

**Comment by arnog** [comment]
Fixed in PR #1606
