### ISSUE TITLE
mix multiple custom virtualKeyboards

### ISSUE THREAD

**Issue by Chrisb0606** [arnog/mathlive#1609]
Hi,
I'd like to use multiple virtualKeyoards. I succeed in mixing one custom virtualKeyboard with core keyboards as follows : 
"virtualKeyboards": "high-school-keyboard functions greek"
But how could I mix multiple custom virtual keyboards, I didn't find any way to do that and the documentation doesn't mention such a case.

Thanks for your help.
Chris

**Comment by arnog** [comment]
You indicate the custom keyboard you want to use in the `virtualKeyboard` property. So, if your virtual keyboard were name `"super-keyboard"` and `"ultra-keyboard"` you would do: `"virtualKeyboard": "super-keyboard ultra-keyboard functions"` for example.

You also need to declare those keyboard using the `"customVirtualKeyboards"` and `"customVirtualKeyboardLayers"` properties. See https://cortexjs.io/mathlive/guides/virtual-keyboards/#defining-custom-virtual-keyboards for more details.
