### ISSUE TITLE
Undefined function bind in firefox

### ISSUE THREAD

**Issue by Kreijstal** [arnog/mathlive#161]
## Prerequisites

* [x] Did you check the [issue tracker](https://github.com/arnog/mathlive/issues) to see if this issue has already been reported?

For more information, see the `CONTRIBUTING` guide.

## Description
[Description of the bug or feature.]
On the mathlive.io website on firefox when we click on the "Taylor series" example we get error.
[Include screenshots or code fragments if applicable]

### Actual behavior
[What actually happened]
We get:  `Undefined function bind()`
[If there are any error messages, include the exact text shown, 
or upload a screenshot]
![grafik](https://user-images.githubusercontent.com/2415206/54821173-b1539000-4ca1-11e9-99a2-72d29910ba0d.png)
### Expected Behavior 
[What you expected to happen]
It should not throw an error
[Is this a regression: did it use to work in a previous version?]

## Steps to Reproduce
[Provide steps that are specific and repeatable, if possible]
1. [First Step]
go to https://mathlive.io/deploy/index.html on firefox
2. [Second Step]
click on "Taylor series"
3. [and so on...]
get error

### Environment
**Operating System** 
[macOS, Windows, iOS. Include the version if possible]
Windows
**Browser** [Safari, Chrome, IE, Firefox, etc...]
Firefox 60.5.2esr
**URL** [URL where the problem can be reproduced, if available]
https://mathlive.io/deploy/index.html

**Comment by stefnotch** [comment]
I can't seem to reproduce this. (Firefox 80) Does this mean that the issue has already been fixed?

**Comment by arnog** [comment]
That specific problem is probably no longer applicable. I'm keeping this open for now to remember to test the bind operator once I've switched to MathJSON 2.0.
