### ISSUE TITLE
math shortcuts work in read-only mode

### ISSUE THREAD

**Issue by IBastawisi** [arnog/mathlive#1614]
![image](https://user-images.githubusercontent.com/13211445/188765354-4f543cef-3cf6-446c-bafc-27bceefa17b4.png)

**Comment by jongwon** [comment]
unsubscribe

2022년 9월 7일 (수) 오전 9:56, Ibrahim El-bastawisi ***@***.***>님이
작성:

**Comment by arnog** [comment]
@jongwon https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions
