### ISSUE TITLE
isTouchCapable seems not work as expected in Hybrid Mobile App Android only (Ionic)

### ISSUE THREAD

**Issue by Chrisb0606** [arnog/mathlive#1618]
Hi,
The side effect of triggering the OS virtual keyboard seems to appear with Android Hybrid App (Ionic).
A <textarea> is generated on Android app instead of a simple span to avoid OS virtual keyboard appearing (as mentioned in the the existing comment). I have to precise that it works as expected on iOS platforms.
I've tried to debug the isTouchCapable() function  in AndroidStudio/Simulator with no success ,but any help would be appreciated to deeper explore the issue cause.

Finnaly, a workaround is to add inputmode="none" ( https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode ) in the textarea (in the code "else" below) which is quite acceptable and well implemented in all browsers. It avoids the displaying of the native virtual keyboards if platform provides one (like iOS or Android) in any event.

In mathfield-private.ts
    // which we want to avoid
` // 1/ The keyboard event capture element.
    // On touch capable devices, we do not create a textarea to capture keyboard
    // events as this has the side effect of triggering the OS virtual keyboard
    // which we want to avoid
    let markup = "<span class='ML__textarea'>";
    if (isTouchCapable())
      markup += `<span class='ML__textarea__textarea' tabindex="-1" role="textbox"></span>`;
    else {
      markup +=
        '<textarea class="ML__textarea__textarea" inputmode="none" autocapitalize="off" autocomplete="off" ' +
        `autocorrect="off" spellcheck="false" aria-hidden="true" tabindex="${
          element.tabIndex ?? 0
        }"></textarea>`;
    }`

Thanks
Chris

**Comment by arnog** [comment]
Thanks for the tip about `inputmode`. I've added this attribute to the `<textarea>` element now. I've also tried to capture more cases to detect if a device is touch capable. It's difficult to do any additional debugging on this however without more detailed information about the hardware/OS where the failure happens.
