### ISSUE TITLE
Documentation for working with IE

### ISSUE THREAD

**Issue by josh18** [arnog/mathlive#162]
Is there a recommended way to get this to work with IE? I might be missing something but I think currently it doesn't work due to having ES6 classes in the output (`dist/mathlive.js`).

The browserslist is set to
```
"> 1%",
"last 2 versions",
"maintained node versions",
"not dead"
```
so I would have thought that babel would have transpiled it.

**Comment by arnog** [comment]
Unless I'm mistaken, the output in `dist` does not go through Babel. I know of some users of MathLive that were able to pass `dist/mathlive.js` through Babel and get it working with IE, though.

**Comment by josh18** [comment]
Oh right, that makes sense. I think I misread Edge as IE in the browser support. And I saw `.babelrc` and assumed it was built using babel. Thanks!
