### ISSUE TITLE
Pressing Enter on physical keyboard of windows machine prints Enter in mathfield

### ISSUE THREAD

**Issue by khanybaba** [arnog/mathlive#1620]
## Description

[Pressing Enter on physical keyboard of windows machine prints Enter in mathfield]
](https://watch.screencastify.com/v/bfHCctwohLKMByB6RKOL). The bug can be experienced on the [mathlive demo page](https://cortexjs.io/mathlive/demo/). Also see screenshot below.

## Steps to Reproduce

1. Visit the [mathlive demo page](https://cortexjs.io/mathlive/demo/) on a windows machine
2. Focus the mathfield and press Enter key on the physical keyboard

### Actual Behavior

The mathfield displays "Enter". See screenshot below:
![image](https://user-images.githubusercontent.com/82975542/190662725-f040c623-9b9f-4191-93d0-cd518637783a.png)

### Expected Behavior

Mathfield should not print Enter. It should either commit the changes or do execute another mode/context dependent command.

### Environment

Mathlive 0.79
OS: Windows 10
Browser: Chrome, Edge

**Comment by arnog** [comment]
I have not been able to reproduce this. Could you provide more information regarding the kind of keyboard you're using (a picture of it would be great), the keyboard layout/language and what key you are pressing (the return key on the main keyboard or the enter key on the numeric keypad or...?)

**Comment by khanybaba** [comment]
Here is a picture of the keyboard.
<img width="847" alt="image" src="https://user-images.githubusercontent.com/82975542/190705066-8cad8a48-577e-43bf-87aa-e43b0d97e9ca.png">
This is on a Lenovo X1 Yoga 1st Gen laptop. The enter key is part of the main keyboard.
Windows 10 keyboard configuration is English (United States) US keyboard

**Comment by NSoiffer** [comment]
I can reproduce this on my similar machine. This is new, so likely some
change in the last few weeks. In my case, I just clicked after the
quadratic formula and hit "enter" and the word "Enter" was added.

**Comment by arnog** [comment]
Nothing immediately comes to mind... A few follow up questions:
1/ Does this happen with other keys? Tab, Capslock, Del, Home?
2/ Does this happen if you run this virtual machine: https://www.browserling.com/browse/win/10/edge/92/http%3A%2F%2Fcortexjs.io%2Fmathlive%2Fdemo

**Comment by khanybaba** [comment]
None of the other keys appear to misbehave.
The choice of browser you linked to was not available to me as I do not have a premium account. However, it did not bug when I chose Windows 7 and Chrome 92. 
![image](https://user-images.githubusercontent.com/82975542/190809623-47484ede-f517-4332-8eec-8f5f7f6c635b.png).

**Comment by NSoiffer** [comment]
Happens for me in the current versions of Firefox and Chrome.

Is it possible that one of the virtual keyboard changes could cause this
problem?

**Comment by arnog** [comment]
That's unlikely. The virtual keyboard would not interact with the physical keyboard code path. I'm going to have to get my hands on a Windows machine, sounds like... :(

**Comment by NSoiffer** [comment]
I'm sure I tried the site in the last two months, although I don't know if
I tried using "Enter". I don't think I tried it in the last month as I've
been travelling. So I would focus on changes that happened 1-3 months ago.
I see some changes with event handlers and "Enter". Maybe one of those
caused "Enter" to leak into the text.

I'm traveling now but will be home tonight and I can check this issue on a
different keyboard (still windows).

**Comment by manstie** [comment]
I do not get the same issue with my windows machine. Perhaps the information shown from [keycode.info](keycode.info) when you pres the enter key may help debug this?

![image](https://user-images.githubusercontent.com/12475567/190854612-8fba48be-17e1-4991-926a-d4bdbd0a191c.png)

**Comment by khanybaba** [comment]
This is the information I gather from keycode.info when pressing Enter on my lenovo laptop that caused this issue:
![image](https://user-images.githubusercontent.com/82975542/190869260-f7fbb248-a265-4684-85c3-d7b138ddf944.png)

**Comment by arnog** [comment]
I have gotten my hands on a Windows 10 machine. I've tried with Chrome and Edge and I'm unable to reproduce. Given that your keycode info is what I would expect it to be, this remains quite mysterious.

Do you have any other software installed that could maybe explain this? Some accessibility settings turned on?
Could you try on the same machine but logging in from a different account?

**Comment by NSoiffer** [comment]
My desktop works fine also. My wife has a different lenovo laptop. I'll try her laptop when she gets back later today and unlocks it.

**Comment by NSoiffer** [comment]
Works fine on my wife's lenovo laptop. The only special thing I can think of for the yoga is that it is a touch screen. I don't know how that could be relevant though.

I'll see if I can get some time in the next few days to build mathlive on my laptop and try to figure out what's going on.

**Comment by arnog** [comment]
Oh... That's actually a useful hint. There is in fact a different code path for keyboard input on touch and non-touch devices and there has been some changes to that code recently...

**Comment by arnog** [comment]
OK, yeah, I can reproduce it now if I pretend to have a touch-capable machine.

**Comment by NSoiffer** [comment]
I am surprised that makes a difference, but I'm happy that I was able to
help you out.

**Comment by arnog** [comment]
Yes, thank you! 

Hybrid devices are interesting... I have to do some gymnastics to prevent the OS virtual keyboard from  getting triggered, but I also need to have a codepath that can capture input on the hardware keyboard...

**Comment by Zahara-Nour** [comment]
Had the same problem on a windows surface

**Comment by arnog** [comment]
@Zahara-Nour yes, any hybrid (touch + keyboard) devices would have been affected. Chromebooks too.

**Comment by Zahara-Nour** [comment]
I also got this problem on a desktop computer (not an hyprid), but with the Enter key from the numpad.
![IMG_4130](https://user-images.githubusercontent.com/32236491/192190060-7deb0385-61c0-41f7-850b-69de726c3025.jpeg)

**Comment by arnog** [comment]
@Zahara-Nour This still happens with the latest version of MathLive that has the fix for the original report? (Try it on https://cortexjs.io/mathlive/demo/)

**Comment by Zahara-Nour** [comment]
Seems to be ok now  ! Thank you !
