### ISSUE TITLE
Input events are fired too often

### ISSUE THREAD

**Issue by ChristopherChudzicki** [arnog/mathlive#1640]
## Description

I've noticed that `<math-live />` components emit `input` events much more often than native HTML input elements. In particular, setting `mf.value = "some value"` emits an input event. In contrast, for native HTML input elements, setting `inputEl.value = "some value"` does **not** emit input events.

I am not sure if this is by design or an area for potential improvement. If it is by design, then is there a way for event handlers to differentiate between "true" user input, and a script programmatically setting the input value?

Here's a video demonstrating the issue (and a link to the HTML file used in the video: https://codesandbox.io/s/angry-chatterjee-8k53kc?file=/index.html)

https://user-images.githubusercontent.com/9010790/192152185-7ae3adf1-fce6-4f78-862f-17ed9c7ceb03.mov

## Steps to Reproduce

1. Attach an 'input' handler to a mathfield: `mf.addEventListener("input", someHandler)`
2. Somewhere else, set `mf.value = "some value"`
3. Manually type or copy into the mathfield the way a user would.

### Actual Behavior
Both (2) and (3) trigger the event handler.

### Expected Behavior
My expectation would be that only (3) triggers the event handler, similar to native HTML inputs.

### Environment

Version 0.79 of MathLive using Chrome on a macbook.

**Comment by ChristopherChudzicki** [comment]
The video above is pretty minimal, but for context I'm working on creating a slider component that should enable users to:
- animate a value using the slider
- or set a specific value user using the math-field input.

Something like this:

<img width="400" alt="Screen Shot 2022-09-25 at 11 33 48 AM" src="https://user-images.githubusercontent.com/9010790/192152011-95e3570c-a742-4759-a51c-163c176129a0.png">

(The screenshot is from https://www.math3d.org/motion; the current version uses MathQuill.)

**Comment by arnog** [comment]
If you set the value programmatically, no event should be emitted. Sounds like a bug. Thanks for reporting it.

**Comment by arnog** [comment]
Very nice app, BTW!

**Comment by ChristopherChudzicki** [comment]
@arnog Thanks for the quick fix, and **very** nice library, BTW!
