### ISSUE TITLE
Hash "#" character is not escaped when typed by user

### ISSUE THREAD

**Issue by dobesv** [arnog/mathlive#1642]
## Description

Currently in the MathLive keyboard you can freely use the `#` character and it just outputs it into the LaTeX without escaping.

However, `#` is a special character in LaTeX used to identify positional parameters to custom definitions.

![image](https://user-images.githubusercontent.com/327833/192621453-306e9a48-8cc2-4290-81e9-fce057c90a9e.png)

Therefore the resulting LaTeX with unescaped `#` might be rejected by other LaTeX engines (in our case, KaTeX).

**Comment by arnog** [comment]
How did you input the `#` character? I just tried here: https://cortexjs.io/mathlive/demo/ typing a `#` (shift-3) character on a US keyboard results in a correctly escaped `\#` character. Can you confirm this is happening for you at the demo page above? What is the layout of your keyboard?

**Comment by dobesv** [comment]
Ah interesting, thanks.  Maybe we configured something incorrectly with our keyboard.

**Comment by arnog** [comment]
OK. Closing.
