### ISSUE TITLE
MHChem chemical bonds are not rendering properly

### ISSUE THREAD

**Issue by RobinPayne** [arnog/mathlive#1647]
## Description

Math live does not properly display chemical bond equations from the mhchem package

![image](https://user-images.githubusercontent.com/1332680/193123376-f5f12e60-b72c-4499-b10d-0e6e82506efb.png)

## Steps to Reproduce

1. navigate to [CortexJS](https://cortexjs.io/mathlive/demo/)
2. copy $\ce{A\bond{~--}B\bond{~=}C\bond{-~-}D}$ 
3. paste it into the latex text area at the end of the page

### Actual Behavior

`\bond` command does not render properly
![image](https://user-images.githubusercontent.com/1332680/193123376-f5f12e60-b72c-4499-b10d-0e6e82506efb.png)

### Expected Behavior

Should render like this:
![image](https://user-images.githubusercontent.com/1332680/193123575-dd031fed-2578-4286-a698-303c1cca090d.png)

### Environment

**MathLive version** 81
**Operating System** macos
**Browser** Chrome

**Comment by mhchem** [comment]
The issue is that `~` (tilde) is replaced by a space before it is handed to mhchemParser. 
Might be related to bad handling of `~` #1668
