### ISSUE TITLE
\operatorname is not being serialized correctly to MathML

### ISSUE THREAD

**Issue by corlick98** [arnog/mathlive#1648]
## Description
When serializing an expression including `\operatorname` to Mathml we are losing information.
For example:
latex: `\operatorname{cm}`
mathml: `<mo>&#x2061;</mo>`

### Actual Behavior
Instead of serializing the `\operatorname` to a mathml element we instead only get a Function Application character.

### Expected Behavior
Based on https://github.com/arnog/mathlive/blob/a1d66b5f3ff367035c40a778ea2754f961019214/src/addons/math-ml.ts#L339 I would expect to get something similar to `<mi>cm</mi>`.

### Environment

**MathLive version** 0.81.0

**Operating System** [macOS, Windows, iOS. Include the version] 
Ubuntu 22.04.1 LTS and Firefox 105.0.1 (64-bit)
also tested on
Windows 10 and Firefox 104.0.2

**Comment by MatousAc** [comment]
Can I we see a Fiddle or CodePen?
I'm interested in this behaviour too.

**Comment by corlick98** [comment]
Sure, here this is a fairly generic fiddle but if you enter `\operatorname{anything}` you will see the issue in MathML.
https://jsfiddle.net/kopaka9726/L3ca9ogx/

**Comment by MatousAc** [comment]
Ahh, I see, okay. Looks like this isn't that important to me as I don't think I will be using MathML representation in my app. Though it is interesting to see that all these different formats are available.
Is this explained in the docs somewhere? It may be useful to get a user's selection as is shown in the fiddle above.
Thanks.

**Comment by arnog** [comment]
Fixed in 069c1b14a0301001212898be5ebec1c446987bcc
