### ISSUE TITLE
Delete in empty input box has infinite recursion

### ISSUE THREAD

**Issue by nickgravelyn** [arnog/mathlive#165]
## Prerequisites

* [X] Did you check the [issue tracker](https://github.com/arnog/mathlive/issues) to see if this issue has already been reported?

For more information, see the `CONTRIBUTING` guide.

## Description
Hitting delete key in empty box causes error that breaks input box events. It still displays the input but it stops firing events.

### Actual behavior
Hitting delete key in empty box causes error that breaks input box events. It still displays the input but it stops firing events.

### Expected Behavior 
Naturally hitting delete in an empty box shouldn't cause issues.

## Steps to Reproduce
1. Go to mathlive.io
2. Open up dev tools.
3. Select entire input and hit backspace to clear the box.
4. Type `2+4` to prove box works (6 is displayed below).
5. Use backspace to remove input (smiley face is shown).
6. Press delete key.
7. Notice error in console. In Firefox on macOS it prints `too much recursion` with a large mathlive.js stack tracek.
8. Type `2+4`. Notice the smiley face stays and the answer isn't displayed.

### Environment
**Operating System** 
macOS and Windows

**Browser** 
Firefox on macOS and Chrome on Windows

**URL** 
mathlive.io

**Comment by arnog** [comment]
Thanks for reporting this issue and for the great bug report. I have been able to reproduce this with the previous version of mathlive.io. 
I was not able to reproduce it with the new version, which is using the just released 0.27. Note that I literally updated it minutes ago, so make sure to purge your cache to get the up to date version.

**Comment by LinGrin** [comment]
Hello, did this bug get re-introduced at some point? I just cloned a fresh copy of the repo and was able to reproduce this in the basic example.
I got: `Error: regexp too big` after hitting `Option` + `delete` on my mac keyboard in an empty field
I could also reproduce the bug in the mathlive.io page.
