### ISSUE TITLE
Catch event to limit amount of characters

### ISSUE THREAD

**Issue by Chrisb0606** [arnog/mathlive#1653]
Hi,
I'd like to implement a feature that limits the number of characters the user can fullfill in a mathfield. It targets kids to limit digits they can enter in certain situations.
I've achieved that with a **standard** html input field with this following code: 

var rawOptions.maxChars = 3; //we want to limit to 3 digits
inputField.onkeypress = limitCharsOnInputField.bind(this)

function limitCharsOnInputField(event) {
    if (inputField.value.length >= rawOptions.maxLength) {
      event.preventDefault(); // the event is "cancelled" and the char has not been added in the input field
      event.stopPropagation();
    }
  }

When I try to apply this approach to a mathfield the character is added in any events. I try to change inputField.onkeypress by inputField.oninput to have a wider spectre with no success. It seems that MathField catch in all cases.

Thanks for your help,
Chris

**Comment by arnog** [comment]
The `onkeypress` and `oninput` attributes are not supported. Instead, you should use the corresponding events:

```js
inputField .addEventListener('keypress', (ev) => {
    if (inputField.value.length >= rawOptions.maxChars) event.preventDefault();
});
```

**Comment by Chrisb0606** [comment]
Thanks, it works when I use the physical keyboard but not when I the mathlive keyboard (for instance when I click on a keycap), any idea to make both works ?

**Comment by Chrisb0606** [comment]
That works and that's perfect for what I strive !
Thanks a lot
Chris
