### ISSUE TITLE
Move through keyboard characters by pressing tab key

### ISSUE THREAD

**Issue by mranosa** [arnog/mathlive#1654]
## Description

I would like to move through the virtual keyboard characters one by one by pressing the tab key.

![Screenshot from 2022-10-04 02-52-32](https://user-images.githubusercontent.com/1808506/193656267-e324d406-b9a3-47b8-943c-01805c7cde8d.png)

Is it possible for me to do that?

Sorry I am very new to this library, so do let me know if this question makes sense or not. Thanks :smile:

**Comment by arnog** [comment]
This is not possible.
