### ISSUE TITLE
VirtualKeyboard is not toggle by click virtualKeyboardToggleGlyph using apple pencil on iPad

### ISSUE THREAD

**Issue by Raton-Obotai** [arnog/mathlive#1658]
## Description

When I press virtualKeyboardToggleGlyph using apple pencil on iPad virtual keyboard is not showing.

## Steps to Reproduce

Watch video evidence

https://user-images.githubusercontent.com/46880921/194463630-836fe4ac-9d8e-47ca-97d1-6802a5341de2.mp4

### Expected Behavior

Virtual keyboard should be toggle by pen touch

### Environment

**MathLive version** 0.83.0

**Device** iPad(8th gen), ApplePencil, [Elecom rechargeable active touch pen](https://www.elecom.co.jp/products/P-TPACSTAP02WH.html), [KINGONE stylus pen](https://www.amazon.co.jp/gp/product/B087T4ZVP8)

**Operating System** iPadOS15.6.1

**Browser** Safari, Chrome

**Comment by huzailhassan** [comment]
I do not use Apple Pencil, but I would like to know if this pencil works with other buttons in a web browser? If so, I can just see this as a simple fix in the code just by using that kind of button (which I assume is a normal ordinary kind of button)

**Comment by arnog** [comment]
yes, the Apple Pencil can be used to interact with other UI elements. In fact, the Apple Pencil can be used to interact with the keys of the virtual keyboard. Interestingly, the same code is used to detect the interaction for the keys of the virtual keyboard and the virtual keyboard toggle button, so there is some unexpected interaction going on with the toggle that makes it non-responsive to the events generated by the pencil. So, unfortunately, it is not a simple fix.

**Comment by arnog** [comment]
Fixed with dd98b5f

**Comment by Raton-Obotai** [comment]
https://github.com/arnog/mathlive/commit/dd98b5f6374f68a023c36192c04c2f104635a973#commitcomment-86398753
