### ISSUE TITLE
a{}+{}b does not render like LaTeX

### ISSUE THREAD

**Issue by mhchem** [arnog/mathlive#1667]
## Description

Testing at https://cortexjs.io/mathlive/ I found an issue that can be described with this minimal example

<img width="688" alt="image" src="https://user-images.githubusercontent.com/16336692/195182575-e54e87be-bac8-467f-a970-96944f6a3df1.png">

### Actual Behavior

The expression `a{}+{}b` should render the same as `a+b`, but is does not.

### Expected Behavior

Compare with `$a{}+{}b, a+b$` at https://www.mathjax.org/#demo

<img width="280" alt="image" src="https://user-images.githubusercontent.com/16336692/195182989-f7aa6bde-31a7-424f-b530-33c800529058.png">

**Comment by arnog** [comment]
This has been fixed now.
