### ISSUE TITLE
CORS issue thrown when mounting MathfieldElement with remote fontsDirectory

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1669]
Hello!

I'm currently working on a Clojurescript wrapper of Mathlive. I'm trying to mount a `MathfieldElement` on a react-rendered page served by a local server that does not give access to any assets on the filesystem.

My issue is that `resolveRelativeURL` is ALWAYS called, even when I set `fontsDirectory` to `""` or `"https://unpkg.com/mathlive@0.83.0/dist/fonts"` to try and disable any attempt to load the fonts locally.

I would love to be able to to supply an absolute fontsDirectory and skip [this call](https://github.com/arnog/mathlive/blob/a1d66b5f3ff367035c40a778ea2754f961019214/src/core/fonts.ts#L53) to `resolveRelativeURL`. Here's `resolveRelativeURL`, of course, where the HEAD request gets issued.

https://github.com/arnog/mathlive/blob/5b083337616979fd5ea549536e4c53250b26c66f/src/common/script-url.ts#L52-L63

The actual error I see is 5 failed HEAD requests:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/69635/195929501-8460c17d-b457-4d01-afef-3fe8000c8ee4.png">

This is with mathlive 0.83.0.

Happy to provide more information or a repro, but I didn't want to burden you with details of the Clojurescript toolchain when the issue here feels clear; it seems that there is no way to supply an absolute URL (for a CDN for example), vs a relative.

Thank you for the lovely project! I'm using Mathlive as an entry component for my Clojure-based computer algebra system: https://github.com/sicmutils/sicmutils lots of fun stuff coming that I'm happy to share as I get rolling.

**Comment by arnog** [comment]
That sounds like a very cool project. Let me know how it goes!
