### ISSUE TITLE
Trying to use logs doesn't work

### ISSUE THREAD

**Issue by Toffee1347** [arnog/mathlive#1677]
## Description

- When attempting to use logs, the latex expression seems to be having problems
- I am currently using mathlive on my frontend, which passes the latex expression to the backend, for the compute engine to generate numbers

## Steps to Reproduce

1) Enter something like log<sub>10</sub>100 into the input
2) Note how the latex expression should be `\\log_{10}100`

### Actual Behavior

- Look at the mathJSON output for the element (with `<ELEMENT>.expression.json`, it should be:
```JSON
[
    "Multiply",
    ["Subscript",
        ["Error",
            ["ErrorCode","'unexpected-command'","'\\log'"],
            ["Latex","'\\log'"]
        ],
        10
    ],
    100
]
```

### Expected Behavior

- I would expect that this is either an issue with the mathJSON format, or latex parsing
- Either way, I'm guessing this isn't intended behaviour

### Environment

**MathLive version** v0.83.0

**Operating System**  Windows

**Browser** Chrome (although this also happens on the compute engine

**Comment by arnog** [comment]
Fixed in the main branch of the Compute Engine
