### ISSUE TITLE
exponents on \mathit{} identifiers are overlapping with the identifiers

### ISSUE THREAD

**Issue by gunnarmein-ts** [arnog/mathlive#1683]
## Description

exponents on \mathit{} identifiers are overlapping with the identifiers

<img width="196" alt="image" src="https://user-images.githubusercontent.com/86687645/197007704-265b7e26-b4a5-45c7-a80e-c66523b330e4.png">

(screenshot from mathlive demo website)

To reproduce, enter latex as in screenshot

### Actual Behavior

exponent overlaps italic "f"

### Expected Behavior

exponent should be slight right of where it is

### Environment

Chrome, MacOS, https://cortexjs.io/mathlive/demo/

**Comment by arnog** [comment]
AFAICT that's consistent with the way LaTeX displays it. See https://latexeditor.lagrida.com/
Since `f` is already italic, I suggest using `x = f^2`
