### ISSUE TITLE
not activated undo button and erase all at once sometimes

### ISSUE THREAD

**Issue by insoohyeon** [arnog/mathlive#1684]
## Description

- If you press the numeric keys and press the undo button, the numbers are not erased one by one, but all at once.
- Pressing some keys does not activate the undo button.

## Steps to Reproduce

please check the video

https://user-images.githubusercontent.com/46772628/197092342-99b97a97-e4c7-4d1d-be39-2bb0816ba365.mp4

### Expected Behavior

The undo button is activated no matter what key you press, and one character is erased when you press the button.

### Environment

**MathLive version** mathlive demo

**Operating System**  windows

**Browser**  Chrome

**Comment by arnog** [comment]
Undoing the string of digit as one is intentional. To remove a single digit, press the backspace key (on the physical or virtual keyboard).
The visual state of the undo is incorrect, although it can be pressed to undo.

**Comment by insoohyeon** [comment]
I see.
Thank you for  tagging bug label.
