### ISSUE TITLE
Cannot edit Chemical equations after being rendered

### ISSUE THREAD

**Issue by ImGelu** [arnog/mathlive#1688]
## Steps to Reproduce

1. Type a chemical formula, for example `\ce{CaCO3 + H2O}`
2. Press `Enter` so the rendering begins
3. Try to edit the formula. The cursor works only for the begining or the end of the formula.

### Environment

**MathLive version**: Latest (0.84.0)

**Operating System**: Windows 11

**Browser**: Firefox

**Comment by arnog** [comment]
Duplicate of #1493
