### ISSUE TITLE
Impossible to unfocus math field

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#169]
## Prerequisites

* [x] Did you check the [issue tracker](https://github.com/arnog/mathlive/issues) to see if this issue has already been reported?

For more information, see the `CONTRIBUTING` guide.

## Description
It is impossible to "unfocus" a math field by clicking outside of it or using `tab`. 

![Screenshot (89)](https://user-images.githubusercontent.com/3444034/56026715-ad4ce800-5d0c-11e9-99e4-61a09e1cdbbc.png)

Clicking outside the box does not make the blinking caret disappear.

### Actual behavior
When clicking inside a mathfield, a caret appear at the location clicked on. When clicking outside the mathfield though, the caret does not disappear. It does not even disappear when clicking inside another mathfield. You end up with multiple active carets.

![Screenshot (90)](https://user-images.githubusercontent.com/3444034/56027100-54ca1a80-5d0d-11e9-97eb-5b9bcc964eef.png)

Screenshot from our own application. Since we use `virtualKeyboardMode: "onfocus"` we end up with multiple open keyboards at the same time occluding each other. Since it's impossible to unfocus a mathfield, the keyboards never go away.

Strangely, the "actual" keyboard focus seems to work correctly, so if you click outside a mathfield or `tab` out of it, no characters appear when typing. The virtual keyboard still inputs into the field though, and with multiple keyboards active it's never clear where the input goes to.

### Expected Behavior 
I expect the insert caret to go away when clicking outside the field or pressing `tab`. When using `virtualKeyboardMode: "onfocus"`, the virtual keyboard should disappear as well.

This used to work correctly in 0.25. I wanted to update to 0.27 for the new text-features and found that our application is broken now. Since `mathlive.io` seems to show the same signs though (and supports the new text mode apparently), this is apparently a problem with the new versions. I tried 0.26 as well (in our application) and got the same issues. 0.25 continues to work just fine.

## Steps to Reproduce
[Provide steps that are specific and repeatable, if possible]
1. Got to [mathlive.io](https://mathlive.io/deploy/index.html)
2. Click into the mathfield
3. Click outside the mathfield. 
4. Notice the caret is still blinking.

### Environment
**Operating System** 
Windows 10.

**Browser**
Chrome 73.0.3683.86 and Firefox 66.0.2.

**URL** 
https://mathlive.io/deploy/index.html

**Comment by arnog** [comment]
Thank you for this detailed bug report. The issue should be fixed now. A new npm drop will address this shortly.
