### ISSUE TITLE
added macros are parsed as errors in math-json format

### ISSUE THREAD

**Issue by MatousAc** [arnog/mathlive#1690]
Let's say I define a new macro to define the "mol" unit

~~~
let field = document.querySelector("math-field")
field.setOptions({
  macros: {
    mol: '\\mathrm{mol}'
  }
})
~~~

When I get the value of the `math-field` in `math-json` format the new macro is parsed as an error. Observe [this Codepen example](https://codepen.io/MatousAc/pen/poKojxP?editors=1111):
![mathLiveIssueDemo](https://user-images.githubusercontent.com/56884762/197666555-f321967e-e159-4ab1-8c7f-8275fadf4b63.gif)

## Steps to Reproduce
1. Define new macro
2. Use it in `math-field`
3. View the value in `math-json` format

### Actual Behavior
Value of mathfield in `math-json` format is something like:
`"['Error',['ErrorCode',''unexpected-command'','\macro''],['Latex',''\macro'']]"`

### Expected Behavior
Value of new macro is like the default macros:
`"\macro"`

### Environment
**MathLive version**: 0.84.0
**Operating System**: Windows 10
**Browsers**: Chrome, Firefox, Edge, Brave (no difference between them)

**Comment by arnog** [comment]
In order for macro LaTeX to be parsed, you need to provide information to the Compute Engine. In this case `\mol` is a symbol, but it could be an operator or a function or something else.

See https://cortexjs.io/compute-engine/guides/latex-syntax/#customizing-the-latex-dictionary

**Comment by MatousAc** [comment]
It looks like all the examples for extending the latex dictionary involve creating a new `ComputeEngine`.
~~~
const ce = new ComputeEngine({
  latexDictionary: [
    ...ComputeEngine.getLatexDictionary(), {
    // extend latex dictionary below
      trigger: ['\\command'],
      parse: (parser: Parser): Expression => { return "command"; }
    }
  ]
});

console.log(ce.parse('\\command').json);
~~~

However, simply calling `field.getValue('math-json')` will return a parsed result. Is it possible to modify the dictionary for the ComputeEngine that is doing this in the background for all the math fields? I would prefer to edit the already present one rather than creating my own.

Also, I keep getting errors about unexpected `:`
![image](https://user-images.githubusercontent.com/56884762/198421240-787f7a56-6b9e-4577-b9a4-4e44f8e7d6c5.png)

**Comment by arnog** [comment]
You can now set a Compute Engine instance using `mf.computeEngine = ...` or `mf.setOptions({computeEngine: ...})`.

**Comment by MatousAc** [comment]
Thanks so much for this ability. It's working fine in my application 👍
