### ISSUE TITLE
soundsDirectory option not working as expected

### ISSUE THREAD

**Issue by evgenyny** [arnog/mathlive#1695]
## Description

`soundsDirectory: null` not working as expected.

Even when specified as `null` media network requests performing anyway.
![image](https://user-images.githubusercontent.com/22072081/198890502-7bbf4170-4199-437f-8d51-7e4f1ed7437a.png)

And mathlive attempts to make it speakable.
Seems like no option to completely disable this "speech" feature.

I've specified `soundsDirectory, keypressSound, plonkSound` to `null` and no any effect.

![image](https://user-images.githubusercontent.com/22072081/198890565-6690c61a-b19c-4e2b-83ea-1dc2360b7f81.png)

I need to disable this feature because I don't need to play any sounds and more on that - it produces this issue:
![image](https://user-images.githubusercontent.com/22072081/198890578-c265ecae-8f61-4ed1-9111-21af6ff132db.png)
Error text: _[Intervention] Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27_

And for me it's a problem because I can have dozens of mathfields on the page. Each one in that case triggers a lot of media requests and takes memory.

## Steps to Reproduce

1. Specify `soundsDirectory` option as `null` for mathfield(s)
2. Reload the page with mathfield(s)

### Actual Behavior

A lot of media requests still performing and mathlive attepmts to make each mathfield speakable.

![image](https://user-images.githubusercontent.com/22072081/198890502-7bbf4170-4199-437f-8d51-7e4f1ed7437a.png)

Error text: _[Intervention] Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27_

### Expected Behavior

When `soundsDirectory` specified as `null` no any media requests performing and mathfield(s) becomes completely "silent", without any speech-related logic happening and stucking the browser.

Seems like `soundsDirectory` config option was introduced in version 0.60.0 and according to the comment, it should work as I described here.

![image](https://user-images.githubusercontent.com/22072081/198890991-150399f4-4f65-492c-a5b3-2274054b8129.png)

### Environment

0.84.0

Windows

Chrome

**Comment by sritchie** [comment]
One note here is that it looks like your options there have a colon in front of them; that said, I've tried the same thing with no colon and I still see the network requests.

What DOES fix them is setting the sounds-directory to the CDN location:

```
https://unpkg.com/mathlive@0.84.0/dist/sounds/
```

**Comment by evgenyny** [comment]
@sritchie ty for your response.

I'll check and reply here again.

**Comment by arnog** [comment]
Setting the `soundsDirectory` option to `null` works, i.e. `mf.setOptions({soundsDirectory: null})`. What doesn't work is setting the `sounds-directory` attribute to the string `"null"`.

**Comment by evgenyny** [comment]
@arnog thank you for your response, I will double check.

**Comment by arnog** [comment]
Using `"null"` as an attribute will now suppress the loading of sounds.

That said, I have rewritten the way sounds are played, and you should  no longer have the errors about `WebMediaPlayer` that you saw before.

**Comment by evgenyny** [comment]
Just to let you know - this fix helped. Issue has been resolved.

Thanks again for the quick response.
