### ISSUE TITLE
Border with \enclose latex command is misplaced while using padding

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#1697]
<img width="760" alt="Capture d’écran 2022-11-02 à 21 52 22" src="https://user-images.githubusercontent.com/32236491/199577176-93f3802f-6e01-4d4f-81d9-b8cd6df555d3.png">

## Steps to Reproduce

on the demo site, enter
`\enclose{roundedbox}[3px solid green, padding="6"]{1234}`

### Environment

**MathLive version**
demo site and 0.84 smoke test

**Operating System** [macOS ]

**Comment by Zahara-Nour** [comment]
Investigating `render` function in `EncloseAtom` class : 
I tried to replace `notation.setStyle('top', -base.height + 2 * padding, 'em');` by `notation.setStyle('top', -padding, 'em');` which looks more logical , but position is still not good.
Is it normal that base.depth is 0 ? I guess there is always a gap under the baseline, no ?

**Comment by arnog** [comment]
`base.depth` represents the space below the baseline. So it's 0 for `123` but  it  would be some non-zero value for `\frac12`.

**Comment by Zahara-Nour** [comment]
This fixed the issue but now the problem is when padding is not set 
<img width="741" alt="Capture d’écran 2022-11-04 à 12 49 01" src="https://user-images.githubusercontent.com/32236491/199943611-3db87900-a347-4919-87e2-ff813affee20.png">

**Comment by Zahara-Nour** [comment]
strange : no error on the demo site but only on my local installation

**Comment by Zahara-Nour** [comment]
maybe because the demo site has not be updated with the last commit

**Comment by Zahara-Nour** [comment]
In fact it seems to work with padding="6" but for every other value than 6, the box is misplaced. We can also see that padding style option doesn't appear in latex output.

**Comment by arnog** [comment]
OK, should be better now.  Cortexjs.io is using the npm published version, which does not yet include this fix, but the version in the main branch does.

**Comment by Zahara-Nour** [comment]
Still some issues 

`\enclose{roundedbox}[3px solid green]{1234}{345}}`

<img width="698" alt="Capture d’écran 2022-11-05 à 05 10 49" src="https://user-images.githubusercontent.com/32236491/200096543-fc06185a-ff0a-4dae-b260-1faa1f5b8d4c.png">


`\enclose{roundedbox}[8px solid green]{\frac{1}{234}}{+345}}`

<img width="665" alt="Capture d’écran 2022-11-05 à 05 17 17" src="https://user-images.githubusercontent.com/32236491/200096823-4c14fc0d-1912-4455-aa08-de5efb58240e.png">

I made some modifications to get 
`123+\enclose{roundedbox}[8px solid green, padding="10"]{\frac{12}{34}-12}+123`
<img width="603" alt="Capture d’écran 2022-11-05 à 05 23 58" src="https://user-images.githubusercontent.com/32236491/200097031-2a23bbe2-4edf-4550-9d79-529834843b74.png">

I made a branch in my fork, i would like to make a PR but I can not merge in a new branch. Could you create a new branch in your repo so that I can  merge into it and you can see what I have done ?

I still have one issue
There is an extra top and bottom gap around the box I can't get rid off

<img width="1440" alt="Capture d’écran 2022-11-05 à 05 33 51" src="https://user-images.githubusercontent.com/32236491/200097322-06b2586d-795b-4630-a8ac-5763ee0f48b8.png">

I have the impression that `calc(100%+${2*padding}em+${2*borderWidth}em` doesn't return the same as `notation.height+notation/depth`

**Comment by Zahara-Nour** [comment]
I found another bug : when padding is not set, its value becomes 0.3 em and not 0. When you set the padding to 0, it's OK.

**Comment by Zahara-Nour** [comment]
Oh Ok it's a default value which comes from `context.getRegisterAsDimension('fboxsep')`

**Comment by arnog** [comment]
You can go ahead and merge into the main branch (`master`).

Yes, the default margin is 0.3em.
