### ISSUE TITLE
addColumnAfter command does not work

### ISSUE THREAD

**Issue by Tanzz1058** [arnog/mathlive#1698]
## Description

addColumnAfter /addColumnBefore commands are not working

## Steps to Reproduce

type this command in the math editor - $$ \begin{array}{ccc}\hat{i} & \hat{j} & \hat{k} \\ b_1 & b_2 & b_3 \\ c_1 & c_2 & c_3\end{array} $$   , use the following function to insert a column in the array. 
mf.addEventListener("keyup", (e) => {
      if (e.which === 13 || e.keycode === 13) {
        mf.executeCommand("addColumnAfter");
      }
    });

### Actual Behavior

nothing happens, the column placeholders do not appear

### Expected Behavior
column should be added , placeholders should appear 

MathLive version - 0.84.0

**Operating System** Windows

**Browser**  Chrome

**Comment by Tanzz1058** [comment]
@manstie , @arnog can you look into this?

**Comment by manstie** [comment]
Your array is limited to three columns denoted by `{ccc}`
