### ISSUE TITLE
Mathfield loses focus when clicking on the vKeyboard

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#170]
## Prerequisites

* [x] Did you check the [issue tracker](https://github.com/arnog/mathlive/issues) to see if this issue has already been reported?

For more information, see the `CONTRIBUTING` guide.

## Description
Clicking anywhere on or typing on the virtual keyboard makes the focussed mathfield lose focus when using `virtualKeyboardMode: "onfocus"`. This results in the virtual keyboard disappearing.

### Actual behavior
Normal typing on the physical keyboad works fine, as does using the virtual keyboard in `manual ` mode. When using `onfocus` though, clicking anywhere (including the virtual keyboard) makes the mathfield lose focus and the keyboard disappear.

### Expected Behavior 
The mathfield should not lose focus when clicking anywhere on the virtual keyboard.

The virtual keyboad worked fine in 0.25. I think this has been to do with #169 and it's recent fix of yours.

## Steps to Reproduce

1. Go to any mathfield that has `virtualKeyboardMode: "onfocus"` set and uses the latest version 0.27.3.
2. Click into it.
3. Type on the virtual keyboard or just click on it.
4. The mathfield loses focus.
5. The virtual keyboard disappears.

### Environment
**Operating System** 
Windows 10

**Browser** 
Chrome 73.0.3683.86

**URL**

**Comment by arnog** [comment]
Sorry about that. 0.27.4 hopefully fixes it...
