### ISSUE TITLE
e^{i*} breaks TeX rendering on demo page

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1703]
## Description

On the [CortexJS demo page](https://cortexjs.io/compute-engine/demo/), if I delete past `\pi` on the `e^{i\pi}` and then add a multiplication sign, I get invalid tex below:

<img width="245" alt="image" src="https://user-images.githubusercontent.com/69635/200376570-aa8752f2-fd2a-444d-90a3-ed5f0e013551.png">

If I delete the `*`, then the fields below stop rendering as TeX, and don't recover, even if I retype the `\pi`:

![2022-10-17 10 54 02](https://user-images.githubusercontent.com/69635/200376256-b19528aa-59c8-469b-ad38-68bb3662ff7d.gif)

**Comment by arnog** [comment]
Fixed in main branch of Compute Engine
