### ISSUE TITLE
e^{i\pi} on demo page is incorrectly evaluated, simplified

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1704]
## Description

On the demo page, `e^{i\pi}` is incorrectly evaluated via `.N()` to be equal to `e`, not the correct value of `-1`.

If I click "Machine" at the bottom, I DO see the correct value of `-1`. Clicking back to `auto` keeps this value. If I then click "decimal" or "complex", I get `e` again, and going back to "auto" keeps the incorrect `e` result.

In fact, when I click "decimal", `e` raised to the power of any symbol evaluates to `e`.

![2022-11-07 10 36 59](https://user-images.githubusercontent.com/69635/200377450-e12a4fac-e7d9-4087-bb62-bcc39b549551.gif)

I also wonder if it's an error, or just missing simplification rules, that `e^{i\pi}` doesn't simplify down to -1. It might be good to include since this is the first example that people see on the demo page.

**Comment by arnog** [comment]
Fixed now.
