### ISSUE TITLE
"cos^2(x)" evaluates to cos(2x)

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1705]
## Description

It's common to see `cos(x)^2` and `sin(x)^2` written as `cos^2(x)` and `sin^2(x). When I try typing these in they are parsed with the exponent pushed into the parentheses, which I would say is probably an error in parsing, even if the shortcut of cos^2 is not supported:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/69635/200378333-22a40cf8-cf42-492d-a809-9e8cddf3e9f8.png">

Also, I would argue that the simplification rule here is not the right thing to run. I get that it is trying to remove trig functions in favor of exponentials, but this is hardcore!

I'd love support for the `cos^2(x)` function, but pending that maybe this should error?

**Comment by arnog** [comment]
`cos^2(x)` now works as expected

**Comment by sritchie** [comment]
@arnog this is still broken for me on the latest master. Here is `examples/basic`:



<img width="368" alt="image" src="https://user-images.githubusercontent.com/69635/205170130-a00db395-2eb8-4591-82a7-5d3e56ea4afe.png">

Code:

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>MathLive Basic Example</title>
    <style>
      body {
        color: #444;
        background-color: #f9f9f9;
      }

      main {
        max-width: 820px;
        margin: auto;
      }

      math-field {
        border: 1px solid #ddd;
        padding: 5px;
        margin: 10px 0 10px 0;
        border-radius: 5px;
        background-color: #fff;
      }

      #value,
      #result {
        padding: 5px;
        border-radius: 5px;
        border: 1px solid #000;

        color: rgb(241, 188, 91);
        background: #35434e;

        font-family: monospace;
        margin-bottom: 1em;
      }
    </style>
  </head>

  <body>
    <main>
      <h2>MathLive Basic Example</h2>
      <math-field id="mf" virtual-keyboard-mode="manual">f(x)=</math-field>
      <div id="value"></div>
      <div id="result"></div>
    </main>

    <script type="module">
      import { renderMathInElement } from '/dist/mathlive.mjs';
      import { ComputeEngine } from 'https://unpkg.com/@cortex-js/compute-engine@latest/dist/compute-engine.min.esm.js';

      document
        .getElementById('mf')
        .setOptions({ computeEngine: new ComputeEngine() });

      document.getElementById('mf').addEventListener('input', (ev) => {
        const mf = ev.target;
        document.getElementById('value').innerHTML = mf.getValue();
        document.getElementById('result').innerText = `${mf.getValue(
          'math-json'
        )}`;

        renderMathInElement('result');
      });
    </script>
  </body>
</html>

```

**Comment by arnog** [comment]
Fixed in Compute Engine. The issue was when the exponent was unbraced, i.e. `^2` vs `^{2}`.
