### ISSUE TITLE
cos(x)^2 has an extra left paren on demo page

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1706]
## Description

I am not sure how this is happening, since I can't recreate it in my Mathlive project, but on the demo page, when I type in `cos(x)^2`, the fields below all have an extra left paren. I would also argue that this expression is already appropriately simplified and that the simplification shown is not the right one!

<img width="455" alt="image" src="https://user-images.githubusercontent.com/69635/200380847-a4d2a5b8-4d69-4582-a9de-e375ccb2f412.png">

**Comment by arnog** [comment]
I believe this has been fixed.
