### ISSUE TITLE
sin^{x <anything else>} in a math-field freezes the page

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1708]
## Description

I haven't fully explored what causes this, but I can reliably freeze the entire page by typing {\sin^x}`, or any other symbol (or `-1`) in the exponent, and then trying to type any other character.

If I leave the exponent, no problem. But if I navigate back and try to type anything after that initial symbol, or `-1`, then the new character doesn't appear and the page freezes (it won't even reload).

Same thing happens with `cos` at the base... again, I haven't explored more, but these reliably reproduce the error.

**Comment by arnog** [comment]
Fixed in main branch of Compute Engine. The trig functions can now include an arbitrary exponent, in addition to -1 for inverse and `\prime`, `\doubleprime` and `'` for derivatives.
