### ISSUE TITLE
\ln x is incorrectly marked !expr.isValid, with empty errors array

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1709]
## Description

Typing `\ln x` results in an expression with `expr.isValid == false`, but `expr.errors` equal to an empty array. When I look at the canonical expression on the demo page, it looks like the parser is expecting some second value. This is incorrect, but I don't see how to supply it.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/69635/200384459-4642fe0e-64ee-4580-9470-359573a9cc79.png">

**Comment by arnog** [comment]
Fixed in main branch of Compute Engine.
BTW, for the two argument version of log, you can use `\\ln_5(2)` (for base 5 log of 2)

**Comment by sritchie** [comment]
Interesting, similar to our previous discussion (I forget which issue!) I would have expected `\log_5(2)` to evaluate to base 5 log of 2. `\ln` to me says "natural logarithm", where natural implies base `e`. `\log` is more "customizable". When I try I see this:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/69635/201501133-05f909a8-bbd6-48ed-abb0-0d368559a7a4.png">

What do you think?

**Comment by arnog** [comment]
Yes, `\log_5(2)` will also work. If you specify a base, it doesn't matter whether you use `\ln` or `\log`. However, without a base `\ln` is natural log and `\log` is base-10 log.

The fixes I have made are in the main branch, but they have not been pushed to the website yet.

**Comment by sritchie** [comment]
Got it, thank you!
