### ISSUE TITLE
SyntaxError: Invalid regular expression: /\p{Letter}/: Invalid escape

### ISSUE THREAD

**Issue by Nifdee** [arnog/mathlive#171]
## Prerequisites

* [x] Did you check the [issue tracker](https://github.com/arnog/mathlive/issues) to see if this issue has already been reported?

## Description
In Google Chrome on Ubuntu, version 63.0.3239.108, mathlive version 0.27.4 fails to load.

The exception seems to be caused by [this regex](https://github.com/arnog/mathlive/blob/master/dist/src/core/definitions.js#L3182) that was recently added.

### Actual behavior
Mathlive does not load; the text box on mathlive.io cannot be used. There is an error message in the console:

![Screenshot from 2019-04-14 21-58-42](https://user-images.githubusercontent.com/3938999/56099149-2d3ba380-5f01-11e9-9cd6-ee035b9f1fe0.png)
![Screenshot from 2019-04-14 21-50-44](https://user-images.githubusercontent.com/3938999/56099190-96231b80-5f01-11e9-97b9-330a1db1f4db.png)

### Expected Behavior 
It should not throw an exception. Everything works fine with version 0.26.0 of mathlive, and with Firefox / new Windows versions of Chrome.

### Environment
**Operating System** 
Ubuntu 18.04.2

**Browser**
Chrome version 63.0.3239.108

**URL**
https://mathlive.io/deploy/index.html

**Comment by Nifdee** [comment]
After upgrading Chrome to version 73.0.3683.103, everything works as expected.

**Comment by arnog** [comment]
The `\p{L}` syntax is a relatively new one which is supported by the most recent versions of modern browsers, except for Firefox (which is special-cased for now), so this is the expected behavior. Let me know if this is a problem.
