### ISSUE TITLE
Valid expr marked as inValid, with empty errors array and valid canonical

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1710]
## Description

Similar to #1709 , the following expression is marked as `!expr.isValid`, but its errors array is empty.

```
\cos\left(x\right)-\sec^{-1}\left(x\right)
```

The canonical expression looks good, and clearly marks that parsing succeeded. (Also note that `\arcsec` is not rendered by the math field.)

<img width="214" alt="image" src="https://user-images.githubusercontent.com/69635/200385183-59b214d1-507b-4397-a3a3-222deeacfe7e.png">

**Comment by arnog** [comment]
Add `\arcsec` and a few other commands.
The other issue is fixed in main branch of Compute Engine.
