### ISSUE TITLE
mathfield-element clobbers window.mathlive

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1711]
## Description

At the bottom of mathfield-element.ts, there is a code snippet that sets a few variables directly on `window`:

https://github.com/arnog/mathlive/blob/f103f9c1e37f3804686565a76bf888e44abb0113/src/public/mathfield-element.ts#L1690-L1694

There are a few references to `window.mathlive`: https://github.com/arnog/mathlive/search?q=%22window.mathlive%22

I'm building a Clojurescript / React wrapper around Mathlive ([code here](https://github.com/mentat-collective/mathlive.cljs), and the JS produced by the Clojurescript build tooling, and I would like to name my main namespace `mathlive.core`, so that users can write

```clj
(ns their-code
  (:require [mathlive.core :as ml]))
```

Clojurescript stores namespaces on these window variables, so `window.mathlive.core = <clojure namespace object>`; so my code gets clobbered when mathlive sets `window.mathlive`, deleting out my code.

## Request

Would it be possible to replace these calls with imports, and then set the global variable only if the user brings in mathlive via a script tag? I'm using mathlive as an NPM dependency and hoping that no globals are introduced.

Hopefully that makes sense... sorry, it felt a bit confusing to write this up, so please ask me for clarification if I've failed!

**Comment by arnog** [comment]
There are a few instances where mathfield instances need to communicate, and they could have been instantiated from different libraries (think of a Wordpress plugin for example, that could create a mathfield, and the main page also creating a mathfield). The `window.mathfield` is used to do this coordination, so it's necessary regardless of whether the library was loaded via a `<script>` tag or a module.

Now, one thing we could (should?) do is to not clobber a pre-existing `window.mathlive` property, so use `window.mathlive = {(...window.mathlive ?? {}),  version: '{{SDK_VERSION}}' }; `. This could work if your toolchain  doesn't clobber the `window.mathlive` property, although it would be fragile: `mathlive.core` is OK, but what if you need a `mathlive.version` with a different meaning than the one used by MathLive?

A more robust solution would really be to use a different namespace, maybe `react-mathlive` or `clojure-mathlive`?

**Comment by sritchie** [comment]
@arnog I am going with mathlive-cljs for now, which definitely solves the issue. I like the idea of not clobbering an existing mathlive.

mathlive use a munged `__mathlive__`, which is less likely to interfere with anything that a user might build on top of the library? Alternatively, something like `mathlive.__version__` for the properties?

Just a few ideas, any of these would be really helpful!

**Comment by sritchie** [comment]
Closing @arnog since your change fixed my issue. Thank you!
