### ISSUE TITLE
Some greek letters (\gamma) autocomplete but are marked invalid

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1712]
## Description

When I type in `\gamma`, I see the following MathJSON output:

```
["Error"
 ["ErrorCode" "'unexpected-command'" "'\\gamma'"] 
 ["Latex" "'\\gamma'"]]
```

And the canonical representation is rendered as `\texttt{\textcolor{red}{\backslash gamma}}`:

<img width="213" alt="image" src="https://user-images.githubusercontent.com/69635/200387163-8f1c2040-2f97-4473-aab8-de8f091c4534.png">

Capital `\Gamma` works fine by comparison. I thought there were more lowercase greek letters giving me issues, but it was a while ago and this is the one obvious one I had found. Hopefully it is just this!

**Comment by arnog** [comment]
Fixed in Compute Engine main branch
