### ISSUE TITLE
\sqrt[x](y) renders but is marked !expr.isValid

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1713]
## Description

Typing `\sqrt[x](y)` incorrectly parses to this MathJSON:

```
["Sequence"
 ["Multiply"
  ["Root" ["Error" ["ErrorCode" "'invalid-symbol-name'" "'('"]] "x"]
  "y"]
 ["Error" ["ErrorCode" "'unexpected-token'" "')'"] ["Latex" "')'"]]]
```

It renders nicely in the math-field but the canonical representation is broken:

<img width="160" alt="image" src="https://user-images.githubusercontent.com/69635/200388321-d43a7c2c-d1ae-48f6-aa8b-88b160af7f61.png">

**Comment by corlick98** [comment]
This is probably because it expects `\sqrt[x]{10}` and so it interprets what you are entering as the cube root of `(` multiplied by 10 instead of the cube root of 10.
I would argue it shouldn't fix this for you but ultimately it is up to arnog.

**Comment by sritchie** [comment]
Ah, yes, @corlick98 you're right! my fault on subbing in () for {}.

**Comment by arnog** [comment]
The `"invalid-symbol-name"` error is not very helpful. Probably could have something better.

**Comment by arnog** [comment]
Sigh... `\sqrt[3](` is actually valid LaTeX (although not very meaningful)

**Comment by arnog** [comment]
Fixed in main branch of Compute Engine. A `missing` error is now returned.
