### ISSUE TITLE
Overriding certain Latex functionality

### ISSUE THREAD

**Issue by MatousAc** [arnog/mathlive#1714]
## Description
This is somewhat of a feature and a follow-up question to issue #1538. This concerns trying to disable certain Latex commands. The advice is to define a macro with the same name that does nothing.
**My Question**:
I have tried to redefine some commands like is mentioned in #1538, but the popup for the default latex command is still appearing as I type. [CodePen](https://codepen.io/MatousAc/pen/xxzRXXq)
![mathLiveIssueDemo3](https://user-images.githubusercontent.com/56884762/200463137-d6c613d1-09ab-4066-bf79-2ab082c29198.gif)

## Steps to Reproduce
1. Define a macro on a field that has the same name as a basic Latex command.
2. Enter the macro into a math field

**Actual Behavior**: Popup shows latex command that is overwritten by your macro.
**Expected Behavior**: Defining your own popup information would be ideal. Not showing the original command you wish to hide is necessary.
Parsing with the custom Compute Engine works as expected regardless.

I've tried to solve this general problem in various ways but to no avail.
|what I have tried|problem I ran into|
|-|-|
|Add macro with the same name as the latex command I want to overwrite.|Works functionally, but not completely with the visuals.|
|Disable the popup altogether|I can't seem to find the option to set for this. I assume it does not exist right now.|
|Remove the command from the `_latexDictionary`|I have done this, but how can I get a math field to use a custom Compute Engine? I can't find this in the documentation either and I am not sure if this solution would even work as I haven't been able to test it yet.|

### Environment
**MathLive version**: `0.84.0`
**Operating System**: Windows
Same across all browsers as far as I can tell. I tried Chrome, Firefox, and Edge.

**Comment by arnog** [comment]
That's a good  point. There isn't currently a way to disable this popup and the popup does not take into account the custom macros.

**Comment by MatousAc** [comment]
Yep. So I think being able to disable it would be a good way to get solve this for now.

**Comment by MatousAc** [comment]
Until the feature to hide of customize the popup is added, I think I will use the following CSS to hide the popup:
~~~
div#mathlive-popover-panel {
    display: none;
}
~~~

**Comment by arnog** [comment]
There is now a `enablePopover` option which can be set to `false` to prevent the popover from being displayed.
The popover also now include custom macros.
It is also now possible to provide a  custom compute engine instance, either via `setOptions()` or `mf.computeEngine = ...`.

**Comment by MatousAc** [comment]
Just tried it and it works as expected.
Thanks for the quick response!
