### ISSUE TITLE
Placeholder default value seems to be ignored?

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1716]
On [the demo site](https://cortexjs.io/mathlive/guides/interacting/#fill-in-the-blank), the `x` in the placeholder's default position is not displayed:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/69635/200669479-b723e018-3449-4a2f-beae-f6f5342a2a5e.png">

I've also noticed that in placeholders, the virtual keyboard is automatically displayed on focus on non-mobile devices, which is different than the usual mathfield behavior.

**Comment by arnog** [comment]
OK, it's a bit confusing, but it turns out the syntax for default value in placeholder is actually `\placeholder[id][default-value]{}`

**Comment by sritchie** [comment]
@arnog , I'm trying this out now and it looks like `input` events aren't firing now when the placeholder value changes. Is this intentional? Is there some other way to capture the placeholder value now?
