### ISSUE TITLE
\mathbb{R} fails to parse to MathJSON

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1717]
## Description

On the demo page, typing `\mathbb{R}` triggers the following error:

<img width="799" alt="image" src="https://user-images.githubusercontent.com/69635/201210215-75b9ad55-9ae2-407e-954a-2e8f48d9ecae.png">

In my code I had this as the MathJSON:

```
["Error"
 ["ErrorCode" "'unexpected-command'" "'\\mathbb'"]
 ["Latex" "'\\mathbb{R}'"]]
```

**Comment by arnog** [comment]
Fixed in Compute Engine
