### ISSUE TITLE
Wonder how to input sin(30deg)?

### ISSUE THREAD

**Issue by BlueCat0** [arnog/mathlive#1721]
## Description

I can write sin function with sin(1/6\pi), but got error when try sin(30\deg).

hope there will be some way to fix it.

**Comment by arnog** [comment]
Just to make sure we're on the same page, what error are you getting? What did you expect to get?
This sounds like that's an issue with Compute Engine, not MathLive (the editor), right?

**Comment by BlueCat0** [comment]
I got this
![2022-11-15_10-44-12](https://user-images.githubusercontent.com/16792362/201813858-ae8c4198-8b22-4940-a2c9-3a0833394325.png)

expect use degree with trigonometric functions
![2022-11-15_10-47-35](https://user-images.githubusercontent.com/16792362/201814294-dd1d541e-12c5-4a37-bbf5-0539ebbda98a.png)

it looks not an error in Compute Engine, because the error seems show not pass the ast check

**Comment by BlueCat0** [comment]
radian was correct in the same time
![2022-11-15_10-49-26](https://user-images.githubusercontent.com/16792362/201814651-9794c52b-703c-45f3-abb5-91325e24e605.png)

but In my scene, degree are used more
