### ISSUE TITLE
[FEATURE] Set mathlive theme(DARK OR LIGHT) programatically

### ISSUE THREAD

**Issue by michelmar** [arnog/mathlive#1722]
## Description
It would be nice to change the theme programatically.
We could still have the default behavior as it is, but giving the option to the user control the theme to be dark or light would be really nice, or if it is already possible I'd like help. Thanks in advance.

**Comment by arnog** [comment]
Can you provide more details on the use case for this? Is it that you want to specify the dark/light theme for an entire page and have the mathfield elements within it match? Of that you want some mathfield in a page with a dark theme and others with a dark theme?

**Comment by michelmar** [comment]
Thanks for your response. My user can choose the default theme with a button, he can choose with he wants light and dark theme, but the default is the theme from the system. I would like to change the theme from the mathlive's keyboard based in the user choosed as well. This way I would like to have more control in what theme is being passed to the mathlive's keyboard, despite the system theme.

**Comment by arnog** [comment]
You can set the attribute `theme` to `"dark"` to force the dark theme, i.e. `<body theme="dark">`.

**Comment by arnog** [comment]
And now you can also set the theme to `"light"`
