### ISSUE TITLE
Copy and paste do not work on Windows (Ctrl-c, Ctrl-v, and Ctrl-x)

### ISSUE THREAD

**Issue by davidbludlow** [arnog/mathlive#1723]
## Description

On Windows 11, when you type Ctrl-c, Ctrl-v, or Ctrl-x it works as if you didn't press Ctrl first. It other words just types c, v, or x, respectively, into the math text field and doesn't do copy/paste. 

This is not reproducible on Mac.

## Steps to Reproduce

1. Go to https://cortexjs.io/mathlive/ on a non-Mac laptop/desktop.
2. Higlight the text in the math text field that is being used for a demo, there.
3. Press Ctrl-c -> you will incorrectly see that it just types "c" and that the clipboard wasn't changes.
4. Try and see the same with Ctrl-x
5. Try and see the same with Ctrl-v

### Environment

**MathLive version** The version that was live on the home page as of 2020-11-21, so I guess that is probably v0.85.1

**Operating System** Windows 11 (Version	10.0.22621 Build 22621)

**Browser**
Firefox latest (107.0)
Chrome latest (107.0.5304.107)
Edge latest

**Comment by arnog** [comment]
I have a fix pending.

**Comment by arnog** [comment]
The fixed is now available in 0.89.4
