### ISSUE TITLE
Fill In The Blank snippet cursor in wrong place

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1727]
## Description

On the demo page: https://cortexjs.io/mathlive/guides/interacting/#fill-in-the-blank

I am getting a weird effect in Brave and Safari where the cursor's position visually does not line up with the editing position. For example:

![2022-11-25 07 46 03](https://user-images.githubusercontent.com/69635/204008545-5f029210-3811-4c60-a299-eceb9e4e473c.gif)

**Comment by arnog** [comment]
This should work better now, the baseline now should line up. Also, the nested mathfield is now using the fontsize of the container. Not sure if scaling it down is valuable, but that could get re-introduced as an option if desirable
