### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by ingodahn** [arnog/mathlive#173]
## Description
Published example pages (e.g. https://mathlive.io/deploy/examples/basic/index.esm.html) are not usable with German keyboard.
![image](https://user-images.githubusercontent.com/3258024/56276967-ca662a00-6103-11e9-99ad-b8155ca422a0.png)

### Actual behavior
Backslashes are removed and slashes are not typeset, while exponentiation, having the same key on US and German keyboards, is typeset.

**Comment by arnog** [comment]
mathlive.io has been updated with master, where those issues have been fixed.
