### ISSUE TITLE
convertLatexToMarkup() doesn't work server-side

### ISSUE THREAD

**Issue by JackWH** [arnog/mathlive#1735]
## Description

I'm trying to use `convertLatexToMarkup` server-side, but it either won't resolve the import, or tries to reference `HTMLElement`.

This seems like it might be related to https://github.com/arnog/mathlive/issues/1330, but the fix doesn't seem to be making any difference.

## Steps to Reproduce

Create a script like this, and run it through Node.js:

```js
import {convertLatexToMarkup} from 'mathlive';

console.log(convertLatexToMarkup('x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}'));
```

I get the following error:

```
import {convertLatexToMarkup} from 'mathlive';
        ^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'convertLatexToMarkup' not found. The requested module 'mathlive' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'mathlive';
const {convertLatexToMarkup} = pkg;
```

If I try changing it as suggested:

```js
import pkg from 'mathlive';

const {convertLatexToMarkup} = pkg;
console.log(convertLatexToMarkup('x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}'));
```

Then it fails with `ReferenceError: HTMLElement is not defined`.

### Environment

This is called in `render.mjs`, using Node.js v19.1.0 and Mathlive v0.85.1.

**Comment by arnog** [comment]
You may need to configure your module resolver to import the esm version of the library. Or maybe try:
```
import {convertLatexToMarkup} from "mathlive/dist/mathlive.min.mjs";
```

**Comment by JackWH** [comment]
@arnog Unfortunately no luck — I'm not using any kind of bundler, simply calling `node ./renderLatex.mjs` in my project. I'd already tried using the `.mjs` version you suggested, but it still fails when trying to reference `HTMLElement`:

```
> node ./renderLatex.mjs
file:///Users/jack/Sites/mysite/node_modules/mathlive/dist/mathlive.mjs:39444
class MathfieldElement extends HTMLElement {
                               ^

ReferenceError: HTMLElement is not defined
    at file:///Users/jack/Sites/mysite/node_modules/mathlive/dist/mathlive.mjs:39444:32
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Feels like I must be missing something obvious, just not sure what! Is this unrelated to https://github.com/arnog/mathlive/issues/1330 ?

**Comment by arnog** [comment]
Ah, OK. You need to include `jsdom`. It's only needed so that the class declaration will pass the interpreter. #1330 was about some actual browser environment code being executed, but as indicated, this has been fixed. So the issue here is different, and including `jsdom` should fix it. Ideally, there would be a special version of mathlive just for the server-side environment, but I haven't gotten to it. Hopefully, the workaround will work for you.

**Comment by JackWH** [comment]
@arnog Thanks for your help 🙏 I managed to get it working but there were a few more steps involved, though I'm not much of a Node expert so I might be making this more complex than it needs to be :) 

I think the issue is to do with using `import` statements in a module file... I was able to include `jsdom` successfully, and hoist the `HTMLElement` class into Node like this:

```js
import {JSDOM} from 'jsdom';

global.window      = new JSDOM().window;
global.document    = window.document;
global.HTMLElement = window.HTMLElement;

console.log({
    object1: global.HTMLElement,
    object2: HTMLElement,
});
```

Both objects are logged successfully, so Node definitely knows what an `HTMLElement` is. But as soon as I add back in the `import {convertLatexToMarkup} from "mathlive/dist/mathlive.min.mjs";` line, it immediately fails with the same error again. I'm assuming this is because `imports` are processed before anything else, so `HTMLElement` isn't available at the time Mathlive references it (?).

In the end I got it to work by renaming my `render.mjs` file to `render.js` (so I can use `require()`), then defining an `HTMLElement` class which extends from a global shim [I found here](https://www.npmjs.com/package/html-element):

```js
require('html-element/global-shim');

class HTMLElement extends Element {}

global.HTMLElement = HTMLElement;

console.log(require('mathlive').convertLatexToMarkup('x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}'));
```

**Comment by arnog** [comment]
There is now a version of MathLive specifically for server-side rendering: `/dist/mathlive-ssr.min.mjs`.
The server-side rendering  code has also been isolated and no longer require jsdom: `src/public/mathlive-ssr.ts`.

**Comment by boompikachu** [comment]
Using `mathlive/dist/mathlive-ssr.min.mjs` and logging out the object gives undefined. I'm using Nextjs 13

```tsx
import mathlive from 'mathlive/dist/mathlive-ssr.min.mjs';
import { useEffect, useState } from 'react';

function TestPage() {
  console.log(mathlive); // undefined in both server and client

  useEffect(() => {
    console.log(mathlive); // undefined
  });

return ....
}
```

**Comment by arnog** [comment]
I think you want to use:
```
import { convertLatexToMarkup } from 'mathlive/dist/mathlive-ssr.min.mjs';
```

**Comment by boompikachu** [comment]
Thanks for the reply; it works!

By any chance, is there a declaration file (.d.ts) for `mathlive/dist/mathlive-ssr.min.mjs`?

**Comment by arnog** [comment]
Yes, it's `mathlive/dist/public/mathlive-ssr.d.ts`

**Comment by boompikachu** [comment]
It seems that the import doesn't recognize the declaration file

<img width="449" alt="Screenshot 2023-02-09 at 12 53 26 PM" src="https://user-images.githubusercontent.com/37561295/217729849-5805b743-3cac-4e46-8802-e08d08c8694c.png">

Here is the codesandbox: https://codesandbox.io/s/clever-microservice-colkz5?file=/src/App.tsx

**Comment by boompikachu** [comment]
Also, from the declaration file, there's no `MathfieldElement` exported from `mathlive-ssr` thus I have to import from 'mathlive' as follows. 

```tsx
import { MathfieldElement } from 'mathlive';
import { convertLatexToMarkup } from 'mathlive/dist/mathlive-ssr.min.mjs';
import { useEffect, useState } from 'react';

function TestPage() {
  const [state, setState] = useState('');

  
  console.log(convertLatexToMarkup);

  useEffect(() => {
    const mfe = new MathfieldElement();
    console.log(mfe);

    console.log(convertLatexToMarkup);
  }, []);

....
```

But this cause `ReferenceError: HTMLElement is not defined` to occur
<img width="959" alt="image" src="https://user-images.githubusercontent.com/37561295/217732309-bbe286bb-4758-48e1-b840-c76a7a4d3e23.png">

**Comment by arnog** [comment]
I'm not sure what you're trying to do. MathfieldElement is a DOM element. It therefore cannot be used server side, since there is no DOM. The call `convertLatexToMarkup` does not depend on a MathfieldElement or the DOM and can be used on the server side.

**Comment by boompikachu** [comment]
I'm trying to use `MathfieldElement` in a Next.JS project (try to render in client normally); however, I could not call `const mfe = new MathfieldElement()` or else it will cause  `ReferenceError: HTMLElement is not defined`. I tried putting it inside `useEffect` hook but it gives the same error.

**Comment by arnog** [comment]
If you are trying to render on the client side, you should be able to call `new MathfieldElement()` or `new TextArea()` for that matter. It sounds like you are configured to do server side rendering. When doing (React) server side rendering, the DOM is not available, and you cannot create dynamic DOM element. You can only render markup, i.e. `<math-field>` or `<textarea>` which will be hydrated on the client later.

To clarify another potential point of confusion, in the context of React (or Next.js) **server side rendering** refers to rendering the content of your page on the document, that is statically generating the markup for your page, then hydrating it on the client.

In the context of MathLive, **server side rendering** refers to the ability to create markup representing a LaTeX expression. 

The MathfieldElement cannot be "rendered" on the server side, since it's an interactive component, just like a `TextArea` element cannot be rendered on the server. Instead, you can create some markup (`<math-field>` and `<textarea>`, respectively) that get sent to the client and instantiated there.

Hope this helps clarify things a bit.

**Comment by boompikachu** [comment]
For anybody who came across my problem (using mathlive in NextJS), there are 3 solutions that I found

1. Use dynamic import to import the component that uses mathlive with ssr turned off (not mathlive itself)

```tsx
const MathInput = dynamic(() => import('path/to/your/component').then(mod => mod.MathInput), { ssr: false })
```

2. Import mathlive in useEffect
``` tsx

const mfeRef = useRef<MathfieldElement>();
const [isMfeReady, setIsMfeReady] = useState(false);

useEffect(() => {
    (async () => {
      const MathfieldElement = (await import('mathlive')).MathfieldElement;
      const mfe = new MathfieldElement(/* config option here */);
      mfeRef.current = mfe;
      // replace children of div with mfe
      setIsMfeReady(true);
    })();
  }, []);
```

3. Use callback ref
```tsx
  const mfeRef = useRef<MathfieldElement>();
  const [isReady, setIsReady] = useState(false);

  const mathInputCallbackRef = useCallback(async (el: HTMLDivElement) => {
    const MathfieldElement = (await import('mathlive')).MathfieldElement;
    const mfe = new MathfieldElement(/* config option here */);
    el?.replaceChildren(mfe);
    mfeRef.current = mfe;
    setIsReady(true);
  }, []);

  return <div ref={mathInputCallbackRef} />;
```
