### ISSUE TITLE
Fill in the blank on demo page misaligned

### ISSUE THREAD

**Issue by sritchie** [arnog/mathlive#1736]
## Description

I've just noticed that the fill in the blank element on the demo page has the blank in the wrong spot; on highlight it jumps to the right.

![2022-12-01 14 09 17](https://user-images.githubusercontent.com/69635/205159839-b2193abf-a5df-4140-a2c1-5eb3110dcc86.gif)

**Comment by arnog** [comment]
Fixed in mathlive 0.90.0
