### ISSUE TITLE
bundle optimizations and tree shaking

### ISSUE THREAD

**Issue by thesabbir** [arnog/mathlive#1751]
Hi, is tree shaking supported? The current bundle size is over 640KB minified. I'd love to see it shrink with tree shaking. I tried to to import the package using git clone then directly importing from typescript but I get a lot of errors.

**Comment by arnog** [comment]
No reason I can think of that it would not work.

That said, if you're using the mathfield component, it's unlikely that tree shaking would be very effective. There's just not much in the package that's not necessary. The only thing that tree shaking may help with is you only use static rendering (i.e. `renderMathInElement()`).

**Comment by thesabbir** [comment]
Well, if everything is required then there is no point. Love this project. 

Cheers 😄
