### ISSUE TITLE
Text mode and currency

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#176]
## Description
With smartMode on for typing text and math, currency amounts (at least when using `$`, but possibly euros also) look poor. Below is an example:
![image](https://user-images.githubusercontent.com/1545836/56616095-7e1e5c80-65d1-11e9-8618-5136c8a79d98.png)

It looks strange to have the digits for the currency separated from the `$` -- either the digits should be part of the text run or the `$` should be part of the math run.

A second problem is that `.` is auto changing to `\cdot`. Potentially, that could be smart to indicate multiplication, but as part of currency, that's very wrong. With smartMode off, I don't see `.` becoming `cdot` in either math or text mode, so it seems likely this is a bug also.

**Comment by NSoiffer** [comment]
Unfortunately the fix is buggy. Type `Salary is \$[return]325 and`.

What you get is `\text{Salary is }\$325and` -- it won't go back to text mode.

**Comment by arnog** [comment]
That's the intended behavior: after a mode switch (triggered in the example above by using "\" to enter command mode), smart mode is temporarily suppressed.

**Comment by NSoiffer** [comment]
When I try it, it is not temporary at all -- it _never_ goes back to text mode. The "and" isn't in text mode in my example above and neither is any other word that is typed after it.
