### ISSUE TITLE
custom strings not working

### ISSUE THREAD

**Issue by johanneswilm** [arnog/mathlive#177]
## Prerequisites

* [X] Did you check the [issue tracker](https://github.com/arnog/mathlive/issues) to see if this issue has already been reported? **Yes**

For more information, see the `CONTRIBUTING` guide.

## Description

I try to call MathLive 0.28.0 with custom strings, like this:

```
MathLive.makeMathField(this.mathliveDOM, {
    ...
    locale: 'fr-CA',
    strings: {
        'fr-CA': {
            'tooltip.undo': 'Annuler',
            'tooltip.redo': 'Refaire'
        }
    }
})
```

### Actual behavior
MathLive does not start and there is an error message:

```
mathlive.js:1 Uncaught TypeError: e is not iterable
    at Function.us.merge (mathlive.js:1)
    at _i.setConfig._i.$setConfig (mathlive.js:1)
    at new _i (mathlive.js:1)
    at Object.makeMathField (mathlive.js:1)
```

### Expected Behavior 
I would expect for MathLive to be run with these strings.

### Environment
**Operating System** 
Linux

**Browser** 
Chrome

**Comment by arnog** [comment]
Good catch. Thanks for writing up this bug report. Fixed now.

**Comment by johanneswilm** [comment]
@arnog Thanks! I am looking forward seeing this in a release so I can pull it in through npm.
