### ISSUE TITLE
setValue doesn't propagate to placeholders

### ISSUE THREAD

**Issue by gerryfletch** [arnog/mathlive#1770]
## Description
- When using `setValue`, or directly setting `.value` on a `mathfield` element, nested mathlive elements (placeholders) don't receive the updates
- My personal expectation is that `setValue` on a parent mathfield should completely rerender the tree, i.e. if the new `setValue` changed from 2 placeholders to 1, the 2nd nested element should be removed

## Steps to Reproduce
1. Create a mathlive element with some placeholders, e.g `(1, 1)`:
```
'(\\placeholder[x]{1}, \\placeholder[y]{1})'
```

2. In your browser, select the parent mathlive and store it as a variable, then call to set the value to `(2, 2)`
```js
mathlive.setValue(
  '(\\placeholder[x]{2}, \\placeholder[y]{2})'
);
```

2. If you would prefer to do it via code, just reference the parent `MathfieldElement` and call `.setValue` in the same respect

### Actual Behavior
- The nested mathfields do not update, but the `.value` of the parent has. No visual changes are made.

### Expected Behavior
- The entire tree should rerender when the parent `.value` has been updated. A good example would be updating it to remove the 2nd placeholder, my expectation is for the whole tree to update and the 2nd nested mathfield to be removed.

### Environment
- Version: latest (0.86.0)
- OS: Mac OS
- Browser: Chrome

**Comment by gerryfletch** [comment]
@arnog Sorry for the bump, I wondered if you had any idea what the work would be to fix this, or a workaround I could take in the meantime?

**Comment by arnog** [comment]
The current version of MathLive has a different implementation for `\placeholder{}`. Changing the value of the mathfield will change the placeholders.

**Comment by arnog** [comment]
Fixed in mathlive 0.90.0

**Comment by arnog** [comment]
It refers to the ID provided with the placeholder, that is the id in \placeholder[id]{}.

I don’t understand what doesn’t work. Could you provide an example with the result you’re getting vs what you’re expecting?

**Comment by gerryfletch** [comment]
Here:

```
> temp1
<math-field read-only contenteditable=​"true" tabindex=​"0" class=​"default-math-editor ">​…​</math-field>​

> temp1.value
'x=\\placeholder[answer]{3}'

> temp1.getPrompts()
['cj1cya']
```

The prompt ID returned from `getPrompts` is some randomly generated short string. It correlates with the `data-atom-id` of the placeholder element in the markup. I was expecting it to return `['answer']`

**Comment by arnog** [comment]
It’s fixed now.
