### ISSUE TITLE
Unexpected result when "/" typed after parentheses

### ISSUE THREAD

**Issue by ChristopherChudzicki** [arnog/mathlive#1772]
## Description
Pressing `/` after a function has unexpected results. For example:

https://user-images.githubusercontent.com/9010790/210697727-8c7f9768-201b-4dfd-94fd-f94836def47b.mov

Expected: `f(x)=\frac{f(x)}{2}` *E.g., this is how [mathquill](http://mathquill.com/) behaves.
Actual: `f(x)=f\frac{(x)}{2}`

This is in Chrome/Safari on the latest version of MathLive:
```html
<!DOCTYPE html>
<html>
<body>
    <script src="https://unpkg.com/mathlive"></script>
    <script>
      window.addEventListener('DOMContentLoaded', 
        () => MathLive.renderMathInDocument()
      );
    </script>
    <p>I will press "<kbd>/</kbd>" then "<kbd>2</kbd>"</p>
    <math-field>y = f(x)</math-field>
</body>
</html>
```

**Comment by gunnarmein-ts** [comment]
I can confirm this. It seems like the mathfield parses this as an implicit product. For cortex, you would have to tell cortex that f is a function, but that seems undue for the plain mathfield.

**Comment by ChristopherChudzicki** [comment]
Thank you! Working great.
