### ISSUE TITLE
Issue with iFrames

### ISSUE THREAD

**Issue by manstie** [arnog/mathlive#1781]
## Description

I am trying to clone a math element and place the contents in an iFrame in order to run `print` on the contents. When doing so I have run into some issues.

Firstly, on Firefox when the element is appended to an iFrame there is the following console error:
![image](https://user-images.githubusercontent.com/12475567/211162645-eab91260-9a67-4019-bb59-eff01e87d926.png)
There is also an error when you click the `math-field` inside the iFrame:
![image](https://user-images.githubusercontent.com/12475567/211163676-8914d768-ca65-4513-b6af-e1c923fc4d63.png)

I do not care about the errors, my main concern is the second issue: the fonts directory does not get set, so the fallback font makes it render differently which I do not want.

Example:
https://svelte.dev/repl/6e96160fc8c74b289fc306586b3b113d

(This link only works in Firefox, Chromium gives CORS errors but if you re-create on a local server it doesn't seem to have the console error but the fonts still don't load)

You can replace the code in `examples/latex/index.html` to see it on chromium:
```html
  <body>
    <header>
      <h1>MathLive LaTeX Editor</h1>
    </header>
    <main>
      <div id="inputs">
        <h2>Formula</h2>
        <math-field id="mf"></math-field>
        <h2>LaTeX</h2>
        <textarea
          class="output"
          id="latex"
          autocapitalize="off"
          autocomplete="off"
          autocorrect="off"
          spellcheck="false"
        ></textarea>
      </div>
      <div class="buttonbar">
        <button id="make-iframe">Make iFrame</button>
      </div>
    </main>

    <script type="module">
      import '/dist/mathlive.mjs';

      const mf = document.getElementById('mf');
      mf.setOptions({
        smartMode: true,
        virtualKeyboardMode: 'manual',
      });
      mf.addEventListener('input', (evt) => {
        document.getElementById('latex').value = mf.getValue();
      });

      document.getElementById('latex').addEventListener('input', (ev) => {
        mf.setValue(ev.target.value);
      });

      document
        .getElementById('make-iframe')
        .addEventListener('click', makeIframe);

      function makeIframe() {
        const iframe = document.createElement('iframe');
        iframe.onload = () => {
          iframe.contentDocument.body.appendChild(mf.cloneNode(true));
        };
        document.body.appendChild(iframe);
        const printDocument = iframe.contentDocument;
        printDocument.open();
        printDocument.write(`
<html>
  <body>
    <button onclick="print()">Print</button>
  </body>
</html>
        `);
        printDocument.close();
      }
    </script>
  </body>
</html>
```

## Steps to Reproduce

1. Open https://svelte.dev/repl/6e96160fc8c74b289fc306586b3b113d in Firefox
2. Open console
3. click "Make iframe" button

### Actual Behavior

1. Console error (In Firefox)
2. Observe the different rendering/font on the iFrame `math-field`

### Expected Behavior

1. No console error
2. Font works in iFrame

### Environment

**MathLive version**
0.86.0

**Operating System**
Windows 10 Build 19044.2364

**Browser**
Firefox 108.0.1
Microsoft Edge 108.0.1462.76
Google Chrome 108.0.5359.125

**Comment by manstie** [comment]
The fonts issue is solved with this:
```
document.fonts.forEach((f) => {
  if (f.family.startsWith('KaTeX')) {
    printDocument.fonts.add(f);
  }
});
```
I am happy for this to be closed if you do not care about the console errors.

**Comment by manstie** [comment]
Due to the different way the fonts directory gets set, this is now an issue again.

**Comment by arnog** [comment]
@manstie this approach (cloning a Mathfield node and inserting it into an iframe) is going to be difficult to make work. The iframe must load the MathLive library.

Another approach that should work is to get the LaTeX from the mathfield, call `convertLatexToMarkup()` and insert the result in a DIV element in the iframe. You also need to load the `mathlive-static.css` stylesheet in the iframe.

**Comment by manstie** [comment]
That's a good idea, I will try it later. Thanks for your insight.

**Comment by manstie** [comment]
Here is a printing test html for your enjoyment:
```
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Print Test</title>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />
    <link rel="stylesheet" href="../style.css" />
    <link rel="icon" href="data:," />
    <style>
      math-field {
        border: 1px solid var(--editable-border);
        padding: 5px;
        margin: 10px 0 10px 0;
        border-radius: 5px;
        background: var(--editable);
        color: var(--on-editable);
        max-width: 640px;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <header>
      <h1>Print Test</h1>
      <ul>
        <li><a href="../smoke/">Smoke</a></li>
        <li class="current"><a href="../printing/">Printing</a></li>
        <li>
          <a href="../virtual-keyboard/">Virtual Keyboard</a>
        </li>
        <li>
          <a href="../mathfield-states/">States</a>
        </li>
        <li>
          <a href="../prompts/">Prompts</a>
        </li>
      </ul>
    </header>
    <main>
      <math-field id="mf">x^2+1</math-field>

      <button id="print">
        Print with iframe
      </button>
    </main>

    <script type="module">
      import {
        convertLatexToMarkup,
      } from '/dist/mathlive.mjs';

      const mf = document.getElementById('mf');
      const btn = document.getElementById('print');

      btn.addEventListener('click', printIframe);

      function printIframe() {
        const iframe = document.createElement('iframe');
        document.body.appendChild(iframe);
        const printDocument = iframe.contentWindow.document;
        printDocument.open();
        printDocument.write(`
<html>
  <head>
    <link rel="stylesheet" href="/dist/mathlive-static.css">
  </head>
  <body>
  </body>
</html>
            `);
        printDocument.close();

        iframe.onload = async () => {
          const markup = convertLatexToMarkup(mf.getValue('latex'));
          const el = printDocument.createElement('div');
          el.innerHTML = markup;
          printDocument.body.appendChild(el);
          iframe.contentWindow.print();
          iframe.remove();
        }
      }
    </script>
  </body>
</html>
```
