### ISSUE TITLE
Bolding and italicizing

### ISSUE THREAD

**Issue by quadmachine** [arnog/mathlive#179]
## Description
Italic and bold keys on the virtual keyboard do not work as expected. I am not sure if I am adding them properly. I would like to have Bold and Italic buttons, which allow me to wrap SELECTED math/text with `\mathbf{}` and `\mathit{}`. 

My current solution is 

```
<li class='keycap' data-insert="\\mathit{#?}~">italic</li>
<li class='keycap' data-insert="\\mathbf{#?}~">bold</li>
```
There are two issues with this:

1. If I select some text and press italic button, the selected text will be lost, and replaced with `\mathit{\placeholder{}}`, I would expect selected text to stay instead of `\placeholder{}` part.

Here is a video of the problem for easier understanding:
http://ul.authoring.profil-klett.hr/mladen/screencast_2019-04-24_11-13-29.mp4

2. Notice I have `~` at the end of my insert, before adding that part once I would enter italic by pressing the button on the keyboard, all text following would still be in italic, I could not move my cursor outside of `\mathit{}`

I have found a working example of bold here https://mathlive.io/sprint15/ but I am not sure how to apply this to a virtual keyboard?

**Comment by arnog** [comment]
```
<li class='keycap' data-command='["applyStyle",{"series":"b"}]'>bold</li>
<li class='keycap' data-command='["applyStyle",{"shape":"it"}]'>italic</li>
```
