### ISSUE TITLE
The documentation doesn't render \enclose examples correctly (although they work as expected in an actual Mathfield)

### ISSUE THREAD

**Issue by JackWH** [arnog/mathlive#1790]
## Description

The [documentation for `\enclose`](https://cortexjs.io/mathlive/reference/commands/#notations) renders each example identically, so it's not possible to tell how each notation differs:

<img width="804" alt="Screenshot 2023-01-14 at 19 00 27@2x" src="https://user-images.githubusercontent.com/627533/212491701-88c2eedd-77c7-4ca0-947f-250a4bd4a55f.png">

When actually using any of the `\enclose` notations in a Mathfield, they do seem to apply correctly (at least from the handful I tried). Perhaps this only affects static math rendering?

I could reproduce this in the latest versions of both Safari and Chrome, on macOS Ventura.

**Comment by arnog** [comment]
The issue could happen depending on the style rules in effect. The annotation (the result of the `\enclose` command) was displayed with a `z-index` of -1. If something opaque was between level -1 and the automatically assigned level of the rest of the expression, the annotation would not display.

**Comment by arnog** [comment]
This is now fixed in MathLive but the documentation page will continue to render incorrectly until a new version of MathLive is pushed to npm.
