### ISSUE TITLE
Virtual Keyboard not showing in custom cintainer

### ISSUE THREAD

**Issue by jaytecch** [arnog/mathlive#1793]
I changed the custom container of the virtual keyboard but it doesn't work and keeps sticking to the bottom of the page. And yes I set the CSS "position" property of my element to  "relative". No progress still!

**Comment by arnog** [comment]
Sorry to read you're having some problem. Unfortunately, there's not enough details here for me to be able to help out. If you had a sample project to share, I'd be happy to have a look.

**Comment by arnog** [comment]
Not enough information to be actionable. Closing.
