### ISSUE TITLE
Can't enter `si^n` or any `{known-operator-with-^-inside}`

### ISSUE THREAD

**Issue by kubaPod** [arnog/mathlive#1798]
## Description

If one enters `si^n` `c^os` it always jumps to `sin`, `cos`. 

### Expected Behavior

While it is not critical I think in general it should be possible to enter `si^n`. 

The more that if we define more 'operators' via `onInlineShortcut` then they are affected as well.

### Environment

**MathLive version 0.87.0**

**Operating System** Windows 10 

**Browser** Chrome

**Comment by arnog** [comment]
I can't reproduce this. Did you try here: https://cortexjs.io/mathlive/demo/ ?

This behavior may be a side-effect of a custom `onInlineShortcut` handler. If you can share your implementation, I'd be happy to have a look.

**Comment by kubaPod** [comment]
@arnog I took https://cortexjs.io/mathlive/demo/ to the incognito window. And I replaced `console.log(mf.expression.json)` with `console.log( mf.getOptions('onInlineShortcut'));`

I press `s` `i` `^` `n` and see:

![image](https://user-images.githubusercontent.com/15227576/214398897-cd63b61c-64df-4491-9a4a-acce94355949.png)

Chrome 109.0.5414.75 64bit
Windows 10

**Comment by arnog** [comment]
That's wild.  I still can't make it happen. You wouldn't have access to a Mac to try it on?

**Comment by NSoiffer** [comment]
Probably not a helpful comment, but I don't have the problem with same chrome/windows 10 config.

It looks very much like the `^` key didn't fire. Maybe a keyboard issue?

**Comment by arnog** [comment]
@NSoiffer actually, that's helpful. It's not a OS specific issue. It's something else. Broken key? 😃

@kubaPod which keyboard layout are you using? QWERTY? And which locale?

**Comment by kubaPod** [comment]
@arnog @NSoiffer I realized what is a problem, me. 
My muscle memory made me enter the superscript with `Ctrl+6` instead of just `Shift+6` . It was so because Ctrl+6 is the way to go in Wolfram Mathematica system, which I used to use extensively on daily basis.

In my defense, when you enter `Ctrl+6` the UX is the same as with `Shift+6`, the superscript is created and caret is moved there, only after `n` the outcome changes. 

I apologize for confusion.

**Comment by arnog** [comment]
Ah... OK. So, yes, there is a bug: typing `s` + `i` + `ctrl`-`6` + `n` yields `\sin` instead of `\si^n`.

**Comment by NSoiffer** [comment]
To close the circle, so to speak... I'm semi-responsible for the bug report in that I wrote the Mathematica math editor. That makes me responsible for your muscle memory using `cntl-6`.  :-)

**Comment by kubaPod** [comment]
@NSoiffer nice to meet you!
