### ISSUE TITLE
Hard to enter multi digit superscripts.

### ISSUE THREAD

**Issue by kubaPod** [arnog/mathlive#1808]
## Description

Insertion point moves to quickly from the superscript, just after the first digit. It does not happen for letters.

## Steps to Reproduce

`x` `^` `1` `1` produces `x^11` while (the second 1 is in the base script)
`x` `^` `a` `b` produces `x^{ab}`

### Expected Behavior

`x` `^` `1` `1` produces `x^{11}` and the insertion point stays in in the superscript unless e.g. right arrow is entered.

### Environment

**MathLive version** 0.87.1

**Operating System** Window 10

**Browser** Chrome

**Comment by kubaPod** [comment]
@arnog didn't expect that, thanks. Feel free to close it then.

**Comment by arnog** [comment]
@kubaPod sure, but FYI since you opened it, you can close it too.
