### ISSUE TITLE
Is it possible to get the caret position in the latex (i.e., getValue()'s return value).

### ISSUE THREAD

**Issue by ichibha** [arnog/mathlive#1812]
HI, when the caret is within the equation like,
![スクリーンショット 2023-02-05 22 00 19](https://user-images.githubusercontent.com/41054969/216820183-acbceb80-108c-4290-81d9-a6a0d27411fa.png)
could I get the position of the caret in the latex output:
f\left(a\right)=ax+b
such as "the caret is after the 17th character (i.e., 'a')"?

**Comment by arnog** [comment]
Hmmm... yes, but not directly. 

You can get the position of the caret with `mf.position`. In your example this would return 6 (each value of `mf.position` is a valid place for the caret).

If you want to know the corresponding position in the value represented as LaTeX you would do `mf.getValue(0, mf.position)`. This would return `"f\left(a\right)=a"`, and you could get the length of that string to get the value you want.

**Comment by ichibha** [comment]
Environments: "mathlive": "^0.86.0", Apple M2, macOS 13.2（22D49）

@arnog Thank you for answering! The solution sometimes doesn't work for my problem because, for example, mf.getValue(0, mf.position) doesn't tell that the cursor is in the fractional in the following equation:
![スクリーンショット 2023-02-06 15 11 35](https://user-images.githubusercontent.com/41054969/216896562-581dd5b0-9a6a-441b-be81-295ad26fb457.png)
The return value of getValue is f(x)=\sin(x+\pi)a. 

My motivation is to revive a placeholder that disappeared by "input a character and delete it in the placeholder". As an alternative way, I am thinking to insert a keyword like CURSORHERE and detect the cursor position with getValue(). However, this solution disturbs the edit history for undo/redo. 

Could I make changes without updating the edit history?

**Comment by ichibha** [comment]
I also want to implement replacing ‘a' by '\vec{a}’ via button push by removing ‘a’ and adding ‘\vec{a}’. However, this also disturbs the edit history. Thus, the function to halt the history updates would be generally important.

**Comment by arnog** [comment]
How do you replace `a` with `\vec{a}`, that is what MathLive calls do you make?

**Comment by ichibha** [comment]
1. Read the left-side character from cursor. 
2. If the character is appropriate for \vec{}, keep it in a variable (let c). Otherwise, break this process. 
3. Call mf.executeCommand("deleteBackward")
4. Call mf.insert("\\vec{"+ c + "}")

Here, I like to avoid to save the state at step 3 into the history. 
I don't have a specific idea for the step 2 yet, but I believe that considering several specific cases will bring a solution.

**Comment by arnog** [comment]
OK, so you can try:

1. `mf.selection = [[mf.position - 1, mf.position]]`
2. `mf.insert(...)`


When calling `mf.executeCommand()`, the command is handled as if it had been issued by the user (think of wiring to a UI button for example), and will be undoable.

However, functions like `mf.insert()` are intended to be programmatic and should not be undoable. So, by changing the selection, then calling insert to replace it, you should get the replacement you are looking for, without having made an undoable operation. Note that `mf.insert()` takes an extra parameter to specify some options, like where you want the selection to be after the insertion.

**Comment by ichibha** [comment]
> OK, so you can try:
> 
> 1. `mf.selection = [[mf.position - 1, mf.position]]`
> 2. `mf.insert(...)`
> 
> When calling `mf.executeCommand()`, the command is handled as if it had been issued by the user (think of wiring to a UI button for example), and will be undoable.
> 
> However, functions like `mf.insert()` are intended to be programmatic and should not be undoable. So, by changing the selection, then calling insert to replace it, you should get the replacement you are looking for, without having made an undoable operation. Note that `mf.insert()` takes an extra parameter to specify some options, like where you want the selection to be after the insertion.

The solution worked. Thank you!

About the other issue, I want to keep the placeholder of A^{#0}_{#1} for the user to confirm the input positions. If A^{}_{}, the user thinks there being just a space after A. Is it possible to visualize empty groups?

**Comment by ichibha** [comment]
I have now made the issue. Thank you again for your answers.
