### ISSUE TITLE
Smart fence doesn't envelope a fraction

### ISSUE THREAD

**Issue by sbondaryev** [arnog/mathlive#1813]
## Description

![mathlive](https://user-images.githubusercontent.com/2843147/217256938-a370d68b-6a62-4b39-9ba1-4cc1b175cf26.gif)

## Steps to Reproduce

0. Go to the demo page https://cortexjs.io/mathlive/demo/

first case
1. Open the parenthesis and write the two-term expression (ex `x-1`)
2. Select the expression and try to create a fraction by typing `/`

second case
1. Write the fraction `\frac{x-1}{x}`
2. Put the pointer before the fraction and open parenthesis

### Actual Behavior
The fraction appears in front of the parenthesis

### Expected Behavior
The fraction appears in the parenthesis

### Environment
**MathLive version**
0.87.1
**Operating System**
macOS
**Browser**
Google Chrome 109.0.5414.119 (Official Build) (x86_64)

**Comment by arnog** [comment]
This behaves correctly now.
