### ISSUE TITLE
[Question]: Is there a doc about placeholder?

### ISSUE THREAD

**Issue by boompikachu** [arnog/mathlive#1827]
I'm trying to customize the keyboard and layers but can't seems to find docs about the placeholder. 

What is the difference between `#@`, `#?`, `#0`, and `#1 - #9`? 

There are some examples in https://cortexjs.io/mathlive/guides/virtual-keyboards/ and simple explanation in https://cortexjs.io/mathlive/guides/macros/ ("The macro definition can contain up to eight arguments, represented by `#1` to `#9`.")

There's also some explanation in the source code 
<img width="467" alt="image" src="https://user-images.githubusercontent.com/37561295/218368453-18e72b8a-2b23-415c-a69b-d4632c4565a7.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/37561295/218368518-5e19224a-aee8-4727-a80e-01c2ff92a1ba.png">

Also some in https://gitter.im/cortex-js/community?at=5f8fb65a955f6d78a940e433

<img width="496" alt="image" src="https://user-images.githubusercontent.com/37561295/218368737-cfac175b-dbcb-490a-a3c3-ebe16bb5744f.png">

So from what I can conclude:
`#@` is a placeholder that will be replace by what is selected
`#?` is a normal placeholder
`#0-9` something for arguments?

**Comment by arnog** [comment]
Yes, that's correct.

Keeping it open, so I update the doc to clarify.

**Comment by arnog** [comment]
Added section https://cortexjs.io/mathlive/guides/virtual-keyboards/#placeholder-tokens

Note that `#0`-`#9` are only applicable to macros. So, the only two special tokens for virtual keyboard keys are `#?` and `#@`
