### ISSUE TITLE
Command mode bug in smartMode

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#183]
## Description
1. Config mathlive with `smartMode: true`
2. Type `If \alph`. A prompt comes up to accept 𝛼.
3. Hit return

Instead of seeing `if 𝛼`, you get:
![image](https://user-images.githubusercontent.com/1545836/56844773-cd32ee80-686a-11e9-83f1-5e9b308d3598.png)

If you only type `al`, then you will only see those letters.

This might be tangentially related to #176 -- I think something wrong is happening is happening with text mode switching and command mode.

**Comment by arnog** [comment]
This is the expected behavior (which was changed to address https://github.com/arnog/mathlive/issues/44). To complete a symbol, press "tab". To complete as is, type return, so if you type "\alp"+[return], you will get the command "\alp" inserted.
