### ISSUE TITLE
Can't shift between text and math mode using keyboard shortcut with Brazilian keyboard layout

### ISSUE THREAD

**Issue by michelmar** [arnog/mathlive#1830]
## Description

The keyboard shortcut defined in the page [keybindings](https://cortexjs.io/mathlive/reference/keybindings/) for alternating between text and math mode isn't working a

## Steps to Reproduce

1. Go to the demo page
2. Type `⇧ '` as described on the page
3. It types " in the Mathlive editor

### Actual Behavior
It types " in the Mathlive editor

### Expected Behavior

The Mathlive editor should toggle between math and text mode.

I think that Shift+' isn't a good keybinding because this should produce " character. I think or this shortcut is wrong or it isn't working properly.
Could you help me?

### Environment

**MathLive version** 0.87.1

**Operating System** macOS 13.0.1

**Browser** Chrome

**Comment by arnog** [comment]
What kind of physical keyboard layout are you using? Are you using an AZERTY keyboard by any chance?

**Comment by michelmar** [comment]
Actually, I'm using the standard keyboard from mac that is QWERTY I think, I went to the configurations to see if something was different. I struggled to have a good way for my user to type something like \mathrm{H_2O} without going to the latex mode.
I tried to include an inline shortcut like text: "\mathrm{#1}" but couldn't focus on the placeholder generated.

We're using Mathlive a lot in our product I'm so excited to show you the results, We'd like to help you develop this awesome library but we're struggling to survive our schedule.

**Comment by arnog** [comment]
The current version of MathLive is 90.0.7. Does the same thing still happens when you try it here: https://cortexjs.io/mathlive/demo/ ?

When you say “I tried to include an inline shortcut like text: "\mathrm{https://github.com/arnog/mathlive/issues/1}" but couldn't focus on the placeholder generated.”, what do you mean? How did you “include an inline shortcut?” Could you share the JavaScript code that you used?

**Comment by michelmar** [comment]
It worked when I changed the input to this 
![image](https://user-images.githubusercontent.com/60835138/227803181-27767261-3083-4e3f-b511-f02b5664a85e.png)
I was using Brazilian input before, there the majority of the shortcuts are not working, unfortunately. 

As for the inline shortcut I'm doing like this (there are more, but I used a less verbose version): 

```typescript
const INLINE_SHORTCUTS: Record<string, InlineShortcutDefinition> = {
  underbrace: { value: "\\underbrace{#1}_{#2}" },
  overbrace: { value: "\\overbrace{#1}^{#2}" },
  overline: { value: "\\overline{#1}" },
   text: { value: "\\mathrm{#1}" },
};

export default INLINE_SHORTCUTS;
```
I'm using like this: 
```typescript
  useEffect(() => {
    if (ref.current) {
      ref.current.inlineShortcuts = {
        ...ref.current.inlineShortcuts,
        ...INLINE_SHORTCUTS,
      };
      ref.current.macros = {
        ...ref.current.macros,
        unit: "{#1}\\,\\mathrm{#2}",
      };
    }
  }, [options]);
```
The other shortcuts are working really well, but with \operatorname{`#1`} or \mathrm{`#1`} it's not working as in the gif bellow: 
![myGif](https://user-images.githubusercontent.com/60835138/227803733-89963f11-578e-43b5-82c4-2670607fa0c2.gif)

**Comment by arnog** [comment]
Sorry, I should have been clearer: US QWERTY layout. With the Brazilian layout, the `'`/`"` is a dead key (pressing it does not produce a character until a second key is pressed) and therefore the `shift`+`'` keyboard shortcut does not work.

I suggest you define a keybinding appropriate for the Brazilian keyboard layout. You can define new keybindings using the `mf.keybindings` property.

There is a bug currently where the text shortcut as you have it defined does not select the placeholder. It should. I'll look at this.

**Comment by arnog** [comment]
I've fixed the issue with the inline shortcut.

I've also added a shift+alt+T keybinding to toggle text mode, which should work when using the Brazilian keyboard layout.
