### ISSUE TITLE
getValue('math-json') returning empty string in version 0.89.1

### ISSUE THREAD

**Issue by gutow** [arnog/mathlive#1831]
## Description
call to `mfe.getValue("math-json") ` returns an empty string while other options ('latex', 'ascii-math', etc...) return the expected strings.

Web Page to reproduce:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script type="text/javascript" src="https://unpkg.com/mathlive">
    import {MathLive} from "mathlive";
</script>
<script type="text/javascript">
    const mfe = new MathLive.MathfieldElement();
    const mathjson = document.createElement('textarea');
    mfe.value = "Type \\, Math \\, Here";
    mfe.virtualKeyboardMode="manual";
    mfe.addEventListener('change', (ev) => {
       //mathjson.value = mfe.getValue("ascii-math");
       mathjson.value = mfe.getValue("math-json");
    })

    document.body.appendChild(mfe);
    document.body.appendChild(mathjson);
</script>
</body>
</html>
```
## Steps to Reproduce

Run the webpage provided in FireFox or Chromium. It works for options other than "math-json". I did try other
typographic variations in case it was a typo in the documentation. Nothing I guessed worked.

### Actual Behavior

The failure is that no text is returned.

### Expected Behavior

I would expect a json string representing the math-json.

[Is this a regression: did it use to work in a previous version?]
I do not know if this worked in a previous version as this is the first I have tried.
### Environment

**MathLive version**
0.89.1

**Operating System** [macOS, Windows, iOS. Include the version]
Linux Ubuntu 22.04
**Browser** [Safari, Chrome, IE, Firefox, etc... Try several browsers and note
if there are differences between browsers. Include the version number of the
browsers.]
Chrome and Firefox

**Comment by arnog** [comment]
You need to import the Compute Engine module to get `math-json` value:

```js
import 'https://unpkg.com/@cortex-js/compute-engine@latest/dist/compute-engine.min.esm.js';
```

**Comment by gutow** [comment]
Thanks, that was not clear to me from the documentation on `getValue()`.

**Comment by arnog** [comment]
@gutow did you look at the documentation of `getValue()` in the header file? Or elsewhere?

**Comment by gutow** [comment]
@arnog First to answer your question, I looked at the online SDK [here](https://cortexjs.io/docs/mathlive/?q=getV#(Mathfield%3Ainterface).getValue) and [here](https://cortexjs.io/docs/mathlive/#(OutputFormat%3Atype)). After your comment, I did recall seeing something about math-json and the compute-engine. So there is definitely something about the requirement elsewhere in the online documentation.

Second, this looks like a neat piece of software. I just started looking at this as a potential way to help students enter Latex into Jupyter style notebook markdown cells and as a possible front-end to an expression builder for Sympy and possibly SageMath. The reason I was interested in the math-json representation is that it looks as if it would be easy to parse into a valid Sympy expression. If I do decide to go that way, I would be interested in seeing the Sympy parser folded into MathLive/Compute-Engine. If a Sympy expression output is a direction you would like to go, I can open an issue for that as a place to start work on it.

**Comment by arnog** [comment]
@gutow yes, there was some info about it here: https://cortexjs.io/mathlive/guides/interacting/#reading-the-content-of-a-mathfield.

But I'm never sure of what path you will navigate the documentation. I've added the info now to the two other places. Thanks!

Parsing (and serializing) to SymPy would definitely be interesting. I have some work in progress along those lines, but it needs lots of work. You can find it here: https://github.com/cortex-js/compute-engine/tree/main/src/math-json

If you are interested in contributing to it, I'd be happy to integrate a PR.
