### ISSUE TITLE
t.inlineShortcutBuffer[s] is undefined

### ISSUE THREAD

**Issue by Trooligan** [arnog/mathlive#1834]
## Description

On a Firefox browser going in a demo page and inputting certain keycodes to the math input throws error to the console: "t.inlineShortcutBuffer[s] is undefined" (tested on keycodes 160 and 192)

I am using "English (Sweden) - Swedish" input method

![input](https://user-images.githubusercontent.com/103884458/219611771-abc890fc-10f8-4a57-a0c9-94a33643854d.gif)

## Steps to Reproduce

1 go to [https://cortexjs.io/mathlive/demo/](https://cortexjs.io/mathlive/demo/) on Firefox
2. Input keycode 160 or characters ¨ and ` (Does not work with copy paste)
3. Error shows up in console

### Actual Behavior

Error shows up in console.

```
Uncaught TypeError: t.inlineShortcutBuffer[s] is undefined
    qa https://unpkg.com/mathlive?module:592
    keystroke https://unpkg.com/mathlive?module:592
    Ss https://unpkg.com/mathlive?module:200
    Ss https://unpkg.com/mathlive?module:200
    Do https://unpkg.com/mathlive?module:592
    connectedCallback https://unpkg.com/mathlive?module:602
    <anonymous> https://unpkg.com/mathlive?module:602
[mathlive:592:24224](https://unpkg.com/mathlive?module)
```

### Expected Behavior

No errors.

I have tested with MathLive version 0.79.0 and this error happens in there also.

### Environment

**MathLive version**:
 0.89.1

**Operating System**
 Windows 10

**Browser**
Firefox 102.8.0esr (64-bit)

Tested browsers with no errors:
- Chrome 110.0.5481.104 (64-bit)
- Edge 110.0.1587.46 (64-bit)

**Comment by arnog** [comment]
Can you reproduce this with other input methods/keyboard layouts? Can you reproduce this on macOS?
(I've tried using a Swedish keyboard on macOS, but no luck)

**Comment by Trooligan** [comment]
US keyboard is working fine but I cant test macOS

I think the problem is Windows (or just my computer) related since for some reason every second click of keycode 160 or 192 is "Dead", whatever that means.

![dead-key](https://user-images.githubusercontent.com/103884458/219764413-2de7ea8e-d1e1-4c58-a4ac-b4391ce80654.gif)


Error now in Demo page:

Uncaught TypeError: mathfield.inlineShortcutBuffer[stateIndex] is undefined
    onKeystroke https://unpkg.com/mathlive/dist/mathlive.mjs:28484
    keystroke https://unpkg.com/mathlive/dist/mathlive.mjs:29696
    delegateKeyboardEvents https://unpkg.com/mathlive/dist/mathlive.mjs:25380
    delegateKeyboardEvents https://unpkg.com/mathlive/dist/mathlive.mjs:25374
    MathfieldPrivate2 https://unpkg.com/mathlive/dist/mathlive.mjs:29664
    connectedCallback https://unpkg.com/mathlive/dist/mathlive.mjs:31113
    <anonymous> https://unpkg.com/mathlive/dist/mathlive.mjs:31558
[mathlive.mjs:28484:32](https://unpkg.com/mathlive/dist/mathlive.mjs)
    onKeystroke https://unpkg.com/mathlive/dist/mathlive.mjs:28484
    keystroke https://unpkg.com/mathlive/dist/mathlive.mjs:29696
    delegateKeyboardEvents https://unpkg.com/mathlive/dist/mathlive.mjs:25380
    (Async: EventListener.handleEvent)
    delegateKeyboardEvents https://unpkg.com/mathlive/dist/mathlive.mjs:25374
    MathfieldPrivate2 https://unpkg.com/mathlive/dist/mathlive.mjs:29664
    connectedCallback https://unpkg.com/mathlive/dist/mathlive.mjs:31113
    <anonymous> https://unpkg.com/mathlive/dist/mathlive.mjs:31558

**Comment by arnog** [comment]
A "dead" key is one that doesn't produce a character until another key is pressed. The Swedish keyboard has two dead keys: "`" and "¨". There's a special sequence of events that should be sent for those keys, but it seems that specifically Firefox on Windows does something different... Looks like I'm going to need to find a Windows machine to debug this...

**Comment by arnog** [comment]
OK, I was able to run a Windows VM. Firefox on Windows consider the second press of the '¨' (or '`') keys to be a regular key, not a dead key.  The weird and unexpected thing is that the second key press is considered to be one key, with a key value of '¨¨'. It sorta makes sense, but key values were not expected to be more than one character...
