### ISSUE TITLE
[Question] Judge whether executeCommand("moveDown") will change the cursor position or not.

### ISSUE THREAD

**Issue by ichibha** [arnog/mathlive#1841]
Hi. I have a question. 
Could I know whether executeCommand("moveDown") will change the cursor position or not programmatically?
For example, executeCommand("moveDown") won't change the position for 
![スクリーンショット 2023-02-19 18 52 09](https://user-images.githubusercontent.com/41054969/219940897-b3c5dc48-11b5-490b-8e7a-ef039c1c17e1.png)
and will change the position for 
![スクリーンショット 2023-02-19 18 53 58](https://user-images.githubusercontent.com/41054969/219940991-e2107fd7-8f19-40d4-ad09-a3dab81bb25f.png)

I am implementing a multiline math-field with combining multiple math-fields. 
I like to implement the transition among the math-fields by arrow keys.

**Comment by arnog** [comment]
Looks like you're looking for the `"move-out"` event:

```js
/**
 * The `move-out` event signals that the user pressed an **arrow** key but
 * there was no navigation possible inside the mathfield.
 *
 * This event provides an opportunity to handle this situation, for example
 * by focusing an element adjacent to the mathfield.
 *
 * If the event is canceled (i.e. `evt.preventDefault()` is called inside your
 * event handler), the default behavior is to play a "plonk" sound.
 *
 */
export type MoveOutEvent = {
  direction: 'forward' | 'backward' | 'upward' | 'downward';
};

```

**Comment by ichibha** [comment]
@arnog Thank you. It works! I should have checked the interacting section in the manual carefully.
