### ISSUE TITLE
inputType empty on Safari - cant listen for Enter button

### ISSUE THREAD

**Issue by Leon-Lj** [arnog/mathlive#1843]
## Description
When listening to input or beforeinput events `inputType` is always empty on Safari (both Mac OS and iPadOS). This means it's not possible to catch specifically that the enter keyboard button has been pressed (`change` is triggered on Enter, but it's also triggered on lost focus, with seemingly no way to tell the difference). It works fine in Firefox and Chrome.
If the same event listeners are registered on a normal textarea the `inputType` parameter is populated as expected.

## Steps to Reproduce

1. Run the code in Safari
```
<!DOCTYPE html>
<html>
<body>
<script src="https://unpkg.com/mathlive"></script>
<math-field id="formula"></math-field>
<textarea id="txt"></textarea>
<script type="text/javascript">
	document.getElementById('formula').addEventListener('input',(ev) => {
		console.log("math-input", ev);
	});
	document.getElementById('formula').addEventListener('beforeinput',(ev) => {
		console.log("math-beforeinput", ev);
	});
	document.getElementById('formula').addEventListener('change',(ev) => {
		console.log("math-change", ev);
	});
	document.getElementById('txt').addEventListener('input',(ev) => {
		console.log("txt-input", ev);
	});
	document.getElementById('txt').addEventListener('beforeinput',(ev) => {
		console.log("txt-beforeinput", ev);
	});
	document.getElementById('txt').addEventListener('change',(ev) => {
		console.log("txt-change", ev);
	});
</script>
</body>
</html>
```
2. Focus in the math-field and press Enter
3. Focus in textarea and press Enter

### Actual Behavior

The console output is
```
[Log] math-beforeinput – InputEvent {isTrusted: false, inputType: "", data: null, …}
[Log] math-change – Event {isTrusted: false, type: "change", target: <math-field id="formula">, …}
[Log] math-input – InputEvent {isTrusted: false, inputType: "", data: null, …}
[Log] txt-beforeinput – InputEvent {isTrusted: true, inputType: "insertLineBreak", data: null, …} 
[Log] txt-input – InputEvent {isTrusted: true, inputType: "insertLineBreak", data: null, …} 
```

### Expected Behavior

`inputType` should be `insertLineBreak`, or if that's not possible there should be some other way to catch that Enter is pressed.

### Environment

**MathLive version**
0.89.2

**Operating System** 
macOS - 13.1 (22C65)
iPadOS 16.3.1

**Browser**
Safari - 16.2 (18614.3.7.1.5) (macOS)
Safari - iPasOS 16.3.1

**Comment by WildYellowfin** [comment]
It looks like this is a broader webkit [bug](https://bugs.webkit.org/show_bug.cgi?id=170416). It's not the change of target that makes a normal text area, but the fact that you're not initializing an event with `new InputEvent()`. 

As a workaround, it would be possible to pass some kind of `enter` code through `event.data`. The bug report suggests relevant [people](https://github.com/karlcow) at Apple are aware of this, but it also seems to have been happening for years.

**Comment by arnog** [comment]
Yes, it's a Safari bug. The `inputType` field is cleared when the event is dispatched. Using a `data` property could be an option (it is actually preserved when the event is dispatched). I'll consider it.

**Comment by WildYellowfin** [comment]
Not that it makes a difference, but I found that even logging the event before dispatch showed an empty `inputType`.
