### ISSUE TITLE
Commit a253718 breaks iPad external keyboard input

### ISSUE THREAD

**Issue by Leon-Lj** [arnog/mathlive#1844]
## Description

The commit a25371831a4421cc2e75e4c291a2296cb2de8f57 seems to break alpha numerical input on external iPad keyboards. Control keys such as backspace still works, but trying to enter any numbers or letter doesn't.
I also suspect, but have not tried it yet, that this commit breaks the workaround for #1832 (since it removes the option to use a span rather than a textarea that the screen readers seems to have a problem with).

## Steps to Reproduce

1. Build mathlive from the latest master (commit 857a099 as currently).
2. Test external keyboard on iPad with this build. Numbers and letters can't be typed.
3. Revert commit  a25371831a4421cc2e75e4c291a2296cb2de8f57
4. Test again, now numbers and letters on the external keyboard works as expected.

**Comment by gunnarmein** [comment]
Leon, do you feel you could attach the attribute described in https://stackoverflow.com/questions/32851413/input-field-ios-safari-bug-cant-type-in-any-text to the internal textarea?  Created in mathfield-private.ts. It's worth a try. FWIW, my colleague tried to repro what you are seeing, with no luck.

**Comment by Leon-Lj** [comment]
My apologies, I tried this in my integration environment and it has the problem there. But when I test with MathLive Smoke Test it works fine. There must be something specific with my environment that's causing it to fail, I have some debugging to do. Closing this issue.

It does however remove the workaround for #1832, so if you with NVDA or JAWS active the math inputfield can't be used.
