### ISSUE TITLE
The caret is invisible after an empty group `{}`

### ISSUE THREAD

**Issue by timmckague** [arnog/mathlive#1846]
## Description

The cursor is not visible when focusing (clicking) on a mathfield if the field was initialized with an empty superscript or subscript.

## Steps to Reproduce

To reproduce open https://cortexjs.io/mathlive/guides/interacting/

in the "changing content" section, enter the latex "x^{}"

then in the math field, click to right of the x, notice the field is in focus but the cursor does not appear.

<img width="303" alt="Screenshot 2023-02-23 at 11 44 44 AM" src="https://user-images.githubusercontent.com/5762072/220974199-35c8773d-4363-4d65-9f9d-919222e115bd.png">

## Environment

Chrome on OSX

**Comment by WildYellowfin** [comment]
Can I ask why you're doing this? `{}` isn't really supposed to happen in general. What is the expected / desired behavior?

**Comment by arnog** [comment]
Not sure what the use case is in this particular instance, but in general any valid LaTeX should be handled correctly by MathLive.

`{}` is used in LaTeX as an "empty" atom, which can be used to control spacing (`{}-1` vs `-1`). It can also be used for example in chemistry to have "floating" superscripts, e.g. `{}^{12}C` to denote the carbon-12 isotope.

**Comment by timmckague** [comment]
> Can I ask why you're doing this? {} isn't really supposed to happen in general. What is the expected / desired behavior?

I have a website that lets people save math expressions and sometimes they enter invalid expressions or expressions that are a work in progress. If they come back later to edit those expressions they might run into this and be confused why a cursor is not appearing. I agree that this is probably not something will happen regularly, but seemed like bug that was worth reporting.

**Comment by arnog** [comment]
This is now working correctly.

**Comment by timmckague** [comment]
Thanks for fixing this.
