### ISSUE TITLE
text mode and /

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#185]
## Description
When you are in math mode, typing `/` will create a fraction using some atoms to the left as the numerator. If you select some atoms, that overrides whatever internal algorithm might choose and that selection becomes the numerator. That seems correct to me.

When you are in text mode, typing `/` seems to pick the text run as the numerator. That seems reasonable. What seems like a bug is what happens if I select something. What happens is that whatever is selected is replaced by `/`. That asymmetry seems like a bug.

## Step to reproduce
1. With `smartMode: true`...
1. Start with `\frac{x}{2}\text{ and y}` which looks like 
![image](https://user-images.githubusercontent.com/1545836/57058030-22ec0a00-6c62-11e9-80b5-c57f2c272fe8.png)
2. Select the `y`
3. Type `/`

You get `\frac{x}{2}\text{ and /}` which looks like
![image](https://user-images.githubusercontent.com/1545836/57058051-4f078b00-6c62-11e9-981d-d31b79554a7e.png)

## Expected result
I expect to get `\frac{x}{2}\text{ and }\frac{y}{y}` which looks like
![image](https://user-images.githubusercontent.com/1545836/57058067-6fcfe080-6c62-11e9-916e-131bad257552.png)

**Comment by NSoiffer** [comment]
Same thing for `^` and `_` (superscript and subscript).

**Comment by saivan** [comment]
I'm not sure if I'm in the right place for this. But it seems like typing something like "sinx" followed by "/" should give you `\frac{\sin{x}}{ _ }`but currently, it gives you `\sin \frac{x}{_}`. I'd say that when you type "/", the expectation is that the previous term to the immediate left of your cursor will end up on the top of the fraction.

Similarly for parenthesis, an opening parenthesis somewhere, should put the closing parenthesis (by default), at the complete end of the same scope.

**Comment by arnog** [comment]
@saivan valid point for the parenthesis, I could see that happen when using smartFence. For the rest of your comment, it's a bit more tricky. The challenge is determining what the proper "scope" is, that is how far back do you go to determine what the numerator should be. For now, the arguments of functions is the boundary that is used. The key question is which is the most common: sin(x/2) or (sinx)/2? 
If you are interested in a further discussion on this, I would suggest opening up a new issue, as this is different enough from the original issue which is very specifically about the behavior when using text mode.

**Comment by saivan** [comment]
Thanks for that @arnog. I am sorry that this ended up in the wrong place. I'd be happy to lend a hand at some point too. I really like where mathlive is going :) Its looking great!
