### ISSUE TITLE
how to display the keyboard in custom container

### ISSUE THREAD

**Issue by montassar-vaionex** [arnog/mathlive#1856]
i try this method with **virtualKeyboardContainer** but not working
`<div className=" ">
                    <math-field
                      style={styleskeyboardText}
                      smart-mode
                      virtual-keyboard-mode="manual"
                    ></math-field>
                    <div className="virtualKeyboardContainer relative"></div>
                  </div>`

**Comment by arnog** [comment]
You can specify a custom virtual keyboard container by using:

```html
<math-field id="mf"></math-field>
<div style="position:relative" id="myKeyboardContainer"></div>
```

```js
mf = document.getElementById("mf");
mf.setOptions({virtualKeyboardContainer: document.getElementById("myKeyboardContainer")})
```

**Comment by montassar-vaionex** [comment]
i get empty space under math-field input and keyboard in full screen

![image](https://user-images.githubusercontent.com/120009390/221957243-b03cb130-5c61-4b15-a3ec-2a022f765ae8.png)



`  useEffect(() => {
    mathFieldRef?.current?.setOptions({
      virtualKeyboardContainer: document.getElementById('myKeyboardContainer'),
    })
  }, [mathFieldRef])`

`      <math-field
              style={styleskeyboard}
              ref={mathFieldRef}
              smart-mode
              value="x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}"
              placeholder="enter"
            ></math-field>
            <div
              style={{ position: 'relative' }}
              id="myKeyboardContainer"
            ></div>`

**Comment by arnog** [comment]
It looks like there's a problem with this feature. I'll have a look.

**Comment by montassar-vaionex** [comment]
do we have option for responsive layout of keyboard ?

![image](https://user-images.githubusercontent.com/120009390/223703871-1c8fbaf1-eb01-49fe-8668-ef08da2b97a6.png)

**Comment by sgiacinto** [comment]
Hello, 
any tips on getting the custom container for the VirtualKeyboard working? 

I've got: 

    <math-field id="math-input"></math-field>
...

    let mf = document.getElementById("math-input");
    let keyb = document.getElementById("keyboard-here");
    mf.virtualKeyboardContainer =  keyb;

but I get the normal body-appended keyboard.

**Comment by arnog** [comment]
Documentation is here: https://cortexjs.io/mathlive/guides/virtual-keyboards/#displaying-the-virtual-keyboard-in-a-custom-container

To define the container, you need `mathVirtualKeyboard.container = keyb`
