### ISSUE TITLE
Cannot input italic characters after \mathrm

### ISSUE THREAD

**Issue by ichibha** [arnog/mathlive#1859]
Hi, 

Let me report an issue that italic characters cannot be written after \mathrm:
To reproduce:
1. Delete whole of the expression in the math-field demo. 
[https://cortexjs.io/mathlive/demo/](https://cortexjs.io/mathlive/demo/) 
2. Paste \mathrm{abc} in the math-field and type Enter. Then, abc is displayed in roman body. 
3. Move the caret to the rightmost position and type some characters. However, the characters are displayed in roman body. 

I think the caret is better to move like
\mathrm{ab|c} -> \mathrm{abc|} -> \mathrm{abc}|
because I did not found a straightforward way to input characters in italic form after the mathrm.

**Comment by arnog** [comment]
I can see why this can be a bit confusing.

The caret is not in fact "inside" `\mathrm{}`. When using the `\mathrm{}` command a style is applied to its content. So when pasting `\mathrm{abc}`, what is pasted inside the mathfield is `abc` with a roman letter style.

So, there is no caret navigation possible to "exit" the `\mathrm{}` command.

Maybe typing a space would make sense to exit that mode?

**Comment by ichibha** [comment]
>>Maybe typing a space would make sense to exit that mode?
Yes, space makes sense to exit the mode for me. 
I think escape is also expected to exit the mode. 
What about ArrowRight at the end of roman letter string to exit the mode without moving the caret?
