### ISSUE TITLE
NPM mathlive not loading fonts and sounds correctly

### ISSUE THREAD

**Issue by QuinnStraus** [arnog/mathlive#1866]
## Description

We have been using React and NPM to install Mathlive, and we have been running into issues with the sound and font imports.  
Whenever we use Mathlive, the fonts, sounds, and other css files don't install correctly.

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. Create a new create-react-app (also fails in Vite, Next.js)
2. npm i mathlive
3. Replace app.js with 
```
import { MathfieldElement } from "mathlive";
import { useRef } from "react";

function App() {
  const ref = useRef(new MathfieldElement());

  return (
    <div className="App">
        <math-field ref={ref}>x</math-field>
    </div>
  );
}
export default App;
```

### Actual Behavior

The math field generates and can be typed in, but the fonts/sounds/other css elements are not loaded, leading to styling and console errors.

Console errors:
On load:
The MathLive fonts could not be loaded from "http://localhost:3001/static/js/fonts" {cause: DOMException: A network error occurred.}

Whenever a sound should play (ex. deleting on an empty mathfield)
DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data

### Expected Behavior

It should load the fonts and styles automatically on import

### Environment

**MathLive version** 0.89.4

**Operating System** macOS M1 Ventura 13.1

**Browser** Chrome, Safari

**Comment by arnog** [comment]
Are the assets present in “static/js/fonts”? If not, you may need to copy them as part of your build step.

**Comment by QuinnStraus** [comment]
What is the expectation for what we need to copy when installing mathlive through npm? I had copied the existing fonts from the node_modules into our project as well as the mathlive-fonts.css file in order to get it to work on my end, but that felt overly complicated and wouldn't automatically sync with new updates.

**Comment by arnog** [comment]
You do not need to copy the .css file. The file is only useful if you're using the output of MathLive without Javascript. You need to copy the "font" and "sounds" folders from the "dist" directory in the npm module.

**Comment by QuinnStraus** [comment]
Thanks, I got it working now. I was having an issue with the fonts/sounds directory in order to get it to work with Next.js but I got it resolved, I realized I needed to set the directory on the math-field html element and not in the MathfieldElement in the ref

**Comment by arnog** [comment]
Glad to hear that.

At the risk of brining some confusion, I should point out that in the next release of MathLive, the `fontsDirectory` and `soundsDirectory` will indeed be static properties of `MathLiveElement`.

**Comment by edward1127** [comment]
can someone give me an example of what's the proper way to set up this library with nextjs?

**Comment by CBrian04** [comment]
Hi!

I would also be quite intested by your implementation @QuinnStraus  and particularly how you handled the fonts and sounds in your NextJs project! (where do you put them and how did you import them : with the fontsDirectory option from MathLive or like shown in nextjs doc ?)

Thanks a lot!
Brian
