### ISSUE TITLE
5cdf957 - cqw not working in firefox

### ISSUE THREAD

**Issue by WildYellowfin** [arnog/mathlive#1867]
Don't know if this is finalized yet, but Firefox 109 does not seem to be handling the new `cqw` correctly. 

![Screenshot 2023-03-06 at 17 38 00](https://user-images.githubusercontent.com/104928632/223266805-0fa9c579-5c28-4bc8-bafc-55011d91fa3d.png)

**Comment by arnog** [comment]
Apparently, support for container query units just landed in Firefox 110: https://caniuse.com/?cats=CSS&statuses=wd,other,unoff

**Comment by WildYellowfin** [comment]
Just updated, it works!
