### ISSUE TITLE
Different behaviour of / depending on the letter that precedes it

### ISSUE THREAD

**Issue by Leon-Lj** [arnog/mathlive#1869]
## Description

When typing / to create a fraction in mathlive the result differs depending on what comes before. All numbers will result in `number/placeholder` while some letter will be `letter/placeholder` while others will be `letter * placeholder/placeholder`. 

For example typing `r` then `/` will result in `r/placeholder` while typing `f` then `/` will result in `f * placeholder/placeholder`. 

So for example if you're to write an expression for the area of a triangle of base=b and height=h then you get different behavior depending on the order you write it in. `A=hb/2` will result in `A=(hb)/2`, while `A=bh/2` will result in `A=bh*2/placeholder`.

_Arno wrote on Gitter_
> "f", "g" and "h" are considered functions which affects how they are handled. However, one could argue that the current behavior is incorrect. When trying to find an implicit argument for the numerator, functions are excluded, which is why it looks left and stops at "f", "g" or "h". This behavior is intended to deal with the case \cos 2 followed by /. In most cases you want the 2 in the numerator, but not the \cos. However, that works because \cos is a special function that can be written without parentheses around its arguments. That should not apply for "f", "g" and "h".

Note: This was just a curiosity that I found, not sure it's the most important of issues. :)

**Comment by gunnarmein-ts** [comment]
A setting to control this behavior would be very nice!
