### ISSUE TITLE
Inserting `\\mathbb{N}` breaks following input

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#187]
## Prerequisites

* [x] Did you check the [issue tracker](https://github.com/arnog/mathlive/issues) to see if this issue has already been reported?

For more information, see the `CONTRIBUTING` guide.

## Description
When inserting `\mathbb{N}` (or `mathbb{R}` ...) via a custom keyboard, all following text will be included inside the `mathbb`-area. See attached fiddle.

### Actual behavior
When inserting a `\mathbb{N}` via the virtual keyboard, and then typing another normal `N` via the normal keyboard, it is also displayed as mathbb-N, and the content of the mathfield will be like `\mathbb{NN}`.

### Expected Behavior 
I expect that when I insert anything via the virtual keyboard (and not set a `#?`), that the insert-caret is moved after the inserted bit. This works for `\mathop{\in}` for example. 

[Is this a regression: did it use to work in a previous version?]
This used to work correctly with previous mathlive versions, though I can't tell right now when it broke. Probably with the 0.27.x-versions.

## Steps to Reproduce
1. Go to https://jsfiddle.net/gjak1dwe/2/
2. Click in the mathfield
3. Click the single virtual keyboard key
4. Type the letter `N` on your normal keyboard. 
5. Type the letter `R` on your normal keyboard.
6. See they're all in mathbb-Formatting.
7. Copy the content of the mathfield and see it's `\mathbb{NNR}`.

### Environment
**Operating System** 
Windows

**Browser** 
Chrome

**URL**
https://jsfiddle.net/gjak1dwe/2/

**Comment by arnog** [comment]
Good find and great bug report. Yes, this behavior is a side effect of the support for styling that was introduced in v27. The rule as currently implemented is that a new atom takes on the style of the left-adjacent atom. Makes sense most of the time, but I agree that's not a desirable behavior in this case. 
One option would be, when there is a programmatic insertion to reset the style to what it was before the insertion (that's already what happens when using inline shortcuts).

**Comment by arnog** [comment]
My previous comment wasn't quite right. The difference is not between inline shortcuts vs. virtual keyboard. 
There is a subtle difference between `\N` (which is inserted using an inline shortcut) and `\mathbb{N}` (which is inserted using the virtual keyboard in this example). In the former, a "N" with a blackboard base font is inserted. It's almost like an emoji, and cannot be restyled (applying another font will not change the character being displayed, i.e. a ℕ). In the latter, the character inserted is an uppercase N with a blackboard font applied. It *can* be restyled, and its font will be used to influence the following characters.
