### ISSUE TITLE
Invalid mathml for superscript/subscript on variables

### ISSUE THREAD

**Issue by Leon-Lj** [arnog/mathlive#1870]
## Description

When a variable in a expression contains a super or subscript the generated mathml is incorrect. This will cause the Speech Rule Engine to throw an exception and thus fail to generate a proper aria-label for what's in the input field.
The problem is that it does not properly wrap the variable in a `<mi>`-tag (it correctly handles numbers by wrapping them in `<mn>`-tags).

This was mentioned in #1803 but I can't see that a separate ticket was created for it.

The mathml can be validated using https://validator.w3.org/nu/#textarea with the template
```
<!DOCTYPE html>
<html lang="en">
<head><title>Test</title></head>
<body>
<math>
     mathml from mathlive here
</math>
</body>
</html>
```

## Steps to Reproduce

In Mathlive Smoke Test

**Variable with superscript - incorrect**
1. Write `a^2`
2. The generated mathml is `<msup>a<mn>2</mn></msup>`
3. The [validator](https://validator.w3.org/nu/#textarea) gives two errors `Text not allowed in element msup in this context.` and `Element msup is missing a required instance of one or more of the following child elements`.
4. The correct mathml is `<msup><mi>a</mi><mn>2</mn></msup>`

**Number with superscipt - correct**
1. Write 2^3
2. The generated mathml is `<msup><mn>2</mn><mn>3</mn></msup>`
3. The [validator](https://validator.w3.org/nu/#textarea) gives no errors, this is correct.

**Variable with subscript - incorrect**
1. Write a_2
2. The generated mathml is `<msub>a<mn>2</mn></msub>`
3. The [validator](https://validator.w3.org/nu/#textarea) gives two errors `Text not allowed in element msub in this context.` and `Element msub is missing a required instance of one or more of the following child elements`.
4. The correct mathml is `<msub><mi>a</mi><mn>2</mn></msub>`

**Number with subscript - correct**
1. Write 2_3
2. The generated mathml is `<msub><mn>2</mn><mn>3</mn></msub>`
3. The [validator](https://validator.w3.org/nu/#textarea) gives no errors, this is correct.

### Environment

**MathLive version**
Current master (f8aa4124eb838ba80e67add9aa29f60f3c0b9ced), 0.89.4 and 0.89.2

**Comment by arnog** [comment]
Fixed in b2066e85936ba520038ee9f45fe185e9c2773e89
