### ISSUE TITLE
Setting read-only or disabled on math-field HTML element overwrites other options set on element (such as fonts-directory)

### ISSUE THREAD

**Issue by QuinnStraus** [arnog/mathlive#1877]
## Description

Setting the fonts and sounds directory on the mathfield works fine if is not read only, but when the read only (or disabled) props are set on the field the props have no effect (it always tries to load fonts from the default directory).

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. Create a new create-react-app (also fails in Next.js)
2. npm i mathlive
3. Copy mathlive fonts directory to public/static/fonts (it default tries to read from public/static/js/fonts)
4. Replace App.js with 
```
import { MathfieldElement } from "mathlive";
import { useRef } from "react";

function App() {
  const ref = useRef(new MathfieldElement());

  return (
    <div className="App">
      <math-field ref={ref} fonts-directory="../fonts" read-only>
        {"\\mathbb{R}"}
      </math-field>
    </div>
  );
}
export default App;
```

### Actual Behavior

The math field generates, but the fonts are not loaded, leading to styling and console errors. No errors or styling issues when read-only is not present.

Console errors:
On load:
The MathLive fonts could not be loaded from "http://localhost:3001/static/js/fonts" {cause: DOMException: A network error occurred.}

### Expected Behavior

The fonts-directory prop should load fonts regardless of read-only status

### Environment

**MathLive version** 0.89.4

**Operating System** macOS M1 Ventura 13.1

**Browser** Chrome, Safari

**Comment by QuinnStraus** [comment]
I've been doing some digging and it seems like the issue is not restricted to react or just the fonts-directory. Everywhere the read-only or disabled props are set on the math-field HTML element, it seems like the other options are not being loaded. There is a workaround if we set readOnly on the ref later on using setOptions, however.

**Comment by arnog** [comment]
The way options work has changed in mathlive 0.90.0. This should take care of this issue, but please re-open if you still see some problems.
