### ISSUE TITLE
how i can display custom placeholder in reactjs like "enter your equation"?

### ISSUE THREAD

**Issue by montassar-vaionex** [arnog/mathlive#1878]

**Comment by WildYellowfin** [comment]
This is not a clean solution, but:
1. Initialize the mathfield with value `\text{\textcolor{grey}{Type your equation}}`
2. When the mathfield is focused, you want to erase this, so add an event listener that checks if the content is the above string, and sets the content to empty.
3. Add a second event listener for the `blur` event, that will reinsert your starting string if the current content is empty.

In future, you might get faster answers if you provide a description.
