### ISSUE TITLE
Different behavior for numeric and alphabetic exponents

### ISSUE THREAD

**Issue by wlewis-formative** [arnog/mathlive#1879]
If I raise an expression to a _numeric_ power by typing `a^1` (for instance), the cursor returns to the baseline. However, if I type an alphabetic power (e.g.) `a^b`, the cursor remains in the superscript. Is this a bug, or expected?

(ℹ️ Using the `x^[]` key on the keyboard followed by a numeric power also keeps the cursor in the superscript.)

https://user-images.githubusercontent.com/91909230/224751076-b6875666-5a77-4314-a294-a60548dbd65f.mov

**Comment by arnog** [comment]
This is expected. This behavior can be controlled with the `smartSuperscript` property (https://cortexjs.io/docs/mathlive/?q=smartsuperscript)
