### ISSUE TITLE
Keyboard shortcuts section on mathlive.io not showing shortcuts

### ISSUE THREAD

**Issue by AlienKevin** [arnog/mathlive#188]
**Keyboard shortcuts section on mathlive.io is not showing shortcuts.**

![image](https://user-images.githubusercontent.com/22850071/57159157-2fcc4300-6db3-11e9-8625-060cc2dd01b2.png)

Chrome DevTool shows an error message:
![image](https://user-images.githubusercontent.com/22850071/57159255-74f07500-6db3-11e9-9ab2-48a3940da014.png)

The tables in HTML aren't displayed:
![image](https://user-images.githubusercontent.com/22850071/57159359-b54ff300-6db3-11e9-819c-0b5d2f3cd7f3.png)

🔗https://mathlive.io/deploy/reference_shortcuts.html

**Comment by arnog** [comment]
Updated mathlive.io to support extended format for inline shortcuts and keyboard shortcuts.
