### ISSUE TITLE
Popover keyboard example broken

### ISSUE THREAD

**Issue by WildYellowfin** [arnog/mathlive#1882]
Hey Arno, was trying to build something like your popover keyboard example and found that keys were not clickable after opening the keyboard with a focus event. Only after toggling the keyboard off and on (using the button) did the keys start responding.

I checked your example, and it seems to be doing the same thing.

**Comment by arnog** [comment]
yes, there’s some work left to be done 😀

**Comment by WildYellowfin** [comment]
I figured :), got a bit excited as we're trying to launch in a couple weeks
