### ISSUE TITLE
setPromptContent not handling selection -> errors

### ISSUE THREAD

**Issue by WildYellowfin** [arnog/mathlive#1884]
I realized the way I wrote `setPromptValue` is not correct, since it does not update the selection. A set can therefore result in the selection being out of bounds, and mathlive crashes on re-render. 

I can rewrite this tomorrow by selecting the content of the prompt and calling the `insert` command with `replaceSelection`, unless I'm made aware of a better way.

**Comment by arnog** [comment]
Ah, yes. `mathfield.insert()` should work.

**Comment by WildYellowfin** [comment]
Hey @arnog, somehow convinced myself this fix was working but `insert` does nothing if given an empty string. Also I realized I can't use `offsetOf`, and instead I rewrote with `getBranchRange`. If you could advise on getting around the empty string issue, I'll make another PR.

**Comment by arnog** [comment]
Sorry about that. Using `.insert()` to replace the selection with an empty string should work. I've checked in a fix.
