### ISSUE TITLE
Can't escape from \text{}

### ISSUE THREAD

**Issue by AllyMarthaJ** [arnog/mathlive#1888]
## Description

Can't escape from `\text{}` when it's at the end of the Mathfield using right arrow.

Reproducible via MathLive Demo.

## Steps to Reproduce

1. Enter `\text{some content}` into a Mathfield. Any content can precede it.

### Actual Behavior

You cannot escape the text environment via right arrow when it's the final content; attempts to type a LaTeX command get escaped. The only way to escape it is by pressing Escape twice, hitting right arrow, typing proceeding content and removing the extra `\`.

### Expected Behavior

A right arrow from a text environment should take me out of the text environment when at the end, or I'm able to type LaTeX commands from within text mode (although that doesn't really make sense).

### Environment

**MathLive version**
Latest.

**Operating System** 
macOS

**Browser** 
Chrome, Firefox, Safari

**Comment by arnog** [comment]
That's a reasonable point, but note that even in this situation, you can exit text mode by pressing the "exit text mode" keyboard shortcut: `"` (the quote key)

**Comment by AllyMarthaJ** [comment]
Ah, alright. Fair enough!
