### ISSUE TITLE
<- and >- are problematic shortcuts

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#19]
## Description
Type "x<-3". My expectation is that it becomes "x < -3". Instead, it turns into  x\leftarrow 3

Similarly, "x>-3" doesn't become "x > - 3", it turns into x\succ 3

### Expected Behavior 
These shortcuts make it very hard to type these simple expressions. I think they should be removed as there are TeX equivalents to (I believe) less likely situations.

It is probably a good idea to review all the shortcuts for unintended consequences when typing simple expressions.

**Comment by arnog** [comment]
The idea was to be able to "undo" unwanted conversions by pressing command-Z, but perhaps that's not obvious enough.

**Comment by NSoiffer** [comment]
Thanks for the fix.

I think using "undo" is too subtle. My feeling is that common things such as "x<-3" shouldn't trigger surprises.
