### ISSUE TITLE
Feature request: insert newlines

### ISSUE THREAD

**Issue by AlienKevin** [arnog/mathlive#190]
I'm wondering if it's possible to insert newlines in MathLive editor. MathLive works fine for multiline latex pasted from clipboard but I can't find a way to insert them in the editor.

**Comment by arnog** [comment]
You can have multiple line using an environment, such as `\begin{equation}\end{equation}` or `\begin{multiline}\end{multiline}` . Inside these environments, you can add new lines using the `RETURN` key.

**Comment by AlienKevin** [comment]
Thanks, I tried both but there are some problems when editing after pasting in the environment code:
![550fafdb-3134-4d12-ad3f-17ed37b1b810](https://user-images.githubusercontent.com/22850071/57171958-d16d8780-6de7-11e9-8f85-023a089d5af2.gif)

**Comment by arnog** [comment]
Uh. Interesting. I was able to reproduce this indeed using mathlive.io, but it doesn't happen with master (mathlive.io has a build from a couple of weeks ago). I don't know what issue I fixed that fixed this, but it appears to be working correctly now.

**Comment by AlienKevin** [comment]
I think it still has the problem when I tested using both npm and <script> imports:
The following is with <script> and npm yields the same problem:
![d39a9994-5aba-492a-bae3-7e4ee1cfb6ea](https://user-images.githubusercontent.com/22850071/57192174-7a58d700-6efb-11e9-80d1-44f533c53b21.gif)
I'm wondering if unpkg and npm is updated to the latest version?

**Comment by arnog** [comment]
The version available via npm and unpkg may very well have this problem. The latest release is 0.28 from two weeks ago, and there have been quite a few changes in master (the latest version in GitHub) since then. This problem should be resolved once a new release is pushed. I'll try to push one early next week.

**Comment by AlienKevin** [comment]
Okay, I see. I really like your active maintenance, great documentation, huge coverage of latex commands, OSK, and auto-suggestions, etc. I think MathLive is in almost all aspects better than other math editors like Mathquill. However, I feel that the editing experience can be improved to be smoother and less error-prone. I'm working on a WYSIWYG math editor and am really looking forward to a more polished MathLive.

**Comment by arnog** [comment]
Thanks! I'm always open to suggestions on how to improve the editing experience, either filed as issues or as PR.

**Comment by dobesv** [comment]
Today I tried this out to see if the begin/end approach would work but it doesn't work on math live website or version 0.69.8
