### ISSUE TITLE
Can't write in placeholder on Firefox

### ISSUE THREAD

**Issue by Leon-Lj** [arnog/mathlive#1901]
## Description
It's not possible to do any input in a placeholder on Firefox when using a physical keyboard. When a placeholder is inserted (for example by using the virtual keyboard) it appears to focus, but no input is possible using a physical keyboard. If you use the virtual keyboard to type anything in the placeholder then it "unlocks" and you can use the physical keyboard for input as well.

This is only a problem on Firefox, it works fine in Safari and Chrome. Tested on mathlive `0.90.8`. It is similar in behavior to #1861

Note: There is one way to "unlock" the placeholder, but it differs slightly depending on if I test on [the demo page](https://cortexjs.io/mathlive/demo/) or using Smoke Test (using commit 74c80e2ef47903a85fc8d8175b0dc7f9bb41df86 as head). On the demo page it will unlock if I press either e, i, j, o, x or m twice in a row (I assume these are all shortcuts). While on Smoke Test, it unlocks if I press any letter twice in a row.

## Steps to Reproduce

Using Firefox
1. Open the virtual keyboard and press any key that results in a placeholder (for example the `√`)
2. The placeholder is inserted and focused
3. Try to type anything using the physical keyboard, as long as you don't press a letter key twice in a row, nothing will appear in the placeholder.

### Environment

**MathLive version**
0.90.8

**Operating System**
Ubuntu 22.04
Windows 10, 21H2 (OS Build 19044.2486)

**Browser**
Firefox 111.0.1

**Comment by mgreminger** [comment]
This is a duplicate of #1898 since it's the same selection issue causing both symptoms on Firefox, I'm currently working on a fix.

**Comment by Leon-Lj** [comment]
Right, sorry. I should have read that ticket more closely, you specifically mention the square root placeholder.
