### ISSUE TITLE
Virtual keyboard does not work

### ISSUE THREAD

**Issue by zxhd863943427** [arnog/mathlive#1909]
## Description

After using vite and vue to package, there will be no response after the virtual keyboard in the project is pressed

## Steps to Reproduce

1. Directly download the running file of [unpkg](https://unpkg.com/mathlive@0.90.11/dist/mathlive.min.js) and pack it into the project
2. Render the virtual keyboard in the project
3. Press a key on the virtual keyboard

### Actual Behavior

virtual keyboard won't work

### Expected Behavior

The virtual keyboard takes effect

Works fine in 0.90.10

### Environment

**MathLive Version** : 0.90.10

**OS** : Windows10

**browser** : electron

**Comment by zxhd863943427** [comment]
I have solved this problem, but it takes a little time to upload Pull requests.
I'm sorry that my ts is not very good, I checked and solved the problem directly through the packaged mathlive.js file.

**Comment by arnog** [comment]
The `Node` class is no longer referenced, so this should no longer be a problem.
