### ISSUE TITLE
Export mathlive-fonts.css

### ISSUE THREAD

**Issue by weakit** [arnog/mathlive#1913]
## Description

Unable to import `mathlive-fonts.css` since it's not exported by the package.

```
Module not found: Package path ./dist/mathlive-fonts.css is not exported from package [...]\node_modules\mathlive (see exports field in [...]\node_modules\mathlive\package.json)
  1 | import * as React from 'react'
> 2 | import 'mathlive/dist/mathlive-fonts.css'
  3 | import styles, {m} from '../styles/mathlive.module.css'
  4 |
  5 | // using class components due to dynamic import.

Import trace for requested module:
./pages/index.js

https://nextjs.org/docs/messages/module-not-found
```

Current package.json:
https://github.com/arnog/mathlive/blob/dd35186570440172b318b20ac1675d9d0e0f1a35/package.json#L26-L32

## Steps to Reproduce

Have `import 'mathlive/dist/mathlive-fonts.css'` somewhere in a react project using webpack.

### Actual Behavior

Import fails

### Expected Behavior

Import is supposed to work. it used to work in older versions

### Environment

Mathlive 0.90.11
Windows

**Comment by arnog** [comment]
That's very odd. The file `mathlive-fonts.css` is still present in the `dist` folder. I can't think of anything in the package.json file that has changed recently.

Do you know which version of MathLive used to work?

Do you have a test case I could test with?

**Comment by arnog** [comment]
Did you previously use MathLive 0.87.1?

**Comment by arnog** [comment]
OK, I think I may have a fix, but I don't have a way to test it. Give it a try and let me know. 

You will need to change

`js
import 'mathlive/dist/mathlive-fonts.css'
`

to

`js
import 'mathlive/fonts.css'
`

**Comment by kongweiying2** [comment]
I'm getting this problem as well, it only appeared recently. But I don't actually import mathlive-fonts.css. So I wouldn't be able to apply that fix you suggested. Additionally, there's also a type error with the toggleVirtualKeyboard, which is new too.

```
ERROR in ./node_modules/react-math-view/dist/index.modern.js 1:0-42

Module not found: Error: Package path ./dist/mathlive-fonts.css is not exported from package /Users/kongweiying/Documents/GitHub/Eusaybia/lifemap/node_modules/react-math-view/node_modules/mathlive (see exports field in /Users/kongweiying/Documents/GitHub/Eusaybia/lifemap/node_modules/react-math-view/node_modules/mathlive/package.json)


ERROR in ./node_modules/react-math-view/dist/index.modern.js 2:0-36

Module not found: Error: Package path ./dist/mathlive.min is not exported from package /Users/kongweiying/Documents/GitHub/Eusaybia/lifemap/node_modules/react-math-view/node_modules/mathlive (see exports field in /Users/kongweiying/Documents/GitHub/Eusaybia/lifemap/node_modules/react-math-view/node_modules/mathlive/package.json)


ERROR in src/view/content/Math.tsx:13:43

TS2345: Argument of type '"toggleVirtualKeyboard"' is not assignable to parameter of type '"scrollIntoView" | "selectAll" | "undo" | "redo" | "performWithFeedback" | "commit" | "complete" | "nextSuggestion" | "previousSuggestion" | "copyToClipboard" | "cutToClipboard" | ... 58 more ... | [...]'.
    11 |     const ref = React.useRef<MathViewRef>(null)
    12 |     const toggleKeyboard = useCallback(
  > 13 |         () => ref.current?.executeCommand("toggleVirtualKeyboard"),
       |                                           ^^^^^^^^^^^^^^^^^^^^^^^
    14 |         [ref]
    15 |     )
    16 |     const text = props.qi.informationText
```

**Comment by arnog** [comment]
> I'm getting this problem as well, it only appeared recently. But I don't actually import mathlive-fonts.css.

This problem was about importing `mathlive-fonts.css`, so if you're not importing `mathlive-fonts.css`, you're probably not getting this problem. Could you provide more details about the problem you're seeing (version of MathLive you're using, error message, etc...)

The `toggleVirtualKeyboard` command on the mathfield is not longer available. The virtual keyboard is now an independent global object. To obtain the same effect you can change your code to:

` const toggleKeyboard = () => mathVirtualKeyboard.visible = !mathVirtualKeyboard.visible`

**Comment by kongweiying2** [comment]
I'm using: 

    "react-math-view": "1.3.2"
    "mathlive": "^0.89.2"

And the error message is the one I posted above, in the code snippet. It appears to be exactly the same as the original poster.

**Comment by arnog** [comment]
The problem is with `react-math-view` which does an import of `mathlive-fonts.css`. You can try to file an issue with this package, but AFAIK it's not maintained. On the other hand, using MathLive with React is considerably simpler than what this package does. You can have a look at https://cortexjs.io/mathlive/guides/react/
