### ISSUE TITLE
Popover panel opens in the wrong direction

### ISSUE THREAD

**Issue by DavidMulder0** [arnog/mathlive#1919]
## Description
The popover panel opens upwards even if there is more space downwards than upwards.

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. Open [MathLive homepage](https://cortexjs.io/mathlive/) on a 1920x1080 display
2. Scroll down so that the demo input is 1/5 down the page (see screenshot below)
3. Type in `\t`

### Actual Behavior

![image](https://user-images.githubusercontent.com/20395438/230451546-fe8c0fd9-ba4d-4966-b8f9-4803a78bcddb.png)

### Expected Behavior

Popover should open in the direction with the most space. (Additionally a scrollbar would be useful as well)

### Environment

**MathLive version**: MathLive 0.91.1 

**Operating System** Windows 11

**Browser** Chrome 112

**Comment by DavidMulder0** [comment]
@arnog This sir, is the quickest turnaround of a bug I have ever seen on an open source project 🙏🙇 . Thank you for your amazing work on this project!

**Comment by arnog** [comment]
😀 Thank you for your kind words.
The fix is available in mathlive 0.91.2.
