### ISSUE TITLE
Design issue: active virtual keyboard with several mathlive fields on the same page

### ISSUE THREAD

**Issue by jlchereau** [arnog/mathlive#192]
**Describe the bug**
With several mathlive fields on the same page, the use of virtual keyboards is confusing.

**To Reproduce**
1. Open a page with 2 mathlive fields
2. Open virtual keyboard on first field
3. Focus second field
4. Type on virtual keyboard
5. Fills first field (unexpected)

You have to open a second virtual keyboard to type in the second field, but then switching between keyboards/fields is even more confusing for users.

**Expected behavior**
You should only have one keyboard and detect the active field with focus.

**Environment**
- Any

**Comment by ghzwy** [comment]
Hello. Have you solved it? I met the same problem.

**Comment by arnog** [comment]
Are you using `virtualKeyboardMode: 'onfocus'`?

If you are using `virtualKeyboardMode: 'manual'`, you have manual control over when the virtual keyboard is shown/hidden. You could call `mf.$perform('hide-virtual-keyboard')` to hide the keyboard from a `onblur` handler.

**Comment by ghzwy** [comment]
Thank you very much. That's quite helpful! ;-D
Base on your suggestion 
```
onBlur:function(mf){mf.$perform('hide-virtual-keyboard');}
```
I added one more config option:
```
onVirtualKeyboardToggle: function(mf,visible,kb) {
    if(visible){
       jQuery(mf.$el()).find("textarea").first().focus();
    }
 }
```
This might fix the problem that sometimes a previous textarea can't be automatically blurred.

Lots of thanks to you and the author.

**Comment by arnog** [comment]
Thanks. I am the author.
For on `onVirtualKeyboardToggle` handle, you can also call `mf.$focus() `that will do the same thing. Although you really shouldn't have to call this, and if you do that's a bug. If you have a reproducible case for this, I'd be happy to investigate and fix it.

**Comment by ghzwy** [comment]
Thanks a lot. Your work is amazing. ;-D

I guess, if a user uses a touch screen, maybe no problem will be met. However, I'm using a laptop with a physical keyboard, so $focus() is needed：

If mf.$focus() is not called explicitly, the expected textarea will not be automatically focused unless you click the vitual keyboard first. Therefore, things go wrong if you directly type numbers from a physical keyboard or open a virtual keyboard of another field. So, I need to force the cursor to show in the expected place before any text is typed. 

I really like your work. Thanks again！

**Comment by arnog** [comment]
Glad you like it.

I see. In that case, I believe the behavior is correct. Generally speaking, and in particular for accessibility reasons, we should avoid changing the focus. In this case, activating the virtual keyboard doesn't require the focus to be changed, since the focus will be changed later when the virtual keyboard is pressed.

However, depending on your situation, it might be the right behavior for you, in which case calling `mf.$focus()` is appropriate.

**Comment by hellosiyan** [comment]
@arnog Thanks, was looking exactly for this, since I couldn't find `$focus()` in the documentation on http://docs.mathlive.io/ . Did I miss something, or should I make a PR to add it to the docs?
