### ISSUE TITLE
Force keyboard to appear within iframe

### ISSUE THREAD

**Issue by DavidMulder0** [arnog/mathlive#1920]
Looking at `src/virtual-keyboard/global.ts` it seems there is no way to configure Mathlive not to use the VirtualKeyboardProxy if the code is running within an iframe. Could we get a way to to configure this behavior?

I was thinking about putting in a PR, but hit a roadblock when I realized I had absolutely no idea on which object it would make sense to put such a configuration, as the logic in question is AFAICT executed as part of the general initialization. 

Usecases:
 - The user might wish to show the keyboard in a specific container within the iframe
 - The user might not have access to the parent (e.g. when running in a cross-origin or sandboxed iframe)
 - The iframe might be taking the full size of the parent anyway

**Comment by arnog** [comment]
The configuration would have to be on the mathfield itself, since there is no reliable way to guarantee access to a global environment in this scenario. 

I could imagine something like `mf.mathVirtualKeyboardPolicy = "sandboxed"`. 

This would also imply that the visibility of the virtual keyboard would have to be adjusted programmatically (i.e. same as when the `mathVirtualKeyboardPolicy is `"manual"`) since it may need to be coordinated across frames to avoid having multiple virtual keyboard visible on screen at once, which would be confusing.

**Comment by arnog** [comment]
Added support for `mf.mathVirtualKeyboardPolicy = "sandboxed"` (or `math-virtual-keyboard-policy=sandboxed`). Once that policy has been set, it cannot be reverted. It also behaves as if the policy had been set to `"manual"`, but the virtual keyboard is hosted inside the browsing context (iframe) of the mathfield. Other mathfields (in different browsing context, i.e. different iframes or top-level document) will have their own shared virtual keyboard instance, unless they also have this policy set, in which case they will have their own VK.

**Comment by szn** [comment]
Hi @arnog, thanks for an excellent library.

I am trying to use the `mathVirtualKeyboardPolicy = "sandboxed"` setting in my project with no luck. 

The error message presents the exact developer console output and a trimmed-down code part of my React app.

```
TypeError: Cannot read properties of null (reading 'addEventListener')
new _a
../node_modules/mathlive/dist/mathlive.min.mjs:2395:6056
[...]
Mr.connectedCallback
../node_modules/mathlive/dist/mathlive.min.mjs:2408:5237
[...]
(anonymous function)
../src/jsx/editor.jsx:73:10

function Editor({display, license}) {
  const mfe = new MathfieldElement()

  useEffect(() => {
    const input = document.getElementById('input')
    mfe.mathVirtualKeyboardPolicy = 'sandboxed'
>   input.appendChild(mfe)
         ^
```

I am using the latest v0.94.8. I am testing this within a simple frame.html with `<iframe src="http://localhost:3000/editor" width=800 height=800>` in it.

I can convert it to a new bug but I decided to start it here within the context.

Any ideas?

**Comment by szn** [comment]
Replaced with: https://github.com/arnog/mathlive/issues/2067
