### ISSUE TITLE
Switching to latex mode clears undo history

### ISSUE THREAD

**Issue by QuinnStraus** [arnog/mathlive#1924]
## Description

Entering into latex mode by pressing "\" seems to clear all undo history, and pressing undo only allows the user to toggle between latex and math.

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. Select math in mathfield (ex in demo on Cortex page)
2. Press "\\" to enter into latex mode
3. Type anything to change selection
4. Press undo (cmd+z)

### Actual Behavior

Pressing undo repeatedly just toggles the current tex in the selection between math and latex. 

### Expected Behavior

Pressing undo should undo recent actions, so we can access prior states if something is mistyped while in latex mode.

### Environment

**MathLive version**
91.2 - on live cortex demo

**Operating System** [macOS, Windows, iOS. Include the version]
macOS Ventura 13.1

**Browser** No browser differences

**Comment by arnog** [comment]
Fixed in aba0a818267f4d86d7d0de8d0ae101e10871700c
