### ISSUE TITLE
Prompt / Read-Only Not Handled For All Inputs

### ISSUE THREAD

**Issue by gerryfletch** [arnog/mathlive#1936]
## Description
- If I am focused within a prompt, in a read-only math editor, `CMD + A` will select the entire Math editor rather than just the content within the prompt
- If I then, for example, press the `/` (slash) key, it will update the read-only editors value to include `\frac`. See screenshot below

## Steps to Reproduce

1. Read-only mathfield in freshly loaded state
![image](https://user-images.githubusercontent.com/24813360/233205688-5c46be23-3fa2-49f4-9e0c-7e1f06988d93.png)

2. Focused state with some text typed
![image](https://user-images.githubusercontent.com/24813360/233205763-4a47920a-6fec-43aa-98a6-1b31b845ced5.png)

3. `cmd + a` select all incorrect highlight
![image](https://user-images.githubusercontent.com/24813360/233205821-fc2e6d84-a6a0-4cad-b947-93ad8981e59a.png)

4. Result after pressing `/`
![image](https://user-images.githubusercontent.com/24813360/233205869-f3a953df-bb02-45f7-aec0-4fe2f4e180df.png)

Seems that we're not limiting `readOnly` with keyboard shortcuts, only your typical `input` events? I don't believe we had this behaviour before the placeholder -> prompt migration though.

### Expected Behavior

- In a readonly field, only prompts should be editable
- Common keyboard shortcuts such as `cmd + a` to select all should be restricted to the current prompt

### Environment

**Version**: `0.92.0`, the latest as of time creating issue

**Operating System** [macOS]

**Browser** [Chrome]

**Comment by WildYellowfin** [comment]
Yikes! I didn't realize shortcuts would run even after preventing regular input. I'll take a look at this.

**Comment by arnog** [comment]
Note: "select all" is a valid command in a readonly field, but "insert" is not (unless the selection is entirely inside a prompt).
