### ISSUE TITLE
Regression: \mathrm{E}{-1} typesets spacing between E and -, but shouldn't

### ISSUE THREAD

**Issue by AlexEdgcomb** [arnog/mathlive#1951]
## Description

\mathrm{E}{-1} typesets spacing between E and -, but shouldn't. Regressed from MathLive 0.91.2 to 0.92.0.

At time of posting, 0.92.1 is latest version and contains regression.

## Steps to Reproduce

1. Go to https://codepen.io/alexedgcomb/pen/eYPWKQO

### Actual Behavior

Horizontal spacing between `E` and `-`

### Expected Behavior

No such horizontal spacing

Last known working in 0.91.2: https://codepen.io/alexedgcomb/pen/gOBWKQv

### Environment

Regression present in all the following combinations:
* MathLive 0.92.0 and 0.92.1
* MacOS 13.2.1 and { Chrome 112, Firefox 112, Safari 16.3 }
* Windows 11 and { Edge 112, Chrome 112, Firefox 112 }

Regression NOT presentin any of the above OS/browser combinations with MathLive 0.91.2

**Comment by arnog** [comment]
Fixed now.
