### ISSUE TITLE
Virtual keyboard's layouts' hints are only partially visible

### ISSUE THREAD

**Issue by jonjbar** [arnog/mathlive#1956]
## Description

When hovering over a virtual keyboard's layout's hint, only the bottom of the hint is visible.

## Steps to Reproduce

1. Open the demo: https://cortexjs.io/mathlive/demo/
2. Click the icon to show the virtual keyboard
3. Place the mouse over one of the keyboard layout switch button to display a hint: only the bottom of the hint is visible

### Actual Behavior

Hint is partially visible

### Expected Behavior

Hint should be fully visible.

This is a regression, it used to work in 0.87.1

### Environment

MathLive version 0.92.1
Windows
Chrome, Firefox, Edge

**Comment by arnog** [comment]
Fixed in master
