### ISSUE TITLE
Restrict input to a subset of operations & variables

### ISSUE THREAD

**Issue by mdugue** [arnog/mathlive#1958]
## Question

I just stumbled upon MathLive and am very impressed by its simplicity of use and the power it delivers at the same time 💪

For a project that I'm currently working on it would need a very similar tool, but restricted to a limited set of operations and variables. For example I would only like to allow the operations **`+`**, **`-`** & **`sqrt`** and the variables **`a`** & **`b`**. 

So the users could enter **`a + b`** but not `d^c`.

Is there any way to do so? ChatGPT pointed me to some options called `customCommands` and `customSymbols`, but those don't seem to exist 😅 . Do you have a hint on how to achieve this with Mathlive or can you point me to other tools in case this is not a valid scenario for mathlive?

Thanks a lot in advance 🙏

**Comment by arnog** [comment]
Thank you for the kind words.

Not sure where ChatGPT got the idea about `customCommands` and `customSymbols`. Maybe it thinks MathLive *should* have those options :)

There are a couple of ways of going about this. One would be to filter keyboard input. It's feasible but can turn out to be quite complicated.

Another approach would be to prevent keyboard input altogether and to use a custom virtual keyboard only. 

To turn off the physical keyboard, see https://cortexjs.io/mathlive/guides/virtual-keyboards/#preventing-input-from-the-physical-keyboard

You can define your own custom virtual keyboard with only the keys for the operations you want to support. See here: https://cortexjs.io/mathlive/guides/virtual-keyboards/#defining-custom-layouts

**Comment by mdugue** [comment]
Hey @arnog , thanks for your reply. Yeah GPTs API-hallucinations are interesting. I stumbled upon quite a lot by now for different libraries. 

So. I think filtering approach would not work out in our case, as the variables we'd like to allow have very long names. This might lead to strange UX. 

A custom keyboard might be a better alternative. Given the fact that we have thousands of allowed variables, is there a way to add extended interactivity to the layouts, such as a search input for filtering and some paging functionalities? Or would you argue, that this does not match the idea of a keyboard anymore?

**Comment by arnog** [comment]
In theory you could add a search field to the keyboard. That said, if you have that many variables, maybe you need to reconsider your UI. Rather than constraining what users can type it might be better to let them type what they want and provide an error message guiding them to the syntax that can actually be accepted. That's an interesting problem...

**Comment by mdugue** [comment]
Yeah, also having a search field inside the keyboard means that you definitely need a second keyboard to control the keyboard. Might not be ideal 🤣

I'll try to explain my case a bit more in detail. We have a huge amount of variables that relate to signals, things like **speed**, **frontPressure**, **roofPressure**, etc. We would like to create a UI that allows the user to create formulas such as `(3.2 + speed) / roofPressure` or whatever. The user knows about the signals, but not necessarily about their correct spelling. Hence ideally we would also provide some auto-complete features for entering the variables (that's where the idea with the search field originated).

So yeah… the more I think about it the more I am unsure if this is a case mathlive tries to solve at all or if its rather sth. completely different. What dou you think @arnog ?

**Comment by arnog** [comment]
Probably not.

**Comment by hsellik** [comment]
I'm implementing a similar functionality although I'm not using the virtual keyboard. Because I have fewer variables, I use badges, which on click insert `\mathord` to the value to get uneditable variables in the input.
```
function insertVariable(variable: string): void {
  mathfield.insert(`\\mathord{${variable}`);
}
```
One could also use a dropdown with a search field for this if there are more variables.

See more https://github.com/arnog/mathlive/issues/1037
