### ISSUE TITLE
Difficult to focus on field since line-height:0 in v0.29 (regression)

### ISSUE THREAD

**Issue by jlchereau** [arnog/mathlive#196]
**Describe the bug**
Difficult to focus on field since line-height:0 in v0.29 (regression)

**To Reproduce**
On mathlive.io, the caret is just not shown when the field is empty, but somehow the field gets the focus.

1. Create html page with mathlile field as documented Math.makeMathField 
2. Open the page in chrome and click on the field: the hotspot is limited to a horizontal line of 4px (thx to padding 2px) in the middle of the field)
3. Hard to get the focus on the field

**Expected behavior**
A line-height that makes foscusing easy and displays the caret
Regression: it did work properly in v0.28

**Environment**
- Device: PC
- OS: Windows
- Browser chrome
 - Version v0.29 (not previsou v0.28)

**Comment by arnog** [comment]
Fixed now.
