### ISSUE TITLE
[Question] How to disable sound playback?

### ISSUE THREAD

**Issue by ichibha** [arnog/mathlive#1962]
I'm facing an issue where I need to disable all sound playback. 
I would appreciate some guidance on how to achieve this.

**Comment by arnog** [comment]
To turn off all sound playback, do this: `MathfieldElement.soundsDirectory = null`

**Comment by ichibha** [comment]
@arnog Thank you for your response. Unfortunately, the solution you provided did not work for me when using React. To help you understand the problem, I have created a simple code example that reproduces the issue. You can find the code at the following GitHub repository: https://github.com/ichibha/mathlive-test.

**Comment by arnog** [comment]
You need to set the direction on the class, not an instance. In `mathlive-test/src/App.js` instead of `mf.current.soundsDirectory = null` use `MathfieldElement.soundsDirectory = null` (and you can probably call this somewhere else than `useEffect()` since you don't need an instance).

**Comment by ichibha** [comment]
Putting the line just after the import commands worked. Thank you!
