### ISSUE TITLE
[Feature] Add \sech and \csch operators

### ISSUE THREAD

**Issue by patmagauran** [arnog/mathlive#1972]
## Description

These operators are currently not valid options. However, \arcsech and \arccsch are. 

Additionally, are there are any plans to allow for customization of the operators available?

**Comment by arnog** [comment]
As far as I know, `\sech` and `\csch` are not standard LaTeX commands, nor are they part of popular package. If I'm wrong, please let me know which package they're defined in.

Typically, LaTeX writers who need those commands often will define macros for them. Of course, you can simply use `\mathrm{sech}` if you only use them infrequently.

You can define additional commands via macros. You can learn more about macros here: https://cortexjs.io/mathlive/guides/macros/

**Comment by arnog** [comment]
Answered. Closing.
