### ISSUE TITLE
ascii-math ouput format for placeholders

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#1985]
## Description

ascii-math output for placeholder doesn't work :

- with mathfield.getValue('ascii-math'), placeholder output is empty
- with mathfield.getPromptValue(promptID, 'ascii-math'), output format is latex

[here is a stackblitz sandbox](https://stackblitz.com/edit/web-platform-6y7eo5?file=index.html)

### Environment

**MathLive version**
0.94

**Comment by Zahara-Nour** [comment]
found the problem with getValue

**Comment by arnog** [comment]
Looks good.
I've added the other half: Ascii Math output for `\placeholder`. I've added a pair of `()` around it, since this is obviously not part of the Ascii Math standard. Let me know if you have another suggestion.
