### ISSUE TITLE
Errors in the console when copying and pasting in a sandboxed iframe

### ISSUE THREAD

**Issue by spraot** [arnog/mathlive#1988]
## Description

Errors in the console when copying and pasting in a sandboxed iframe

## Steps to Reproduce

Unfortunately I wasn't able to reproduce this in jsfiddle so far, but I will continue trying.

### Actual Behavior

The copy/paste behavior works, but errors are shown in the console:

```
MathLive: The CortexJS Compute Engine library is not available.
Load the library, for example with:
import "https://unpkg.com/@cortex-js/compute-engine?module"
```

```
Uncaught TypeError: navigator.clipboard.readText is not a function
    pasteFromClipboard vendors.js:2
    executeCommand vendors.js:2
    executeCommand vendors.js:2
    ui vendors.js:2
    onKeystroke vendors.js:2
    keyboardDelegate vendors.js:2
    sentryWrapped helpers.ts:98
vendors.js:2:1042519
    pasteFromClipboard vendors.js:2
    executeCommand vendors.js:2
    executeCommand vendors.js:2
    ui vendors.js:2
    onKeystroke vendors.js:2
    keyboardDelegate vendors.js:2
    sentryWrapped helpers.ts:98
```

```
Error: NotAllowedError: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
```

### Expected Behavior

No error messages

### Environment

MathLive version 0.89.4

macOS/Windows, Chrome/Firefox/Edge/Whale

**Comment by arnog** [comment]
Could you please try again with the current version, 0.94.5?

**Comment by arnog** [comment]
I believe this is fixed. Please re-open if that is still an issue.

**Comment by RambabuPatina** [comment]
Hi @arnog , We are on 0.97.1 version still getting the issue. Any idea?

**Comment by arnog** [comment]
The current version is 0.98.6.
