### ISSUE TITLE
the demo page does not show math formula in my iphone browsers (safari and chrome)

### ISSUE THREAD

**Issue by ninesunqian** [arnog/mathlive#1989]
the demo page (https://cortexjs.io/mathlive/demo/) does not show math formula in my iphone browsers (safari and chrome)

![WechatIMG4](https://github.com/arnog/mathlive/assets/1024983/a6b4afa9-3d62-4876-9737-abab5eb4decf)
(![WechatIMG3](https://github.com/arnog/mathlive/assets/1024983/029aa679-6524-4787-b754-0663b8664534))

my phone is  iPhone12  iOS 16.1.1（20B01）

**Comment by arnog** [comment]
Weird. I can’t reproduce this. A few thoughts:
- the current version of iOS is 16.5
- does the same thing happen if you try to open it as a regular page (not in “Private” mode)?
- does the same thing happen with the landing page: https://cortexjs.io/mathlive/ ?
- do you have a slow or intermittent network connection? The first download could take a while.
- Do you have JavaScript turned off?

**Comment by mgreminger** [comment]
I was able to reproduce on the iOS simulator (which happens to be on iOS 16.2 on my system). The error is occurring using the [`CSSStyleSheet` constructor](https://github.com/arnog/mathlive/blob/f3f9b02ca4bad5067b2e2369b46d67eb38f8e80d/src/common/stylesheet.ts#L35). According to [caniuse](https://caniuse.com/mdn-api_cssstylesheet_cssstylesheet), this API became available on iOS 16.4.

**Comment by arnog** [comment]
Ah, yes, that makes sense. iOS 16.4 FTW. Or 16.5, really.

**Comment by vozian** [comment]
It also doesn't work in the Desktop Safari (Mac version 13.2.1, Safari version 16.3)
<img width="1286" alt="image" src="https://github.com/arnog/mathlive/assets/32716252/465b588d-d772-4857-8fcc-cb5edf5235e7">

**Comment by arnog** [comment]
@vozian that's right. It's not going to work with any version of Safari that's older than 16.4, regardless of the OS, platform or device.

**Comment by timmckague** [comment]
@arnog Any chance you're planning to add back support for older versions of safari?

**Comment by arnog** [comment]
@timmckague I might consider it, temporarily. 

Can you help me understand why updating to a more recent version of Safari is not an option?

**Comment by timmckague** [comment]
@arnog: Thanks for considering it. 

Prompting users to update to a more recent version of safari is certainly a possibility. That said it seems like an unpleasant approach given the current adoption rate of safari >=16.4. Based on [this data from caniuse](https://caniuse.com/usage-table), which claims to be up to date as of April 2023, it seems like most safari users are running on <= 16.3.

I'm speculating here, but perhaps given that safari is tied to the OS/iOS version, people might be more resistant to updating than they would be for chrome on a desktop (which just requires the app to be restarted) for example. People with older hardware may be even more resistant or may not be able to update to a new major version.

**Comment by arnog** [comment]
I have added, temporarily, a workaround to support older versions of Safari. In general, using the latest version of browsers is highly recommended in order to be protected from malware and other security issues.

The browsers are freely available, so I'm not sure I understand the financial impact this would have on anyone.

It does have a financial impact on me, though :) as I have to spend time and effort to fix and support these outdated browsers.

Speaking of which, if you cannot afford to support the project monetarily, something you can do that wouldn't cost you much is to star the project in GitHub. Thank you for your support!

**Comment by Leon-Lj** [comment]
Schools can sometimes be a bit slow in updating their iOS/iPad OS devices to the latest version. The update is centrally controlled, sometimes at the municipality level even, so getting them to speed up a update can be hard. The result is often rather that they stop using us.

If possible I think a good compromise would be if minimum browser version could be noted in the change log. Then we could just hold off on updating mathlive to a new version until sufficient time has passed.

**Comment by UpygeoSiegel** [comment]
Well said @Leon-Lj - I think that's a fair assessment. 

I did just star the project! Thank you for this amazing library @arnog!

**Comment by arnog** [comment]
mathlive 0.94.7 includes a workaround for this issue
