### ISSUE TITLE
[Bug] Buttons are not functioning after right-click on virtual keyboard

### ISSUE THREAD

**Issue by poincare15** [arnog/mathlive#1995]
Step - 1: To access the sub-elements of any button, right-click is performed.
Step - 2: Left-click is performed on the sub-button.
Step - 3: It is observed that the sub-property is not added. In fact, this issue locks the entire virtual keyboard. It does not resolve until the virtual keyboard is closed and reopened.

Video:
The cursor is not visible in the video. I'm sorry for that.

https://github.com/arnog/mathlive/assets/134855855/855276c0-4b79-4df3-8502-87d2ff400045

**Comment by poincare15** [comment]
@arnog is this an error? Or am I using it wrong?

**Comment by arnog** [comment]
This looks like a bug, but I haven’t had the chance to investigate yet.

**Comment by arnog** [comment]
I can't reproduce this issue.

Do you use a trackpad or a mouse or something else?

Which browser/OS did you use?

Are there any messages displayed in the console?

**Comment by poincare15** [comment]
I'm using mathlive with a mouse on Windows 10.

No error in console.

Google chrome 114
