### ISSUE TITLE
\left( to math-ml missing >

### ISSUE THREAD

**Issue by kubaPod** [arnog/mathlive#1996]
## Description

`math-ml` representation of `x(x+1)^2` contains `<sup>` with 3 arguments.

## Steps to Reproduce

```js
MathLive.convertLatexToMathMl("\\left(\\right)")
```

```
'<mrow><mo(</mo><mo>)</mo></mrow>'
```

### Expected Behavior

`<mo>(` not `<mo(`

### Environment

**MathLive version** 0.94.6

**Operating System** Window 10

**Browser** Chrome

**Comment by arnog** [comment]
Fixed
