### ISSUE TITLE
Inline Errors/Annotations based on MathJSON

### ISSUE THREAD

**Issue by scytacki** [arnog/mathlive#1998]
## Description

This is a feature for showing more information inline in the MathLive field.
We want users to see there are missing parts of their expression. If the user types `1+` we'd like them to see `1+□`.

As far as I understand `1 +` is valid LaTeX so this isn't something that should be enabled all the time. I also think it also isn't something that should be figured out via the MathLive field itself since it doesn't evaluate the expression. It would probably be possible to identify "binary" operators and figure out they don't have a right and left operand. However with the Compute Engine is already doing this, so it seems better to use that. 

The MathJSON output of `1 +`, is `["Add", 1, ["Error", "'missing'", ["Latex", "'+'"]]]`. If the MathJSON included the atom ids then this MathJSON result could be used to annotate the MathLive field. Alternatively we could render the MathJSON to LaTeX and then replace the content of the MathLive field. However, that kind of replacement seems like it would cause problems since it would be hard to keep track of the caret if we are constantly replacing model as the user is typing. So I think an annotation system is better.

**Comment by arnog** [comment]
That's an interesting problem, but a really hard one.

Note that if a MathJSON expression has an error and you call `expr.latex` you will get back an annotated LaTeX expression that includes a tooltip explaining the error. Maybe that's something you could display below the mathfield? See https://cortexjs.io/compute-engine/demo/

**Comment by scytacki** [comment]
That demo is really useful, thankyou.  Perhaps it will be enough for my group.
I forgot to mention that we have resources to work on this feature.

**Comment by arnog** [comment]
Looks like this was abandoned.
