### ISSUE TITLE
Library css not working inside iframe

### ISSUE THREAD

**Issue by SachinShetty11493** [arnog/mathlive#1999]
## Description

I am trying to create math-live element inside an iframe, but the default library css are not getting applied. Hence the whole UI is breaking .
Which css library css do i need to import or to add in script?
How do i add mathlive library css inside iframe?

**Comment by arnog** [comment]
Could you share the code you are using?

**Comment by SachinShetty11493** [comment]
Code snippet:-

`   

      
      let newElem = document.createElement("math-field");
          newElem.setAttribute(
            "id",
            `div-${leftCoordinate}-${topCoordinate}-${width}-${height}`
          );
          newElem.style.position = "absolute";
          newElem.addEventListener("input", (ev) => {
            newElem.setAttribute("data-ans", ev.target.value);
          });
          newElem.addEventListener("focus", (ev) => {});
          newElem.addEventListener("move-out", (ev) => {
            ev.preventDefault();
            console.log("called focus out");
          });
          for (var key in props.answers) {
            newElem.value = props.answers[key];
          }
          newElem.style.border = "2px solid #333";
          newElem.style.borderRadius = "12px";
          newElem.style.background = "rgba(255, 255, 255, 0.4)";
          newElem.style.left = leftCoordinate + "%";
          newElem.style.top = topCoordinate + "%";
          newElem.style.width = width + "%";
          newElem.style.height = height + "%";
          newElem.style.fontSize = props.styles.size;
          newElem.style.color = props.styles.color;
          newElem.style.cursor = "pointer";
          let canvasDiv =
            frameRef.current.contentDocument.querySelector("#canvas");
          canvasDiv.appendChild(newElem);
`
Screenshot:-
![Screenshot 2023-05-31 at 8 57 25 PM](https://github.com/arnog/mathlive/assets/30428264/8f0bf206-a5a8-4cef-b9cb-7748c7fce5a8)

**Comment by arnog** [comment]
It's working for me. Do you have messages in the console? Which OS/browser version are you running?

**Comment by SachinShetty11493** [comment]
Console:- 
<img width="1439" alt="Screenshot 2023-05-31 at 11 25 58 PM" src="https://github.com/arnog/mathlive/assets/30428264/8b404d4f-24bf-4fab-a2e5-e218f19ef425">

Chrome browser:- Version 113.0.5672.126 (Official Build) (arm64)
MacOS Big Sur:- Version 11.4

**Comment by SachinShetty11493** [comment]
I am trying to dynamically create through JS  and its not happening.  If i do it directly without iframe it's working.

**Comment by arnog** [comment]
Did you try the example I pointed out earlier?

I can't reproduce this problem. When I tried to run your code, it worked fine for me.

If you can create a minimal example in Codepen that demonstrate the problem and I'd be happy to investigate.

**Comment by SachinShetty11493** [comment]
Yes I did try above example but no luck. Here is the complete code.

`
import Frame from "react-frame-component";
import {
  MathfieldElement,
  MathfieldOptions,
  MathfieldElementAttributes,
  VirtualKeyboardPolicy,
  VirtualKeyboardCommands,
} from "mathlive";

const IFrame = forwardRef((props, ref) => {
      const frameRef = useRef();
      const [height, setHeight] = useState(100);
      const [font, setFont] = useState(false);
      const [size, setSize] = useState("");
      const [color, setColor] = useState("");
      const prevSelectedBoxRef = useRef(null);

  useEffect(() => {
    const frame = frameRef.current;

    const handleLoad = () => {
      setHeight(frame.contentDocument.body.scrollHeight);

      frame.contentDocument.querySelectorAll("[data-ans]").forEach((node) => {

      const iframeDocument = frameRef.current.contentDocument;

      const mathScript = document.createElement("script");
      mathScript.src = "https://unpkg.com/mathlive/";

      // Append the script to the body
      iframeDocument.body.appendChild(mathScript);

     let newElem = document.createElement("math-field");
     newElem.style.position = "absolute";
          newElem.addEventListener("input", (ev) => {
            newElem.setAttribute("data-ans", ev.target.value);
          });
          newElem.addEventListener("focus", (ev) => {});
          newElem.addEventListener("move-out", (ev) => {
            ev.preventDefault();
            console.log("called focus out");
          });
          newElem.style.border = "2px solid #333";
          newElem.style.borderRadius = "12px";
          newElem.style.background = "rgba(255, 255, 255, 0.4)";
          newElem.style.left = "10%";
          newElem.style.top = "10%";
          newElem.style.width = "300px";
          newElem.style.height = "300px";
          newElem.style.cursor = "pointer";
          let canvasDiv =
            frameRef.current.contentDocument.querySelector("#canvas");
          canvasDiv.appendChild(newElem);
    };

    frame.addEventListener("load", handleLoad);

    return () => {
      frame.removeEventListener("load", handleLoad);
    };
  }, [
    props.clearAnswers,
    displayAnswers,
    props.answers,
    displayCorrectAnswers,
    props.tab,
  ]);

  return (
    <>
      <Frame
        id="worksheet"
        ref={frameRef}
        initialContent={`<!DOCTYPE html><html><head></head><body style="margin: 0"><div id="canvas" style="position: relative; border: 2px solid rgb(184, 184, 184); cursor: default;"><div style="text-align: center;"></div></body></html>`}
        style={{
          height,
          width: "100%",
          border: 0,
          margin: 0,
        }}
      />
    </>
  );
});

export default IFrame;
`

**Comment by arnog** [comment]
> Yes I did try above example but no luck.

What do you mean by "no luck"? Did the example not work for you?

> CodeSandbox Link:- [https://codesandbox.io/s/lucid-fog-7v5r4w?file=/src/Iframe.js](https://github.com/arnog/mathlive/issues/url)
In code sandbox link i am not able to toggle keyboard but styles are applied. But in my local its the other way round I am ble to toggle the keyboard but styles are not applied.

Thanks for the sandbox. The virtual keyboard is not showing due to the peculiarities of the codesandbox environment. If you click on the full screen icon, the virtual keyboard works fine.

Since this example is not showing the problem you're encountering, I can't really use it to debug your problem. It does seem like there's something specific about your environment that is preventing the styles from being applied, but I don't know what it is.

**Comment by SachinShetty11493** [comment]
No it did not work. And I have issues with toggling of keyboard as well. It does not toggle when clicked for the first time.

**Comment by arnog** [comment]
Let me know if you can build a sandbox that reproduces the problem and I'll be happy to have a look at it.

**Comment by SachinShetty11493** [comment]
Hey I added the script and it worked for desktop devices. But the keyboard is disappeared for mobile devices. Is there anything which i need to add it explicitly for it to show for mobile devices?

**Comment by arnog** [comment]
No, nothing special. There must be something about your environment...

**Comment by SachinShetty11493** [comment]
I haven't added anything much. I have just loaded the script in body and added math-field.It is working for android devices but not on iphones. Very Strange.

**Comment by SachinShetty11493** [comment]
$ and @ symbols are present in virtual keyboard and I am unable to add it through mac keyboard as well. Can u please tell me how can i customise it?

**Comment by arnog** [comment]
There is insufficient information available to be acting on this issue. Please open a new issue if you can share an environment where the issue can be repoduced.
