### ISSUE TITLE
Stops recognizing functions without backslash after backspacing function with backslash

### ISSUE THREAD

**Issue by jlchereau** [arnog/mathlive#200]
**Describe the bug**

Stops recognizing functions without backslash after backspacing function with backslash. Backslash (\\) seems to be triggering a mode that is not reverted when the \ that triggered it is then removed.

**To Reproduce**

1. Go to mathlive.io
2. Focus the field and remove content (select all + delete)
3. Type `sum`: great it works!
4. Remove the sum (select all + delete)
5. Type backslash \\ (with or without more letter)
5. Backspace (back to and including \\)
7. Type `sum` + carriage return: it does not work

**Expected behavior** 

step 7 should display a sum as in step 3.

**Environment**

Device: PC
OS: Windows 10
Browser Chrome
Version v0.29.0

**Comment by arnog** [comment]
I couldn't reproduce this issue exactly with the steps provided, but there were cases where the command mode could get out of sync, and deleting the last character in command mode (the "\") would not terminate it, resulting in a confusing state. This should no longer happen. Please open a new issue if you encounter other cases of the command mode behaving in unexpected ways.

**Comment by jlchereau** [comment]
# PLEASE REOPEN

I take from the vocabulary you use that mathlive implements a **command mode** and a **smart mode**. By default, mathlive is in smart mode and command mode is entered hen typing a backslash `\\`. The bug reported here is if you remove the backslash with a backspace, smart mode is not restored and you remain im command mode as shown below:

![E51EFEC4-5D9F-4101-9B73-2623446CD6B8](https://user-images.githubusercontent.com/2556751/58075288-3a524f00-7b9f-11e9-8594-8ccc1598afec.GIF)

**Comment by arnog** [comment]
You are testing with mathlive.io, which is using mathlive.js 0.29.1 (the version number is displayed at the bottom of the page).
This is fixed in HEAD. You can verify it by updating to HEAD and using npm start to try some of the examples.
