### ISSUE TITLE
renderMathInElement(): Illegal constructor

### ISSUE THREAD

**Issue by UpygeoSiegel** [arnog/mathlive#2001]
## Description

Users with Safari 15.xx get this error when renderMathInElement() is called in their browser

[Error] TypeError: Illegal constructor
	(anonymous function) (mathlive.min.js:2145:278271)
	wo (mathlive.min.js:2145:278271)
	Mr (mathlive.min.js:2396:681843)
	define
	(anonymous function) (mathlive.min.js:2408:701503)
	(anonymous function) (mathlive.min.js:2412:709793)
	(anonymous function) (mathlive.min.js:2:269)
	Global Code (mathlive.min.js:2:295)

[Error] renderMathInElement(): Illegal constructor
	(anonymous function) (LogRocket.min.js:2:49190)
	Ml (mathlive.min.js:2412:708175)
	vm (mathlive.min.js:2412:709744)
	create (math-live-quill.js:14)
	create (quill.js:183:94)
	(anonymous function) (quill.js:3407:87)
	(anonymous function) (quill.js:7406)
	(anonymous function) (quill.js:3404)
	(anonymous function) (quill.js:7145)
	insertAt (quill.js:4252:108)
	(anonymous function) (quill.js:2484)
	reduce
	(anonymous function) (quill.js:399)
	applyDelta (quill.js:2452)
	(anonymous function) (quill.js:1459)
	modify (quill.js:1610)
	createQuestion (assignment-view.js:254)
	(anonymous function) (assignment-view.js:155)
	asyncFunctionResume
	getQuestion (assignment-view.js:153)
	(anonymous function) (assignment-view.js:72)
	asyncFunctionResume
	setUpQuestion (assignment-view.js:68)
	setUpTimer (assignment-view.js:35)
	Global Code (assignment-view.js:66)

## Steps to Reproduce

You can reproduce this by using an iPad/iPhone simulator on xCode with IOS 15 and below. I've gone to the MathLive website and math text does not render on the site because of this same error.

**Comment by arnog** [comment]
Safari 15 is not supported.
