### ISSUE TITLE
Overline not rendering

### ISSUE THREAD

**Issue by AllyMarthaJ** [arnog/mathlive#2008]
## Description

`\overline` command doesn't render anything. (Nor does \underline)

## Steps to Reproduce

1. Navigate to either the demo or https://cortexjs.io/mathlive/reference/commands/
2. Enter LaTeX `\overline{ABC}` or `\underline{ABC}` into the demo, or scroll to the overline/underline commands.

### Actual Behavior

Neither `\overline{ABC}` or `\underline{ABC}` render a over/underline, or the content at all.
<img width="725" alt="image" src="https://github.com/arnog/mathlive/assets/28497049/4c4e743f-fd0f-4689-8353-e51d292ce83c">

### Expected Behavior

The content should be rendered.

### Environment

**MathLive version**
0.94.6 (replicated locally)

**Comment by zeyad-aql-nagwa** [comment]
Sorry for the rush but any updates @arnog 😃?

**Comment by arnog** [comment]
I haven't had the chance too look at it yet. I'll try to find some time this week.
