### ISSUE TITLE
Feat request: \textcolor and \colorbox commands in virtual keyboard

### ISSUE THREAD

**Issue by zeyad-aql-nagwa** [arnog/mathlive#2019]
## Description

In older versions of mathlive, there were 2 keycaps in the virtual keyboard that were resposible for changing the foreground and background colors of texts. They looked like this:

<img width="520" alt="Screenshot 2023-06-14 at 3 00 25 PM" src="https://github.com/arnog/mathlive/assets/87318803/5c8b4484-8e38-496d-a1f6-301013fc0a1e">

<img width="455" alt="Screenshot 2023-06-14 at 3 00 54 PM" src="https://github.com/arnog/mathlive/assets/87318803/8721733c-ebd7-4970-bbb0-a0905bffb5db">

If possible, I would like to request that you include them in the virtual keyboard once again.

### Environment

**MathLive version**: 0.94.7

**Comment by arnog** [comment]
Although they are not part of the default keyboard, you can use them when building a custom keyboard as the keycap shortcuts `"[foreground-color]"` and `"[background-color]"`.

**Comment by zeyad-aql-nagwa** [comment]
Noted, Thanks 😃.

**Comment by zeyad-aql-nagwa** [comment]
Noted, Thanks 😃.
