### ISSUE TITLE
mathml output usage in browser

### ISSUE THREAD

**Issue by johanneswilm** [arnog/mathlive#202]
TeXZilla provides a method to create a mathml XML node from a latex string that can be called with `const mathmlNode = TeXZilla.toMathML(latex)`.

As I was switching to MathLive for math editing, I was trying to see if I could also use MathLive to convert the equations to MathML and replace TexZilla. 

In order to get the mathmlNode, I did this:

```
const domParser = new DomParser()
const mathmlNode = domParser.parseFromString(
            `<math xmlns="http://www.w3.org/1998/Math/MathML"><semantics>${
                MathLive.latexToMathML(latex)
            }</semantics></math>`,
            "application/xml"
        ).documentElement
```

This worked to a certain degree. Unfortunately it stumbles on certain mathml character entities, such as `&InvisibleTimes;` or `&pi;`. The DOM parser returns errors like "Entity 'pi' not defined".

I then compared the output that comes out of TexZilla and MathLive and I noticed that TexZilla uses the standard unicode characters instead of the character entities. Is there a reason why MathLive is producing this kind of output and is there a way to create a node that the browser can read without throwing errors?

**Comment by NSoiffer** [comment]
It is a much better idea to use either the characters directly or numeric references to them such as '&#x2062;'. Numeric references work everywhere and don't require a DTD to define the chars.

**Comment by NSoiffer** [comment]
Why are you wrapping the presentation MathML that mathlive returns in a `semantics` element? If you use `application/xml`, you also need to set the `encoding` attr to `application/mathml-presentation+xml` or 
`MathML-Presentation`. It's much simpler to just wrap with `math xmlns="http://www.w3.org/1998/Math/MathML">` and skip `semantics`.

**Comment by johanneswilm** [comment]
I am just wrapping them in a `semantics` element because that corresponded 1:1 with what TeXZilla was outputting in some cases. 

How would you set the `encoding` attr given the code above?

**Comment by johanneswilm** [comment]
> It is a much better idea to use either the characters directly or numeric references to them such as '⁢'. Numeric references work everywhere and don't require a DTD to define the chars.

**Comment by NSoiffer** [comment]
My bad, I misread what you wrote as using `<annotation-xm> ... </annotation-xml>` inside the semantics element. Instead, you telling the parser to parse it as XML which I believe is good. So in your code, just change your example to remove `semantics` -- it adds nothing.

**Comment by johanneswilm** [comment]
Ok, so that leaves me with:

```
const domParser = new DomParser()
const mathmlNode = domParser.parseFromString(
            `<math xmlns="http://www.w3.org/1998/Math/MathML">${MathLive.latexToMathML(latex)}</math>`,
            "application/xml"
        ).documentElement
```

However, the issue with the character entities still exists. Could we maybe replace those with the characters/numeric references, as @NSoiffer seems to suggest when he writes?:

> It is a much better idea to use either the characters directly or numeric references to them such as '⁢'. Numeric references work everywhere and don't require a DTD to define the chars.


I noticed that I can get rid of some errors by doing

```
MathLive.latexToMathML(latex).replace(/\&InvisibleTimes;/g, '&#8290;')
```

But that kind of postprocessing is really not very precise and it would be better if this could be done directly in the mathlive source code.

Or alternatively, given that you want to deprecate this module in #159, maybe you think it's a better idea to stick with TeXZilla anyway?

**Comment by arnog** [comment]
That module is going to get moved out of the core MathLive project, but it will still be around, so it's something still worth addressing. I'll look at it.

**Comment by johanneswilm** [comment]
Hey @arnog I think the merge of this went well, but there hasn't been a version released since then. I currently have a PR on Fidus Writer open for this that I was planning on merging once there is a new mathlive release. But if you don't plan on releasing any time soon, maybe I should not plan for that.

**Comment by arnog** [comment]
@johanneswilm : Version 0.30 has been released that incorporates this and other fixes.

**Comment by johanneswilm** [comment]
Thanks so much!

**Comment by johanneswilm** [comment]
@arnog WIll it be pushed to npmjs.com as well?

**Comment by arnog** [comment]
Yes, sorry, the push to npmjs apparently failed the first time around, but it's up now (with a new version number, but it's the same package).

**Comment by johanneswilm** [comment]
@arnog This issue seems to be back in 0.34

**Comment by arnog** [comment]
I can't reproduce it. Could you write up a new issue with a code sample showing what you see vs. what you expect?
