### ISSUE TITLE
longdiv is broken

### ISSUE THREAD

**Issue by tommy-schmitz** [arnog/mathlive#2020]
## Description

When did enclose longdiv break? (And a few other enclose commands.) It does not yield any error or anything, but the longdiv symbol does not actually show up. Here is a screenshot of the brokenness on the Mathlive website:

<img width="1324" alt="Screenshot 2023-06-14 at 10 19 09 AM" src="https://github.com/arnog/mathlive/assets/10479143/3cda8210-ea7a-46fa-9b3d-53f8f56045a7">

As you can see in the screenshot, the longdiv symbol (and a few other enclose commands) are not showing up properly.

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. Use the enclose longdiv macro, like `\enclose{longdiv}{x=0}`

### Actual Behavior

Observe a lack of a long division symbol in the rendered formula.

### Expected Behavior

The long division symbol should appear in the formula.

This is probably a regression, but I haven't been using Mathlive for very long, so I don't know for sure.

### Environment

**MathLive version** In my project currently 0.72.3, but it's also broken on the website as of today 2023-06-14

**Operating System** macOS

**Browser** Chrome

**Comment by arnog** [comment]
Not sure exactly when, but it's been a while that this enclose variation is not supported.

**Comment by arjunexalture** [comment]
Is there any alternative to use longdiv in mathLive?

**Comment by arjunexalture** [comment]
@arnog Thanks. When we can expect the next release?
