### ISSUE TITLE
[Bug] The virtual keyboard layout is broken on iOS

### ISSUE THREAD

**Issue by LinhTT46** [arnog/mathlive#2028]
## Description

https://github.com/arnog/mathlive/assets/44936298/a1a2b998-92ad-46aa-96f9-0b0a789b29bd

### Environment

**MathLive version**: Newest 

**Operating System**:  **iOS 15.7.3 (iPhone 6s)** 

**Browser**:  Safari

**Comment by arnog** [comment]
The minimum system requirement is iOS 16.0 or later.

**Comment by arnog** [comment]
In general, I try to support older version of OS (although using older versions of OSes is bad practice from a security standpoint, I do understand that it may be difficult in some education environment to keep devices up to date).

However, when some new features or capabilities are introduced that are not supported in older versions, I will attempt to implement a workaround, if it is simple. If it requires too much work, unless someone is willing to sponsor the work, I'm not likely to spend time on it.

In this particular case, iOS 16 introduced support for CSS container queries, which are used to do responsive layout of the virtual keyboard, i.e. so you can display a virtual keyboard for example in an iframe without the keyboard taking the whole width of the screen.

An attempt was made to introduce a simple workaround, but it ended up breaking other things, so I had to back it out. I have an idea on how a workaround could be implemented, but it's a substantial amount of work, and I suspect the number of users relying on OS pre-iOS 16 will diminish over time.
