### ISSUE TITLE
Superscript is too far to right for a unit

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#203]
**Describe the bug**
For units such as `mm`, a superscript is positioned too far to the right (see below for example).

**To Reproduce**
Type `4\operatorname{cm}^2`
You get:
![image](https://user-images.githubusercontent.com/1545836/58072927-0bfc5180-7b56-11e9-845f-3e1852300dd4.png)

For text, there is no problem:
![image](https://user-images.githubusercontent.com/1545836/58073084-8fb63e00-7b56-11e9-8e69-411e54d7f489.png)

**Comment by NSoiffer** [comment]
Hmm... looks like it is problem for `sin`, etc:
![image](https://user-images.githubusercontent.com/1545836/58073291-06533b80-7b57-11e9-84d0-1e6f47f4dbfb.png)

**Comment by arnog** [comment]
This seems to be working now.
