### ISSUE TITLE
[Bug] Angular Missing fonts 

### ISSUE THREAD

**Issue by mikepziegler** [arnog/mathlive#2034]
## Description

I want to implement mathlive in my angular app, but when I start up, there are no mathlive input

The link to the repo is [here](https://github.com/mikepziegler/ng-mathlive)

The project is inspired by [syedabdulaala](https://github.com/syedabdulaala/mathlive-ng-sample)

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. `ng new`
2. in the project, do `npm i mathlive`
3. Edit app.component.ts to this

```typescript
@Component({
  selector: 'app-root',
  template: `<div id='mathfield'></div>"
})
export class AppComponent implements AfterViewInit {
  @ViewChild('mathField', { static: true })
  mathFieldElement: ElementRef<HTMLDivElement>;

  mathfield: any;
  latex: string;
  mathML: string;

  ngAfterViewInit() {
    renderMathInElement('mathfield');
  }

}

```

4. Copy all the fonts from the mathlive npm package into the assets folder
5. `ng serve`

### Actual Behavior

The mathlive input will not be displayed and the browser console shows lots of errors, because the fonts and sounds are missing.

![image](https://github.com/arnog/mathlive/assets/20162405/62d936e3-dd3a-4341-a814-f1277acb8dda)

### Expected Behavior

The mathlive input should be displayed

I also have looked into #1376.
[Ionic mathlive](https://www.npmjs.com/package/ionic-mathlive) does not work because there is no update for angular 16 and I also tried it out.

#1476 returns a MathfieldElement. Should I use that instead of `renderMathInElement()`? If yes, where is the setOptions method and which method replaced it?

### Environment

Mathlive Version: 0.94.8

Operating System: Macos Ventura 13.4.1 and Windows 11 2023-06 (KB5027231)

Tested Browsers: Firefox, Chrome and Safari

**Comment by arnog** [comment]
`renderMathInElement()` is used to transform some LaTeX into a math equation. It does not provide an editable mathfield. Are you trying to use an editable mathfield?

If so, you should set your `template` to `<math-field #mathField />`

You should also change `mathfFieldElement` to `@ViewChild('mathField', { static: true }) mathFieldElement: ElementRef<MathfieldElement>;`

You also need to import `MathfieldElement` from MathLive.

Once you've done that you can access the content of the mathfield with `this.mathFieldElement.value`.

Note that `$perform()` or `$text()` do not exist.

See https://angular.io/guide/template-reference-variables

The issue with the fonts has to do with the setup of your build system. MathLive is expecting the fonts in a `/fonts` directory (as per the error messages). You should copy the fonts there. Alternatively, you can change where the fonts (and sounds) should be searched for by setting `MathfieldElement.fontsDirectory` to the path where you have the fonts. Similarly for the sounds assets.

See https://cortexjs.io/mathlive/guides/integration/#fonts-folder

**Comment by mikepziegler** [comment]
Great, thanks for your help. 
I just want to publish https://github.com/mikepziegler/ng-mathlive, because I use angular a lot and also provide others with the package. 

You've been a great help. thank you very much.

**Comment by arnog** [comment]
Great, got to hear you've got it sorted.

I'm not an Angular expert, but I don't think you need the `ngOnInit` (my understanding is that the mathfield will be created from the `<math-field>` tag in the template and will already have the `nativeElement` set to the `MathfieldElemnent` object corresponding to the tag.)

**Comment by mikepziegler** [comment]
I just checked it. You are right, I dont even need the `ngOnInit`
