### ISSUE TITLE
angular 13  once a button is selected then it is unselectable after clicking another for eg : if  i click 1 and then 2 ..it wont select 1 again

### ISSUE THREAD

**Issue by Bazil-cp** [arnog/mathlive#2035]
project demonstrating the issue.]

[To quickly build a demo project, consider

- (https://github.com/mindreframer/mathlive-bug-issue-templates)
- (https://github.com/mindreframer/mathlive-create-app) ]

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. [First Step]
2. [Second Step]
3. [And so on...]

### Actual Behavior

[What happens when you follow the steps above?]

[If there are any error messages, include the exact text shown. Some error
messages may be displayed in the Javascript console. Copy and paste them. Do not
include a screenshot of the error messages.]

### Expected Behavior

[What did you expect to happen instead?]

[Is this a regression: did it use to work in a previous version?]

### Environment

**MathLive version**

**Operating System** [macOS, Windows, iOS. Include the version]

**Browser** [Safari, Chrome, IE, Firefox, etc... Try several browsers and note
if there are differences between browsers. Include the version number of the
browsers.]

**Comment by manstie** [comment]
You should fill in the headings to describe the issue in detail. The title alone does not help at all.

**Comment by arnog** [comment]
There is insufficient information in this issue report to reproduce and investigate it. Please file an issue with more details, including step by step instructions on how to reproduce the problem, and relevant source code if applicable.
