### ISSUE TITLE
Pressing `Shift` on physical keyboard ideally should not have side effects or "toggle" virtual keyboard

### ISSUE THREAD

**Issue by oscarhermoso** [arnog/mathlive#2065]
## Description

This is some feedback on what I believe was a feature from [0.94.0](https://github.com/arnog/mathlive/releases/tag/v0.94.0)

> Improved behavior of the Shift key in the math keyboard. Single-press
the Shift key to set it temporarily, double-press it key to lock it (similar
to CapsLock), triple-press it to unlock. This is similar behavior to the
ones of mobile virtual keyboards.

While this works well for mobile virtual keyboards, where users are "tap typing" and looking at the virtual keyboard, users with physical keyboards find this behaviour buggy/unexpected.

Here are some unexpected behaviours with the current version ([0.94.7](https://github.com/arnog/mathlive/releases/tag/v0.94.7)) of MathLive when using a physical keyboard on https://cortexjs.io/mathlive/:

### Steps to reproduce
- User presses `Shift` once and releases the key
- User types `abc` quickly

### Expected
If the user is familiar with MathLive `Shift` toggling, they will expect `Abc`

If they are a PC user and using MathLive for the first time, they probably expect `abc`, because they don't expect `Shift` to toggle.

### Actual
- Math field may contain `ABC`, `ABc` or `Abc` depending on how fast they were typing

### Steps to reproduce
- User intends to type `a * b = c` on their physical keyboard
- Type `a`
- Hold `Shift`, but then release immediately (perhaps user was distracted for a second, or changed their mind about including a bracket in their equation)
- Type `Shift` + `8` to enter an `*`
- Press `b`

### Expected
Math field contains `a * b`

### Actual
Math field contains `a * B`, and virtual keyboard is "locked in"

### Steps to reproduce
- User is on a physical keyboard, and is familiar with current MathLive shift to toggle while the virtual keyboard is open
- They collapse the virtual keyboard
- They press `Shift` and release
- They press `=`

### Expected
- They expect to see `+` (`Shift` + `=`), same as 

### Actual
- They see `=`

### Steps to reproduce
- User types `Shift` + `a`, but continues holding shift
- They then type `Shift` + `b` and continue holding shift

### Expected
- Mathlive keyboard continues to show `Shift` being held, Mathfield contains `AB`

### Actual
- Mathlive keyboard no longer showing `Shift` is held, Mathfield contains `AB`

## Ideal outcome (in my opinion)

While I'm sure you could fix all of these unexpected behaviours while still keeping `Shift` to toggle keyboard, it would still force desktop users to "remember" the current `Shift` state.

With the three states being, "base", "shift", "locked-in shift", this is how I believe it should behave:

* Mouse-clicking on `Shift` in the virtual keyboard toggles through states _(no change from current behaviour)_
* Any MathLive virtual keyboard input considers the `Shift` state to determine whether _(no change from current behaviour)_
* From any starting state, holding `Shift` on a physical keyboard takes it to the "shift" state, and then returns to "base" state once released
* Any keyboard event should ONLY consider the modifier state from the keyboard event to determine whether `Shift` is held (ignore the virtual keyboard `Shift` state is)

If this was implemented, these would be the advantages:

* Keyboard input behaviour would not change whether Virtual Keyboard is open or closed.
* Any buffered input on slow computers will be handled correctly (modifier consistent with when it was typed in, not when it is received)
* Users on touch-screen laptops can swap between mouse/touch screen "toggling" and physical keyboard "modifying" without any change in behaviour
* Reduce risk of future bugs with race-conditions/timing problems when using physical keyboard

Thankyou again for all of your hard work Arnog. If you agree with my opinion, perhaps @manstie or myself would be able to help with this ticket.

### Environment

Mathlive v0.94.7
Operating system: Pop!_OS, 22.04 LTS
Browser: Chrome Version 114.0.5735.133

**Comment by arnog** [comment]
Thanks for taking the time to write this up and look into it. The behavior you propose make sense and I believe it would be an improvement over the current behavior. If you submit a PR, I'd be happy to review and merge it.
