### ISSUE TITLE
mathVirtualKeyboard is not defined Error

### ISSUE THREAD

**Issue by AbhishekNayak007** [arnog/mathlive#2066]
## Description
In a react project to change the behaviour of the math-field when i click on it it should show me keyboard and when i clicked outside it must disappear  but when i have written the code then it showed me the error ``mathVirtualKeyboard is not defined ``

## React Code
``` import "//unpkg.com/mathlive";
import React, { useState, useEffect, useRef } from "react";

function App() {
  const [value, setValue] = useState("");

  // Customize the mathfield when it is created
  const mf = useRef();
  useEffect(() => {
    mf.current.mathVirtualKeyboardPolicy = "manual";
    mf.current.addEventListener("focusin", (evt) => mathVirtualKeyboard.show());
    mf.current.addEventListener("focusout", (evt) =>
      mathVirtualKeyboard.hide()
    );
  }, []);

  return (
    <div className="App">
      <math-field ref={mf} onInput={(evt) => setValue(evt.target.value)}>
        {value}
      </math-field>
      <p>Value: {value}</p>
    </div>
  );
}

export default App;
```

### Actual Behavior
```
Line 11:  'mathVirtualKeyboard' is not defined  no-undef
Line 13:   'mathVirtualKeyboard' is not defined  no-undef
```

### Expected Behavior
I want that the above code must run smoothly as I am using the same code that is provided in the site : 
``` https://cortexjs.io/mathlive/guides/react/```

### Environment

**React Version** ["^16.7.0"]

**node Version**["16.14.2"]

**npm Version**["8.5.0"]

**react-dom Version**["^16.7.0"]

**react-scripts Version**["^2.1.3"]

**MathLive version** ["0.55.0"]

**Operating System** [Ubuntu 18.04]

**Browser** [Chrome Version Version 114.0.5735.106 (Official Build) (64-bit)]

**Comment by arnog** [comment]
You are not importing the MathLive library. Add `import "//unpkg.com/mathlive";`. Also, the current MathLive version is 0.95. Version 0.55 is no longer supported.

**Comment by AbhishekNayak007** [comment]
```
import "//unpkg.com/mathlive";
import React, { useState, useEffect, useRef } from "react";

function App() {
  const [value, setValue] = useState("");

  // Customize the mathfield when it is created
  const mf = useRef();
  useEffect(() => {
    mf.current.mathVirtualKeyboardPolicy = "manual";
    mf.current.addEventListener("focusin", (evt) => mathVirtualKeyboard.show());
    mf.current.addEventListener("focusout", (evt) =>
      mathVirtualKeyboard.hide()
    );
  }, [mf]);

  return (
    <div className="App">
      <math-field ref={mf} onInput={(evt) => setValue(evt.target.value)}>
        {value}
      </math-field>
      <p>Value: {value}</p>
    </div>
  );
}

export default App;
```

Still showing the same problem 

 Line 11:  'mathVirtualKeyboard' is not defined  no-undef
 Line 13:   'mathVirtualKeyboard' is not defined  no-undef

**Comment by AbhishekNayak007** [comment]
**I got the solution**
@arnog Please check this link in the documentation **https://cortexjs.io/mathlive/guides/react/**
there no where mentioned that **mathVirtualKeyboard** is available in the window object so you can add that in documentation and also update the reference code which is present in this link. 

**My Updated Code**
import React, { useState, useEffect, useRef } from "react";
import * as MathLive from "mathlive";

const App = () => {
  const [value, setValue] = useState(null);
  const mf = useRef();

  useEffect(() => {
    mf.current.mathVirtualKeyboardPolicy = "manual";
    mf.current.addEventListener("focusin", (evt) =>
      window.mathVirtualKeyboard.show()
    );
    mf.current.addEventListener("focusout", (evt) =>
      window.mathVirtualKeyboard.hide()
    );
  }, []);

  return (
    <div className="App">
      <h1>MathLive with React</h1>
      <math-field
        style={{ width: "300px", margin: "auto" }}
        ref={mf}
        onInput={(evt) => setValue(evt.target.value)}
      >
        {value}
      </math-field>
      <p>Value: {value}</p>
    </div>
  );
};

export default App;



**It works**
