### ISSUE TITLE
Some Keyboard Keys Shortcut keys are not working 

### ISSUE THREAD

**Issue by AbhishekNayak007** [arnog/mathlive#2073]
**Some buttons Shortcut Keys are not working**
```\opeartorname*{arg~max}_{}``` keyboard shortcut not showing the arg max
```\opeartorname*{arg~min}_{}``` keyboard shortcut not showing the arg max
```\%``` is also not showing percentage symbol in keyboard its showing empty

**How to delete the custom created variable at once**
Means to create a custom variable I need to use latex of \\mathrm{var} but when I am deleting that is not deleting the comple var at once it is deleting it one by one which create a problem 

**Expected Solution**
need the same functionality as like sin when we press backspace at that time sin is deleted completely without wasting time to delete one by one character.

Waiting for reply @arnog

**Comment by rs-mobitech** [comment]
Maybe this is not related to your problem, maybe it's the way it is for the application, but I notice you spelled opeartorname incorrectly.

**Comment by AbhishekNayak007** [comment]
**How to delete the custom created variable at once**
Means to create a custom variable I need to use latex of \\mathrm{var} but when I am deleting that is not deleting the comple var at once it is deleting it one by one which create a problem 

**Expected Solution**
need the same functionality as like sin when we press backspace at that time sin is deleted completely without wasting time to delete one by one character.

**Comment by arnog** [comment]
I can't reproduce this (when using the correct spelling for `\operatorname*{}`).

To prevent the custom variable from being editable, use a macro:
```js
mf.macros = {...mf.macros, var: "\\mathrm{var}"}
```

**Comment by AbhishekNayak007** [comment]
Hey @arnog 
I have used the above code but that is not working

# React Code
```
mathFieldRef.current.macros = {...mathFieldRef.current.macros,speed: "\\mathrm{speed}"};
```

**Comment by arnog** [comment]
It's working for me. Please provide more details. What exactly did you? What happens? Share your code.

**Comment by AbhishekNayak007** [comment]
### Github Link to sample code : https://github.com/AbhishekNayak007/React-Mathlive-Keyboard
**Install node modules then do npm start to run the above repository files**

### Image 1 [Showing the keyboard with a custom variable i.e, speed]
![Screenshot from 2023-08-25 12-32-17](https://github.com/arnog/mathlive/assets/128050690/031a8edc-bf5e-4859-91d1-1281d2910d81)


### Image 2 [when you click on the backspace button it is not deleting the speed at once but deleting it character by character]
![Screenshot from 2023-08-25 12-32-24](https://github.com/arnog/mathlive/assets/128050690/56b28d5f-8309-484e-84b9-adecbc0ac470)




## Expected Result - It must delete speed at once when i click on backspace

**Comment by arnog** [comment]
Right. So you need not only to define the macro, but you also need to use it.
Replace line 27 of `App.js` with: `"\speed"` instead of `"\mathrm{speed}"`

**Comment by AbhishekNayak007** [comment]
## Github Link to sample code : https://github.com/AbhishekNayak007/React-Mathlive-Keyboard

**Its only working for string keys but not working for the keys containing numbers check the screenshot and source code speed and abc is working fine but j1 is a key that is not working why ?** 


![Screenshot from 2023-08-28 14-40-23](https://github.com/arnog/mathlive/assets/128050690/54794763-2c99-4ffe-8a95-ff6db3cce993)

### Expected Solution - J1 key should work in same manner as speed and abc

**Comment by arnog** [comment]
because LaTeX commands cannot contain digits, only letter. Use `\jone` for example instead of `\j1`

**Comment by AbhishekNayak007** [comment]
## Github Link to sample code : https://github.com/AbhishekNayak007/React-Mathlive-Keyboard
***As you said to add macros and to use them so deletion process will work its working great but when I am using that latex to compute engine then this is not working you can check the image and source code there are 2 speed keys out of which one is made using macros and one is made using mathrm where the key which is made using macros that is working for deletion but unable to evaluate and the key that is made using mathrm works well in evaluation but unable to delete the speed at once.***

## Image 1 (when 1st speed keycap with added macros is cliked)
![Screenshot from 2023-09-07 11-43-03](https://github.com/arnog/mathlive/assets/128050690/e7c925ad-5afa-433b-9100-9969e30065b5)

***Latex Expression: \speed***
***Evaluated Value : ["Error",["ErrorCode","'unexpected-command'","'\\speed'"],["Latex","'\\speed'"]]***


## Image 2 (when 2nd speed keycap with mathrm is clicked)
![Screenshot from 2023-09-07 11-43-38](https://github.com/arnog/mathlive/assets/128050690/9f8a4872-f3ba-49f5-8a4b-c9621792569c)

***Latex Expression: \mathrm{speed}***
***Evaluated Value : 10***

## Image 3 (When deleting the 2nd speed keycap with mathrm) 
![Screenshot from 2023-09-07 11-55-12](https://github.com/arnog/mathlive/assets/128050690/2df073e5-c75e-4ff5-87a7-5046219e5174)

***deleting one by one characters but able to evaluate using compute engine***
