### ISSUE TITLE
[FEATURE] Support \mqty, \smashoperator and \bordermatrix

### ISSUE THREAD

**Issue by dkappfire** [arnog/mathlive#2075]
## Description

I want to use \mqty from the physics package or \smashoperator from the mathtools package or \bordermatrix. These commands are not supported in mathLive. How can we add support for these additional commands/packages? 

Also, LatexMath provides "accents" package to add a start over a letter. In mathLive, how can we display a star over a letter like this- 
<img width="146" alt="image" src="https://github.com/arnog/mathlive/assets/140609208/72de29a1-4734-479b-8fc3-28e87690bb60">

https://tex.stackexchange.com/questions/484464/how-to-put-asterisk-over-a-letter

**MathLive version**
0.94.8

**Comment by arnog** [comment]
`\overset{\ast}{\mathbf{M}}`

See for how to define macros: https://cortexjs.io/mathlive/guides/macros/

For more complex commands, this may require implementing them in MathLive directly.

**Comment by dkappfire** [comment]
Hi arnog, 
Thanks for the response. 

In that case could you please add the support for the followings in MathLive: 
- \mqty from the physics package 
- \smashoperator and  \bordermatrix from the mathtools package

Thanks

**Comment by arnog** [comment]
I'm open to reviewing a PR if someone wants to submit one.
