### ISSUE TITLE
Unable to focus on a mathfield div on mobile

### ISSUE THREAD

**Issue by manuelsabu** [arnog/mathlive#208]
**Describe the bug**
If the MathField is set to "onfocus", the keyboard does not show up when the user clicks the related div. The "manual" option works fine to open the keyboard, however it's not possible to move the cursor to a specific position in the equation using touch.

**To Reproduce**
Steps to reproduce the onfocus behavior:
1. Create a mathField with "virtualKeyboardMode": "onfocus"
2. Use mobile Safari or Chrome to click on the mathfield div
3. Keyboard doesn't pop up

Steps to reproduce the lack of focus with the cursor
1. Create a mathField with "virtualKeyboardMode": "manual"
2. Use mobile Safari or Chrome and toggle the virtual keyboard
3. Type something using the keyboard
4. Touch anywhere in the displayed text to attempt to move the cursor
5. Unable to move the cursor using touch

**Expected behavior**
The MathField should maintain focus on mobile devices so that the "onfocus" functionality works, as well as moving the cursor works.

**Environment**
- Device: [iPhone]
- OS: [e.g. iOS 12.2]
 - Version [e.g. Chrome 74, Safari 12.2]

**Comment by leerobert** [comment]
@arnog any ideas on how we can fix an environment specific issue like this? I'd like to help

**Comment by arnog** [comment]
I believe this is fixed now. Let me know if this is still a problem for you.

**Comment by camjosen** [comment]
I can still repro:

Mathlive version: 0.35.1
Device: [iPhone 6s]
OS: [e.g. iOS 12.4.1]
Browser [e.g. chrome, safari]
Version [e.g. Chrome 81, Safari 12.2]

**Comment by arnog** [comment]
To clarify: this is fixed in the master branch. The version on npm (35.1) is lagging behind.
