### ISSUE TITLE
Inline shortcut `int` has conflict with `sint`

### ISSUE THREAD

**Issue by sylee957** [arnog/mathlive#2082]
## Description

It is difficult to enter $\sin t$ because it conflicts with the keyboard shortcut with `int`.

https://cortexjs.io/mathlive/demo/

https://github.com/arnog/mathlive/assets/34944973/9a62401d-42e8-417d-ac6b-6695752e8e27

### Environment

**MathLive version**

**Operating System** 

**Browser** 
Microsoft Edge
Version 115.0.1901.188 (Official build) (64-bit)

**Comment by arnog** [comment]
Note that pressing the spacebar will prevent the shortcuts from taking effect, i.e. `sin t` will correctly be interpreted as `\sin t`
