### ISSUE TITLE
moveToPreviousChar and moveToNextChar traverse macro's argument

### ISSUE THREAD

**Issue by AlexEdgcomb** [arnog/mathlive#2097]
## Description

The commands moveToPreviousChar and moveToNextChar do not traverse a macro's argument, rather the commands jump out of (and over) a macro's argument.

## Steps to Reproduce

1. Go to https://codepen.io/alexedgcomb/pen/eYbOGvw?editors=1010
2. Type `E`, `1`, `←`

### Actual Behavior

Caret is outside the macro and to the left of the `E`

### Expected Behavior

Caret to be inside the macro's argument, between `E` and `1`

### Environment

MathLive version: 0.95.4
macOS: 13.4
Chrome 115, Firefox 116, Safari 16.5

### More repro steps

1. Go to https://codepen.io/alexedgcomb/pen/eYbOGvw?editors=1010
2. Type `E`, `1`, `←`, `→`
Actual: Caret is after the macro's argument
Expected: Caret is inside the argument and after `1`

1. Go to https://codepen.io/alexedgcomb/pen/eYbOGvw?editors=1010
2. Type `E`, `1`, `2`, `←`,
Actual: Caret is outside the macro and to the left of the `E`
Expected: Caret to be inside the argument, between `1` and `2`

**Comment by arnog** [comment]
I think you need to add `captureSelection: false`, i.e. 
```
mf.macros = {
  ...mf.macros,
  eNotation: '\\mathrm{E}{#1}',
  captureSelection: false,
};
```

**Comment by AlexEdgcomb** [comment]
@arnog , you are correct m(_ _)m Changing to
```js
mf.macros = {
  ...mf.macros,
  eNotation: {
    args: 1,
    captureSelection: false,
    def: '\\mathrm{E}{#1}',
  },
};
```

Yields the desired behavior. Ex:
https://codepen.io/alexedgcomb/pen/JjwPvgP?editors=1010
