### ISSUE TITLE
The `user-select` CSS property has no effect on a mathfield

### ISSUE THREAD

**Issue by ikramsaedi** [arnog/mathlive#2102]
## Description

The `math-field` element swallows pointer events because it has `pointer-events:auto` defined on its uppermost `span` child node in its shadowroot. When you want to specify `pointer-events: none` on a parent element, the span element’s `pointer-events` attribute overrides it.

## Steps to Reproduce

1. Create a div that has CSS styling of `pointer-events: none`
2. Render a `math-field` element as a child of that div.
3. Observe that the MathLive content is still selectable and interactive.

### Actual Behavior

The `math-field` element explicitly defines `pointer-events:auto` as an inline style in its uppermost child in its shadow DOM.  This cannot be modified from outside the shadow DOM without hacks.

![image](https://github.com/arnog/mathlive/assets/80010127/8cbb00df-fbe8-461c-8557-9baf23d7eccd)

### Expected Behaviour

I would love to be able have an option to pass through when instantiating a `new MathField()` element that allows for pointer-events to none to be set. Or perhaps exposing this via a `part` attribute.

At the moment, I am working around this by piercing the shadow root of the `math-field` element, iterating through all of its child nodes and changing the `pointer-events` attribute manually. However, this is a hack and could easily break with updates to MathLive.

### Environment

**MathLive version** 0.95.0

**Operating System** Apple M2 Pro, macOS Version 13.4

**Browser** Chrome 115.0.5790.170 (happens across Firefox, Edge, Safari)

**Comment by arnog** [comment]
You can set the `readonly` or `disabled` attribute on a mathfield: `<math-field readonly/>` or `<math-field disabled/>`

**Comment by ikramsaedi** [comment]
Thank you for getting back to me so quickly Arno! Really, really appreciate it! 😁 

Unfortunately, neither of those options work for this use case 😅 . The field is already set to `readonly` (you can see the `read-only` attribute in the screenshot of the `math-field` element in dev tools!) . 

In the below screenshot you can see that the field has the `disabled` attribute but this has no effect on the `pointer-events: auto` inline style set on the child `span` node. It subsequently still receives `pointer-events`, while also greying out the text, which isn't the behaviour I'm looking for. 

<img width="608" alt="image" src="https://github.com/arnog/mathlive/assets/80010127/f68db33d-a417-427f-aa6c-22abfaab919a">
<img width="414" alt="image" src="https://github.com/arnog/mathlive/assets/80010127/46050679-33e2-4837-a8d2-31dc80f581bc">

If possible I'd love an extra config option that is along the lines of `noPointerEvents` to pass through to the `math-field` element.

Thanks again, Arno!

<img src="https://media4.giphy.com/media/osjgQPWRx3cac/giphy.gif"/>

**Comment by arnog** [comment]
Help me understand what you are trying to do. Are you trying to prevent the user from selecting the formula? Do you basically want the `user-select` property to apply to the mathfield?

**Comment by ikramsaedi** [comment]
> Are you trying to prevent the user from selecting the formula?

Exactly that!  The use case is: We are embedding the math-field within a table cell. Every time a user clicks on the table cell, we want them to be able to immediately edit the cell like shown below. 
![Screen Recording 2023-08-28 at 1 28 53 pm](https://github.com/arnog/mathlive/assets/80010127/14c83a9c-3a55-422a-b1f1-9397d2c14ed5)

But this is currently not possible without hacks because the math field keeps stealing the pointer events from the table cell, so the onClick is not propagating through properly. 
![Screen Recording 2023-08-28 at 1 31 51 pm](https://github.com/arnog/mathlive/assets/80010127/7525b7ce-4aee-4580-8415-b975363fd923)

**Comment by arnog** [comment]
OK, thanks, that's helpful. It seems like respecting the `user-select` property would be a better fix, then.

**Comment by ikramsaedi** [comment]
Awesome, thank you so much!

**Comment by lhotejc** [comment]
I add my voice to this issue : I want to make à select-like list with math-field inside, and the read-only math-field take the pointer-event for itself :-( even it's read-only or contentEditable = false.
I try to put à div behind th math-field but it is complex to get the correct width and height of the math-field below...
an option to make all childs have the pointer-events = none will be very usefull !

**Comment by lhotejc** [comment]
> At the moment, I am working around this by piercing the shadow root of the math-field element, iterating through all of its child nodes and changing the pointer-events attribute manually. However, this is a hack and could easily break with updates to MathLive.

@ikramsaedi , I'm intersting in your piece of code to do that, waiting the fix...

**Comment by lhotejc** [comment]
Oh ! I make that and it's running ok :
```
function setPointEventsToNone (htmlString: string) {
  return htmlString.replaceAll('pointer-events:auto', 'pointer-events:none')
}
const shadowRoot = mf.shadowRoot
if (shadowRoot) mf.shadowRoot.innerHTML = setPointEventsToNone(shadowRoot.innerHTML)
```

**Comment by ikramsaedi** [comment]
@lhotejc Glad to see you have a working solution! Rather than manipulating the HTML of the shadow DOM as a string, in my solution, I iterated over the nodes in the shadow DOM like below:

```
    removePointerEvents() {
        const mathfieldShadow = this.mathfield.shadowRoot;
        const shadowChildren = mathfieldShadow?.childNodes;

        if (shadowChildren) {
            shadowChildren.forEach((shadowChild) => {
                const shadowHTMLElement = shadowChild as HTMLElement;

                if (
                    shadowHTMLElement.style.pointerEvents &&
                    shadowHTMLElement.style.pointerEvents !== "none"
                ) {
                    shadowHTMLElement.style.pointerEvents = "none";
                }
            });
        }
    }
```

**Comment by lhotejc** [comment]
Thank you.

Le jeu. 2 nov. 2023 à 23:59, Ikram Saedi ***@***.***> a
écrit :

**Comment by arnog** [comment]
The mathfield will now respect the CSS property `user-select`. Set it to `none` to prevent any selection in the mathfield.

**Comment by AllyMarthaJ** [comment]
Hiya - I'm wondering how this fix works and how we can go about making effective use of it.

AFAICT, the element's computed style is only meaningful when attached to the DOM; that is to say that the user select property can't actually be set at instantiation. Am I missing something?

**Comment by arnog** [comment]
@AllyMarthaJ please share the code you tried to use and the result you got.

**Comment by AllyMarthaJ** [comment]
Ah, I'm instantiating the mathfield directly to inject it elsewhere later;

```js
const mf = new MathfieldElement();

mf.style.userSelect = "none"; // too late
```

**Comment by arnog** [comment]
I suspect there is some other setup that is not included in the code you shared, as I don’t understand where the `class=“ml-static”` is coming from.

That said, I see a content-editable attribute set to true. That conflicts with user-select=none. I would try to see where it’s coming from and remove it.

Also, since you use the ml-static class, why don’t you set the user-select attribute in the definition for that rule?

**Comment by AllyMarthaJ** [comment]
Apologies... yeah. That's more or less just some options I've got set up.

`ml-static` is a styling class I added after this code, sorry; it's largely superficial and changes the display to inline flex for compatibility with the ProseMirror editor it's nested in (hence the content editable field).

Having played around with contenteditable as well, I agree I should disable it, though it doesn't seem to change the behaviour in the way I expect it to (at least with user-select: none) - I understand this will change across browsers.

`pointer-events:auto` still appears regardless, though.

**Comment by arnog** [comment]
OK, I was able to create a test case that replicates the problem. I have checked-in a fix for it. I can't be sure it will fix your issue, since I don't have the code you're using.

Setting the `user-select` attribute in your `ml-static` class is still the simplest and cleanest way to do this, though.
