### ISSUE TITLE
When the cursor is position at the top limit number of a sum and I press delete, it takes about 5 seconds before the delete happens

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2106]
Here is an example from the demo

<img width="301" alt="Screenshot 2023-08-24 at 13 07 18" src="https://github.com/arnog/mathlive/assets/39233783/b178396b-8b61-47da-bcd0-98f1e747a176">

When the cursor is positioned to the right of the 5 and the virtual keyboard delete key is pressed, it takes about 5 seconds before the 5 is deleted.

I noticed the same long delay on both the chrome and safari browsers.

**Comment by arnog** [comment]
This is because when no upper limit is provided, the compute engine assumes the upper limit is +Infinity. It currently takes a while to calculate that sum. I have a fix pending for it in the compute engine, though.

**Comment by rs-mobitech** [comment]
Thanks for the quick reply.  Hope all goes well with the fix.

**Comment by arnog** [comment]
The performance has been improved.
