### ISSUE TITLE
It seems not possible to enter a simple integral using the virtual keyboard

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2111]
This is what I would like to try and enter:

<img width="278" alt="Screenshot 2023-08-26 at 14 33 21" src="https://github.com/arnog/mathlive/assets/39233783/8436d6a2-ae2a-41f0-ade3-de2691e4230b">

But so far the closest I have been able to enter is this:

<img width="338" alt="Screenshot 2023-08-26 at 14 36 31" src="https://github.com/arnog/mathlive/assets/39233783/d52153ab-5093-4e16-a6e8-0282b7068426">

I am not at all sure how to enter the remaining part

`", dx"`

Can you let me know if this is something missing with the keyboard, or if I am doing something wrong.

**Comment by arnog** [comment]
You can enter "dx" using the "abc" (alphabetic keyboard) by pressing the "d" keycap followed by the "x" keycap.

**Comment by rs-mobitech** [comment]
I will try again. I thought when I tried that the latex didn’t look correct. Also, can the compute engine compute values for numerics?

**Comment by arnog** [comment]
The "d" is part of the notation in LaTeX to indicate the variable the integral is relative to. It does not need to be included in the MathJSON.

The Compute Engine currently does not evaluate integral. There is an issue tracking this here: https://github.com/cortex-js/compute-engine/issues/79

At some point someone had volunteered to provide an implementation for this, but it seems it was never delivered.

**Comment by rs-mobitech** [comment]
Do you feel adding that capability might be a feature that you add before year end, or do you have other more important features you are considering working on for MathLive or CortexJS?

**Comment by rs-mobitech** [comment]
I spent some more time on this, and I still find it impossible to enter the correct Latex, which from my research is:

     \int \sin(x) \, dx
     
here are some of my attempts at entering what's needed

<img width="786" alt="Screenshot 2023-08-29 at 18 32 49" src="https://github.com/arnog/mathlive/assets/39233783/0d580353-9f49-4ae8-9f85-745049831afb">
<img width="782" alt="Screenshot 2023-08-29 at 18 22 08" src="https://github.com/arnog/mathlive/assets/39233783/c9b6a87a-cddc-46c8-ad67-c4201ddc8fb8">
<img width="788" alt="Screenshot 2023-08-29 at 18 22 28" src="https://github.com/arnog/mathlive/assets/39233783/34b1cb51-4fe2-4124-bc1a-9f106e37ae9b">
<img width="626" alt="Screenshot 2023-08-29 at 18 27 54" src="https://github.com/arnog/mathlive/assets/39233783/e61d6bb8-8416-47e7-bd65-79e1842f7cc5">

Can you please give some advice on how I can enter the correct latex using the virtual keyboard:  \int \sin(x) \, dx

Thanks

**Comment by arnog** [comment]
There is no comma before the `dx`

**Comment by rs-mobitech** [comment]
I am sorry, I don't understand.  Are you saying it's not normal convention to have a comma before the dx.  If that is what you are saying then when I look at your documentation all the integrals use a comma.  Also my research on the web that I looked at also said there should be a comma.

https://cortexjs.io/compute-engine/reference/calculus/

Can you enter an example into the mathfield, take a screen print to show the mathJSON, so I will understand what to do. 

Thanks

**Comment by arnog** [comment]
> Are you saying it's not normal convention to have a comma before the dx

Yes, that is what I am saying.

> when I look at your documentation all the integrals use a comma

Good catch. There was a bug in the documentation software that did not render the formula correctly. The comma should have been a horizontal space.

> Also my research on the web that I looked at also said there should be a comma.

Interesting. Could you please provide some references? If that is indeed the case, I'd be happy to add support for this convention, but I haven't seen it before.

<img width="810" alt="Screenshot 2023-08-29 at 10 32 19" src="https://github.com/arnog/mathlive/assets/760798/8cb85410-48b9-4767-a1e7-ee8ae00c0d27">

**Comment by rs-mobitech** [comment]
Thanks!  Yes you are correct, I was confusing a comma , with the command `\,`. 

- I realize now that it's not needed, but is there a way to enter the spacing command with the virtual keyboard?
- Also do you think it would be a good idea to add dx to the virtual keyboard,  I see you already have a number of similar keycaps that can be added.

<img width="388" alt="Screenshot 2023-08-30 at 14 18 03" src="https://github.com/arnog/mathlive/assets/39233783/91309891-b9d9-43c0-b567-9bcfb588f6e8">

**Comment by rs-mobitech** [comment]
I tried again to enter the integral, and I had a work colleague try to do this also.  Neither of us were able to do it correctly, (perhaps because we don't know where the space key is), so I think it's reasonable to assume that others would not be able to do it also.  Can you explain the keypresses that you use to enter, we both must be doing something wrong.  Also is there any way it could be made more easy to enter, as I believe this may be difficult for others also.  Thanks

**Comment by rs-mobitech** [comment]
@arnog - Were some changes made to the way integrals are input.  When I enter the integral sign, I now see this:

<img width="755" alt="Screenshot 2023-09-01 at 21 05 05" src="https://github.com/arnog/mathlive/assets/39233783/29525acc-6625-4c64-86de-4e6d66345682">

and when I enter sin(x)

<img width="759" alt="Screenshot 2023-09-01 at 21 05 28" src="https://github.com/arnog/mathlive/assets/39233783/9f6deb15-ca68-4954-badf-f7fe0de8f514">

and then when I add in an x

<img width="761" alt="Screenshot 2023-09-01 at 21 05 53" src="https://github.com/arnog/mathlive/assets/39233783/b8757465-31a1-4907-bda1-34eb2b61433f">

I'm not sure if this is correct, so perhaps you can advise:

     ["Integrate",["Sin","x"],"Nothing"]
     
When I try to add an x after that, it assumes a multiplication

["Integrate",["Multiply","x",["Sin","x"]],"Nothing"]

Also I see your code adds in a "dx", but what if I had wanted to show an integral with respect to dy or dz.  I was thinking that adding in a dx, would be something that could be done by tapping keys and not added automatically.

**Comment by rs-mobitech** [comment]
Hello, apologies for any confusion.  

What I would like to be able to do is to use the virtual keyboard to create this latex.

      \int \sin(x) dx

which results in this, which shows "nothing", in the place where I would expect to see "x"

> <img width="243" alt="Screenshot 2023-09-02 at 13 44 45" src="https://github.com/arnog/mathlive/assets/39233783/a75bd2f7-34ad-4e72-8cd5-3d8de307b69f">

I have tried many combinations, but I still cannot do this with the virtual keyboard.

The most close I can get now is this

> <img width="758" alt="Screenshot 2023-09-02 at 13 51 19" src="https://github.com/arnog/mathlive/assets/39233783/dcbb1e4e-feb9-4704-97d3-1eb2481f2d1d">

**Comment by arnog** [comment]
You can enter "dx" using the "abc" (alphabetic keyboard) by pressing the "d" keycap followed by the "x" keycap.

**Comment by rs-mobitech** [comment]
I don’t have my computer with me right now, but I believe when I did that it didn’t create a clean mathJSON. Can you show me the keypresses you do to achieve the correct json, and I wil try those. Thanks

**Comment by arnog** [comment]
I am unable to reproduce this problem. If you still have difficulties, please file a new issue, and provide a step by step explanation of what you are doing, what happens and what you were expecting instead.
