### ISSUE TITLE
Mathlive selection does not display properly on an iOS phone in dark mode.

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2112]
It's not possible to see the content selected.  See the image below:

![D69A4C74-07B3-4B74-AE6D-0C22AB29A234](https://github.com/arnog/mathlive/assets/39233783/745ef4bc-b340-46d0-94d1-be5c2d449613)

**Comment by arnog** [comment]
Not an issue with MathLive, but fixed in cortexjs.io
