### ISSUE TITLE
Representation of fractions such as 1/2: \frac12 vs \frac{1}{2}

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2114]
Is there a way that I can  enable single digit fractions such as 1/2 to be display as:

 `\frac{1}{2}`
 
  instead of the shorthand 
  
` \frac12`

Note that I tried the following, which I found mentioned in the documentation, but it didn't seem to work:

     MathfieldElement.computeEngine.latexSyntax.options.fractionStyle = () => 'quotient';

**Comment by arnog** [comment]
ChatGPT is correct: both are valid ways to typeset a fraction.

Which package are you having trouble with? A solution might be to fix the package that doesn't handle LaTeX correctly.

The setting you describe affects the serialization of expressions from the compute engine, not the serialization from MathLive. You might be able to use `mf.expression.latex` to get what you want, though.

**Comment by rs-mobitech** [comment]
Thanks for your advice.  The package I that was not accepting the short form of the fractions was Nerdamer, and I did already file an issue with them:

https://github.com/together-science/nerdamer-prime/issues/32

I also tried a solution of my own which is to do this to the latex.  I hope this solution covers all possibilities, but I am not sure if it does.

     mathLatex = mathLatex.replace(/\\frac(\d+)(\d+)/g, '\\frac{$1}{$2}');

Can you tell me where I can look in the MathLive documentation to learn about mf.expression.latex?

**Comment by arnog** [comment]
Actually, you want `mathLatex = mathLatex.replace(/\\frac(\d)(\d)/g, '\\frac{$1}{$2}');`
Note that this also applies to `\sqrt`.

> When you say about using mf.expression.latex, do you mean using that, and then changing it with a replace, like I did with getValue('latex') ?

No. If you use `mf.expression.latex` with the compute engine configuration above you should get braces around all numerators and denominators. Give it a try.

**Comment by rs-mobitech** [comment]
Thanks for the correction to replace.  Just to confirm. Is the first line:

     let mathLatex = mf1.getValue('latex')

okay, as the way to get the latex, or is it different if I use 

    let mathLatex = mf.expression.latex

**Comment by arnog** [comment]
You can use either:

```js
 let mathLatex = mf1.value;
 mathLatex = mathLatex.replace(/\\frac(\d)(\d)/g, '\\frac{$1}{$2}');
```

or

```js
MathfieldElement.computeEngine.latexSyntax.options.fractionStyle = () => 'quotient';
let mathLatex = mf1.expression.latex
```
