### ISSUE TITLE
Inline shortcuts not working with custom virtual keyboards

### ISSUE THREAD

**Issue by eliaspanagiotidis** [arnog/mathlive#2115]
### Description

I have created some inline shortcuts that work perfect when using the physical keyboard. However, the same key combinations do not work on my custom virtual keyboard. I also noticed that shortcuts containing other symbols than letters do not work even on the integrated alphabetic keyboard.

I use math-field in a vue-3 component and apart from the problem described above it works great.

Here is a simplified code snippet that describes the way that inline shortcuts and virtual keyboards are defined:

```
mounted () {
    this.update()
    const mf = this.$refs.mathField
    mf.inlineShortcuts = {
      '--': '\\_',
      ...mf.inlineShortcuts
    }
    // eslint-disable-next-line no-undef
    mathVirtualKeyboard.layouts = [
      'alphabetic',
      {
        label: 'Test Keyboard',
        rows: [
          { latex: '-' }
        ]
      },
```
When I press two consecutive dashes on the physical keyboard I get an underscore character, when I click two dashes on the virtual keyboard I simply get two dashes.

Is this problem related to the difficulty of handling keyboard shortcuts described in the documentation? If yes, is there any workaround?

Thanks,
Elias

### Environment

**MathLive version** 0.95.1

**Operating System** Windows 10

**Browser** Chrome

**Comment by arnog** [comment]
In this case you want to use `{key: '-'}` instead of `{latex: '-'}`: when using the`latex` property to define the keycap, the specified LaTeX is inserted, bypassing the keyboard shortcut recognition. When using the `key` property, the physical keyboard key is simulated, triggering the keyboard shortcut.

**Comment by arnog** [comment]
The documentation has been updated.
