### ISSUE TITLE
How can I enter 2^3/4*5 using the virtual keyboard

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2116]
I was testing out some capabilities and had a problem entering 2 to the power 3 divided by 4 times 5.  Can you please try it out and see if you encounter the same difficulties.

**Comment by arnog** [comment]
Nope, no difficult for me.

**Comment by rs-mobitech** [comment]
Here are images that show what I was doing:

2^3 then tap the divide gives me this as expected

<img width="387" alt="Screenshot 2023-08-29 at 13 33 15" src="https://github.com/arnog/mathlive/assets/39233783/416ea4de-5bea-430b-8b85-08346182771a">

2^3 then tap the ">", then tap divide sets me up for entering a fraction

<img width="252" alt="Screenshot 2023-08-29 at 13 33 32" src="https://github.com/arnog/mathlive/assets/39233783/d4643c14-d85a-4337-bc96-b28992a6030e">

This is the only way I was able to do it:

<img width="196" alt="Screenshot 2023-08-29 at 13 34 06" src="https://github.com/arnog/mathlive/assets/39233783/97b159e2-1da0-4ff9-af5c-4e70669acffc">

Were you able to enter 2^3 divided by 4 times 5, without using parenthesis?

**Comment by rs-mobitech** [comment]
Hello, I tried entering the < and then << and it seemed to work.  Thanks

I noticed one thing however.   The superscript is no longer next to the number 2.  Is there anything that could be done to fix this?

<img width="83" alt="Screenshot 2023-08-30 at 1 23 36" src="https://github.com/arnog/mathlive/assets/39233783/061948fc-836b-4d44-bd03-68badebf154c">

**Comment by arnog** [comment]
Yes, you should make sure to select both the "2" and the "3" before pressing the "/" key.
