### ISSUE TITLE
Using simplify I observed some unusual simplifications

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2117]
Is there any way the code for simplify could be made to correctly simplify something like this

<img width="104" alt="Screenshot 2023-08-29 at 14 56 15" src="https://github.com/arnog/mathlive/assets/39233783/690a3f6f-5ca4-47eb-b4c6-cba148bdc232">

Here's the result of simplify:

<img width="41" alt="Screenshot 2023-08-29 at 14 57 50" src="https://github.com/arnog/mathlive/assets/39233783/99dab6a5-c306-4ea2-b371-2f490ad14dd7">

**Comment by arnog** [comment]
This has been fixed in Compute Engine 0.12.4
