### ISSUE TITLE
Entering x to the power 3, then deleting the 3 and clicking the >, still leave the placeholder for power

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2118]
- I entered:

<img width="257" alt="Screenshot 2023-08-29 at 18 49 02" src="https://github.com/arnog/mathlive/assets/39233783/1ba7ab5a-ca24-421c-a9c7-cf7bf3ec9992">

- tapped the delete key and at this time, although you can't see on the screen print, the cursor is still located above the x

<img width="444" alt="Screenshot 2023-08-29 at 18 49 44" src="https://github.com/arnog/mathlive/assets/39233783/ae705d97-d34d-418b-aebb-381079039a41">

- So at this point the only way I can get the cursor to move down is by pressing the > arrow key.  The result is this:

<img width="68" alt="Screenshot 2023-08-29 at 18 57 30" src="https://github.com/arnog/mathlive/assets/39233783/8fb5d7af-cb86-49d4-b2c9-25b5c6fddcb2">

I tried different combinations of pressing delete, < and >, but I cannot remove the ^{}, once it's been entered.

**Comment by arnog** [comment]
To remove the superscript, do the following:
- Type "x^3"
- Type `Backspace` `Backspace` `Backspace`

The result is now `x`.

The first `Backspace` moves to the superscript, the second one remove the "3" and the third one removes the empty superscript.
