### ISSUE TITLE
When there is a division, there is a gap between a number and it's superscript 

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2119]
This is difficult to explain, but I think you can follow what I mean with the image below:

<img width="83" alt="Screenshot 2023-08-30 at 1 23 36" src="https://github.com/arnog/mathlive/assets/39233783/2e221c5c-c600-4911-8990-37949d6700ac">

As the expression at the bottom of the fraction gets longer,  the superscript on top moves further and further away from the number.  In this case the 3 is far from the 2

**Comment by arnog** [comment]
The expression above is `((2)/(4x8))^3 x 8`, so the position of the superscript is correct: it applies to the entire fraction. 

If you want the superscript to only apply to the numerator, the LaTeX expression would be `\frac{2^3}{x\times8}\times 8`
