### ISSUE TITLE
Special characters in text mode are treated similarly to math mode

### ISSUE THREAD

**Issue by eliaspanagiotidis** [arnog/mathlive#2124]
## Description

Many thanks for this great library!

However, it seems that the text mode behaves somewhat different than other libraries (different standard?). For instance take a look to the following example (snapshot from https://cortexjs.io/mathlive/editor/): 
![image](https://github.com/arnog/mathlive/assets/37274701/6ec5a5b3-b6de-4d81-875e-27702d2e9e23)

My application transfers the resulting latex to docx documents to form MS Word editable equations, but neither Word nor any other tool I've tried correctly interprets escaped characters when in \text{} (the example below uses https://latexeditor.lagrida.com/ online editor):
![image](https://github.com/arnog/mathlive/assets/37274701/885fc3c6-afc4-4752-b2bf-af269781457e)

Is this the expected behavior?

Thanks in advance,
Elias

**Comment by arnog** [comment]
Fair enough, there are a couple of commands that should not be used in text mode, i.e. `\lparen` and `\rparen`.

The `\textasciicircum` is a standard command and should be supported.
The characters `#`, `$`, `%` and `&` must be escaped. Compliant implementation of LaTeX will produce errors if they are not escaped (see https://www.latex4technics.com/)
