### ISSUE TITLE
Confused over what happens when "/" is entered in a mathfield

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2126]
Your documentation states:

<img width="1206" alt="Screenshot 2023-09-02 at 16 38 05" src="https://github.com/arnog/mathlive/assets/39233783/c9f58685-f607-490f-bc69-8a40a49a4a1f">

But when I enter the "/", then it brings up the fraction like this

<img width="57" alt="Screenshot 2023-09-02 at 16 40 51" src="https://github.com/arnog/mathlive/assets/39233783/e46dabf6-bc26-44ce-bec6-a1fca6a81933">

Did you mean to say the "\\" key ?

**Comment by arnog** [comment]
Yes
