### ISSUE TITLE
sounds - when MathLive is not being used on a computer

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2127]
**0.95.5 and 0.95.4 release**

I notice that when there are errors, then it will look for the sounds folder and try to play sounds.  But for my, and possibly the situation of others, it may not desirable.  Is it possible to configure MathLive, not to try and play sounds?  

Here's a screen print showing what happens when the sounds folder is not present. 

<img width="1136" alt="Screenshot 2023-09-04 at 15 08 19" src="https://github.com/arnog/mathlive/assets/39233783/2722feb3-612d-4dfe-bd82-d58cb91f0261">

**Comment by arnog** [comment]
Yes, `MathfieldElement.soundsDirectory = null`
