### ISSUE TITLE
MathLive - virtual keyboard disappearing after every key press

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2128]
**0.95.5 release**

I asked a work colleague to help and provided him with a link to the other Cortex Demo page. However here's what he gets on multiple browsers when he opens it.  What he sees is that when a key on the virtual keyboard is pressed, then after that the keyboard is removed from view.  Here is a video that shows what happens. The same is happening on his Edge and Safari browsers on Mac OS. 

Note that the console on Google Chrome is empty and shows no sign of errors.

https://github.com/arnog/mathlive/assets/39233783/0953db4c-46d5-4b4c-9229-25dd61c844da

I then checked my own code **with 0.95.5 release** and I cannot open the virtual keyboard.  Here is what happens when I click to open it:

<img width="1327" alt="Screenshot 2023-09-04 at 17 29 05" src="https://github.com/arnog/mathlive/assets/39233783/3ce8dab1-e814-40b2-8b1b-73bb95218945">

Here is the index.html that I am using:

```
<!DOCTYPE html>
<html>
<head>
   <script type="module" src="mathlive.mjs"></script>
   <script type="module" src="cortex.mjs"></script>
   <style>
       .mf {
           width: 390px;
           display: inline-block;
           vertical-align: top;
       }
    
       .flex-container {
           display: flex;
       }
   </style>

</head>
<body>
    <div class="flex-container">
        <div class="heading">MathLive input</div><math-field class="mf" id="mf" ></math-field>
    </div>
        
  </body>
</html>
```

The Javascript I am using is a copy / paste from here:

     https://unpkg.com/mathlive@0.95.5/dist/mathlive.min.js

I asked him to test out this HTML and he also sees the same problem that I am seeing in the developer tools window of Google Chrome. 

**0.95.4 release**

My example above is working okay with no problems.  The virtual keyboard opens okay

**Comment by arnog** [comment]
I am unable to reproduce.
If you replace the `<script>` lines with `<script defer src="//unpkg.com/mathlive"></script>`, does it still happen?
