### ISSUE TITLE
Feature Template

### ISSUE THREAD

**Issue by rs-mobitech** [arnog/mathlive#2131]
Copied the feature template from the compute engine:

**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Add a Feature template

**Describe alternatives you've considered**
Had to copy from compute engine

**Additional context**
I assume it's needed here as I see many feature requests coming up

**Comment by arnog** [comment]
If someone is interested in this, I'd be happy to review a PR.
