### ISSUE TITLE
Infinite loop / Maximum call stack size exceeded with sandboxed when in an iframe from different origin

### ISSUE THREAD

**Issue by DegrangeM** [arnog/mathlive#2135]
DEMO OF THE BUG : https://degrangem.github.io/mathlivebug/

### Steps to Reproduce

1. Put mathlive with the sandboxed mode
2. Iframe the above page from a different origin
3. Open the keyboard and press a key

### Actual Behavior

There will be a freeze, a huge repetiting sound, and your number will be pasted a lots of time.

(and also your browser will request a lots of time the sound file so don't try too many time as you will DDOS github (and might get banned ?))

Error in console
```
Uncaught RangeError: Maximum call stack size exceeded.
    at t.sendMessage (mathlive:2265:21073)
    at t.executeCommand (mathlive:2265:22747)
    at t.handleMessage (mathlive:2265:20113)
    at t.handleEvent (mathlive:2265:19566)
    at t.sendMessage (mathlive:2265:21073)
    at t.executeCommand (mathlive:2265:22747)
    at t.handleMessage (mathlive:2265:20113)
    at t.handleEvent (mathlive:2265:19566)
    at t.sendMessage (mathlive:2265:21073)
    at t.executeCommand (mathlive:2265:22747)
```

### Expected Behavior

It should write your number normally

### Environment

**MathLive version**  '0.95.5'

**Operating System** Windows 10

**Browser** Chrome : Version 116.0.5845.142 (Build officiel) (64 bits)

**Comment by arnog** [comment]
I have checked in a potential fix but I haven't been able to test it. Your demo project was useful in tracking down the project, but I don't have a setup where I can reproduce it. Please give it a try with the next published version of MathLive and let me know how that goes.

**Comment by arnog** [comment]
I believe a PR related to this has been merged. Please reopen if you still have this issue.
