### ISSUE TITLE
The virtual keyboard layout is broken on Safari MacOS

### ISSUE THREAD

**Issue by phillipngn** [arnog/mathlive#2136]
## Description
Virtual keyboard layout is broken on safari (macOS). Do you know which is the minimum macos version / safari version that support the version of mathlive 0.95.5?
<img width="1028" alt="Screen Shot 2023-09-13 at 15 45 08" src="https://github.com/arnog/mathlive/assets/114401625/98a489b7-38a8-4b99-9476-edb336a7f45a">

### Environment

**MathLive version**  0.95.5

**Operating System** MacOS Monterey 12.6.1

**Browser** Safari 15.6.1

**Comment by arnog** [comment]
Safari 16.

In general, I try to support older version of OS (although using older versions of OS is bad practice from a security standpoint, I do understand that it may be difficult in some education environment to keep devices up to date).

However, when some new features or capabilities are introduced that are not supported in older versions, I will attempt to implement a workaround, if it is simple. If it requires too much work, unless someone is willing to sponsor the work, I'm not likely to spend time on it. 

In this particular case, iOS 16/Safari 16 introduced support for CSS container queries, which are used to do responsive layout of the virtual keyboard, i.e. so you can display a virtual keyboard for example in an iframe without the keyboard taking the whole width of the screen.

An attempt was made to introduce a simple workaround, but it ended up breaking other things, so I had to back it out. I have an idea on how a workaround could be implemented, but it's a substantial amount of work, and I suspect the number of users relying on OS pre-iOS 16/Safari 16 will diminish over time.

**Comment by phillipngn** [comment]
@arnog Appreciate your detailed explanation. Would you mind sharing the idea how your workaround could be implemented and then I can try my own?
