### ISSUE TITLE
mapsfrom operation missing

### ISSUE THREAD

**Issue by arjunexalture** [arnog/mathlive#2141]
![mapsfrom](https://github.com/arnog/mathlive/assets/94816933/554aa740-34af-4a02-8dd3-fa13b9febd14)
@arnog Is there a way for showing mapsfrom operation in mathLive?

**Comment by arnog** [comment]
which LaTeX command would that be?

**Comment by arjunexalture** [comment]
@arnog The following packages have it as follows
MnSymbol provides \leftmapsto
stmaryrd provides \mapsfrom

**Comment by arnog** [comment]
Fixed in 9750d160a05a829b092486d8f4a18cc7847e8dd4
