### ISSUE TITLE
ERROR - Deleting custom keys is not working 

### ISSUE THREAD

**Issue by AbhishekNayak007** [arnog/mathlive#2142]
## Github Link to sample code : https://github.com/AbhishekNayak007/React-Mathlive-Keyboard
***As you said to add macros and to use them so deletion process will work its working great but when I am using that latex to compute engine then this is not working you can check the image and source code there are 2 speed keys out of which one is made using macros and one is made using mathrm where the key which is made using macros that is working for deletion but unable to evaluate and the key that is made using mathrm works well in evaluation but unable to delete the speed at once.***

## Image 1 (when 1st speed keycap with added macros is cliked)
![Screenshot from 2023-09-07 11-43-03](https://github.com/arnog/mathlive/assets/128050690/e7c925ad-5afa-433b-9100-9969e30065b5)

***Latex Expression: \speed***
***Evaluated Value : ["Error",["ErrorCode","'unexpected-command'","'\\speed'"],["Latex","'\\speed'"]]***

## Image 2 (when 2nd speed keycap with mathrm is clicked)
![Screenshot from 2023-09-07 11-43-38](https://github.com/arnog/mathlive/assets/128050690/9f8a4872-f3ba-49f5-8a4b-c9621792569c)

***Latex Expression: \mathrm{speed}***
***Evaluated Value : 10***

## Image 3 (When deleting the 2nd speed keycap with mathrm) 
![Screenshot from 2023-09-07 11-55-12](https://github.com/arnog/mathlive/assets/128050690/2df073e5-c75e-4ff5-87a7-5046219e5174)

***deleting one by one characters but able to evaluate using compute engine***

**Comment by arnog** [comment]
Could you try to rewrite this report following the provided issue template?

**Comment by AbhishekNayak007** [comment]
## Description
As you said to add macros and to use them so deletion process will work its working great but when I am using that latex to compute engine then this is not working you can check the image and source code there are 2 speed keys out of which one is made using macros and one is made using mathrm where the key which is made using macros that is working for deletion but unable to evaluate and the key that is made using mathrm works well in evaluation but unable to delete the speed at once.

### Steps to Reproduce

## CASE 1 (when 1st speed keycap with added macros is cliked)
![Screenshot from 2023-09-07 11-43-03](https://github.com/arnog/mathlive/assets/128050690/e7c925ad-5afa-433b-9100-9969e30065b5)

***Latex Expression: \speed***
***Evaluated Value : ["Error",["ErrorCode","'unexpected-command'","'\\speed'"],["Latex","'\\speed'"]]***


## CASE 2 (when 2nd speed keycap with mathrm is clicked)
![Screenshot from 2023-09-07 11-43-38](https://github.com/arnog/mathlive/assets/128050690/9f8a4872-f3ba-49f5-8a4b-c9621792569c)

***Latex Expression: \mathrm{speed}***
***Evaluated Value : 10***

## CASE 3 (When deleting the 2nd speed keycap with mathrm) 
![Screenshot from 2023-09-07 11-55-12](https://github.com/arnog/mathlive/assets/128050690/2df073e5-c75e-4ff5-87a7-5046219e5174)

***deleting one by one characters but able to evaluate using compute engine***

### Actual Behavior

***In case 1 when I have added macros for custom variable then when i press backspace then it delete the complete word but when used that latex for evaluation in computing engine it is giving me a error. [screenshot in Case 1].***

***In case 2 when I have used mathrm  for creating a keycap then when I am using that latex in computing engine then it can easily evaluate the latex. [screenshot in Case 2].***

***In Case 3 when i press backspace then it deletes one by one characters but when i used the latex for evaluation then it gives correct answer. this keycap is made using mathrm not macros [screenshot in Case 3].***


### Expected Behavior
***I need that deletion must be done at once when i click on backspace and computing should also work with the method may be mathrm or macros for creating a custom variable***

### Environment

**MathLive version**  latest

**Operating System** Ubuntu 18

**Browser** Chrome
