### ISSUE TITLE
I can't create inlineShortcuts for the left bracket "["

### ISSUE THREAD

**Issue by Deseux** [arnog/mathlive#2144]
With inlineShortcuts, I succeed to make all shortcuts I want except for one. I can't replace the left bracket "[" by something. It's always the default value "[  ]". If it's possible, how can I do ?

The reason is for french mathematical interval like [5;6[. I want left bracket mais I don't want classical left bracket.

Firefox 117.0.1 on Ubuntu 20.04 LTS

**Comment by arnog** [comment]
Can you provide the code you used?

**Comment by Deseux** [comment]
mf.inlineShortcuts = {'[': { mode: 'math', value: '$toto$' }}

**Comment by arnog** [comment]
Are you using an AZERTY keyboard layout?

**Comment by Deseux** [comment]
Yes, I am. [ is AltGr+5 on my keyboard

**Comment by arnog** [comment]
The issue was that you had `smartFence` on. When `smartFence` was on, it took priority over the inline shortcuts. The priority has now been changed so that inline shortcuts are considered before smartFence.
