### ISSUE TITLE
Missing Vue Export

### ISSUE THREAD

**Issue by brtinney** [arnog/mathlive#2145]
## Description

Similar to the solution to other export issues (e.g., #1913), can we get `vue-mathlive.mjs` named in `exports` in `package.json`?

### Steps to Reproduce

`import MathfieldComponent from 'mathlive/dist/vue-mathlive.mjs'`

### Actual Behavior

`[plugin:vite:import-analysis] Missing "./dist/vue-mathlive.mjs" specifier in "mathlive" package`

### Expected Behavior

The Vue component is actually able to be imported. (The contents can be copied into a separate file and imported and it works, but this obviously defeats the purpose of a package.)

### Environment

We continue to be stuck on 0.87.1 until this is resolved. It has been a regression for a while, but I finally put in the time to track down the exact errors and test different versions.

**MathLive version**  Any > 0.87.1, tested with at least a half-dozen.

**Operating System** Linux

**Browser** Chrome

**Comment by arnog** [comment]
Could you submit a PR with the exact change that you're looking for? As may be obvious, I'm not a Vue expert. I'm actually surprised you find the `vue-mathlive` wrapper useful: it was more intended as a sample code than something you would use in production. Feel free to make suggestions to improve it as well...

**Comment by brtinney** [comment]
Done (#2151)! I don't have any particular suggestions for it. It works well enough for our project. We're using it within a Tiptap editor to provide math support in a Nuxt project, and it seems to hold up well enough.
