### ISSUE TITLE
Inserting fraction deletes numerator

### ISSUE THREAD

**Issue by JMSS-Unknown** [arnog/mathlive#215]
**Describe the bug**
Inserting fraction deletes numerator making it impossible to insert `sin(x)/2`. It seems to be related to the brackets as (sin x)/2 works. Probably related to #189.

**To Reproduce**
On the math live playground type `sin(x)`, make sure to include the brackets, then press `/`. Only a forward slash will remain.

**Expected behavior**
That the `sin(x)` will be the numerator of the fraction, displaying `sin(x)/...`

**Environment**
Tried with both Firefox and Chrome on Windows 10.

**Comment by saivan** [comment]
that seems to be a side-effect of #189 for sure. I can confirm I get the same behaviour

**Comment by arnog** [comment]
I've lost track of when this got fixed, but it seems to be working correctly now in MASTER.
