### ISSUE TITLE
display static math

### ISSUE THREAD

**Issue by physedo** [arnog/mathlive#2154]
can't display this in static mathfield

 ` \​begin{gather}          

    3(a-x) = 3.5x + a - 1 \\
    3a - 3x = 3.5x + a - 1 \\
    a = \frac{13}{4}x - \frac{1}{2}

  \end{gather}`

version:  "mathlive": "^0.95.5",

**Comment by arnog** [comment]
Works for me.

**Comment by physedo** [comment]
it works now @arnog
