### ISSUE TITLE
[FEATURE] Enhanced support for entering environments, such as matrices, arrays, etc.

### ISSUE THREAD

**Issue by tumidi** [arnog/mathlive#2156]
## Is your feature request related to a problem? Please describe.

- Currently, it is easy to miss the hover menu for modifying columns/rows in environments, as it only appears when the virtual keyboard is active.
- Entering matrices can be somewhat cumbersome or hidden for new users, as it requires a special sequence of keystrokes and is not present on the virtual keyboard by default.

## Describe the solution you'd like

We propose general improvements to the user experience (UX) for environment input, and we welcome discussion on the following suggestions:
- Show the tooltip menu for modifying environments independent of the virtual keyboard's visibility.
- Provide presets on the virtual keyboard for different environments (e.g., matrices, arrays).
- Introduce a small button or indicator that creates the environment and activates the hover menu when, for example, an opening square bracket is typed. This would hint to the user that the input can be extended to a full environment. Currently, users need to press <kbd>Ctrl</kbd> + <kbd>Enter</kbd> to jump to the next row, effectively creating the environment. While this works well, it might not be immediately clear to some users.
- Create small animations in the documentation to illustrate the correct sequence of keyboard shortcuts for adding a matrix or other environments.

## Describe alternatives you've considered

- Provide better descriptions of environment creation using keyboard shortcuts to the user. However, not all users are comfortable with keyboard shortcuts.
- Add an external button to inject environment LaTeX code into the editor. This approach could be cumbersome to maintain and should ideally be handled within MathLive.

## Additional context

- Matrices and other environments are crucial components in certain mathematical, scientific, and educational fields, and they should be treated as first-class citizens in MathLive.

- Environments are complex LaTeX constructs that can be challenging for non-LaTeX users to learn. Users could greatly benefit from MathLive's ability to support the input of complex environments without requiring knowledge of LaTeX syntax.

- Relevant issues/PRs
  - #1863
  - #1926

**Comment by arnog** [comment]
After thinking about this, I'm leaning towards adding a contextual menu (which would also be available via an icon, next to the virtual keyboard toggle), that would contain commands like "Insert Matrix", "Add Column", etc...)

**Comment by arnog** [comment]
Completed.
