### ISSUE TITLE
[FEATURE] Improve keyboard shortcuts

### ISSUE THREAD

**Issue by tumidi** [arnog/mathlive#2157]
## Is your feature request related to a problem? Please describe.

- The [documentation on shortcuts][shortcuts-doc] seems to be tailored towards Mac OS users and doesn't seem to work well for PC users on Windows and Linux.
- Examples of issues with the current documentation:
  - The documentation states that <kbd>⌥</kbd> + <kbd>[</kbd> is used to type a matrix, supposedly equivalent to <kbd>Alt</kbd> + <kbd>[</kbd> on PC. However, on PC, it's sufficient to just type a square bracket without the Alt key, making it confusing for Windows users.
  - There's inconsistency in representing keyboard keys in the documentation. <kbd>⌃</kbd> is used to denote <kbd>Ctrl</kbd> or <kbd>Control</kbd>, while <kbd>⌘</kbd> is used for <kbd>Ctrl</kbd> on Windows, which can lead to confusion.

## Describe the solution you'd like

We propose implementing a user-friendly solution by adding a switch to the keyboard shortcuts page. The switch would allow users to toggle between Mac and PC shortcuts display. When a user chooses a specific platform, the shortcuts and "special keys" overview will dynamically switch to display the keys typically found on the selected platform. This change will provide a better and more accurate reference for both Mac and Windows users.

## Describe alternatives you've considered

One alternative would be to recommend virtual keyboard or mouse interaction. However, this approach may not be optimal for users who prefer keyboard-based interactions.

## Additional context

- [MathLive documentation on Keyboard Shortcuts][shortcuts-doc] 
- Related issue: #2158  

[shortcuts-doc]: https://cortexjs.io/mathlive/reference/keybindings/

**Comment by arnog** [comment]
@TouchstoneTheDev A sponsored issue is an issue that someone is funding me to work on.

**Comment by arnog** [comment]
Completed.
