### ISSUE TITLE
[FEATURE] Improve documentation on Keyboard Shortcuts

### ISSUE THREAD

**Issue by tumidi** [arnog/mathlive#2158]
## Is your feature request related to a problem? Please describe.

- Keyboard shortcuts might need to be reworked to be more useful.
- On PC, many shortcuts don't do what they are supposed to.
- See the [table](#table_tests) of preliminary tests.

## Describe the solution you'd like

- The key bindings should optimally "just work," regardless of the keyboard layout, browser, or operating system someone is using.
- It seems many shortcuts are "shadowed" by browser or OS shortcuts. We might need to find a set of the most important shortcuts and try to map them to keys with the least chance of colliding with pre-existing shortcuts.

## Describe alternatives you've considered

- Using virtual keyboard/mouse interaction (which is suboptimal for users who prefer using the keyboard).

## Additional context
- [MathLive documentation on Keyboard Shortcuts][shortcuts-doc]
- Related issue: #2157

### Overview of documented keyboard shortcuts and their effect on PC

<details id="table_tests">
<summary>[Toggle table]</summary>

| Shortcut                                                     | Desired Effect                      | Actual Effect (Firefox/Linux)     | Actual Effect (Chrome/Linux)                 | Reason                        | Existing Working Alternative |
| ------------------------------------------------------------ | ----------------------------------- | --------------------------------- | -------------------------------------------- | ----------------------------- | ---------------------------- |
| <kbd>Ctrl</kbd>+<kbd>B</kbd>                                 | move backward                       | opens bookmark side bar           | none                                         | Browser shortcut              | yes                          |
| <kbd>Ctrl</kbd>+<kbd>F</kbd>                                 | move forward                        | opens search bar                  | opens search bar                             | Browser shortcut              | yes                          |
| <kbd>Ctrl</kbd>+<kbd>P</kbd>                                 | move up                             | opens print dialog                | opens print dialog                           | Browser shortcut              | yes                          |
| <kbd>Ctrl</kbd>+<kbd>N</kbd>                                 | move down                           | opens new window                  | opens new window                             | Browser shortcut              | yes                          |
| <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>B</kbd>                | extend selection backward           | opens bookmark bar                | toggles bookmarks bar                        | Browser shortcut              | yes                          |
| <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>F</kbd>                | extend selection forward            | none                              | none                                         |                               | yes                          |
| <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>P</kbd>                | extend selection upward             | opens private window              | opens print dialog                           | Browser shortcut              | yes                          |
| <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>N</kbd>                | extend selection downward           | opens new window                  | opens private window                         | Browser shortcut              | yes                          |
| <kbd>Ctrl</kbd>+<kbd>H</kbd>                                 | delete backward                     | opens history side bar            | opens history tab                            | Browser shortcut              | yes                          |
| <kbd>Ctrl</kbd>+<kbd>D</kbd>                                 | delete forward                      | opens add bookmark dialog         | opens add bookmark dialog                    | Browser shortcut              | yes                          |
| <kbd>Alt</kbd>+<kbd>Ctrl</kbd>+<kbd>B</kbd>                  | move to previous word               | none                              | none                                         |                               | yes                          |
| <kbd>Alt</kbd>+<kbd>Ctrl</kbd>+<kbd>F</kbd>                  | move to next word                   | none                              | none                                         |                               | yes                          |
| <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Ctrl</kbd>+<kbd>B</kbd> | extend selection to previous word   | none                              | none                                         |                               | yes                          |
| <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Ctrl</kbd>+<kbd>F</kbd> | extend selection to next word       | none                              | none                                         |                               | yes                          |
| <kbd>Page Up</kbd>                                           | move to group start                 | Scroll page up                    | Scroll page up                               |                               | yes                          |
| <kbd>Page Down</kbd>                                         | move to group end                   | Scroll page down                  | Scroll page down                             |                               | yes                          |
| <kbd>Shift</kbd>+<kbd>space</kbd>                            | move before parent                  | move after parent                 | move after parent                            |                               | no                           |
| <kbd>Ctrl</kbd>+<kbd>←</kbd>                                 | move to mathfield start             | move to group start               | move to group start                          | collision with other shortcut | no                           |
| <kbd>Home</kbd>                                              | move to mathfield start             | scroll to page start              | works as expected                            |                               | no                           |
| <kbd>Ctrl</kbd>+<kbd>A</kbd>                                 | move to mathfield start             | select all                        | select all                                   |                               | no                           |
| <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>←</kbd>                | extend selection to mathfield start | extend selection to group start   | extend selection to group start              | collision with other shortcut | no                           |
| <kbd>Shift</kbd>+<kbd>Home</kbd>                             | extend selection to mathfield start | none                              | works as expected                            |                               | no                           |
| <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>A</kbd>                | extend selection to mathfield start | opens addon window                | opens "Search tabs" dialog                   | Browser shortcut              | no                           |
| <kbd>Ctrl</kbd>+<kbd>→</kbd>                                 | move to mathfield end               | move to group end                 | move to group end                            | collision with other shortcut | no                           |
| <kbd>End</kbd>                                               | move to mathfield end               | scroll to page end                | works as expected                            |                               | no                           |
| <kbd>Ctrl</kbd>+<kbd>E</kbd>                                 | move to mathfield end               | none                              | Opens default search engine in the quick bar | Browser shortcut              | no                           |
| <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>→</kbd>                | extend selection to mathfield end   | extend selection to group end     | extend selection to group end                | collision with other shortcut | no                           |
| <kbd>Shift</kbd>+<kbd>End</kbd>                              | extend selection to mathfield end   | none                              | works as expected                            |                               | no                           |
| <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>E</kbd>                | extend selection to mathfield end   | opens network monitor (dev tools) | none                                         | Browser shortcut              | no                           |
| <kbd>Ctrl</kbd>+<kbd>5</kbd>                                 | move to opposite (upper/lower)      | none                              | works as expected                            |                               | no                           |
| <kbd>Ctrl</kbd>+<kbd>6</kbd>                                 | move to upper                       | none                              | works as expected                            |                               | no                           |
| <kbd>Ctrl</kbd>+<kbd>-</kbd>                                 | move to lower                       | decrease zoom level               | works as expected                            | Browser shortcut              | no                           |
| <kbd>Ctrl</kbd>+<kbd>Z</kbd>                                 | undo                                | redo                              | redo                                         | Keyboard layout               | no                           |
| <kbd>Ctrl</kbd>+<kbd>Y</kbd>                                 | redo                                | undo                              | undo                                         | Keyboard layout               | yes                          |
| <kbd>Ctrl</kbd>+<kbd>L</kbd>                                 | scroll into view                    | move cursor to url bar            | move cursor to url bar                       | Browser shortcut              | no                           |
| <kbd>Alt</kbd>+<kbd>space</kbd>                              | toggle virtual keyboard             | opens dropdown                    | none                                         | OS shortcut?                  | no                           |
| <kbd>Alt</kbd>+<kbd>=</kbd>                                  | apply text mode                     | none                              | none                                         |                               | no                           |
| <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Home</kbd>              | toggle math/text mode               | none                              | none                                         |                               | no                           |

</details>

[shortcuts-doc]: https://cortexjs.io/mathlive/reference/keybindings/

**Comment by arnog** [comment]
FYI, there's a number of those shortcuts that are only applicable to macOS. For historical reasons (because macOS is built on a Unix foundation) the text fields in macOS support standard EMACS shortcuts, this includes Ctrl+A, Ctrl+H, etc... These shortcuts are not essential because they all have more "standard" equivalent, i.e. command+left arrow/ctrl+left arrow, etc...

These shortcuts are not an issue on macOS because macOS computers have both a "ctrl" and "command" key. However, on Windows or Linux, "Ctrl+A" is mapped to the equivalent "Command+A", which is "Select All". In other words, the EMACS shortcuts are not supported on Windows or Linux, but this shouldn't be an issue since users are unlikely to be used to them, since they are not supported in text fields in these environments in general anyway.

Admittedly, the documentation is not very clear about that, and this could be confusing for a Windows/Linux users. I will rework that as part of the clarification of the documentation.

Thanks for the table, that's helpful.

**Comment by arnog** [comment]
The issue seemed to have been that there was the keyboard layout for German keyboards on Linux was missing (German keyboards on macOS and Windows were supported). The keyboard layout for the German keyboard on Linux has been added and should fix the issues like ctrl+Z not triggering Undo.
