### ISSUE TITLE
Shortcuts not working with international Keyboard (German)

### ISSUE THREAD

**Issue by hannibal7ML** [arnog/mathlive#216]
**Describe the bug**
When typing "-" on a German keyboard "\frac" is inserted.  

**To Reproduce**
1. Go to  https://mathlive.io/deploy/index.html (mathlive.js 0.29.1 5/29/19)
2. Empty  the mathfield and type "2-" on German keyboard: \frac is inserted ; type  "2/": no \frac inserted; "\\" is still  not recognized, see #173 

**Expected behavior**
Recognize key strokes as intended. 
I could solve the problem by putting in src/editor-keyboard.js lines 122-124 after lines 126-141. 
It appears line 123 blocks other keyboards by using evt.code before evt.key.
Fixes also #173 problem with backslashes.

**Environment**
- Device: pc
- OS: Windows 10
 - Browser: Chrome
 - Version: 74

**Comment by leonfrischauf** [comment]
This would be also very important for us as an Austrian based math site, as then we could use your framework for over 2000 pupils.

**Comment by jkdufair** [comment]
👍 affects Dvorak keyboard layout. In my case the slash key ends up inserting \frac
