### ISSUE TITLE
Event geometrychange not fired when clicking on keyboard button to hide the virtual keyboard

### ISSUE THREAD

**Issue by ybi55** [arnog/mathlive#2161]
Here is the code of an html page to visualize the problem.
For me the mathlive version displayed in the console is 0.95.5
If you click on the keyboard button in the editor, an alert message appears (keyboard display status changed) and the virtual keyboard appears in a custom div as container : the geometry change event listener is launched.
If you click again on the keyboard button to hide the virtual keyboard, the virtual keyboard disappears but no alert message : the geometrychange event seems not to be fired.
The problem can bee seen on chrome, firefox or edge (windows 11).
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<p></p> <p id="editor">
    A = <MATH-FIELD></MATH-FIELD>
</p>
<div id="keyboardcontainer" style="position: absolute; left: 0px; top: 100px; width: 400px; height:300px">

</div>
<script type="module">
  window.addEventListener('DOMContentLoaded', () =>
    import('//unpkg.com/mathlive?module').then((mathlive) => {
        console.log(globalThis[Symbol.for('io.cortexjs.mathlive')].version);
        mathlive.renderMathInDocument()
        window.mathVirtualKeyboard.container = document.getElementById('keyboardcontainer')
        window.mathVirtualKeyboard.addEventListener('geometrychange', function (ev) {
          alert('keyboard display status changed')
        })
      }
    )
  )
</script>
</body>
</html>
</html>
```

**Comment by lhotejc** [comment]
It seems that mathVirtualKeyboard do not extend the standard virtualKeyboard interface ?

virtualKeyboard interface is experimental technology [in this mdn page](https://developer.mozilla.org/en-US/docs/Web/API/VirtualKeyboard).

what about the Mathlive mathVirtualKeyboard ?

what events it can fire ?
