### ISSUE TITLE
Generating LaTeX mixed numbers (factors)

### ISSUE THREAD

**Issue by truebluepl** [arnog/mathlive#2163]
Hello,
is there any option for generating LaTeX mixed fractions like: 2\\frac{1}{2}, as (2+\\frac{1}{2})?

**Comment by arnog** [comment]
Yes, it generates mixed fractions by default.

**Comment by truebluepl** [comment]
Yes, as I wrote above it generates mixed fractions, but for example for 2,5 syntax is: 2\frac{1}{2}, which parsed gives 2*0.5=1.
I'm interested in syntax like: (2+\frac{1}{2})

**Comment by arnog** [comment]
Sorry, I do not understand what you are saying. It would help if you could provide more information, such as some code that illustrate the issue.

If you go to https://cortexjs.io/compute-engine/demo/ and paste `$$ 2\frac{1}{2} $$` you will the result is `["Add", "Half", 2]` or `2.5`. I don't know what you're expecting.

**Comment by NSoiffer** [comment]
My two cents: I think what is being asked for is to interpret a whole number followed by a numeric fraction as "mixed number". Mixed numbers have an implied plus, not an implied times between the two parts.

FYI: U+2064 is "invisible plus" (meant to help resolve these kind of issues)

**Comment by arnog** [comment]
That's where I am confused. A whole number followed by a numeric fraction *is* interpreted as a mixed number, i.e. as an invisible plus. Did you try with the demo link above? Did you *not* get the mixed fraction? Maybe it only works on my machine...

**Comment by NSoiffer** [comment]
My bad, I was responding to the email and didn't see your response. I tried several different ways of doing $2 \frac12$ on the cortexjs.io site and all worked properly.

**Comment by truebluepl** [comment]
Hello Guys!
You don't have to be sorry:)

I wrote about generating LaTeX numbers, not calculating. MathLive generating proper mixed numbers.
But because Compute Engine has no method to solve equation (finding "x"), I use Nerdamer (to be exact it is Nerdamer-Prime) which has solveFor method. Nerdamer parsing LaTeX 2\frac{1}{2} as 1, so I'm looking of option to generating mixed fraction with visible plus and surronding brackets for safety.
If Compute Engine had solve method it would be much easier:)

P.S. It's not so easy to use just regex to change syntax - there could be nested fractions.

**Comment by arnog** [comment]
As I've previously answered here: https://github.com/cortex-js/compute-engine/issues/88
you can solve equations with the Compute Engine using `ce.solve()`.

**Comment by truebluepl** [comment]
Could you show me example for solving: 4*x+3=19 ?
I don't know how to use this method, and how to be called (from ComputeEngine object or from BoxedExpression object).
I can't find any example in documentation.

```
let ce = new ComputeEngine.ComputeEngine();
console.log(ce.solve('4*x+3=19','x'));
```
above code gives me: Uncaught TypeError: ce.solve is not a function

**Comment by arnog** [comment]
Try this: 

```js
console.info(ce.parse("3x+1=19").solve(["x"])?.toString());
// -> 6
```

**Comment by truebluepl** [comment]
Hello Arnog,
why this gives me empty result?
`console.log(ce.parse("x=\\left(8-\\sqrt{13}\\right)\\left(8+\\sqrt{13}\\right)").solve(["x"]).toString());`
Should return 51.

P.S. What does "some equations can be solved using ce.solve()" mean? Why "some"?
