### ISSUE TITLE
Bug: Mathfield stylesheet does not apply after consecutive unmounts and mounts. 

### ISSUE THREAD

**Issue by kristofk01** [arnog/mathlive#2165]
## Description

Mathfield styling disappears sporadically on consequent unmounts and mounts.

There are no runtime or TypeScript errors.

I am using the following logic to customise when the `math-field` should appear:

```js
mf.mathVirtualKeyboardPolicy = "manual";
mathVirtualKeyboard.show();
mf.addEventListener("unmount", () =>  mathVirtualKeyboard.hide());
```

This is what the issue looks like:

![IMG_6253](https://github.com/arnog/mathlive/assets/23499974/4b7756aa-5929-40cb-ac92-d0563a1e5b88)

### Steps to Reproduce

1. Mount math-field.
2. Interact with the page.
3. Unmount math-field.
4. Interact with the page.
5. Mount math-field => styling missing.

### Actual Behavior

Styling on math-field element is not applied.

### Expected Behavior

Styling on math-field element should be applied.

### Environment

**MathLive version**  `0.95.5`

**Operating System** `iOS 16.x.x and 17.0.x`

**Browser** `Safari` (mobile only, desktop seems to work fine)

**Comment by screambeard** [comment]
Sorry for opening this one again, but we encountered the same issue a while back. I see this one is closed, but I don't see a mentioning of the issue number (#2165) in the CHANGELOG. Could you confirm this issue is closed because it has been fixed?

**Comment by kristofk01** [comment]
Thanks for the comment, looks like I accidentally closed this issue. I have replicated the issue again with the latest version of mathlive.

**Comment by arnog** [comment]
@screambeard can you confirm that you are also seeing this issue, but only on iOS?

**Comment by arnog** [comment]
Do you have any report of this happening with iOS 17.1 or later?

There was a potentially relevant fix in [iOS 17.1](https://developer.apple.com/documentation/safari-release-notes/safari-17_1-release-notes): "Fixed intermittent removal of adoptedStyleSheet CSSStyleSheet instances when assigning an adoptedStyleSheet array. (107768559)"

**Comment by kristofk01** [comment]
You may be right. I have been unable to reproduce this on iOS 17.1 and 17.2.x

**Comment by arnog** [comment]
I'm going to assume that this was fixed in Safari. Please reopen if you see it again on iOS 17.1 or later.

**Comment by loveleet-convivity** [comment]
@arnog i'm getting issue of keyboard. error is "Uncaught TypeError: document.adoptedStyleSheets is not iterable" and i'm specifically this error on chrome 
my chrome version is "Version 123.0.6312.107 (Official Build) (arm64)" and mac version 14.4

**Comment by arnog** [comment]
@loveleet-convivity unlikely to be related, since this issue was specific to iOS and you're seeing your issue in Chrome.
