### ISSUE TITLE
Copy not working on mobile + select on contextmenu

### ISSUE THREAD

**Issue by Mopiel** [arnog/mathlive#2170]
Hey, we found 2 bugs:
* it is not possible to copy value on a mobile (tested on demo from here https://cortexjs.io/mathlive/demo/)
* it is not possible to click right button (contextmenu) with selection (it acts like left click) 😢

**Comment by arnog** [comment]
Still can't reproduce this. There isn't enough information on the report. I don't know what OS/browser is being used. The screencasting also doesn't appear to be from the demo page. Is this a website with a custom contextual menu perhaps? Have you tried other browsers?

Here's a screenshot showing it working as expected in Chrome on macOS:

![Screenshot 2023-11-09 at 06 50 29](https://github.com/arnog/mathlive/assets/760798/67ee8c68-80d9-4b0a-ae55-bd0d9f8686bf)

**Comment by arnog** [comment]
Still can't reproduce it. 

I notice your contextual menu has a "Sprawdź" and "Przetłumacz" commands, which don't seem to be standard. 

Do you have a browser plugin or system service installed that could be interfering?

Could you try switching to the English system locale and see if that still happens?

Do you have another Mac you could try this on? If you don't have another Mac, could you try this on another user account, maybe a guest user account, that wouldn't have any plugins installed (see System Settings > Users & Groups).

This is what I get:
![Zrzut ekranu 2023-11-9 o 11 48 23](https://github.com/arnog/mathlive/assets/760798/f7adfbb0-110c-49ab-ac08-d1f518d70290)

**Comment by arnog** [comment]
I believe this has now been fixed.
