### ISSUE TITLE
Defined integral is deleted entirely with 1 backspace hit

### ISSUE THREAD

**Issue by VladyslavBagat** [arnog/mathlive#2173]
## Description

I use HTML and JavaScript to create a simple instance of math-field. After inputting definite integral using Virtual Keyboard and pressing Backspace, whole integral gets deletes instead of boundary value. HOWEVER, if Delete is used, boundary works correctly. 
### Steps to Reproduce

> Steps to reproduce:

1. Create a math-field object
2. Using Virtual Keyboard input predefined definite integral
3. Select entry box for upper or lower boundary 
4. Press Backspace

### Actual Behavior

> When backspace is clicked, whole integral gets deleted.

### Expected Behavior

> When backspace is clicked, only value of boundary is deleted

### Environment

**Operating System**  Windows 11

**Browser** Opera GX 105.0.4970.10

**Comment by VladyslavBagat** [comment]
After trying again today issue was resolved. Either it was a quantum tunneling issue or @arnog did exceptional job.

**Comment by arnog** [comment]
The issue was really there, but it has been fixed in mathlive 0.96.
