### ISSUE TITLE
Disable All the inline shortcuts

### ISSUE THREAD

**Issue by SahilPatel2349** [arnog/mathlive#2174]
import React, {
  useImperativeHandle,
  useEffect,
  forwardRef,
  useRef,
} from "react";
import "mathlive/dist/mathlive.min";

import "mathlive/dist/mathlive-fonts.css";
import "mathlive/dist/mathlive-static.css";

const MathLiveEditor = forwardRef((props, ref) => {
  const _ref = useRef(null);
  useImperativeHandle(ref, () => _ref.current, [_ref]);

  useEffect(() => {
    if (_ref.current?.getValue() !== props.value) {
      _ref.current?.setValue(props.value || " ");
    }
  }, [props.value]);

  useEffect(() => {
    _ref.current?.addEventListener("input", () => {
      props.onEditorInput(_ref.current?.getValue());
    });

    return () => {
      _ref.current?.removeEventListener("input", () => { });
    };
  }, []);

  const attributes = {
    "keypress-sound": "none",
    "plonk-sound": "none",
  };

  return <math-field ref={_ref} {...attributes} style={props.style} />;
});

export default MathLiveEditor;

how can I disable all the inline shortcuts that I type from physical keyboard on this code?

**Comment by arnog** [comment]
Set the `inlineShortcuts` property of the mathfield to `{}`

**Comment by SahilPatel2349** [comment]
<img width="848" alt="image" src="https://github.com/arnog/mathlive/assets/37297657/5d304b5a-23ec-4497-9883-a641ba8656e9">


I have used it like this and it is not working.

**Comment by arnog** [comment]
It's not an attribute, it's a property. So you need to change the property on the mathfield. If you could paste some code, I could show you how to modify it. I can't modify a screenshot.

**Comment by SahilPatel2349** [comment]
import React, {
  useImperativeHandle,
  useEffect,
  forwardRef,
  useRef,
} from "react";
import "mathlive/dist/mathlive.min";

import "mathlive/dist/mathlive-fonts.css";
import "mathlive/dist/mathlive-static.css";

const MathLiveEditor = forwardRef((props, ref) => {
  const _ref = useRef(null);
  useImperativeHandle(ref, () => _ref.current, [_ref]);

  useEffect(() => {
    if (_ref.current?.getValue() !== props.value) {
      _ref.current?.setValue(props.value || " ");
    }
  }, [props.value]);

  useEffect(() => {
    _ref.current?.addEventListener("input", () => {
      props.onEditorInput(_ref.current?.getValue());
    });

    return () => {
      _ref.current?.removeEventListener("input", () => { });
    };
  }, []);

  const attributes = {
    "keypress-sound": "none",
    "plonk-sound": "none",
    "inlineShortcuts": {},
  };

  return <math-field ref={_ref} {...attributes} style={props.style} />;
});

export default MathLiveEditor;

THIS IS THE COMPONENT THAT I am currently using, can you help me with modifying this code

**Comment by arnog** [comment]
```js
import React, {
  useImperativeHandle,
  useEffect,
  forwardRef,
  useRef,
} from "react";
import "mathlive/dist/mathlive.min";

const MathLiveEditor = forwardRef((props, ref) => {
  const _ref = useRef(null);
  useImperativeHandle(ref, () => _ref.current, [_ref]);

  useEffect(() => {
    if (_ref.current?.getValue() !== props.value) {
      _ref.current?.setValue(props.value || " ");
    }
  }, [props.value]);

  useEffect(() => {
    _ref.current?.addEventListener("input", () => {
      props.onEditorInput(_ref.current?.getValue());
    });

    if (_ref.current) _ref.current.inlineShortcuts = {};

    return () => {
      _ref.current?.removeEventListener("input", () => {});
    };
  }, []);

  const attributes = {
    "keypress-sound": "none",
    "plonk-sound": "none",
  };

  return <math-field ref={_ref} {...attributes} style={props.style} />;
});

export default MathLiveEditor;
```

Since `inlineShortcuts` is a property, not an attribute, you need to change it in the `useEffect`. Also, note you do not need include the `.css` files.
