### ISSUE TITLE
\dots cannot be recognized as ellipses by latex

### ISSUE THREAD

**Issue by Yuchaocheng** [arnog/mathlive#2188]
## Description
\dots cannot be recognized as ellipses by latex，Is there currently a way to solve this problem?

### Actual Behavior

Latex: \dots not resolved to ellipsis, but \cdots can

### Expected Behavior

Latex: \dots resolved to ellipsis

### Environment

You can reproduce the problem on the official website

<img width="793" alt="image" src="https://github.com/arnog/mathlive/assets/38006754/7a5c31b6-35ab-4683-aa88-37050860eaa9">

<img width="770" alt="image" src="https://github.com/arnog/mathlive/assets/38006754/f34e29a4-a555-442e-8e95-27e1e879e256">

**Comment by jjlankinen** [comment]
This does not seem to be fixed yet so why is this issue closed (I can see the issue creator closed this right after creating it)?
