### ISSUE TITLE
Keycup for latex: "{#?}\\atopwithdelims\\{{#?}"

### ISSUE THREAD

**Issue by truebluepl** [arnog/mathlive#2192]
Current behaviour:
Keycap with latex syntax: "{#?}\\atopwithdelims\\{{#?}" is displayed and prints bracket with only one squared placeholder, but there is editable place for second line in the matfield.

Expected behaviour:
There should be two squared placeholder in the mathfield and displayed in the label.

**Comment by arnog** [comment]
The correct syntax is `#? \atopwithdelims\{. #?`: the `\atopwithdelims` command needs two delimiters. If you only need one, you must use a `.` to indicate an empty delimiter, otherwise the `#?` is interpreted as the right delimiter. Also, you don't need braces around the `#?`.

**Comment by truebluepl** [comment]
Yes! Now it works perfect. Thank you.
