### ISSUE TITLE
Tabbing out of a mathfield breaks command mode and some functions

### ISSUE THREAD

**Issue by panoschal** [arnog/mathlive#220]
**Describe the bug**
When I press Tab inside a mathfield, focus correctly goes to the next element in the form, but when I click back to the mathfield, some features stop working.
Namely:

- `onContentDidChange` is not executed when I type into the mathfield
- pressing `\` triggers math mode (I know it because `onModeChange` is called) instead of command mode and I can't enter commands

**To Reproduce**
1. Go to https://mathlive.io/deploy/index.html
2. Click into the mathfield
3. Press Tab key
4. Focus the mathfield again
5. Press backslash

**Expected behavior**
Command mode should be triggered, in order to be able to insert commands into the mathfield.
Also, `onContentDidChange` should be executed.

I think this issue is related to #81 

**Environment**
 - Browser: Chrome, others not tested

**Attempts to get around this bug**

- I tried using `onTabOutOf`
- I tried using `perform(['switchMode'])` to programmatically change the mode to command mode, on `\` keypress. It didn't work because mathlive changes mode again to math mode.
- I tried to prevent Tab altogether, with no luck.
- I actually managed to solve this problem by reinitializing the mathfield, when it loses focus. With `onBlur`. I populated the mathfield with the same latex (with `.latex()`) as before blur, so the user does not see anything strange.

**Comment by arnog** [comment]
Good catch. When losing focus the content change notifications were suppressed, resulting in an inconsistent state with interesting side-effects. Fixed now.
