### ISSUE TITLE
Option to Disable Automatic `\mathbf` Extension to Subsequent Characters

### ISSUE THREAD

**Issue by ichibha** [arnog/mathlive#2208]
## Description
In the current implementation, when typing characters immediately after a `\mathbf{foo}` expression, the typed characters (e.g., `bar`) automatically convert to `\mathbf{bar}`. This feature can sometimes be inconvenient, especially since `\mathbf` is commonly used for single characters, for example, matrices.

## Expected Behavior
Is there a way to disable this automatic `\mathbf` extension so that subsequent characters are not automatically formatted without typing space key?

**Comment by arnog** [comment]
As you mention, there is already a way to do this by pressing the SPACE key. Another way would be to use a custom `onInlineShortcut` hook. See https://cortexjs.io/mathlive/guides/shortcuts/#multicharacter-identifiers for more info.

**Comment by ichibha** [comment]
@arnog, I appreciate your prompt response. I've encountered an issue where, despite having a non-empty mathModeSpace, using the SPACE key both inserts a space symbol and exits the typeface extension. It would be helpful if the executeCommand function could include an option to exit the typeface extension programmatically, for example, to assign a different keybinding.

**Comment by arnog** [comment]
I'm sorry, I don't follow. The initial report was about a user typing in a mathfield, but now you're talking about using an API? You can change the style using the `mf.applyStyle()` function, but I'm really not sure what you're trying to do or whether there is an issue or not.
