### ISSUE TITLE
Autocomplete text color css

### ISSUE THREAD

**Issue by JamMaster1999** [arnog/mathlive#2209]
## Description

I was not able to find how to change the autocomplete text color that gets activated via "\". The current color is quite hard to read specially in dark mode. 

### Steps to Reproduce

> (Required) Provide steps that are specific and repeatable

Press "\" and tyoe any letters in. 

### Actual Behavior
 
> (Required) What happened when you followed the steps above?

The text color is a shade of blue that is hard to read especially in dark mode.

### Expected Behavior
> (Required) What did you expect to happen instead? It may be obvious to you what should have happened, but if you don't state it explicitly it may not be obvious to others.

The text color should change with dark/light mode and/or be exposed as a css variable.

**Comment by arnog** [comment]
The color can be set with the CSS variable `--latex-color`.

**Comment by JamMaster1999** [comment]
Thank you @arnog  I was just able to figure it out and were about to post it.

**Comment by JamMaster1999** [comment]
Two small follow up issues:

- The theme="dark"/"light" option set on the body only affects the keyboard and not the menu. However the menu does change its appearance based on system/browser's light or dark mode. It would be more consistent if the menu inherited its styling based on theme attribute set on the body element. 
- Additionally, do you know what css variable affect the color of the hover in the menu or autocomplete menu such as 
![image](https://github.com/arnog/mathlive/assets/46285145/0f1d6f1a-72c2-46f6-adc1-785a1e994be9)
![image](https://github.com/arnog/mathlive/assets/46285145/9810074e-7ea1-487b-88e5-2d0e3b8fd184)
