### ISSUE TITLE
The menu style does not follow theme attribute

### ISSUE THREAD

**Issue by JamMaster1999** [arnog/mathlive#2213]
## Description

Consistent light dark mode on menu styling.

### Actual Behavior

The theme="dark"/"light" option set on the body only affects the keyboard and not the menu. However the menu does change its appearance based on system/browser's light or dark mode.

### Expected Behavior

It would be more consistent if the menu inherited its styling based on theme attribute set on the body element and not just the system/browser. 

### Optional to answer but would be appreciated
- Is there a css variable that affects the color of the hover in the menu or autocomplete menu such as 
![image](https://github.com/arnog/mathlive/assets/46285145/0f1d6f1a-72c2-46f6-adc1-785a1e994be9)
![image](https://github.com/arnog/mathlive/assets/46285145/9810074e-7ea1-487b-88e5-2d0e3b8fd184)

**Comment by arnog** [comment]
It is unfortunately not possible for a `theme="dark"` attribute on the body to influence the styling of a component. However, I could add support for a `theme="dark"` attribute applied to the math-field element itself. Only other option is to specifically override the desired CSS variables.

**Comment by JamMaster1999** [comment]
@arnog ok thanks for checking. It is not a big deal so whatever you decide is fine. I just wanted to point it out. Also setting --primary-color does not change anything based on my testing. Might it be a different name?

**Comment by arnog** [comment]
I don't know. It's working for me.

![Screenshot 2023-12-16 at 12 27 46](https://github.com/arnog/mathlive/assets/760798/e9ceab20-e587-4bee-9666-c7c4acb1c12c)
![Screenshot 2023-12-16 at 12 27 32](https://github.com/arnog/mathlive/assets/760798/e9a50c46-1ce2-4fc6-9727-bd33097f900e)

**Comment by JamMaster1999** [comment]
ahh man sorry about that @arnog . I thought this was a global css variable and not based on the math-field tag. Closing the issue now
