### ISSUE TITLE
Entering superscript fails using German keyboard layout

### ISSUE THREAD

**Issue by tumidi** [arnog/mathlive#2214]
## Description

Using a German keyboard layout, the following input doesn't render correct superscript:

- <kbd>x</kbd> <kbd>^</kbd> <kbd>2</kbd>, <kbd>x</kbd> <kbd>^</kbd> <kbd>3</kbd>, etc.
- <kbd>x</kbd> <kbd>Alt Gr</kbd> + <kbd>2</kbd> or <kbd>x</kbd> <kbd>Alt Gr</kbd> + <kbd>3</kbd>

### Steps to Reproduce

1. Open MathLive editor in a web browser
2. E.g., type <kbd>x</kbd>, <kbd>^</kbd>, <kbd>2</kbd> (using a German keyboard layout)
3. Check the formular rendering and also MathJSON output.

### Actual Behavior

- MathLive editor outputs unicode character `²` instead of superscript `2`.
- MathJSON outputs an error code.

See the difference in rendering:  
![Screenshot_2023-12-12_13-27-45](https://github.com/arnog/mathlive/assets/41736868/d06c4e94-c3c7-4f51-bb8f-5e82386c2dc0)

### Expected Behavior

- Editor should display proper superscript `2`.
- MathJSON output be correct.

### Environment

**MathLive version** 0.98.4

**Operating System** Linux 6.6.2-arch1-1

**Browser** Chromium, Firefox

**Comment by arnog** [comment]
Can you clarify which key you are pressing to get the `^` character?

**Comment by buzz** [comment]
> Can you clarify which key you are pressing to get the `^` character?

On a German layout, it's this key (without modifier)

![key](https://github.com/arnog/mathlive/assets/12035/95fb869c-f823-442a-b60e-4ec1136d3c02)

**Comment by tumidi** [comment]
> Can you clarify which key you are pressing to get the `^` character?

On a german layout, it's this key (without modifier)

![key](https://github.com/arnog/mathlive/assets/41736868/815ac85a-42d6-4c9b-9888-5ea99f5af3ff)

**Comment by tumidi** [comment]
After thinking about this some more; this issue should probably be generalized to handle all [sub/superscript Unicode characters](https://en.wikipedia.org/wiki/Superscripts_and_Subscripts_(Unicode_block)#Block),

- to take into account other keyboard layouts emitting sub/superscript characters,
- also handle copy/pasting of sub/superscript characters correctly.

I think, MathLive should translate those characters on the fly.

**Comment by arnog** [comment]
@tumidi Could you try the following experiment:
1/ Create a new browser window
2/ Bring up the JS console (context menu > "Inspect")
3/ Paste this in the console: `window.addEventListener('keydown', console.log)`
4/ Click on the page
5/ Press the `^` key
6/ Copy the resulting message in the console and paste it below.

**Comment by tumidi** [comment]
> @tumidi Could you try the following experiment:
> 1/ Create a new browser window
> 2/ Bring up the JS console (context menu > "Inspect")
> 3/ Paste this in the console: `window.addEventListener('keydown', console.log)`
> 4/ Click on the page
> 5/ Press the `^` key
> 6/ Copy the resulting message in the console and paste it below.

![Screenshot_2023-12-21_21-05-29](https://github.com/arnog/mathlive/assets/41736868/4cf19190-69ac-446e-9d97-756dc01b7505)
