### ISSUE TITLE
Using mathlive menu leads to many blur events firing

### ISSUE THREAD

**Issue by QuinnStraus** [arnog/mathlive#2215]
## Description

Using the new mathlive menu and navigating into the submenus leads to lots of blur events being fired. In our project, we had been making use of blur events, so this has created problems for us.

### Steps to Reproduce

1. Simple example at https://codepen.io/Quinn-Straus-the-animator/pen/NWoZEPJ
2. Open codepen console
3. Click mathfield menu
4. Move into submenus (colors, matrix) and back 

### Actual Behavior

A blur event logs when the menu is closed or whenever a submenu is closed

### Expected Behavior

Blur events should only be fired when the mathfield is actually blurred (such as when we click outside the mathfield), and not when menus inside the mathfield open or close.

### Environment

This has been an issue ever since the menu has been released, and has prevented us from upgrading to the new version

**MathLive version**  98.4

**Comment by arnog** [comment]
You can turn off the menu with `mf.menuItems = []`. This way, you can upgrade to the current version without loss of functionality compared to the pre-menu version.
