### ISSUE TITLE
Curly brackets get removed in frac and sqrt

### ISSUE THREAD

**Issue by hellozebra73** [arnog/mathlive#2224]
When getting the value of expressions that have curly brackets like frac or sqrt, if the arguments inside the brackets are single digit numbers, the curly brackets get removed. Example, frac{1}{3} is displayed correctly, but when getting the value I get frac13. I tried the demo in the Cortex webpage and it has the same behaviour,as when I copy the content of the formula on notepad frac{1}{3} gets converted to frac13. Is there a way to remove this behaviour?

**Comment by hellozebra73** [comment]
![mathlive](https://github.com/arnog/mathlive/assets/29196050/68147f93-ac1c-4925-9b04-216b8db5830c)

**Comment by arnog** [comment]
The braces after `\sqrt` and `\frac` are optional in LaTeX under certain circumstances. If you want to introduce unnecessary braces, you can do so using a regex pattern: `s.replace(/\frac(\d)(\d)/g, "\\frac{$1}{$2}")` and `s.replace(/\sqrt(\d)/g, "\\sqrt{$1}")`

**Comment by hellozebra73** [comment]
Ok, thanks for the answer.
