### ISSUE TITLE
Input value won't get updated

### ISSUE THREAD

**Issue by edward1127** [arnog/mathlive#2227]
[sandbox](https://codesandbox.io/p/devbox/nextjs-sandbox-6tg8qd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpb03g4c00092v6ipzrh33ol%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpb03g4c00032v6ie3hhlsz4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpb03g4c00062v6i1du2g3s0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb03g4c00082v6itopo9f7m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpb03g4c00032v6ie3hhlsz4%2522%253A%257B%2522id%2522%253A%2522clpb03g4c00032v6ie3hhlsz4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb0bd6s00032v6i89jdg69m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A24%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A24%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fcomponent%252FMathInput.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpb0bd6s00032v6i89jdg69m%2522%257D%252C%2522clpb03g4c00082v6itopo9f7m%2522%253A%257B%2522id%2522%253A%2522clpb03g4c00082v6itopo9f7m%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb03g4c00072v6ivrgzqggh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3001%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpb03g4c00072v6ivrgzqggh%2522%257D%252C%2522clpb03g4c00062v6i1du2g3s0%2522%253A%257B%2522id%2522%253A%2522clpb03g4c00062v6i1du2g3s0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb03g4c00042v6in4bv7d37%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clpb03g4c00052v6iw0n3pp24%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp1zlxc1000gedjw0kvy7j6h%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpb03g4c00042v6in4bv7d37%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

[Screencast from 12-21-2023 05:49:20 PM.webm](https://github.com/arnog/mathlive/assets/45161984/74df0881-283c-4adf-be09-e886f6cceeae)

## Description

Value within the mathlive won't update

### Steps to Reproduce

click the "add 1 button"

### Actual Behavior

only the value display outside the input will be updated

### Expected Behavior

both outside and within mathlive values should be updated

**Comment by truebluepl** [comment]
It's problem within your app. Did you update math-field value onClick button event?

**Comment by edward1127** [comment]
@truebluepl  I'm not sure how react communicates with web components, but when the value state is updated in react, it triggers the rerender and mathlive's HTML does look like it's getting updated. However, the mathlive's value update is not reflected in the actual rendering. Are you suggesting that using setValue is insufficient, and I have to do something like `mf.current.value = <updated value>` manually?
![image](https://github.com/arnog/mathlive/assets/45161984/0b626360-31d4-4f80-ab95-d58760ffb631)

**Comment by arnog** [comment]
It's a bug. Updating the content of a mathfield currently does not trigger an update to its value. I have checked in a fix for it.

As a workaround, you would have to set the `value` property of the mathfield.

**Comment by edward1127** [comment]
@arnog thank you for checking it!
