### ISSUE TITLE
Doesnt load in firefox 67.0.4 

### ISSUE THREAD

**Issue by Kreijstal** [arnog/mathlive#223]
**Describe the bug**
It appears that there is a javascript that is being served as text instead of javascript, which is why it doesnt appear to work at all.
**To Reproduce**
1. Go to main website
2. Open dev tools
3. See error

**Expected behavior**
You should be able to at least type something in the input box

[Is this a regression: did it use to work in a previous version?]

**Screenshots**
![image](https://user-images.githubusercontent.com/2415206/60398556-fbc69180-9b59-11e9-9b23-30ff63003679.png)

**Environment**
- Device: [pc, mac, iPhone, Android...]
PC
Linux
firefox
67.0.4

**Comment by arnog** [comment]
Thanks for reporting this issue. There was a server configuration issue. It has been fixed now.
