### ISSUE TITLE
\ast translated to asciimath "**"

### ISSUE THREAD

**Issue by gunnarmein-ts** [arnog/mathlive#2236]
## Description

getValue("ascii-math") gives unexpected result with \ast and a fraction

### Steps to Reproduce

- go to https://cortexjs.io/mathlive/demo/
- paste in "$$b\ast c$$" (without quotes)
- In the debugger console:
- document.querySelector("math-field").getValue()
        ==> 'b\ast c'
- document.querySelector("math-field").getValue("ascii-math")
        ===> 'b**c'
Note the double asterisk. I looked through the change log to see whether this is intended, but did not find anything.

### Actual Behavior

\ast was translated into double-asterisk: 'b**c'

### Expected Behavior

\ast should be translated into single asterisk: "b*c"

### Environment

> Is this a regression: did it use to work in a previous version?
worked correctly before \ast was introduced to represent the asterisk (last version I tested was 0.93.0)

**MathLive version**  0.98.5
**Operating System** macOS Sonoma (also happens on github Ubuntu test runner)
**Browser** Chrome

**Comment by gunnarmein-ts** [comment]
Sorry a bunch of things were converted to markdown formatting. editing ...

**Comment by arnog** [comment]
According to https://asciimath.org/ `**` is the correct translation of `\ast`

**Comment by gunnarmein-ts** [comment]
I'd argue that typing "*" to have it represented with "\ast", to be converted to asciimath "**" is counterproductive, especially since "**" is "to the power of" in a couple of languages like python, but I agree that you implemented the spec.
