### ISSUE TITLE
[FEATURE] multiline input

### ISSUE THREAD

**Issue by panoschal** [arnog/mathlive#224]
## Description
In order to be able to type content across multiple lines, you must add `\begin{multiline} ... \end{multiline}` (#190). I think it would be better if there were an option to specify if you want to enable the multiline environment natively. In Katex, just adding `\\` without any environment, specifies a newline.

### Actual behavior
The problem is that if you go to mathlive.io and paste `\begin{multiline} \end{multiline}`, you must press the left arrow in order to move the cursor in the right position. This could be solved by using `mf.perform(['insert', '\\begin{multiline} #0 \\end{multiline}']);` but again, if the user clicks at the right blank side of the mathfield, they would focus *outside* the multiline environment.
![image](https://user-images.githubusercontent.com/27917356/60401911-e02aad80-9b90-11e9-9f76-b41d578d2d96.png)

### Expected Behavior 
I think that allowing both multiline and regular input side to side, is of no use, so it would make sense if only one mode was allowed, for the whole mathfield, without the need for the user to manually add `\begin{multiline} ... \end{multiline}`.

**Comment by rpdiss** [comment]
Ye i agree with @arnog 2 many modes gonna provide many bugs it would be great if u add configuration to config that allows open only one mode many users like the multi line feature and complain that was missing regarding to other editors.

**Comment by arnog** [comment]
Changing the title from "Multiline support is not user-friendly" to "Feature: multiline input".

I agree this would be an interesting feature to add. Regarding the implementation, I think you would need to do the following:
- add a multiline/single line mode to the config object
- when multiline is on, let the `root` atom be an array, with each row of the array corresponding to a line. This can leverage the existing mechanics in place to support multiline environments, with the minimum amount of code changes
- Change the Latex (and other output formats) round-tripping to support this new type of root appropriately

**Comment by johnhbenetech** [comment]
@arnog Benetech also votes for this feature! We played around a bit on our side with intercepting key input and trying to manipulate the underlying LaTex on the fly - but it wasnt very stable.

**Comment by stefnotch** [comment]
Maybe it's also worth considering adding the `\substack{}` command.

**Comment by danzyaka** [comment]
> Maybe it's also worth considering adding the `\substack{}` command for multiple lines.

don't work yet

**Comment by ashayp22** [comment]
Is there any way to add content across multiple lines right now?

**Comment by elisaado** [comment]
I wonder if multiline support has been added

**Comment by arnog** [comment]
@elisaado Thank you for your interest in this feature. 

I am not actively working on it right now, so if someone else want to pick it up, let me know. 

The status of this issue will be updated once the feature has been implemented.

**Comment by Smef** [comment]
This is pretty big for high school math and would be very useful to have. GitHub needs a "Star issue" feature!

**Comment by dobesv** [comment]
Pasting `\begin{multiline} ... \end{multiline}` into a mathlive input doesn't work right now on the website or the latest npm version, FWIW.

**Comment by Joewings-jw** [comment]
I can attest `\begin{multiline} ... \end{multiline}`  its not working.

**Comment by Joewings-jw** [comment]
We are using Mathlive to embed a virtual keyboard that enable users edit math path solutions,for this one mathfield,the desired output is to move the cursor to the next column on pressing enter.The same is achieved but horizontally,kindly assist.

**Comment by evyatarbh** [comment]
Over 3 years since the original request was created, any updates on this issue?
Can we achieve any sort of line breaking (and height increase) in latest version, either manual or by automatic wrapping?

**Comment by arnog** [comment]
> Pasting `\begin{multiline} ... \end{multiline}` into a mathlive input doesn't work right now on the website or the latest npm version, FWIW.

The name of the environment is `multline` not `multiline`. It's the LaTeX spelling 🤷 and it's working right now.

**Comment by zanzlender** [comment]
Another update. After some digging I found out you COULD style a shadow DOM element, however that element needs to have a exposed attribute ```part``` like in [this example](https://css-tricks.com/styling-in-the-shadow-dom-with-css-shadow-parts/). 

If you inspect the example you can see that the example component has a wrapper div inside which has the exposed attribute ```part="box"```.

![image](https://user-images.githubusercontent.com/44570474/220355218-2d2a1381-b25a-42fc-9cce-980cf6cffcf1.png)

Using that attribute you can style the component like so: 

```
example-component::part(box) {
  background-color: pink;
}
```

However when you look at the math-field component you can see that the wrapper div has no classes and no part attribute (because of which you cannot style it - as far as I know for now)

![image](https://user-images.githubusercontent.com/44570474/220354801-39c81292-82e8-4bb0-b9d6-ef7fc3a0b34b.png)

**Comment by evyatarbh** [comment]
@zanzlender I actually succeeded styling the textarea in a somewhat hacky way as follows -
  `this.mathField = new MathfieldElement();
this.mathField.shadowRoot.innerHTML +=
      "<style>" +
      ".ML__fieldcontainer {" +
      "min-height: 3rem !important;" +
      "margin-top: 0.125rem;" +
      "}" +
      "textarea {" +
      "width: 10px !important;" +
      "height: 10px !important;" +
      "background: transparent;" +
      "caret-color: transparent;" +
      "transform: none !important;" +
      "}" +
    "</style>";`

Some of it was needed for our E2E tests to be able to edit the inner text (I couldn't set focus to the textarea at first) and some was to conform with our UI/UX requirements.

**Comment by arnog** [comment]
@zanzlender it's a good start, but there would be more work needed. For example, the selection across multiple lines doesn't work: put the caret in the middle of the first line, then shift click in the middle of the second line: the entire mathfield appears selected, although only a portion of it is). Also, the cuts are not done in the right place, for examples multi-digits numbers can get cut in half.

Also, it's true that there's no way to style the "root" `<div>` inside the shadow DOM. I could add a part for it, but I'm not sure why you need it?

@evyatarbh that's a creative approach, although it's not supported and might break in the future. I assume that for `.ML__fieldcontainer` you meant `.ML__container`? Note that this is addressable using `math-field::part(container)`. The `<textarea>` component inside the mathfield is not addressable. Note also that it's not always present (it's not present on touch-enabled devices, for example). And I'm not clear what you were trying to do. For E2E tests, you can set the focus on the `<math-field>` directly and send it keydown events directly.

**Comment by zanzlender** [comment]
@arnog will try to think about it when I'm free :) However, I would say although it may have some broken use cases for me it's better to have it like that than to have the formula disappear when it gets too big. 
And regarding the styling part... It were just my thought on how I could get around this if I wanted to do

**Comment by jana14pb** [comment]
> 

how to implement & where ?

**Comment by arnog** [comment]
You can now enter multiple lines by typing alt+return.

**Comment by jana14pb** [comment]
Great work Mr.Arno Gourdol. I'm glad to hear that!.

**Comment by Smef** [comment]
This is great! We're going to update and do some testing soon.

**Comment by molaei2000** [comment]
@arnog  Thank you for adding this feature but it not working on text mode.
I am working on a exam project this library save my life.
I need something like textarea behavior because question's description is long.
I have solved this problem for now by adding overflow: scroll to content part but it is not good approach.
please add this feature.

**Comment by langit** [comment]
@molaei2000 This may partially help solve your problem: in the text mode if you press enter, you will get a new line to continue in text mode:

```
<script type="text/javascript">
mf = document.getElementById('math-Q1-Answer');
mf.addEventListener('beforeinput', (ev) => {
    if(ev.inputType === 'insertLineBreak' && ev.target.mode === "text") {     
        mf.executeCommand(["switchMode", "math"]);
        mf.executeCommand(["insert", "\\\\"]);
        mf.executeCommand(["switchMode", "text"]);} });
</script>
```

What falls short is that if you are in the middle of a text line, this code can't break it into two parts and move the latter part into the next line. You probably need to make more `executeCommand` calls to do some selecting, copying & pasting, etc. to succeed.

**Comment by langit** [comment]
For those who are interested, this example code supports both insert and delete of newlines:

```
<math-field id="math-Q1-Answer" style="display: block">  </math-field> 
<script type="text/javascript">
mf = document.getElementById('math-Q1-Answer');
mf.addEventListener('beforeinput', (ev) => {
    // console.log(ev.inputType);
    let imf = ev.target;
    let mode = imf.mode;
    function restore_cursor(value) {
        imf.value = value;
        console.log(value);
        imf.executeCommand(["moveToMathfieldStart"]);
        for(let ph in imf.getPrompts()){
            imf.executeCommand(["moveToNextPlaceholder"]);
            if (ph == cursor) break;
        }
        imf.executeCommand(["moveToNextChar"]);
        imf.executeCommand(["deleteBackward"]);
        if(mode=='text') imf.executeCommand(["switchMode", mode]);
    }
    const cursor = "thecursor";
    const magic = `\\placeholder[${cursor}]{}`;
    const groupstt = "\\placeholder[cursorgroupstt]{}";
    const groupend = "\\placeholder[cursorgroupend]{}";
    const dslash = "\\\\ ";
    const displn = "\\displaylines";
    if(ev.inputType === 'insertLineBreak') { 
        imf.executeCommand(["switchMode", "math"]);
        //side-effect: break text into two parts
        imf.executeCommand(["insert", magic]); 
        imf.executeCommand(["moveToGroupStart"]); 
        imf.executeCommand(["insert", groupstt]); 
        imf.executeCommand(["moveToGroupEnd"]); 
        imf.executeCommand(["insert", groupend]); 

        let value = imf.value;
        if (value.includes(dslash+groupstt)||value.includes(displn+groupstt)){
            value = value.replace(groupstt, " ");
            value = value.replace(groupend, "");
        }else{
            value = value.replace(groupstt, `{${displn} `);
            value = value.replace(groupend, "}");
        } 

        value = value.replace(magic, dslash + magic);
        restore_cursor(value);
        ev.preventDefault();    
    }else if(ev.inputType === 'deleteContentBackward'){
        imf.executeCommand(["switchMode", "math"]);
        //side-effect: break text into two parts
        imf.executeCommand(["insert", magic]); 
        let value = imf.value;
        if (value.includes(dslash+magic)){
            value = value.replace(dslash+magic, magic);
            ev.preventDefault();    
        }
        restore_cursor(value);
    }else if(ev.inputType === 'deleteContentForward'){
        imf.executeCommand(["switchMode", "math"]);
        //side-effect: break text into two parts
        imf.executeCommand(["insert", magic]); 
        let value = imf.value;
        if (value.includes(magic+dslash)){
            value = value.replace(magic+dslash, magic);
            ev.preventDefault();    
        }        
        restore_cursor(value);
    }
});
</script>
```

Cheers!

**Comment by Shrookin** [comment]
Hey, seems the issue has been dead for a while, I wanted to try to help.

I opened https://github.com/arnog/mathlive/pull/3060, which adds experimental free-math and free-text modes.

free-math is closely related to the native multiline behavior requested here: the entire mathfield uses a multiline row model, so users do not need to manually insert a multiline environment. It also preserves empty lines, trailing lines, tabs, and multiline round-tripping.

free-text builds on the same model for prose with inline LaTeX and text styling.

Linking this PR for context and maintainer review.
