### ISSUE TITLE
Virtual Keyboard Tooltips on shifted keycap

### ISSUE THREAD

**Issue by GGilli** [arnog/mathlive#2242]
FEATURE REQUEST:
In the definition of a keycap it can be declared only one tooltip so on the shifted keycap is shown the same tooltip. Is possible to have a different tooltip of a shifted keycap?

**Comment by arnog** [comment]
You can now specify a tooltip on the shifted variant:
```json
{
  latex: "\\times",
  tooltip: "Multiply",
  shift: { latex: "\\ast", tooltip: "Star" },
},
```
