### ISSUE TITLE
Removing Macros not working

### ISSUE THREAD

**Issue by claudiabudimir** [arnog/mathlive#2253]
## Description

> I'm trying to remove the macros from being used by math-filed. I followed the [example](https://cortexjs.io/mathlive/guides/macros/) provided in the documentation, but it is not working. I saw another issue previously (#1422) mentioning that the math field could still fall back on some default values. The issue was marked as solved, but it still looks like the macros are not disabled entirely. Code example [here](https://codepen.io/Claudia-Budimir/pen/MWxjYzV). 

### Steps to Reproduce

1. Create a math-field element in the HTML file with id='mf', and the corresponding latex = '\in'.
2. Set the macros of the element as mf.macros = {} in the JS file.

### Actual Behavior

> The macro '$$ \in $$' renders as ∈. 

### Expected Behavior

> The macro '$$ \in $$' renders as plain text "in".

### Environment

It might be a regression, in issue #1422 is mentioned that it was fixed as well as in the [change log](https://github.com/arnog/mathlive/blob/master/CHANGELOG.md#0720-2022-04-18) of version 0.72.0.

**MathLive version**  0.98.4

**Operating System** ubuntu 22.04.3

**Browser** _Chrome, Firefox, etc...

**Comment by arnog** [comment]
The command `\in` is not a macro, it's a built-in symbol. If you want to prevent it from displaying you can define a macro with the same name that does nothing.

**Comment by claudiabudimir** [comment]
Thanks a lot! It is working, `\in` is now displayed like "in". 

What confused me was when logging `mf.macros` I could see a macro called 'isin' with the latex definition as '\\in'. That's why I thought `mf.macros = {}` will disable it. What is actually disabled when setting `mf. macros = {}`? Is there a list with the built-in symbols? 

Another question is, I'm trying to make the latex "\\imaginaryI" serialized as "i" instead of "ImaginaryUnit" to MathJSON. To do so, I added it to the latexDictionary as in this [example](https://codepen.io/Claudia-Budimir/pen/MWxjYzV?editors=1111), but is still serialized as "ImaginaryUnit". Is there any way to override this behaviour? For "G" the CatalanConstant seems to work, but following the same pattern.

**Comment by arnog** [comment]
> What is actually disabled when setting mf. macros = {}? Is there a list with the built-in symbols?

You can see the macros by printing them to the console: `console.log(mf.macros)`.

> Is there any way to override this behaviour?

No that I can think of. A lot of things would break if the MathJSON representation was changed.
