### ISSUE TITLE
Input/Renderer do not initialize on Safari (iOS 10.2.1)

### ISSUE THREAD

**Issue by CharlesAnifowose** [arnog/mathlive#226]
**Describe the bug**
I first encountered as an issue with `MathLive.renderMathInElement`. It throws an error on older versions of Mobile Safari only (`Undefined is not an object `) and the math text between the "$$" encapsulators stays as plain text. 

I used the device with the older iOS version to access mathlive.io and I learned that the input did not work either.

**To Reproduce**
Steps to reproduce the behaviour:

1. Use a phone with iOS 10.2.1
2. Go to mathlive.io
3. the "julia" does not display, and the input field is permanently blank

**Expected behavior**
Math should render in both the input and the output modes.

**Environment**
- Device: iPhone
- OS: iOS 10.2.1
 - Browser Safari

**Comment by arnog** [comment]
This version of iOS/Safari is not supported (I believe what's missing is the support for native modules). 
If you need to support MathLive in your application on older versions of Safari/iOS, I suggest using Babel to transpile MathLive and add the necessary polyfills to work with the browsers you target.
