### ISSUE TITLE
Wrong MathML output

### ISSUE THREAD

**Issue by rvt01** [arnog/mathlive#2262]
I have added the below LaTeX code in a display equation:
\text{loss}_i

However, it produced the following MathML which does not parse due to the base is not inside mml:msub. Any idea about how to solve it?
<mml:mtable columnalign="right left ">
<mml:mtr>
  <mml:mtd>
    <mml:mrow>
       <mml:mtext >loss</mml:mtext>
       <mml:msub>
           <mml:mi>i</mml:mi>
       </mml:msub>
    </mml:mrow>
  </mml:mtd>
</mml:mtr>
</mml:mtable>

**Comment by rvt01** [comment]
When I replace \text with \mathrm, I got the correct MathML output. However, I would like to know what is the problem with the previous command.

**Comment by arnog** [comment]
This appears to be fixed now and produces `<msub><mtext >loss</mtext><mi>i</mi></msub>`
