### ISSUE TITLE
When in text mode, some commands are not working properly

### ISSUE THREAD

**Issue by panoschal** [arnog/mathlive#228]
**Describe the bug**
In mathlive.io, when text mode is enabled, and:

- you type `ii`, `jj`, `pi` or `dx`, or
- you click `e` or `i` from the virtual keyboard

the corresponding latex code appears inside the text block.

**Expected behavior**
Not sure. It could change to math mode and insert the command properly, or it could stay with text mode and prevent the shortcut from executing (in order to literally see ii, jj, pi, dx, while it is rare).

**Comment by arnog** [comment]
I believe this has been fixed in 0.34.
