### ISSUE TITLE
Selection Highlight for Multiple Math Fields Regression

### ISSUE THREAD

**Issue by mgreminger** [arnog/mathlive#2282]
## Description

In recent versions of MathLive there is a regression of a previous issue where selected portions of math fields are highlighted even when a math field does not have focus. This behavior is different than how the input HTML element handles this situation where only the currently focused input element highlights the selection (see the screen recording below).

With #1987, I had previously fixed this issue. With, 3ff2f06, this fix was rolled back with the commit that fixes #2169. However, this change seems unrelated to fixing #2169. Was this change intentional? Is it possible to revert to the previous behavior where the selection is only highlighted for the currently selected math field? If so, I'm happy to submit a pull request. 

### Steps to Reproduce

For a page with multiple MathLive elements, select a portion of one MathLive element and then switch focus to another MathLive element (or any other focusable element on the page).

### Actual Behavior

The selection will remain highlighted in the MathLive element that no longer has focus.

The following screen recording shows the issue. The elements on the left are HTML Input elements to show the difference in behavior.

[Screencast from 2024-01-31 15-42-29.webm](https://github.com/arnog/mathlive/assets/6439649/a19a89bb-b8ed-4af3-93a7-61990cf7ee51)

### Expected Behavior

The selection will only be highlighted for the currently focused MathLive element to match the behavior of native HTML elements. If multiple MathField elements appear to have active selections, it's unclear to the user which math field will change when typing. 

### Environment

This is a regression caused by 3ff2f06 when [this fix](https://github.com/arnog/mathlive/pull/1987/files#diff-00bb05a76914aaede5595f18f738d5bd4707e8d11cd90f0156cda249e7213f0cL223) in #1987 was removed.

**MathLive version** 
0.98.6

**Operating System** 
Linux

**Browser** 
Firefox and Chrome

**Comment by arnog** [comment]
It seems like the selector was modified by mistake. Reverting that change.

**Comment by mgreminger** [comment]
@arnog thanks, much appreciated!
