### ISSUE TITLE
[Bug] Updating value causes cursor to move to the end

### ISSUE THREAD

**Issue by Mathias-S** [arnog/mathlive#2289]
## Description

When trying to use MathLive as a controlled component, i.e. binding the slot value of the field to an external variable, every update to the content causes the cursor to move the end.

This is typically done when combined with libraries such as React, in fact the bug is reproducible with the MathLive/React code from the docs: https://cortexjs.io/mathlive/guides/react/

### Steps to Reproduce

1. Create a MathLive component using the React example from the [official docs](https://cortexjs.io/mathlive/guides/react/).
2. Enter something into the MathLive field
3. Move the cursor to the start or middle of the content, and enter something.

Minimal example on CodePen, using the code from the docs: https://codepen.io/mathias-s/pen/XWGYGZo

### Actual Behavior

The cursor will move to the end instead of staying in the correct place.

https://github.com/arnog/mathlive/assets/225531/8f41ecfd-6b0a-4b0f-b9e1-b6849c1ae6e8

### Expected Behavior

The cursor should stay in place while entering something in the start/middle of the content.

### Environment

Using MathLive 0.98.6 on various browser such as Chrome, Safari and Firefox.

**Comment by arnog** [comment]
Thanks for the detailed report and code sample
