### ISSUE TITLE
Popover can only appear underneath math field, and will get cut off if it's at the bottom of the window

### ISSUE THREAD

**Issue by jack-arms** [arnog/mathlive#229]
**Describe the bug**
Popover for math field can only ever appear under the math field, and is not aware of the bottom of the window, so when the math field is at the bottom of the window it gets cut off. 

**To Reproduce**
- Make math field at the bottom of web page, with default options
- Type to trigger the popover
- Observe popover is cut off

**Expected behavior**
Popover should have an option to appear above the math field if there is no room below it.

**Screenshots**
![Screen Shot 2019-07-16 at 5 52 21 PM](https://user-images.githubusercontent.com/2754685/61339498-ce811100-a7f2-11e9-9602-65eb2955f822.png)

**Environment**
- Version: 29.1
- Browser: chrome

**Comment by arnog** [comment]
This is fixed with that PR, right? Thanks for contributing that fix. 
Let me know and re-open if there's still something missing.
