### ISSUE TITLE
Fraction keyboard entry regression

### ISSUE THREAD

**Issue by mgreminger** [arnog/mathlive#2291]
## Description

Regression in fraction behavior since 0.98.6 (tested on 24081c25e2a0332b351bb340ecd59802df2520c9)

### Steps to Reproduce

Create a fraction using the / key and then enter the numerator and denominator. Use Tab or Arrow to get out of the fraction and type the multiplication symbol to the right of the fraction.

### Actual Behavior

The contents of the fraction will disappear and be replaced by prompts. See screen recording below:

https://github.com/arnog/mathlive/assets/6439649/b64a01f9-9d84-473e-b473-ec445757cef2

### Expected Behavior

This worked correctly in the most recent release 0.98.6. See the screen recording below:

https://github.com/arnog/mathlive/assets/6439649/852d9577-9602-4ba3-9611-fd21af9abb4f

### Environment

This is a regression, issue seen at head of master (24081c25e2a0332b351bb340ecd59802df2520c9), works correctly in 0.98.6

**Operating System** Windows and Linux

**Browser** Firefox and Chrome

**Comment by arnog** [comment]
I think it's a problem with keyboard shortcuts. What keyboard keys did you type for the multiplication symbol?

**Comment by mgreminger** [comment]
I used the asterisk key `*` to create the multiplication.

**Comment by arnog** [comment]
OK, I've narrowed down where I think the problem might be, but I can't trigger it by pressing the `*` key. I can only trigger it by pressing `xx` and it only reverts the denominator, not the numerator. Are you trying this with the smoke test? Do you have any additional configurations to the mathfield?
