### ISSUE TITLE
the Configuration options scriptDepth don't work 

### ISSUE THREAD

**Issue by laipp** [arnog/mathlive#230]
**Describe the bug**

**To Reproduce**

**Expected behavior**

[Is this a regression: did it use to work in a previous version?]

**Screenshots**

**Environment**
- Device: [pc, mac, iPhone, Android...]

**Comment by arnog** [comment]
Could you provide a code sample that demonstrates the problem? I can't reproduce it. 
If I set `scriptDepth: 0` in the config field, it completely suppresses super and subscripts, as expected, and if I set it to `scriptDepth: 1` it limits it to one level.
