### ISSUE TITLE
Selection position auto jumps to the end of the input on input changed

### ISSUE THREAD

**Issue by phillipngn** [arnog/mathlive#2308]
## Description

I'm using mathlive version 0.98.6, every time math field input changes, the selection position jumps to the end of the input.
I did try the demo on `https://cortexjs.io/mathlive/demo/` which is also using version of 0.98.6, the selection position does not auto jump to the end. 

### Steps to Reproduce

1. Clone react-mathlive repo which is using latest version (0.98.6) (https://github.com/arnog/react-mathlive).
2. Input some numbers, move selection to the left, then press any number
3. Selection position auto jumps to the end of the input

Here is the sandbox reproduction link: https://stackblitz.com/edit/react-h1tdkb

### Actual Behavior

- Selection position auto jumps to the end of the input

https://github.com/arnog/mathlive/assets/114401625/217cd27e-86f5-4e64-acc4-3830d532cb78

### Expected Behavior

- Selection position stays at the position as it is

### Environment

**MathLive version** 0.98.6

**Operating System** MacOS 12.6.1 

**Browser** Chrome 121.0.6167.184 (Official Build) (x86_64)

**Comment by johnsmithecon** [comment]
I'm also experiencing this, I think this is pretty critical issue. @phillipngn have you found a workaround?

**Comment by arnog** [comment]
I believe this issue is caused by the `onInput` handler: each time a key is pressed, it resets the value of the mathfield, causing the selection to change. The fix is to remove this `onInput` handler.

**Comment by johnsmithecon** [comment]
Thanks so much for the reply.

Yes, but isn't it almost impossible to use this with React if we can't have any onInput handlers? For example, the official MathLive showcase for React uses onInput handler. What do you propose is the best way to go about solving it?
<img width="833" alt="image" src="https://github.com/arnog/mathlive/assets/62140912/6b39bc68-38b4-4d0a-b4f9-0a99b1964fc7">

**Comment by arnog** [comment]
You can of course have an `onInput` handler, as per the documentation. However, the `onInput` handler in the code that was submitted is recursively setting the value of the mathfield. Each time a key is typed the handler changes the value of the mathfield causing the selection to change. Simply don't change the value of the mathfield inside the `onInput` handler.

**Comment by johnsmithecon** [comment]
Doesn't the documentation do it this way as well, though? Here is a StackBlitz that mirrors the documentation: https://stackblitz.com/edit/sandbox-react17-vwnirm?file=src%2FApp.js

Notice that the same issue is present.

<img width="550" alt="image" src="https://github.com/arnog/mathlive/assets/62140912/0f3b943b-3736-48d6-bfb9-65703e44be4a">

**Comment by arnog** [comment]
Well, not quite. If you look closely at the code, you will notice that the handler in the example in the documentation does not modify the value of the mathfield. Instead, it calls `setValue` which is a React function that will update the `value` variable.

Now, there is an issue as this variable is used as the body of the mathfield, which unnecessarily triggers a re-render. This is covered by #2289.

**Comment by johnsmithecon** [comment]
Thanks for that information. I've tried your newest commit on master and it does fix the issue when using it in the way you're specifying.

The issue I'm seeing now, however, is that if I use `mf.current.setPromptState(id, val);` then it does the same thing of jumping the cursor to the end. Are you noticing this as well?

**Comment by johnsmithecon** [comment]
I've attached two videos below. The first is the expected behavior as demonstrated on the Mathlive website. The second is what I'm actually seeing when I use the setPromptState from your newest commit on master in React. The key difference is that whenever you call the setPromptState in React it results in the cursor jumping to the end of the whole math element instead of staying at the desired position within the square placeholder.

Expected:

https://github.com/arnog/mathlive/assets/62140912/c852bcc0-829d-4733-a904-afabc9c788a8

Reality:

https://github.com/arnog/mathlive/assets/62140912/63ae61b6-31cc-45cb-98cd-8df1671cccc2

**Comment by phillipngn** [comment]
@arnog Thanks @arnog , #2289 is the answer for my issue.
