### ISSUE TITLE
[Feature] Allow disabling math field focus when browser tab regains focus

### ISSUE THREAD

**Issue by pwawrzynczyk** [arnog/mathlive#2337]
## Description

I'd like to be able to stop the math field from regaining focus and scrolling back to it when the browser tab is focused again. I realize the current behavior may still be desirable for some use cases, so a flag to configure it would be perfect.

### Steps to Reproduce

0. Have a page with a math field at the top and some other content below, so that if we scroll to the bottom of the page, the math field won't be visible anymore.
1. Focus the math field.
2. Scroll to the bottom.
3. Switch tab.
4. Switch back to the original tab.

### Actual Behavior

When the user switches back to the original tab, page refocuses the input and scrolls to it. This may confuse some people, who left the focus on the field, but then started looking at the rest of the page and don't want to get back to it.

### Expected Behavior

When the user switches back to the original tab, there is no scroll or focus change - the math field stays blurred.

### Environment

**MathLive version**: 0.92.1 and 0.98.6.

**Checked on**: Firefox, Chrome, Safari on desktop, Brave on mobile.

**Comment by arnog** [comment]
I am not able to reproduce this. When I switch back to the original tab, the mathfield is not scrolled into view. Whether the focus is restored or not is browser dependent (Chrome does restore the focus, but Safari does not).

Do you have some event handlers perhaps that could get triggered and cause this to happen?

**Comment by d7ark** [comment]
Hey @arnog. Sorry for bothering you. When could I expect this to be released?

I see this being merged 2 weeks ago, but recent release notes does not mention this. I'm not very good at figuring things like this out, so sorry if this is stupid question :D 

Have a nice day!
