### ISSUE TITLE
Difficult to focus on empty field

### ISSUE THREAD

**Issue by arncet** [arnog/mathlive#236]
**Describe the bug**
Similar to https://github.com/arnog/mathlive/issues/196.
Difficult to focus on empty field.

**To Reproduce**
1. Go to https://mathlive.io/deploy/examples/virtual_keyboard/ (or any example without default value)
2. Try to focus the field (`ML__fieldcontainer__field`'s height = `0`).

**Expected behavior**
A line-height that makes focusing easy.

**Environment**
- Device: mac
- OS: Mojave 10.14.5
 - Browser: Chrome 75.0.3770.142
 - Version: 0.32

**Comment by ChillingVan** [comment]
You can try to listen pointer events and call ``` mathField.$focus() ```
