### ISSUE TITLE
Selection area exception in low version of chrome

### ISSUE THREAD

**Issue by skimklin** [arnog/mathlive#2362]
My current chrome version is 87. The mouse clicks once on the input box, but the editor behaves like a long press to select it.

Can you take a look at what's wrong, thanks a lot!

Mathlive version:  online version ( https://cortexjs.io/mathlive/editor/ )
Browser: Chromium 87.0.4243.0
OS: Windows 10

https://github.com/arnog/mathlive/assets/27659365/6ab6d20b-5fc0-4eb3-a04d-b9390f4f023a

**Comment by arnog** [comment]
Only the most recent versions of Chrome are supported. The current version is 124.

**Comment by skimklin** [comment]
Thank you for your reply.
The reality is that for some we can't upgrade our browsers. And in some cases there is no way to control the version of the browser the user is using.
We would like to support more versions if possible.

**Comment by arnog** [comment]
Of course, I understand. I also have very limited resources, but I can suggest two approaches:

1/ Find a sponsor willing to fund the work required. This could be a commercial sponsor or a non-profit.

2/ Investigate and propose solutions for the issue as a contribution to this open source project. I will be happy to review any submitted PR and merge it with the baseline project.

**Comment by skimklin** [comment]
Thanks for the suggestion, I'll take a look at what's wrong.If I can fix the problem, I'd be happy to contribute PR.
