### ISSUE TITLE
keybinding command switchMode should insert the prefix in the previous mode and the suffix with the new mode

### ISSUE THREAD

**Issue by EmaGht** [arnog/mathlive#2375]
## Use case

Being able to write quoted text while autmatically entering text mode

### Actual Behavior

With a configuration as follows:
```
{ key: 'shift+[Digit2]', ifPlatform: 'windows', command: ['switchMode', 'text', "", "\""], ifMode: "math" },
{ key: 'shift+[Digit2]', ifPlatform: 'windows', command: ['switchMode', 'math', "\"", ""], ifMode: "text" }
```
I'm trying to switch between math mode and text mode while adding a `"` for extra visual clarity as it's difficult for a user to notice he is writing actual text otherwise.

The first half is actually possible using 
```
{ key: 'shift+[Digit2]', ifPlatform: 'windows', command: ['switchMode', 'text', "\""], ifMode: "math" },
```
As the prefix gets added using the new mode, which is "text", but when i type `"` again it gets added by this keybinding
```
{ key: 'shift+[Digit2]', ifPlatform: 'windows', command: ['switchMode', 'math', "\"", ""], ifMode: "text" }
```
in math mode, breaking the visual

### Expected Behavior

Be able to write the prefix from "switchMode" in the previous mode, while writing the suffix in the next mode.

I guess what i'm asking is using `previousMode` instead of `mode` [here](https://github.com/arnog/mathlive/blob/0d6ab51e6244425b381a7d5be5e58f68eff6b95c/src/editor-mathfield/mathfield-private.ts#L1218)

### Environment

> Is this a regression: did it use to work in a previous version?
no

**MathLive version** 
latest

**Operating System** 
windows

**Browser**
all

**Comment by arnog** [comment]
The `SwitchMode` command has two optional arguments. The first one is a "prefix" that is rendered in the current mode, and the second one is a "suffix" that is rendered in the new mode. So, you should use it to do what you want.

However, the implementation is currently broken and needs to be fixed.
