### ISSUE TITLE
Typing error this.focus() instead of this.$focus()

### ISSUE THREAD

**Issue by plfort** [arnog/mathlive#238]
**Describe the bug**
Small typing error in https://github.com/arnog/mathlive/blob/7a66b0c8eee002393d5311b5eddfc07d86f9ca9e/src/editor/editor-mathfield.js#L1055
Any button pressed on the virtual keyboard involving performWithFeedback_ function doesn't work.

**To Reproduce**
Got to https://mathlive.io/deploy/examples/customization/index.html, open JS console, open the virtual keyboard, click on "<" or ">".
In the JS console:
Uncaught TypeError: this.focus is not a function

**Environment**
Any

**Comment by plfort** [comment]
Just realized that there are 2 buttons "<" and ">", I meaned the buttons involving performWithFeedback_ :
moveToPreviousChar
moveToNextChar
moveToNextPlaceholder
etc.

**Comment by arnog** [comment]
Fixed with PR#239
