### ISSUE TITLE
Repeating decimal and parenthesis

### ISSUE THREAD

**Issue by truebluepl** [arnog/mathlive#2384]
## Description

In Polish language repeating decimal is presented as:
`a,(b)`

### Actual Behavior
Typing integer then decimal separator and decimal part with brackets, causes space between separator and left bracket. 

### Expected Behavior

There should not be space.

**Comment by arnog** [comment]
To get the proper spacing you must use ```MathfieldElement.decimalSeparator = ","`

**Comment by truebluepl** [comment]
It works when I put number in format a,b (integer part, decimal separator and decimal fraction).
But not when fraction is surrounded by brackets: a,(b)

**Comment by arnog** [comment]
Ah, ok, this happens when using `\left(...\right)`, not when using `(...)`. OK, I could temporarily turn off smartfence when in this context.

**Comment by arnog** [comment]
Fixed with 0382ccd124b0ed1708b58498ca60eb1cec2be836
