### ISSUE TITLE
Hide virtual keyboard always

### ISSUE THREAD

**Issue by kingfisherphuoc** [arnog/mathlive#2388]
## Description
We want to hide the virtual keyboard always because we use other elements with commands instead. Is there any option to do so? I tried `virtual-keyboard-toggle: off`, but it seems not working. 

### Steps to Reproduce

> (Required) Provide steps that are specific and repeatable

1. Use `math-field`
2. Style the keyboard:
```
math-field::part(virtual-keyboard-toggle) {
          display: off;
}
<math-field id="formula" style="display: block">\frac{11}{101}</math-field>
```

### Actual Behavior

> (Required) What happened when you followed the steps above?"

The virtual keyboard still shows up when I touch the `math-field`. 

### Expected Behavior

> (Required) What did you expect to happen instead? It may be obvious to you what should have happened, but if you don't state it explicitly it may not be obvious to others.

The virtual keyboard should remain hidden. It can be shown manually when we want. 

### Environment

> Is this a regression: did it use to work in a previous version?

**MathLive version**  
0.98.6

**Operating System**
Android

**Browser** 
Webview

![Screenshot_20240606_175313](https://github.com/arnog/mathlive/assets/962484/3d8ddfeb-ea4f-4749-8249-d5208b583be7)

**Comment by arnog** [comment]
To hide the virtual keyboard toggle see: https://cortexjs.io/mathlive/guides/virtual-keyboards/#controlling-the-virtual-toggle-visibility

To prevent the virtual keyboard from being displayed automatically, set the virtual keyboard policy to manual: `mf.mathVirtualKeyboardPolicy = "manual";`

**Comment by kingfisherphuoc** [comment]
@arnog thanks. You are right.
