### ISSUE TITLE
Backspace propagation bug in mathlive 0.99.0

### ISSUE THREAD

**Issue by anisabboud** [arnog/mathlive#2392]
I'm using mathlive inside Quill.
- In v0.98.6, inserting a mathlive field and typing `123`, then hitting backspace would delete just the "3" (makes sense).
- In v0.99.0 (released yesterday), inserting a mathlive field and typing `123`, then hitting backspace would delete the entire field (bug).
  It seems like in certain cases the backspace is propagating outside the field, so it's getting caught by quill, thus deleting the field.

This might be related to https://github.com/arnog/mathlive/commit/bd1c0618ba388a19633a79b19b569fecea31fb15 and `evt.preventDefault();` / `evt.stopPropagation();` (haven't looked closely yet).

**Comment by arnog** [comment]
Hmmm... In some cases, backspace now does an Undo. I think that's what's going on here.
