### ISSUE TITLE
arrows and delete key don't work

### ISSUE THREAD

**Issue by OMR8X** [arnog/mathlive#2396]
<img width="1080" alt="Screenshot 2024-06-12 at 10 43 59 PM" src="https://github.com/arnog/mathlive/assets/136569828/90763589-2cfb-4a81-b18d-2716750b803c">

arrows and deleting key don't work!

**Comment by tuviakg** [comment]
Same issue here. 
Started a few days ago.
![image](https://github.com/arnog/mathlive/assets/69410982/9462e83b-1099-44f7-9f30-925ee74aac8f)
