### ISSUE TITLE
Cannot select the last placeholder on dfx function

### ISSUE THREAD

**Issue by kingfisherphuoc** [arnog/mathlive#2398]
## Description

Cannot select the last `placeholder` on `dfx: \int`

### Steps to Reproduce

> (Required) Provide steps that are specific and repeatable

1. insert dfx into `mathfield`: `\int_{\placeholder{}}^{\placeholder{}}{\placeholder{}}` 
2. Move the selection with arrow key
3. The last `placeholder` is not selectable. 

### Actual Behavior

The last placeholder was not selectable, even though the previous ones could be selected by navigating using arrow keys. 

### Expected Behavior

The last placeholder should be selected as other placeholders. 

### Environment

**MathLive version**: 0.98.6

**Operating System** _macOS

**Browser** Chrome

The last placeholder should be selectable as the previous one.
<img width="408" alt="Screenshot 2024-06-13 at 10 20 01" src="https://github.com/arnog/mathlive/assets/962484/de280895-b0c3-493f-ae3c-647d7600276c">

**Comment by arnog** [comment]
Note: the error is happening because of an extra pair of braces. The following expression works: `\int_{\placeholder{}}^{\placeholder{}}\placeholder{}`
