### ISSUE TITLE
Click+Drag selection aggressively selects surrounding operators

### ISSUE THREAD

**Issue by johnhbenetech** [arnog/mathlive#240]
From Benetech's MathShare work. See:
https://github.com/benetech/MathShare/issues/602

**Describe the bug**
When using click+drag based selection, the selection seems to jump unexpectedly to include surrounding operators when variables are present

Here it is on MathShare: https://youtu.be/leOT7AVL95w

Here it is on MathLive: 
with variable:
![math](https://user-images.githubusercontent.com/12927553/62581596-52b53a00-b86f-11e9-9b29-c91439f7899b.gif)

without variable:
![math2](https://user-images.githubusercontent.com/12927553/62581599-5648c100-b86f-11e9-9e46-dc2a31a4d8ef.gif)

**To Reproduce**
See video above. Some weird things:

If you attempt to click+drag straight across an operator horizontally near a variable it selects too much.

However, if you click then drag down (under the operator) it will work as expected. Probably some weird bounding box thing.

**Expected behavior**
Dragging should select up to (and not beyond) position of cursor

[Is this a regression: did it use to work in a previous version?]
It did work in previous versions, but I dont know exactly which version broke it :(

**Comment by arnog** [comment]
This has been fixed a while ago.
