### ISSUE TITLE
Virtual keyboard style problems

### ISSUE THREAD

**Issue by prohorova** [arnog/mathlive#2426]
Virtual keyboard is rendered incorrectly for some versions of ipads. Browserstack is used for tesing. 
![unnamed](https://github.com/arnog/mathlive/assets/7326154/97ad570d-bc09-4d0e-acc5-6846fb5d5bdc)
![unnamed (1)](https://github.com/arnog/mathlive/assets/7326154/a147ae19-8399-423d-95cd-58a0a042b8a2)
![unnamed (2)](https://github.com/arnog/mathlive/assets/7326154/9ae06b8f-098a-4e5e-a801-cb52b5d5335f)

**Comment by arnog** [comment]
iOS 16 is the minimum supported release.
