### ISSUE TITLE
Bold menu option doesn't appear when selecting pi

### ISSUE THREAD

**Issue by andrew-murdza** [arnog/mathlive#2428]
### Steps to Reproduce

1. Run this code
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Change FontShape of MathField</title>
  <script defer src="https://unpkg.com/mathlive"></script>
</head>
<body>
<math-field id='mf'>\pi</math-field>
</body>
</html>
```
2. Right select pi, right-click, choose FontStyle

### Actual Behavior

3. Three options appear but none of them are bold

### Expected Behavior

One of the options that appears is bold

### Environment
0.100.0 Windows Google Chrome

**Comment by arnog** [comment]
Fixed in TOT.
