### ISSUE TITLE
Bug: Deleting the \ does not leave latex mode

### ISSUE THREAD

**Issue by andrew-murdza** [arnog/mathlive#2445]
### Steps to Reproduce
>
1. Type \ttt in a MathField
2. Delete all four characters

### Actual Behavior

> Deleting the \ at the end does not leave latex mode

### Expected Behavior

> Deleting the \ at the end should leave latex mode

### Environment
0.100.0

**Comment by arnog** [comment]
That is the intended behavior. You might start with "\", but then realize you need to type something else, first, perhaps a "{", so it would seem inconvenient if simply deleting the "\" caused the LaTeX mode to be exited.

**Comment by andrew-murdza** [comment]
I see your point. You can close this issue.
