### ISSUE TITLE
In mathlive.io, multiline output is written on a single line

### ISSUE THREAD

**Issue by jlchereau** [arnog/mathlive#245]
**Describe the bug**

1. Go to www,mathlive,io
2. Focus on the field, select all and delete
3. click `e` or `i` on the virtual keyboard
4.  it entre double e or double i in the field

**Expected behavior**
single characters

**Screenshots**

![image](https://user-images.githubusercontent.com/2556751/64014269-a424b200-cb19-11e9-9305-811c98dded79.png)

**Environment**
- Device: pc
- OS: windows
 - Browser chrome
 - Version 76

**Comment by arnog** [comment]
Fixed in updated mathlive.io site.
