### ISSUE TITLE
fonts- 404

### ISSUE THREAD

**Issue by chenjiayu119** [arnog/mathlive#2450]
## Description

> react project fonts is 404

### Steps to Reproduce

> i try, 
```
      customElements.whenDefined('math-field').then(() => {
        MathfieldElement.fontsDirectory = null;
        const mathField = new MathfieldElement();
        mfRef.current.appendChild(mathField);
      });
```
but fail
![image](https://github.com/arnog/mathlive/assets/65727405/c3e58be2-dbe9-4a8e-a9be-315fd713c932)

### Actual Behavior

> fonts is 404

### Expected Behavior

> I hope to prevent him from appearing 404. It would be best if the font file could be successfully loaded, and if not, disable it

### Environment

0.100.0

**Operating System** Windows10

**Browser** Chrome

**Comment by arnog** [comment]
An attempt to load the fonts from the indicated location (https://172.16.64.95:9002/docs/static/fonts) is made before your code gets executed. That location does not have the needed fonts. In order to prevent that error message, make sure the fonts are available at that location.

By setting the `fontsDirectory` to null you are preventing the fonts from being loaded subsequently.

If you want to change the fonts directory, you should do so before the custom element is defined. Try something like this:

```js
      MathfieldElement.fontsDirectory = "https://my-host/my-fonts-directory;
      customElements.whenDefined('math-field').then(() => {
        const mathField = new MathfieldElement();
        mfRef.current.appendChild(mathField);
      });
```

**Comment by chenjiayu119** [comment]
> [在执行代码之前，系统会尝试从指定位置 ( https://172.16.64.95:9002/docs/static/fonts](https://172.16.64.95:9002/docs/static/fonts) )加载字体。该位置没有所需的字体。为了避免出现该错误消息，请确保该位置有可用的字体。
> 
> 通过将其设置`fontsDirectory`为空，您可以阻止添加加载字体。
> 
> i already try，But it still failed
> 
> ```js
  useEffect(() => {
      // 设置静态属性
      customElements.whenDefined('math-field').then(() => {
        MathfieldElement.fontsDirectory = null;// 禁止加载字体(不起作用)
        const mathField = new MathfieldElement();
        mfRef.current.appendChild(mathField);
        mathliveConfig();
        // 打开弹窗自动聚焦（位置在最后）
        setTimeout(() => {
          mfRef.current.executeCommand('moveToGroupEnd')
        }, 100);
        // 绑定点击事件，点击父级后进行聚焦
        mfRef.current.parentElement.addEventListener('click', () => {
          mfRef.current.focus();
        });
        // 自动聚焦
        onFocus()

      });
  }, []);

> ```

**Comment by chenjiayu119** [comment]
I have tried following your method, but it still failed
```
  useEffect(() => {
      MathfieldElement.fontsDirectory = '';// 禁止加载字体(不起作用)
      // 设置静态属性
      customElements.whenDefined('math-field').then(() => {
        const mathField = new MathfieldElement();
        mfRef.current.appendChild(mathField);
        mathliveConfig();
        // 打开弹窗自动聚焦（位置在最后）
        setTimeout(() => {
          mfRef.current.executeCommand('moveToGroupEnd')
        }, 100);
        // 绑定点击事件，点击父级后进行聚焦
        mfRef.current.parentElement.addEventListener('click', () => {
          mfRef.current.focus();
        });
        // 自动聚焦
        onFocus()
      });
  }, []);
```

![image](https://github.com/user-attachments/assets/6aa4d4b4-b8f3-4944-ae4e-625343d4bbe9)
