### ISSUE TITLE
How to export SVG

### ISSUE THREAD

**Issue by quanzhongxian** [arnog/mathlive#2516]
I think this demand is very important，I don't want to use MathJax to convert SVG because Mathlive's selected formula symbol MathJax doesn't support it。For example, parallelograms：\parallelogram

**Comment by arnog** [comment]
There is no support to render SVG with MathLive.

**Comment by quanzhongxian** [comment]
> There is no support to render SVG with MathLive.

Rendering static formulas is also not supported？Rendering static formulas might consider supporting it.Whether it's because there are some challenges, or for design reasons, it is not supported

**Comment by arnog** [comment]
Rendering static formulas is supported: https://cortexjs.io/mathlive/guides/static/

**Comment by quanzhongxian** [comment]
> Rendering static formulas is supported: https://cortexjs.io/mathlive/guides/static/

I know that rendering static formulas is supported, but static rendering svg formulas are not supported
