### ISSUE TITLE
mathVirtualKeyboard is of type never

### ISSUE THREAD

**Issue by CoderDen732** [arnog/mathlive#2523]
## Description

TypeScript says that MathfieldElement.mathVirtualKeyboard is of never type.

### Steps to Reproduce

I followed [this](https://cortexjs.io/mathlive/guides/virtual-keyboards/#displaying-the-virtual-keyboard-in-a-custom-container) from the website and tried the following code in TypeScript to put the virtual keyboard in a custom container
```ts
import { MathfieldElement } from 'mathlive';

const mfe = new MathfieldElement();
mfe.mathVirtualKeyboard.container= document.getElementById("keyboard-container");
```

### Actual Behavior

Typescript errors with
>Property 'container' does not exist on type 'never'. ts(2339)

Also, I get this by hovering over mathVirtualKeyboard (VS Code)
![image](https://github.com/user-attachments/assets/8f58ead9-1c32-4781-a5c8-552b9c3ddbc1)

Further, I found this on the [mathlive npm code listing](https://www.npmjs.com/package/mathlive?activeTab=code) at /mathlive/dist/types/mathfield-element.d.ts at line no 766 (not sure whether it is significant here though)

![image](https://github.com/user-attachments/assets/8e10342d-585d-4a0c-b04a-53be6fda614d)

### Expected Behavior

mathVirtualKeyboard should not be of type never

### Environment

**MathLive version**  0.101.0

**Operating System** Windows 10

**Comment by arnog** [comment]
TypeScript is correct. `mathVirtualKeyboard` is not a property of `MathfieldElement`. It is a global. As per the doc you site, use `mathVirtualkeyboard.container` *not* `mfe.mathVirtualkeyboard.container`
