### ISSUE TITLE
Placeholder of the MATH-FIELD element and space character

### ISSUE THREAD

**Issue by truebluepl** [arnog/mathlive#2537]
## Description

I would like to add space character into placeholder attribute of MATH-FIELD element, but space is ignored.

### Steps to Reproduce

`<math-field value="1" placeholder="some text"></math-field>`

### Actual Behavior

Placeholder is rendered as sometext.
I was trying also "some\spacetext" and "some\\spacetext", but with no luck (wrong parsing Latex).

### Expected Behavior

Space should not be ingored.

**Comment by arnog** [comment]
The value of the placeholder text is a LaTeX string. To display it as text (including visible whitespace), use the `\text` command:

```html
<math-field placeholder="\text{some text}"></math-field>
```
