### ISSUE TITLE
'rightarrow' changing to 'rarr'

### ISSUE THREAD

**Issue by gustavo4ntunes** [arnog/mathlive#2545]
I noticed that when adding an 'arrow,' whether it be 'rightarrow,' 'Rightarrow,' or to the left as well, the LaTeX content displayed was as '/larr,' which causes issues for tools that do not use MediaWiki syntax, resulting in an error. It would be more appropriate to prioritize LaTeX syntax over MediaWiki syntax.

![Captura de tela 2024-11-05 112756](https://github.com/user-attachments/assets/0c6136e0-1864-4b42-88c8-d2128c5982ad)

When we copy the formula with ctrl + c, we can see that it copies correctly as 'rightarrow,' but when we use getValue(), the value is changed to 'rarr.

**Comment by arnog** [comment]
I tried to reproduce this issue, but I'm afraid I don't understand how to reproduce this problem. What do you mean when you say "adding an 'arrow'"? How do you add it? What does the screenshot represent? When you say "we copy the formula", which formula do you mean? It would really help if you could follow the issue template and provide step by step instructions that I could attempt to reproduce.

**Comment by arnog** [comment]
It took me a while, and I'm still not sure what this is about, but the only thing I could guess is that maybe this has something to do with the virtual keyboard? The => key was mapped to `\rarr`, and I changed it to `\rightarrow`. No idea if this was the problem or not.
