### ISSUE TITLE
Error in new Next JS 15

### ISSUE THREAD

**Issue by noams24** [arnog/mathlive#2550]
I tried to migrate my app from Next js 14 to 15, and got error when compiling the app:

![image](https://github.com/user-attachments/assets/b6c85026-6b97-4d15-8c08-e9a1f9642499)

⨯ ./node_modules/mathlive/package.json
Error parsing package.json file
invalid exports field value "./dist/fonts/*" for key "./fonts/": folder exports must end with "/"

**Comment by victorvianaom** [comment]
Same for me:

![image](https://github.com/user-attachments/assets/296b32dc-07bf-4be3-a4d5-c6ca559994c1)

**Comment by victorvianaom** [comment]
Opened a PR to fix this #2555
