### ISSUE TITLE
Multiline Invalid Latex

### ISSUE THREAD

**Issue by BodiMeCTO** [arnog/mathlive#2551]
## Description

This line:
`    if (this.environmentName === 'lines') result.push(`{\\displaylines`);`
at Line 599 in array.ts
generates invalid latex. 

### Expected Behavior
There should not be a { before \\displaylines`);`
it should be
`    if (this.environmentName === 'lines') result.push(`\\displaylines{`);`

This is stopping multilines being rendered correctly if "addRowAfter" is called on carriage return press.

### Environment
**MathLive version**  0.101.2

**Comment by BodiMeCTO** [comment]
We are debugging this because multiline does not work, if you call addRowAfter when Return is pressed.

`this.mfe.addEventListener('input', (ev: any) => {
      //for some reason, the enter key is not inserting a new line, so we do it manually
      if (ev.inputType === 'insertLineBreak') {
        this.mfe.executeCommand("addRowAfter");
        if (this.selectedOption === 'text') {
          this.switchToText();
        }
        ev.preventDefault();
      };
      this.formulaChange.next(this.getFormula());
    });`

This is what is seen in the browser:
"\( {\displaylines\text{some text}\\ \left(x-3_{}\right)\text{ asdasdasd}\\ x=3} \)" does not work in mathjax

if we modify it using:

`formula.replace("{\\displaylines", "\\displaylines{")`

we then get
"\( \displaylines{\text{some text}\\ \left(x-3_{}\right)\text{ asdasdasd}\\ x=3} \)" which works

**Comment by arnog** [comment]
Good point, I had the syntax wrong. I thought it was an environmental command, but it's a functional one.
