### ISSUE TITLE
Disabling/enabling custom layouts of Virtual Keyboard

### ISSUE THREAD

**Issue by truebluepl** [arnog/mathlive#2559]
How to show only selected custom layouts of Virtual Keyboard?
I have structure and there is no default layout, only customs.

Start of the structure (&starf; is the first layout):

```
const mathLiveKBDesktopLayout = [
  {
    label: "&starf;",
    layers: [
      {
        style: ".bigger {font-size:26px !important;}",
        rows: [
          [
            /* { label: "1", width: 0.5 }, */
            "1",
            "2",
```

**Comment by arnog** [comment]
The documentation on creating custom virtual keyboard layouts is here: https://cortexjs.io/mathlive/guides/virtual-keyboards/

If you have a specific question, let me know.

**Comment by truebluepl** [comment]
So my question is "How to disabling/enabling customs layouts?" :)
I know how to create layouts and I have created Virtual Keyboard structure with 5 custom layouts, but I would like sometimes show/hide some of them while opening keyboard.

**Comment by truebluepl** [comment]
Only solution what I found is just creating and destroying keyboard container.
