### ISSUE TITLE
Special keys in virtual keyboard aren't work

### ISSUE THREAD

**Issue by Paosder** [arnog/mathlive#259]
**Describe the bug**
When push the special key buttons in virtual keyboard, it won't work with no response.

**To Reproduce**
1. Show any virtual keyboard.
2. Click on '<' or '>' or any other special key buttons.

**Expected behavior**
Move caret position left or right appropriately.

0.32, 0.29 also broken with same issue.

**Screenshots**
![error](https://user-images.githubusercontent.com/20926881/65129757-f41ad880-da36-11e9-9e84-f59d3edbd587.gif)

**Source Code**
```
import React, {useRef, useEffect} from 'react';
import logo from './logo.svg';
import MathLive from 'mathlive';
import 'mathlive/dist/mathlive.core.css';
import 'mathlive/dist/mathlive.css';
import './App.css';

function App() {

  const targetRef = useRef();
  useEffect(() => {
    if (targetRef) {
      const mathField = MathLive.makeMathField(targetRef.current);
      mathField.$setConfig({
        virtualKeyboardMode: 'onfocus',
        virtualKeyboards: 'all'
      })
    }
  }, [targetRef]);
  return (
    <div className="App">
      <header className="App-header">
        <div ref={targetRef}>
          y=x
        </div>
      </header>
    </div>
  );
}

export default App;
```

**Environment**
- Device: pc, iPhone
- OS: Windows, iOS
 - Browser: Chrome, Safari(in iPhone)
 - Version [e.g. .32.1, .32, .29.1]

**Comment by Paosder** [comment]
Okay, I found that current mathlive in npm repo had these problems, however it is resolved in latest master branch. I hope it will be fixed soon!

**Comment by arnog** [comment]
I have pushed an update (0.32.2) that should address this issue.
