### ISSUE TITLE
Fraction line disappears at some font sizes

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#26]
## Description
The line used for fractions (and probably other cases) disappears at certain font sizes.

## Steps to Reproduce
1. Open a chrome tab andt ype cntl+0 to set the size to 100%
1. Open mathlive.io in that tab.
1. After the '=', type 1/3 -- looks good
1. Click outside the edit area and type cntl+= to increase fontsize to 110% -- fraction line goes away
![image](https://user-images.githubusercontent.com/1545836/31844731-5d70d6bc-b5af-11e7-9e1e-20deab99a200.png)

It's back 125%. Going the other way, it's there at 90%, but not at 80%.

Same thing happens for the horizontal line in roots.

## Environment
It happens on
* Windows 10
* Chrome, but not Firefox (at least the cases I tried)

**Comment by NSoiffer** [comment]
Seems to still be broken...

# Steps to reproduce
1. Open mathlive.io
2. Paste `\frac{55}{\frac{1}{2}}`
3. Fraction line is missing for the 1/2

Here's what I see:
![image](https://user-images.githubusercontent.com/1545836/33742636-2055c4ac-db5e-11e7-8749-cef71408df7d.png)


Note: this is Chrome Version 62.0.3202.94 (Official Build) (32-bit) at the default  size. Other sizes are showing problems also.

I see some of the same problems when I look at the master/origin branch, so I don't think it is something simple like mathlive.io not being updated.

**Comment by arnog** [comment]
mathlive.io has not been updated. However, you're correct the problem still occurred under some conditions. It appears to be this issue: https://productforums.google.com/forum/#!topic/chrome/r1neUxqo5Gc;context-place=topicsearchin/chrome/category$3ABeta. The workaround suggested in this suggestion seems to work. I'll put it in.

**Comment by OrkhanAlikhanov** [comment]
This is still an issue for me in chrome 80. Line disappears sometimes at font 16px. Increasing  `border-bottom-width`, `min-height` or `margin-top` to `0.05em` fixed for me. 

That said, what actually caused this was `box-sizing: inherit;` which was added by vuetify framework. As soon as I disabled it line showed up again. The `box-sizing` was inherited to be `border-box`, when I disabled it set browser's default style which was `content-box`.  @arnog what do you think about forcing `box-sizing: content-box;` in the css by default?.

You can try setting `box-sizing: content-box;` for ::after element in mathlive.io, it breaks there too.

**Comment by arnog** [comment]
I can't replicate this, even by setting the `box-sizing: border-box` of `frac-line:after` (I assume you meant `border-box`, and not `content-box` to break it, right?)

Just to clarify, you're suggesting explicitly setting `box-sizing: content-box` on `frac-line:after`? Have you tried setting `box-sizing: content-box` on a rule higher-up, like `ML__fieldcontainer__field`?

**Comment by OrkhanAlikhanov** [comment]
Yeah, I meant having `box-sizing: border-box` breaks it and yes I am suggesting explicitly setting `box-sizing: content-box` on `frac-line:after`. See how adding `box-sizing: border-box` breaks it.


![Screen-Recording-2020-03-01-at-2](https://user-images.githubusercontent.com/15037839/75629674-52aacc00-5bfd-11ea-94f2-33b0ee0f0d27.gif)

This was the case for me because of vuetify having `*:after { box-sizing: inherit }`.

**Comment by NSoiffer** [comment]
I've also seen the fraction line disappear in MathShare, but I haven't
spent the time to narrow it down. I'll try to do that later today.
Hopefully that will help find the problem.

**Comment by NSoiffer** [comment]
I hope this is of some help...

Here's the image:
![image](https://user-images.githubusercontent.com/1545836/75832238-8fe09c80-5d6a-11ea-9d2e-2ff8e098698b.png)

From the (Chrome) debugger:
![image](https://user-images.githubusercontent.com/1545836/75832494-29a84980-5d6b-11ea-8a93-da9c526987f5.png)
![image](https://user-images.githubusercontent.com/1545836/75832731-ba7f2500-5d6b-11ea-9f70-5e4aaa41b902.png)

**Comment by arnog** [comment]
I've added the `box-sizing: content-box` rule to `.frac-line:after`, however, a few questions:
- In your screenshot the frac-line sometimes appears, sometimes it doesn't (i.e in "Step 1", it is displayed). Do you know the difference between the two.
- Do you know where the rule `*, *::before, *::after {...}` come from?

**Comment by OrkhanAlikhanov** [comment]
@arnog Seems like it's the exact same case as mine. It was appearing/disappearing sometimes for me as well. The only difference between images is font size I guess.

Css libraries usually normalize/reset styling (probably to silence browser differences) and probably `*:after...` is added for that purpose by a library. 

Also it seems the latest addition hasn't made it's way there. @NSoiffer did you try adding `box-sizing: content-box` rule to `.frac-line:after` and see if it brings the line back?

**Comment by NSoiffer** [comment]
I assumed the reason for the line drop out was related to the font size -- it's the difference in what I see below. Here's the debugger info for the fraction that does display the fraction line:
![image](https://user-images.githubusercontent.com/1545836/75834590-447dbc80-5d71-11ea-954c-2d6615355e27.png)
![image](https://user-images.githubusercontent.com/1545836/75834623-5d866d80-5d71-11ea-9cc9-dc41d3c27fc6.png)

The after rule looks like some default kicking in. I don't see anything in the CSS in mathlive to cause that to be there. I think the fix you added seems like a good idea. I'll test in MathShare, but I (mistakenly) did a pull first and now it won't run for me. Hopefully someone will get a fix in soon.

**Comment by arnog** [comment]
Yeah, it looks like the font-size difference triggers a different rounding. But yeah, adding `box-sizing: content-box` manually should fix it. It might be that that `box-sizing` rule you have comes from the MathShare stylesheet. Oh well, once you get the head version of MathLive, that should take care of it.

**Comment by NSoiffer** [comment]
It took awhile to resolve the build issues in MathShare, but they are now
fixed as is the fraction line problem. Thanks!
