### ISSUE TITLE
Bad MathML for overscript

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#276]
## Describe the bug
If you paste in `\overset{?}{=}` to mathlive (![image](https://user-images.githubusercontent.com/1545836/66274677-e9818100-e835-11e9-8d5a-4607f70064ec.png)), the generated MathML is wrong:
`<mover><mi extid="3u3kyd">?</mi></mover>`

It is missing the base (`=`).

**Comment by arnog** [comment]
Thanks for your interest in this. I'll assign the bug to you. But you're right, it looks like the MathML generation is broken right now. I'll have a look.

**Comment by arnog** [comment]
OK, I've pushed a fix to master, it should be good now.

**Comment by bhujoshi** [comment]
@arnog conversion of  latex `\overset{?}{=}` to mathml is already this `<mover  ><mo>=</mo><mi>?</mi></mover>` which looks correct. I think already solved by @NSoiffer https://github.com/NSoiffer/mathlive/commit/2e55160feb2601604c2462042510f47f54adabf8#commitcomment-35381835

**Comment by arnog** [comment]
Ok, fantastic. Thanks for looking into this. I'll close the bug.
