### ISSUE TITLE
Undo deletes initial contents

### ISSUE THREAD

**Issue by DiogoLeite96** [arnog/mathlive#285]
### Description

On the undo stack is (apparently) the initial contents of the editor. I don't believe that is correct. This leads to some things that seems wrong.

Overall, I get the feeling there is an off-by-one or fence post error going on.

### Steps to Reproduce issue
Start with mathlive/examples/basic/index.html. This starts with f(x)=
Click after the =. Type ctrl-z/undo. The entire expression disappears. This seems wrong -- nothing should happen since there is nothing typed to undo.

### Steps to Reproduce variation on issue
Start with mathlive/examples/basic/index.html. This starts with f(x)=
Click after the =. Type a
Type ctrl-z/undo. The a goes away. Good.
Type ctrl-z/undo. The entire expression disappears (as above).

**Comment by arnog** [comment]
Fixed now.
