### ISSUE TITLE
ML__scroller overlapping keyboard toggle

### ISSUE THREAD

**Issue by johanneswilm** [arnog/mathlive#290]
In version 0.32.3, sometimes when I first click on an empty mathfield so it gets focus, mathlive creates two elements of the type `<div class="ML__scroller" ...></div>`. One of these two then overlaps the keyboard toggle. When I move focus somewhere else on the page and then back to the mathlive field, it creates two more without removing the existing ones. I can continue with that indefinitely so that there are more and more elements of that type.

**Comment by arnog** [comment]
I can't reproduce this.

The `"ML__scroller"` elements are created on pointer down. They intentionally hide the keyboard toggle to avoid triggering it while dragging/selecting.

They are removed when the pointer up event is received.

They could persist if there is some interruption after the point down event (for example if hitting a breakpoint in the debugger) that would prevent the pointer up event from being generated.

Do you have a JSFiddle reproducing the problem?

**Comment by johanneswilm** [comment]
I can try to make one. But it's in the middle of my code so maybe something on my side blocking it. So let me try to find it first. Are the scroller elements supposed to cover the entire screen vertically? For me it's also blocking a submit button that just happens to be near the toggle switch.

**Comment by arnog** [comment]
Yes, they block the entire region on the left and right of the mathfield, but since they should be up only during a drag operation inside the mathfield, it should not interfere with the rest of your content.

**Comment by johanneswilm** [comment]
@arnog I did a little debugging. The issue seems to be that the anchor here [1] is undefined. Therefore the section below it is never called including the part where it sets the event handlers for the mouseup event.

This is happening on a simple mousedown on the math field just to move the focus there.

If this is not enough to give you a clue, I can try to make an example, but I fear it has something to do with me using it as part of a modal dialog with a z-index value higher than 100 and absolute positioning.

[1] https://github.com/arnog/mathlive/blob/872cb7627c4c9a4729e2eedf8f9f274ee57fb48f/dist/src/editor/editor-mathfield.js#L777

**Comment by arnog** [comment]
Thanks, that's a useful clue. I tried to reproduce it, but still no luck. I've made a change so that the divs will only be added if the anchor is found. That should address the problem with the scroller divs, but I'm afraid you'll have other issues when drag selecting if the anchor can't be found.

**Comment by johanneswilm** [comment]
Ok, under what circumstances would one do this dragging? Is this as part of editing one formula in which one would drag part of a formula to some other place within that same formula?

**Comment by arnog** [comment]
You would do this dragging when selecting a portion of the formula: 
(1) press the mouse button down in a part of the formula 
(2) while holding the mouse button, move the mouse pointer to another part of the formula
(3) release the mouse button.
That's one dragging operation.

**Comment by arnog** [comment]
Did this happen on mobile by any chance? There was an issue that occurred on browsers that do not support PointerEvent that could explain this (at the time Safari on iOS did not support PointerEvent, it does now).

**Comment by johanneswilm** [comment]
Unfortunately, no, this was in the regular browser.

**Comment by arnog** [comment]
Was never able to reproduce it, but I got rid of the `scroller` divs altogether so it should no longer occur.
