### ISSUE TITLE
FEATURE REQUEST: support \widehat, \overbrace, \underbrace

### ISSUE THREAD

**Issue by nguyenvanthinh06** [arnog/mathlive#292]
Can you help me? how to add new latex for mathlive? 
new latex list: '\widehat, \overbrace, \underbrace'

**Comment by arnog** [comment]
You can specify a dictionary of LaTeX macros to like this:
```javascript
mf.$setConfig({
   macros: {
   'smallfrac': '^{#1}\\!\\!/\\!_{#2}',
}
});
```
The code above will support the following notation:
```tex
\smallfrac{5}{16}
```

However, for commands that require more complex drawing, you will need to make changes to the core Mathlive rendering engine. See #182, #180, #126 for similar requests.

**Comment by nguyenvanthinh06** [comment]
Thank @arnog!
It seems that the 3 latex above is a special case where mathlive does not support each item, so I cannot combine them.

I want it to look like katex support: https://katex.org/docs/supported.html

Can you add this feature latexes support?

**Comment by arnog** [comment]
Changing the title to better reflect the issue.
