### ISSUE TITLE
examples page broken

### ISSUE THREAD

**Issue by johanneswilm** [arnog/mathlive#294]
The link https://mathlive.io/deploy/examples/ leads to a 404 and https://mathlive.io/examples/ doesn't work either as the examples there seem broken.

**Comment by arnog** [comment]
The correct URL is https://mathlive.io/examples/ and it was indeed broken. It should be fixed now.

**Comment by johanneswilm** [comment]
@arnog The link on https://github.com/arnog/mathlive/ leads to https://mathlive.io/deploy/examples/ .

**Comment by arnog** [comment]
Ooops... Yep, that link was out of date. Updated now.
