### ISSUE TITLE
Problems in the contribution guide

### ISSUE THREAD

**Issue by bhujoshi** [arnog/mathlive#311]
I followed the contribution guide for start development and npm start and npm run build commands giving the error. 
**missing script: watch-js**

**To Reproduce**
Follow the contribution guide https://github.com/arnog/mathlive/blob/master/tutorials/CONTRIBUTOR_GUIDE.md

**Comment by arnog** [comment]
I can't reproduce this. Which version of npm are you running (`npm -v`)?

**Comment by NSoiffer** [comment]
I see this problem also. I have npm v6.5.0. I tried blowing away node_modules and re-installing and the problem is still there.

I also get "3 high severity vulnerabilities":

```
mathlive-> npm audit

                       === npm audit security report ===

# Run  npm update handlebars --depth 3  to resolve 3 vulnerabilities

  High            Arbitrary Code Execution

  Package         handlebars

  Dependency of   nyc [dev]

  Path            nyc > istanbul-reports > handlebars

  More info       https://nodesecurity.io/advisories/1316




  High            Arbitrary Code Execution

  Package         handlebars

  Dependency of   nyc [dev]

  Path            nyc > istanbul-reports > handlebars

  More info       https://nodesecurity.io/advisories/1324




  High            Prototype Pollution

  Package         handlebars

  Dependency of   nyc [dev]

  Path            nyc > istanbul-reports > handlebars

  More info       https://nodesecurity.io/advisories/1325
```

**Comment by arnog** [comment]
npm 6.5 is from November 2018. The current version is 6.13.2. Try to update and see if it still happens.  The error log is very confusing. "Couldn't find "watch-js". Did you mean "watch-js"?"

The security notices are probably not related. I don't see them either. Try to do a "npm update", or follow the instructions from the notice (i.e "npm update handlebars --depth 3").

**Comment by NSoiffer** [comment]
Updating npm and then 'npm install' after remove 'node_modules' solved the start problem for me. I still see the vulnerabilities warning. Running `npm audit fix` solves that problem.

**Comment by arnog** [comment]
Great. There's still something a bit puzzling: the package.json file for the project requires npm 6.7 or later, so you should have at least gotten a warning. Could you check your version of the package.json file and look for the `engines.npm` entry?

**Comment by NSoiffer** [comment]
```
"engines":  {
  "npm": ">=6.7",  
  "node": ">=10.0" 
},
```

**Comment by arnog** [comment]
OK, so, it turns out that the "engines" property is checked when doing a `npm install` of the package (mathlive) as a dependency. Not when actually running the package (as you are here). 
So... it looks like we would need to add an explicit version check at build time.
