### ISSUE TITLE
Missing documentation for smartMode

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#312]
## Description
The documentation for configuration options (`docs/tutorial-CONFIG.html`) is missing documentation on `smartMode`.

Somewhat separately, I think `smartMode` should be on by default (should be set in $setConfig in editor-mathfield.js). If that's controversial, I guess there should be separate issue to argue the pros and cons.

**Comment by arnog** [comment]
Fixed in 0.34
