### ISSUE TITLE
Can't arrow through functions like "sin"

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#318]
**Describe the bug**
The left/right arrow keys typically move from one character to the next. However, for`sin`, etc., they jump over the function name. 
**To Reproduce**
1. Type `sin(x)`
2. [insertion cursor at end of expression]. Hit left arrow three times. Insertion cursor is now after `sin` and before `(`.
3. Hit left arrow. Insertion cursor is at the start of the expression.

**Expected Behavior**
I expected the insertion cursor to move character by character.  Delete and Backspace behave similarly. I.e., if you type `sin` and hit backspace, you don't have `si`, you have an empty input field.

**Comment by leerobert** [comment]
I'd argue thats the expected functionality. sin/cos are functions and the keyboard is for parsing mathematical operators. If I want to delete the sin function I shouldn't have to delete 3 letters.

**Comment by arnog** [comment]
Indeed, "sin" is an atomic operator by design. If you desire a different behavior, you can override the default inline shortcuts.
