### ISSUE TITLE
Vector or bar signs are not growing with bottom content

### ISSUE THREAD

**Issue by Krecik-pam** [arnog/mathlive#338]
**Describe the bug**
Horizontal sign for vector or arrow should be for whole length of its content. For now doesn't matter how many letters are in contetnt

**To Reproduce**
[Steps to reproduce the behavior, for example:]
1. use \vec or \bar
2. put value '2\cdot 22222'
3. arrow for vector sign  has solid length

**Expected behavior**
- Arrow for \vec should has the same length as text in the bottom

[Is this a regression: did it use to work in a previous version?]
no

**Screenshots**
![bar](https://user-images.githubusercontent.com/59367472/71587992-2781fe80-2b20-11ea-83f7-2e1f55795b82.png)

**Source Code**

**Environment**
- Device: [PC]
- OS: [Win10]
 - Browser [Chrome  79.0.3945.88 (Official Build) (64-bit), firefox 71.0 (32-bit)]
 - Version []

**Comment by arnog** [comment]
Note that this behavior (no stretching of `\vec` and `\bar`) is consistent with the Latex behavior. The proper way to have a stretchy vector is to use `\overrightarrow{2\cdot22222}` or `\overline{2\cdot22222}`. However, these commands are currently not supported in MathLive.
