### ISSUE TITLE
Feature Request: Readonly mode

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#339]
# Problem

I currently use katex when I am just displaying math formulas somewhere where I don't want the user to edit them. Sometimes though users want to select and copy these formulas into a mathfield though to edit them / reuse them, which doesn't work per se. My current workaround for this is to offer a copy-to-clipboard button next to the katex-formula that appears on hover, but that does not feel as natural / the same as in the mathfield and doesn't allow to select parts.

# Solution

What about a simple "readonly"-option for mathfields, that make them ignore all key-presses, does not show an insert-caret and doesn't allow to focus? That would work like "normal" text then and would guarantee complete compatibility with other "mutable" mathfields.

**Comment by Khazuar** [comment]
@arnog Any news on this?

**Comment by ChristopherChudzicki** [comment]
This would be great. I've been meaning to migrate my project from MathQuill to MathLive. Since MathQuill supports static math fields, the migration would be much simpler if MathLive also supported a read-only field.

**Comment by arnog** [comment]
I haven't been able to look at this yet. I anticipate it shouldn't be too hard. I will look at it after 1/19.

**Comment by NSoiffer** [comment]
I think you could use just the static math (what you get from `renderMathInDocument`, not the live mathfield you get from `makeMathField`). You just need to attach a context menu listener to it. The static math stores both the MathML (inside the element with` class='sr-only'`) and the TeX (`data-original-content`), so both of those can be gotten with a single line of JavaScript. If you want to be able to select some subpart, then that would be more work.

I think the ability to copy static math into various formats is something useful so I agree with your idea that this should be part of mathlive.
