### ISSUE TITLE
Mathfield doesn't conserve `{`, `}`

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#349]
**Describe the bug**
Braces in 

**To Reproduce**
[Steps to reproduce the behavior, for example:]
1. Go to https://mathlive.io/
2. Click on "Show code section"
3. Type `a` `^` `b` `+` `c`. The code section shows the latex-content of the field to be `a^{b+c}`. Nice.
4. Select and copy to clipboard either the content of the mathfield or the latex-content in the code-section.
5. Insert the clipboard content into the mathfield.
6. Notice that the code-section now states the mathfield content is `a^{\mleft.a+b\mright.}`

**Expected behavior**
The content should remain the same, which is `a^{b+c}`.

I did not expect the insertion of the `\mleft.`. When inserting `{}` into the mathfield, the result even is `\left.\mleft.\mright.\right.`, completely removing the braces.

**Environment**
- Device: PC
- OS: Windows 10
- Browser: Chrome 79.0.3945.117 (Official Build) (64-bit)

**Comment by ChillingVan** [comment]
Currently my solution to insert x^n is 
```
mathField.$insert('#@^')
mathField.$keystroke('Left')
mathField.$insert('#0')
```
This may help.

**Comment by arnog** [comment]
@ChillingVan Doesn't `mathField.$insert('#@^{#?}')` do what you need?

**Comment by ChillingVan** [comment]
> 
> 
> @ChillingVan Doesn't `mathField.$insert('#@^{#?}')` do what you need?

Hello. 
The ```mathField.$insert('#@^{#?}') ```
will be
```
^{\mleft.\placeholder{}\mright.}
```
If 3^9 is input, it will be 
```
3^{\mleft.9\mright.}
```
The \mleft. and \mright. seems to be not be able to be recognized by other latex renderer.
But ``` 3^9 ``` or ``` 3^{9} ``` can be recognized.

**Comment by Khazuar** [comment]
We're using katex in some places to show static math, and indeed `\mleft.x\mright.` is not recognized. We need our latex to be portable and as minimal/clean as possible, so it can be written and read by people *and* as many different latex-renderers as possible.

![image](https://user-images.githubusercontent.com/3444034/72807289-5ee35700-3c57-11ea-828b-8886b6ea0a06.png)

**Comment by arnog** [comment]
OK, got it. So there are a couple of different issues. 

First, there are cases where there shouldn't be an insertion of `\mleft.` and `\mright.` (which are no-ops anyway). I'm going to look at this. 

But there will still be cases where some legitimate `\mleft(`, `\mright)` will be inserted. Two options for this: don't use smartfence mode or strip the `\mleft` `\mright` before using with another renderer (or define a macro for those renderers).

**Comment by Khazuar** [comment]
> But there will still be cases where some legitimate \mleft(, \mright) will be inserted.

**Comment by arnog** [comment]
Yes, `\mleft` and `\mright` are used to provide proper spacing with scaled fences. 

For example, `\sin\left(x\right)` has too much space between the "sin" function and the parentheses.

On the other hand, `\sin(x)` has proper spacing, and so does `\sin\mleft(x\mright)`
