### ISSUE TITLE
`\operatorname{\text{fubar}}` cannot be inserted

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#354]
**Describe the bug**
If I insert `\operatorname{\text{fubar}}` into a mathfield, it get `\operatorname{text}`. 

**To Reproduce**
1. Go to mathlive.io
2. Paste `\operatorname{\text{fubar}}` into the mathfield
3. The code section shows `{fubar}` vanished

**Expected behavior**
The mathfield should show `fubar` with proper operatorspacing and whitespaces in the text (compare `x\operatorname{\text{is prime}}`) and the latex-content should contain `\operatorname{\text{fubar}}`.

**Why I am writing `\operatorname{text{...}}` instead of `\operatorname{...}`**
The handling of `\operatorname` is not uniform in different latex-implementations:

Latex impl               |  \text{...} | \operatorname{...} | \operatorname{\text{...}}
-------------------- |--------- | -------------------- | --------------------------
Latex(amsmath + amsopn) | no operatorspacing | no whitespaces in text | all good
Katex                    | no operatorspacing | no whitespaces in text | all good
MathJax                | no operatorspacing | all good | all good
Mathlive               | no operatorspacing | all good | **broken**

I want the latex we use to look correctly in a many dialects of latex as possible, especially since I am dependent on Katex right now (see #339) and I want to show the same formulas in all places, so it has to be `\operatorname{text{...}}` unfortunately, even though I have the `text`-noise in the markup.

**Environment**
- Device: PC
- OS: Windows 10
 - Browser Chrome
 - Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by arnog** [comment]
For reference, the actual TeX implementation does render this as expected (see https://www.quicklatex.com/) which is a strong argument for the behavior that MathLive should have.

**Comment by Khazuar** [comment]
https://www.quicklatex.com/ shows `\operatorname{fu bar}` visually as "fubar" to me. So mathlive is behaving differently.

**Comment by arnog** [comment]
I think I worded this poorly: MathLive should render `\operatorname` more closely to what TeX would do, as demonstrated by QuickLatex. It currently does not, but it should, which is the issue. It is a stronger argument (to me) about what the correct behavior should be than what other (non reference) renderers might be doing.
