### ISSUE TITLE
HTML checker says role="none presentation" on textarea is not valid

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#36]
Title says it all -- from the w3c HTML checker:

`Error: Bad value none for attribute role on element textarea.`
`... <textarea class="ML__textarea--textarea" autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" aria-hidden="true" role="none presentation" aria-label="">...`

Looking at the valid values, only `aria-multiline` appears to be legal.

**Comment by arnog** [comment]
That would seem to conflict with section 2.9 of the ARIA usage guide (https://www.w3.org/TR/using-aria). See also section 2.8 about validators.

**Comment by NSoiffer** [comment]
I don't see the conflict. That section says it removes it from the accessibility tree, but that's only valid to do for some elements.

The ARIA usage guide says:
> 2.4 Fourth rule of ARIA use
>Do not use role="presentation" or aria-hidden="true" on a visible focusable element .
> Using either of these on a visible focusable element will result in some users focusing on 'nothing'.

`textarea` is focusable.

The [HTML spec](https://www.w3.org/TR/html51/sec-forms.html#the-textarea-element) says don't set the role for textarea.

**Comment by arnog** [comment]
I think this has been fixed. Please re-open if that's not the case.
