### ISSUE TITLE
Wrong selected element when click placeholder

### ISSUE THREAD

**Issue by ChillingVan** [arnog/mathlive#364]
**Describe the bug**
Wrong selected element when click placeholder.
When click one placeholder in some situations, the selected point is wrong.

**To Reproduce**

1. Input \prod from virtual keyboard.
2. Input parenthesis
3. Input differentialDx
4. Click the placeHolder of the differential
5. The selected point will be "d" instead of the placeholder

**Screenshots**
![图片](https://user-images.githubusercontent.com/7666419/72882883-574aad80-3d3e-11ea-8678-38876c2b43f1.png)

**Source Code**
The field isSelected in MathAtom of the "d" is true. But the isSelected in MathAtom of the placeHolder is false.

**Environment**
- Device: [pc]
- OS: [Windows]
 - Browser [chrome]
 - Version [0.33.2]

**Comment by ChillingVan** [comment]
Related value when debug:
![图片](https://user-images.githubusercontent.com/7666419/72884432-1011ec00-3d41-11ea-9669-ea007b8efe94.png)

![图片](https://user-images.githubusercontent.com/7666419/72884697-8282cc00-3d41-11ea-8095-c1f43aa8d7f7.png)

**Comment by ChillingVan** [comment]
It may be caused by this code in edior-editableMathlist:
```
        if (extent === 0 && this.anchor().type === "placeholder") {
            // select the placeholder
            newPath[newPath.length - 1].offset = 0;
            extent = 1;
        }
```

**Comment by ChillingVan** [comment]
It seems this code can solve this issue:
![图片](https://user-images.githubusercontent.com/7666419/73636524-fbb6e300-46a0-11ea-9d0e-538ecc97aaa7.png)

**Comment by arnog** [comment]
Thanks for reporting and looking into this. The fix you suggest is close, but not quite right. The proper fix is to set the offset to be the offset of the anchor - 1, since this is where the placeholder will always be as per the test on line 277.
