### ISSUE TITLE
Redundant caret after supsub element

### ISSUE THREAD

**Issue by ChillingVan** [arnog/mathlive#373]
## Description
There are more than one ML__caret element when insert supsub element. For example, ∫ or log

![图片](https://user-images.githubusercontent.com/7666419/74399421-aecbcd00-4e55-11ea-9af8-d05cacaa6d2c.png)

### Expected Behavior

It should be only one caret instead of two after the supsub element

## Steps to Reproduce

1. Insert the integrate symbol from virtual keyboard
2. See the element tree in chrome debug tool.

### Environment

**Operating System**
[macOS, Windows, iOS. Include the version if possible]

**Browser** [Safari, Chrome, IE, Firefox, etc...]

**Comment by ChillingVan** [comment]
The solution is remove the code below:
![图片](https://user-images.githubusercontent.com/7666419/74399643-695bcf80-4e56-11ea-8b53-6ec47e93137c.png)

**Comment by arnog** [comment]
Good find!
