### ISSUE TITLE
Need macros support in MathLive.latexToMarkup() 

### ISSUE THREAD

**Issue by bhujoshi** [arnog/mathlive#378]
## Description

I am able to write macros commands in MathLive.makeMathFeild() but I want to write macros commands in  MathLive.latexToMarkup(). Is it possible? 
If Yes can you show me the way?

**Comment by arnog** [comment]
Yes, it's possible. This is a documentation issue: the `MathLive.latexToMarkup()` functions takes a fourth (undocumented) parameter, which is a macros dictionary (same as the `config.macros` parameter of `makeMathField`
