### ISSUE TITLE
latexToAST Flattening Lists Of Lists

### ISSUE THREAD

**Issue by ClintonWB** [arnog/mathlive#379]
## Prerequisites

-   [X] New issue

## Description

latexToAST flattens lists of lists to single lists, instead of lists containing lists.

### Actual behavior

```javascript
MathLive.latexToAST("((1,2),(3,4))")
```
returns

```javascript
{"fn":"list","arg":[
    {"num":"1"},
    {"num":"2"},
    {"num":"3"},
    {"num":"4"}
]};
```
### Expected Behavior

```javascript
MathLive.latexToAST("((1,2),(3,4))")
``` 
returns 
```javascript
{"fn":"list","arg":[
    {"fn":"list","arg":[
        {"num":"1"},
        {"num":"2"}
    ]},
    {"fn":"list","arg":[
        {"num":"3"},
        {"num":"4"}
    ]}
]}
```

## Steps to Reproduce

Invoke `MathLive.latexToAST("((1,2),(3,4))")`

### Environment

**Operating System**
Windows 10 Home Version 10.0.18362 Build 18362
**Browser**
Firefox 73.0
Chrome 80.0

**Comment by arnog** [comment]
Lists of lists are now parsed correctly: `$$ \left\lbrack\left\lbrack1,2\right\rbrack,\left\lbrack3,4\right\rbrack\right\rbrack $$`
