### ISSUE TITLE
select sub-region of mathField that matches latex string?

### ISSUE THREAD

**Issue by zoranpopovic** [arnog/mathlive#387]
what is the most straightforward way to search for a latex string (e.g. `\frac{2}{4}` ) in an active MathField and if found, select the occurrence of subexpression in the mathField.  I can think of a way of creating a DOM-detached mathField just with  `$$\frac{2}{4}$$` and then doing a deep comparison of the resulting spans with the existing active mathField, but that sounds painful.  Also, not clear how i would select a specific portion programmatically after the span section is found. search probably needs to be done on MathAtom internal representation, but those traversal functions are not in documentation.

Any help would be greatly appreciated. i'm working on a speech driven selection and this is a key missing component.

**Comment by zoranpopovic** [comment]
Ok, so after reading the code, it seems like MathList is the key entity to manipulate.  I've gotten it to work with the following code, I was wondering if anyone has suggestions for a more efficient or accurate way to do it.
```
find() {
      // this.mf is main mathfield.  this.smf is mathfield with subexpression to search
      const item = this.smf.$text("latex");
      const item0 = this.smf.mathlist.root.body[1].latex; // ignore first no-op atom
      const item_extent = this.smf.mathlist.root.body.length - 1;

      // find all paths that start with the same atom as a search item
      var possible_starts = this.mf.mathlist.filter(
        (path, atom) => atom.latex === item0,
        1
      );
      window.console.log(possible_starts);

      // augment all paths with extent, and adjust start
      var possible_finds = possible_starts.map(s => {
        // add extent at the end of each path (same as search item)
        const with_extent = `${s}#${item_extent}`;
        // move each path one back to start of possible find
        const one_back = with_extent.replace(
          /:([0-9]+)\/#/g,
          (m, n) => `:${parseInt(n) - 1}/#`
        );
        return one_back;
      });
      window.console.log(possible_finds);

      // identify all equal subexpressions by comparing latex of each path selection
      var finds = possible_finds.filter(f => {
        this.mf.mathlist.setPath(f, item_extent);
        var fnd = this.mf.$selectedText("latex");
        return fnd === item;
      });
      window.console.log(finds);
      if (finds.length) {
        this.mf.mathlist.setPath(finds[0], item_extent);
        this.mf._requestUpdate();
      }
    }
```

**Comment by arnog** [comment]
That's a reasonable approach, although that requires using some internal APIs that could change in future versions. This is a difficult problem in general, but looks like this approach might satisfy your needs for now.
Just out of curiosity, would you have the possibility of tagging sub-expressions (i.e. using `\cssId`) and would that help with your use case at all?

**Comment by zoranpopovic** [comment]
I wish, but the actual voice commands are something like 

> distribute 3 open x minus 2 close into 3x minus 6

which would then search for `3(x-2)` subexpression in the equation, and replace it with `3x-6`.  so commands could be arbitrary thing people say, meaning pre-populated cssid would not help.

**Comment by arnog** [comment]
Oooh... You're doing voice selection!? Very cool. Yeah, so you would need something like `mf.find("3(x-2))`... In the meantime, your approach is probably the best for now.

**Comment by NSoiffer** [comment]
@zoranpopovic: I've been very interested in voice recognition of math for many years. I'm very keen to hear more about what you are doing, how you are doing it, and what kind of problems/error rates you are getting. Based on Arno's response, I suspect he may be interested also. Can you tell us about your project?

**Comment by zoranpopovic** [comment]
@arnog would the above approach work in 0.51 given that i was using unexposed methods, and now everything is transpiled from ts?

**Comment by arnog** [comment]
Yes, that should still work. A few things have been renamed, though. For example, `mf.mathlist` is now `mf.model`.

**Comment by arnog** [comment]
The `find()` method has now been added to `MathfieldElement`. Its argument is either a latex string or a regular expression. It returns an array of ranges matching the search input.

**Comment by arnog** [comment]
The `find()` method has now been added to `MathfieldElement`. Its argument is either a latex string or a regular expression. It returns an array of ranges matching the search input.

For example the following code snippet will add a yellow background to the fractions in the expression:

```javascript
    mf.find(new RegExp(/^\\frac{[^}]_}{[^}]_}\$/)).forEach((x) =>
        mf.applyStyle({backgroundColor: "yellow"}, x, {
            suppressChangeNotifications: true
        });
    });
```

**Comment by zoranpopovic** [comment]
@arnog that's awesome.  Things will be so much cleaner with this.  thanks for adding it.

**Comment by arnog** [comment]
Upon further reflection, it seems like a `replace()` method would be useful as well. It's been added now. It's similar to the `String.replace()` method and can take either string or regular expression as input pattern and a string or function as a replacement pattern.

You can use it for example to inverse fractions:
```javascript
    mf.replace(/^\\frac{([^}]*)}{([^}]*)}$/, '\\frac{$2}{$1}');
```

I should point out that there are limitations to this approach, of course, since RegEx cannot parse Latex code, so the example above will only work in some simple cases, but still, this might be useful.

**Comment by stefnotch** [comment]
Out of curiosity, will there be a variant with MathJson?
