### ISSUE TITLE
Infinite loop when extracting ASCIIMath

### ISSUE THREAD

**Issue by arnog** [arnog/mathlive#394]
Issue submitted by https://github.com/shenzhuxi in #323 

---
version: 0.35.1

```javascript
<script type="module"> 
import MathLive from 'mathlive/dist/src/mathlive.js'; 
const mf = MathLive.makeMathField('mathfield', 
{ 
smartMode: true, 
virtualKeyboardMode: 'manual', 
onContentDidChange: mf => { 
console.log(mf.$text('ASCIIMath'));//**You need to output with ASCIIMath to reproduce this problem.**/
 }, 
}
); 
</script>
```

Here is the fix:

--- a/dist/src/editor/outputASCIIMath.js
+++ b/dist/src/editor/outputASCIIMath.js
@@ -73,6 +73,7 @@ export function toASCIIMath(atom, options) {
         let result = '';
         if (atom.length === 0) return '';
         if (atom[0].type === 'first') atom.shift();
+        if (atom.length === 0) return '';

For the '^' problem, I just figured out that Mathlive considers it as "msubsup" instead of power.
Atom {mode: undefined, type: "msubsup", body: "​", color: undefined, backgroundColor: undefined, …}
"mode: undefined" causes infinite loop in outputASCIIMath.js

@@ -88,6 +89,7 @@ export function toASCIIMath(atom, options) {
                 result += toASCIIMath(atom[i], options);
                 i++;
             }
-             result += toASCIIMath(atom.slice(i), options);//infinite loop here
+            result += toASCIIMath(atom.slice(i)[0], options);

**Comment by shenzhuxi** [comment]
I just provided a quick (and very probably dirty) fix and still haven't figured out why it doesn't happen to other formats. Was it supposed to be "mode: undefined"?

**Comment by arnog** [comment]
No, the mode is not supposed to be undefined. There was a bug elsewhere that caused it to be, though.
