### ISSUE TITLE
Macros don't work properly

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#395]
## Description
Expanded macros are wrapped in `{...}` and text in them doesn't work properly.

### Actual behavior
I defined a macro `myMacro: "\\operatorname{\\text{#1}}"` via the mathfield configuration. When I insert `\myMacro{fu bar}` though, it's displayed as a single word:
![image](https://user-images.githubusercontent.com/3444034/77911473-23858a00-7291-11ea-8d7c-b32bb3682bed.png)

Also, the latex and latex-expanded of the mathfield are `{\myMacro{fubar}}` and `{\operatorname{fubar}}` respectively.

### Expected Behavior
I expect `\myMacro{fu bar}` to look like `\operatorname{\text{fu bar}}`:

![image](https://user-images.githubusercontent.com/3444034/77911560-4b74ed80-7291-11ea-97f5-2cc09bb82226.png)

The latex of the mathfield should be `\myMacro{fu bar}` and the latex-expanded `\operatorname{\text{fu bar}}`.

## Steps to Reproduce

See https://jsfiddle.net/51wjztf0/2/

### Environment

**Operating System**
[Windows 10]

**Browser**
Chromium Edge

**URL**
See https://jsfiddle.net/51wjztf0/2/

**Comment by Khazuar** [comment]
To clarify: I am very happy with and actually expect that the macros don't *behave* like their expanded form (e.g. that you can't edit the text in them). But unfortunately they don't even look like or expand like what I thought.

**Comment by arnog** [comment]
Fixed in master:head
