### ISSUE TITLE
integral intervals missing in mathJSON

### ISSUE THREAD

**Issue by Paosder** [arnog/mathlive#396]
## Prerequisites

-   [ O ] New issue

## Description

When call `$text` using 'json' param, integral symbol lost intervals like below.

![image](https://user-images.githubusercontent.com/20926881/77977154-df9a8f80-7339-11ea-92af-cc7acfccb525.png)

### Expected Behavior

Parse intervals correctly.

## Steps to Reproduce

0. Go to https://mathlive.io/examples/basic/index.esm.html
1. type `\int_{a}^{b}x^2dx`
2. Compare text area and json area. Something is went wrong.

### Environment

**Operating System**
Windows 10

**Browser**
Chrome

**Comment by arnog** [comment]
Integrals are now parsed correctly. The json returned for `\int_{a}^{b}x^2dx` is:
```
[
  "Integrate",
  ["Lambda", ["Square", "_"]],
  ["Triple", "x", "a", "b"]
]
```
