### ISSUE TITLE
Bug in math.js example on your website

### ISSUE THREAD

**Issue by J2thearo** [arnog/mathlive#397]
## Description

Hello there,

your library is very impressive and I have decided to use it in my future projects.

The math.js example on your website https://mathlive.io/examples/mathjs/ does not seem to work properly.  No matter what I type into the input box, it always shows the emoji. I guess thats not what you intended to demonstrate. It would be great if you could take a look at it, thank you.

![Screenshot 2020-03-31 21 55 56](https://user-images.githubusercontent.com/55392372/78069633-b78f4880-739a-11ea-9110-d42bdffa45d9.png)

Regards,
Jaro

**Comment by arnog** [comment]
The repo had an out of date version of the mathjs library. Updated to the cdn version.

**Comment by J2thearo** [comment]
Thank you for your quick reply! I just checked the example again and the bug is still there.

**Comment by arnog** [comment]
The bug is fixed in GitHub in 0e30ed1 . The website will need to get updated later. In the meantime, you can look at 0e30ed1 for the fix (which basically only involves updating to a more recent version of math.js)
