### ISSUE TITLE
Inline shortcuts trigger in text-mode

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#401]
## Description

Inline-shortcuts are applied even while typing text.
![image](https://user-images.githubusercontent.com/3444034/78454067-089e8580-7696-11ea-948a-58fa48406b45.png)

### Actual behavior

When typing in text-fields, shortcuts are matched that were only meant for inputting math.

### Expected Behavior

I don't expect shortcuts to work in text-mode. It would make sense to have different shortcut-sets for math and text mode at least, since both environments probably have very different requirements.

## Steps to Reproduce

1. Go to https://jsfiddle.net/549pgj7k/1/
2. Click into the fiddles mathfield
3. Type `N`
4. See how `\N` is inserted.

### Environment

**Operating System**
Windows 10

**Browser**
Chromium Edge

**URL** 
https://jsfiddle.net/549pgj7k/1/

**Comment by arnog** [comment]
When specifying a shortcut, it is possible to restrict the shortcut to specific context, including only certain modes. In your example, you would use:
```
      inlineShortcuts: {
      	"N": { mode: "math", value: "\\N"}
      },
```
The documentation about this is in the changelog, but I will also move it to CONFIG.MD and to the shortcuts example.

**Comment by Khazuar** [comment]
ah, thanks!
