### ISSUE TITLE
Does MathLive use KaTeX or MathJax for rendering?

### ISSUE THREAD

**Issue by leontepe** [arnog/mathlive#402]
And what were the reasons for prefering one over the other?

**Comment by arnog** [comment]
MathLive includes its own rendering engine. MathLive can be used to render static math as well, although it was optimized for editing.

**Comment by leontepe** [comment]
What was the reason for this? Were MathJax or KaTeX not suited for this purpose??

**Comment by arnog** [comment]
Editing and displaying text (and math formulas) are vastly different problems.

Imagine that you are dealing with "\sin x". Now, to display it you must parse that string, build a tree that represent its content (a "sin" operator and a "x" symbol next to each other), then generate some rendering abstraction (probably another tree) that represents what must be displayed (a "sin" string in a certain font, an "x" in another font), then actually render that to your target rendering environment (HTML for example, as a set of `<span>` tags with appropriate attributes and classes). That's basically what KaTeX and MathJax do, although they each have their own way of doing it (they use different intermediate representations, and can target different final rendering models, for example).

For editing, you still need to do the first part, parsing the string and having an abstract representation of it. But now, you must also be able to handle editing operations on that, for example if the `backspace` key is pressed when the cursor is after "sin". You must have a way of not only "going down", but also "going back up", that is reconstructing the input, which now would be just "x". In addition to all the logic necessary to handle the editing (responding to keyboard input, keeping track and displaying a selection, handling mouse input), you also need data structures that can support being modified and still reconstruct TeX input.

It might have been possible to start with KaTeX or MathJax, and heavily modify them to do this, but this would have been a much bigger effort. And I was kinda curious what it would take to implement an engine to do the TeX rendering as well :)

**Comment by leontepe** [comment]
@arnog Well actually that's quite a good reason to implement it yourself, I'm curious as well and would love to do so too x)

But wouldn't it be able to use the intermediate representation of either MathJax or KaTeX (which I think, as of now, doesn't even have one, though...?)  and apply the operations needed for editing directly on that tree? Then, as I think of it, you wouldn't need to transform it back and forth between the LaTeX string, since you can store the math as the intermediate representation and also render it by just passing it to the respective render engine (without LaTeX to intermediate representation conversion).

I haven't had the time yet to look into your code yet, but how do the data structures you used in MathLive differ from the ones KaTeX and MathJax use as their intermediate representations? Do they share the same basis with additional attributes or is it completely different?

And, since I'm curious, how much of your time in this project went into creating the rendering and how much into making it editable and implementing the logic? I believe the rendering part probably took the most time, right?

**Comment by arnog** [comment]
> But wouldn't it be able to use the intermediate representation of either MathJax or KaTeX 

That's possible. Might be more trouble than it's worth.

> Then, as I think of it, you wouldn't need to transform it back and forth between the LaTeX string, since you can store the math as the intermediate representation and also render it by just passing it to the respective render engine (without LaTeX to intermediate representation conversion).

There are some editing operations that you can do directly on the intermediate representation. However, you still need to be able to roundtrip: you need Latex -> IR for users to set the initial value of the field, and you need the IR -> Latex so they can read it.

> And, since I'm curious, how much of your time in this project went into creating the rendering and how much into making it editable and implementing the logic? I believe the rendering part probably took the most time, right?

The rendering is fairly straightforward, since it involves implementing a documented layout engine (TeX). Although, the number of oddities and weird corner cases in TeX is daunting (`mathbf{\Gamma}\mathbf{\gamma}`: only one of the symbols is in bold).

But the editing is non-trivial and involves a lot of UX, and you basically have to invent it. I spent more time on the editing than on the core rendering. To give you a rough idea of the complexity of each, the rendering engine is about 15kloc, and the editor 17kloc.
