### ISSUE TITLE
can't click in empty numerator

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#41]
## Description
When the numerator of a fraction is empty, you can't click in it to set an insertion cursor. This likely applies to any 2D notation slot.

## Steps to Reproduce
1. Type 'a/' to get a fraction with 'a' in the numerator and a placeholder in the denominator.
2. Click in the numerator and delete the 'a'
3. Click outside of the fraction so the insertion cursor moves out of the numerator
4. Try to click inside the numerator -- the insertion cursor is placed on the left or right side of the fraction.

It is possible to arrow into the numerator.

**Comment by arnog** [comment]
This was fixed via #20: a placeholder is now automatically inserted, so there's never an empty numerator.
