### ISSUE TITLE
Deactivating smart fences doesn't work

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#412]
##Description

Deactivating the smartFences with `smartFence: false` doesn't turn off all smart-fence functions.

### Actual behavior

In a mathfield with deactivated smart-fences, inserting `\left(\frac{1}{2}\right)` looks like it's supposed to:
![image](https://user-images.githubusercontent.com/3444034/79131984-c669f800-7da9-11ea-9648-62103e5506ae.png)

When I remove the trailing closing parenthesis, it automatically get's replaced by a ghost-parenthesis though:
![image](https://user-images.githubusercontent.com/3444034/79132047-e4cff380-7da9-11ea-93ea-00cf6e98bbde.png)

Typing `)` or `\right)` in it's place inserts a normal parenthesis (so there's virtually no way to fix this):
![image](https://user-images.githubusercontent.com/3444034/79132208-311b3380-7daa-11ea-9faa-145a8b4e51f6.png)

If I instead remove the leading parenthesis, both parentheses disappear:
![image](https://user-images.githubusercontent.com/3444034/79132112-029d5880-7daa-11ea-8514-00b34be76a48.png)

### Expected Behavior

I expect `\left(` and `\right)` to behave the same as `(` and `)` when smart-fences are deactivated. The only difference should be visually, in that `\left(` and `\right)` should scale with what's inbetween them.
When imbalanced `\left(` and `\right)` are inserted, I expect the mathfield to either
* show an error message, like katex does 
![image](https://user-images.githubusercontent.com/3444034/79132493-ba326a80-7daa-11ea-86aa-043019fc23c3.png),
* to treat all `\left(` and `\right)` as `(` and `)` temporarily or
* to use `\right.` and `\left.` to auto-balance (like this: 
![image](https://user-images.githubusercontent.com/3444034/79132821-3fb61a80-7dab-11ea-87ac-bd4993f31ebf.png)). Ideally these would not be included in the `$text`-output.

In general, users get confused a lot when their input is changed automatically. 

## Steps to Reproduce

[Provide steps that are specific and repeatable, if possible]

1. Go to https://jsfiddle.net/o9z8va4j/1/
2. Remove the parentheses

**Comment by arnog** [comment]
> Ideally these would not be included in the $text-output.
They have to be because otherwise it's an unbalanced \left\right command which cannot be rendered by TeX and I don't want to generated invalid Latex.

The behavior to display the "ghost" fence is not related to smartFence. It's the behavior needed to deal with balancing of `\left\right`. However, adding back the parenthesis is part of smartFence and maybe it shouldn't.

Also, if smartFence is off, I could insert a `\right.` instead of `\right)`

I'm not sure exactly what you are trying to do after deleting the closing parenthesis. Are you looking to insert another fence (a square bracket for example)?

**Comment by Khazuar** [comment]
> I'm not sure exactly what you are trying to do after deleting the closing parenthesis. Are you looking to insert another fence (a square bracket for example)?

Usually users want to put the brackets somewhere else. They start with one term and then want to change it to another one, e.g. expand a product.

**Comment by arnog** [comment]
OK,  I've made the changes I discussed above. Let me know if that helps or if you have further suggestions on how to improve it.
