### ISSUE TITLE
MathField Docs broken

### ISSUE THREAD

**Issue by bengolds** [arnog/mathlive#413]
If you click any of the links under Class -> Mathfield on the docs page, they all 404. It appears to be because they're redirecting to `Mathfield.html` instead of `MathField.html`

**Comment by arnog** [comment]
That's an interesting bug... It turns out that the capitalization of that file has changed, but that confused Git. There's a special incantation you have to do to fix it. I'll take care of it the next time I do a docs update, which should be in the next day or so.

**Comment by arnog** [comment]
Done.
