### ISSUE TITLE
toASCIIMath() fails with empty MathField content

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#415]
## Description

`toASCIIMath()` fails with empty MathField content  with error message :
`Uncaught TypeError: Cannot read property 'mode' of undefined`

<img width="1278" alt="Capture d’écran 2020-04-14 à 10 51 51 AM" src="https://user-images.githubusercontent.com/32236491/79199689-04b0f700-7e3e-11ea-841a-efb1b9f1879e.png">

## Fixing
When a MathField is Empty, it's necessary to check one more time in `toASCIIMath() `if the atom list is empty after having shifted the 'first' atom.
I proposed a pull request to fix this  #414

**Comment by arnog** [comment]
Good fix!
