### ISSUE TITLE
Brace disappears when type `/` in smartFence mode

### ISSUE THREAD

**Issue by Paosder** [arnog/mathlive#416]
## Prerequisites

-   [O] New issue

## Description

Brace disappears when type divide(`/`) in smartFence mode.

### Actual behavior

![missing-brace](https://user-images.githubusercontent.com/20926881/79200003-c41ea100-7e70-11ea-9b48-6e2c87ef4b88.gif)

### Expected Behavior

Brace must not disappear when type `/`.

## Steps to Reproduce

1. Type `(1/2`.
2. Brace `(` suddenly disappears.

### Environment

**Operating System**
Windows, MacOS.

**Browser**
Chrome.

**Comment by arnog** [comment]
Thanks for reporting this. The issue should now be fixed. Please open a new issue if there are still some problems.
