### ISSUE TITLE
strikes don't display

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#419]
## Description

Since the last commit, strikes don't display anymore. There is also a display offset downward (which already existed before the last commit).
<img width="1018" alt="Capture d’écran 2020-04-15 à 6 45 04 PM" src="https://user-images.githubusercontent.com/32236491/79358679-331bf880-7f4a-11ea-8db8-f117e79e361a.png">

## Steps to Reproduce
In the test-cases examples, add a new test with
 `latex: 3+\\enclose{updiagonalstrike downdiagonalstrike}[6px solid rgba(205, 0, 11, .4)]{18}+5`

### Environment

macOS Catalina

Chrome, Firefox

**Comment by arnog** [comment]
Thanks for the report! Both issues should be addressed now.
