### ISSUE TITLE
perform['deleteAll'] seems to work not completely

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#420]
## Description

I'm facing a problem when erasing a mathfield with `deleteAll` command : the mathfield display is empty, but `$text` returns the former content.

To check that, I added these 3 lines  in the  test-cases  _index.html_  , after the main mathfield is rendered.
```
console.log('text before deleting', mf.$text())
mf.$perform('deleteAll')
console.log('text after deleting', mf.$text())
```

,and I initiated the mathfield content.
<img width="1322" alt="Capture d’écran 2020-04-17 à 12 13 36 PM" src="https://user-images.githubusercontent.com/32236491/79554004-1268b580-80a6-11ea-913b-5affc95ac157.png">

In fact, it works for he ASCIIMath output 

```
console.log('text before deleting', mf.$text('ASCIIMath'))
mf.$perform('deleteAll')
console.log('text after deleting', mf.$text('ASCIIMath'))
```

<img width="1309" alt="Capture d’écran 2020-04-17 à 12 32 34 PM" src="https://user-images.githubusercontent.com/32236491/79554972-8b1c4180-80a7-11ea-866b-fb5db44e21a5.png">

and for the 'latex-expanded' output

```
console.log('text before deleting', mf.$text('latex-expanded'))
mf.$perform('deleteAll')
console.log('text after deleting', mf.$text('latex-expanded'))
```
<img width="1313" alt="Capture d’écran 2020-04-17 à 12 34 04 PM" src="https://user-images.githubusercontent.com/32236491/79555180-d2a2cd80-80a7-11ea-80b2-4231b95b7782.png">

### Environment

**Operating System**
macOS

**Browser** Chrome

**Comment by arnog** [comment]
This should now be fixed.
