### ISSUE TITLE
MathLive support in Angular 6

### ISSUE THREAD

**Issue by poojas17** [arnog/mathlive#423]
Can you please provide its integration support with Angular 6?

**Comment by physedo** [comment]
> Can you please provide its integration support with Angular 6?

https://github.com/mathquizily/ionic-mathlive

**Comment by poojas17** [comment]
Thanks for sharing the link :)

**Comment by physedo** [comment]
IonicMathliveModule

https://www.npmjs.com/package/ionic-mathlive

works with mathlive": "^0.35.1

I will upgrade it later to latest version

**Comment by arnog** [comment]
OK, great. Can this issue be closed, then?

**Comment by physedo** [comment]
> OK, great. Can this issue be closed, then?

yes
