### ISSUE TITLE
Add conversion to/from MathML

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#43]
## Description
It would add utility to mathlive to support both input and output of MathML. No one will type MathML, but it is a common interchange language so someone might have copied it from somewhere and want to paste it into mathlive.

For output, it would be good to make it an accepted format for the existing `text` function. Supporting output will enhance accessibility as it can be used internally to produce hidden MathML that screen readers can see and use for speech, navigation, and braille.

**Comment by arnog** [comment]
Conversion to MathML can now be performed using `text("mathML")`. It covers basic usage of formulas. Please file additional bugs for cases that are not covered.
