### ISSUE TITLE
Mathlive issues with our project

### ISSUE THREAD

**Issue by rmeniche** [arnog/mathlive#434]
## Prerequisites

-   [ 👍 ] News issues and additional information on old ones.

## Context

Hello everyone.
We want to use Mathlive in our project of a new kind of maths exerciser for two reasons. First, it's a great tool for printing mathematicals expression with Latex. Then, with the abstract syntax tree created with latexToAST it's a good way for us to return informations, given by both students and teachers, to our server.
We found out that there were 5 problems for our use. I'm going to list them.

## Version

I cloned Mathlive project with git Wednesday, April 8th and didn't update it from the git yet,but as some of the bugs are still present in the main page (https://mathlive.io/) and others are really specific. I guess they haven't been fixed yet.

### "<" error

As I saw here https://github.com/arnog/mathlive/issues/417, I was not the only one who got this problem. The fact is that it's still here for me in the main page, and I don't get a german keyboard (I've got an AZERTY). 
I fixed it in the mathlive project by going to editor/editor-shortcut.js and adding a new line `'<': '\\lt',`
To conclude, there is still a problem for me with <
### Parser errors

As reported here : https://github.com/arnog/mathlive/issues/396

Some importants symbols or functions for us yield a problem with parsing. 
There is a known problem wih integral intervals, I'd like do say that it's the case for others symbols/functions which are important for us such as :
- \le ($\le$) is not working contrary to < > or $\ge$
![](https://i.imgur.com/i4cY7sH.png)

- \overline (also the case for vectors)
![](https://i.imgur.com/PVTk71C.png)

- \overrightarrow{ABC}
![](https://i.imgur.com/347jlez.png)
 EDIT : I forgot to mention in "Parser errors" that it was the case for \subseteq (⊆) \nsubset (⊄) \supseteq (⊇) \nsupset (⊅) which can be important too.

This is a key issue in our project, since we need to work on tree representation. 

When \lt, \gt and \ge works totally, I don't see why \le creates a problem

### Json keyboard errors

In order to understand how the keyboards could be created, I went to /examples/virtual_keyboard.html to see how it was treated and began to test differents things.

At first, I wanted to add a new keyboard with HTML like the 'basic' or 'hp' ones just by copying and pasting 'basic' and adding it to the list "virtualKeyboards". This worked.

Then, I wanted to do the same thing with JSON keyboards, so I did a copy of the one present in the file and added it in the same way I did with HTML keyboards. So there was in the list of keyboards : hp basic json1 json2. This time, it didn't work correctly as when I clicked on json keyboard, it has shown me this.

![](https://i.imgur.com/nQaZBbw.png)

At first, I thought that I did something wrong and checked the way the first JSON keyboard was created. I saw that and I did the same thing by copying it. 

So I thought it was due to the fact that 2 JSON keyboard could not be implemented if a JSON follows another JSON (in the virtualKeyboards list). 
So I've added a JSON keybord after an HTML keyboard. Things were the same, the same result was obtained once I clicked on a json keyboard.

At last, I decided to clear everything and get the file back to his origin form. I've just decided to change the order of the virtualKeyboards list : from hp basic json to hp json basic. This created the same error. I have no clue of why this happens, but it happens.

### Problems with display, shortcuts & preset buttons

Our goal with keyboard was to create buttons that generates latex which let us declare functions, variables or other specials math objects with empty fields to be completed by user.

Example : `<li class='keycap' data-insert='\left\rbrack #?, #?\right\rbrack' >]]</li>` 
whichs shows this : 
![](https://i.imgur.com/IJLmKch.png)

The thing is that sometimes, with special buttons, when we want to complete empty fields by expression with shortcuts, the display is unstable

#### Steps to Reproduce

For example, with this button :

```
<li class='keycap' data-insert='f(#?) = #? \left\lbrack #?, #?\right\rbrack'>func</li>
```

which declare a function showing this :
![](https://i.imgur.com/2e4L9mi.png)

when I type RR (for the shortcut of the real set) in the first empty field (I agree that It doesn't make sense), the result is this 

#### Actual Behavior
![](https://i.imgur.com/OE0Nyo4.png)

#### Expected Behavior
instead of this
![](https://i.imgur.com/EMpY4cv.png)

This is a very weird bug as it doesn't always happen and happens only the first time after you click the button.

### Environment

**Operating System**
Windows 10

**Browser** 

Firefox

Hope I have been clear and that my post is relevant. If you want me to do the issue report in a different format, if you have any questions or answers, I'll be happy to see this !

**Comment by rmeniche** [comment]
I forgot to mention in "Parser errors" that it was the case for \subseteq (&sube;) \nsubset  (&nsub;) \supseteq (&supe;) \nsupset  (&nsup;)  which can be important too.

**Comment by arnog** [comment]
Thanks for reporting these issues and thanks for your patience: the resolution of most new issues will be delayed until the migration to TypeScript is completed (#418).

It is generally easier to file a report for each separate issue: this makes it easier for you (and me) to track the issue and allows them to be resolved independently. Could you split this report in 3 separate ones (I think I'm seeing three issues above, in addition to #417 ?)

**Comment by rmeniche** [comment]
First, thanks for your answer. I'll indeed split this report to make everything easier.

As we'll be using Typescript too with another tool, this migration is really great for us. As I'm currently in an internship, I was wondering if there was any idea of the date of the end of the migration.

I'm going to post the reports individually. Thanks again.

**Comment by arnog** [comment]
Great, thanks.
The TypeScript migration should be a few more days. It's basically completed, but I need to do some minor cleanup and additional testing.
