### ISSUE TITLE
Json Keyboard issues

### ISSUE THREAD

**Issue by rmeniche** [arnog/mathlive#435]
## Prerequisites
-   [👍  ] New issue
(Linked to https://github.com/arnog/mathlive/issues/434)

## Version 
I cloned Mathlive project with git Wednesday, April 8th and didn't update it from the git yet,but as some of the bugs are still present in the main page (https://mathlive.io/) and others are really specific. I guess they haven't been fixed yet.

## Description
In order to understand how the keyboards could be created, I went to /examples/virtual_keyboard/index.html to see how it was treated and began to test differents things.

At first, I wanted to add a new keyboard with HTML like the 'basic' or 'hp' ones just by copying and pasting 'basic' and adding it to the list "virtualKeyboards". This works.

Then, I wanted to do the same thing with JSON keyboards, so I did a copy of the one present in the file and added it in the same way I did with HTML keyboards. This time, it didn't work correctly as when I clicked on json keyboard, it has shown me this.

![](https://i.imgur.com/nQaZBbw.png)

I thought that I did something wrong and checked the way the first JSON keyboard was created. I saw that and I did the same thing. So I thought it was due to the fact that 2 JSON keyboard could not be implemented if a JSON follows another JSON. 
So I've added a JSON keybord after an HTML keyboard. Things were the same, the same result was obtained once I clicked on a json keyboard.

At last, I decided to clear everything and get the file back to his origin form. I've just decided to change the order of the virtualKeyboards list : from hp basic json to hp json basic, and the same thing happens.

### Actual behavior

![](https://i.imgur.com/nQaZBbw.png)

There is no messages in the console.

### Expected Behavior

I expected it to act as other keyboards.

## Steps to Reproduce

1. Get to examples/virtual_keyboard/index.html
2. Swap json/basic in this line ```  virtualKeyboards: 'hp json basic', L340 for me```
3. Go to http://localhost:8080/examples/virtual_keyboard/
4. Click on the JSON keyboard

### Environment

**Operating System**
Windows 10

**Browser** 
Firefox

**Comment by arnog** [comment]
Thanks for reporting this.
There was an issue in the markup generation for JSON-specified virtual keyboards that resulted in an un-closed tag being generated. Fixed now.
