### ISSUE TITLE
Problems with display, shortcuts & preset buttons

### ISSUE THREAD

**Issue by rmeniche** [arnog/mathlive#436]
## Prerequisites

-   [👍  ] New issue

(linked to https://github.com/arnog/mathlive/issues/434)

## Description

Our goal with keyboard was to create buttons that generates latex which let us declare functions, variables or other specials math objects with empty fields to be completed by user.

Example : `<li class='keycap' data-insert='\left\rbrack #?, #?\right\rbrack' >]]</li>` 
whichs shows this : ![](https://i.imgur.com/IJLmKch.png)

The thing is that sometimes, with special buttons, when we want to complete empty fields by expression with shortcuts, the display is unstable

For example, with this button :

```
<li class='keycap' data-insert='f(#?) = #? \left\lbrack #?, #?\right\rbrack'>func</li>
```

which declare a function showing this :
![](https://i.imgur.com/2e4L9mi.png)

when I type RR (for the shortcut of the real set) in the first empty field (I aggree that It doesn't make sense), the result is this ![](https://i.imgur.com/OE0Nyo4.png)

This is a very weird bug as it doesn't always happen and happens only the first time after you click the button.

### Actual behavior

![](https://i.imgur.com/OE0Nyo4.png)

The result of the shortcut is placed after the placeholder and after the ')'

### Expected Behavior

It should be placed at the 1st placeholder.
![](https://i.imgur.com/EMpY4cv.png)

## Steps to Reproduce

1. Go to examples/virtual_keyboards/index.html
2. Edit one button in the HTML format by this
 ```
<li class='keycap' data-insert='f(#?) = #? \left\lbrack #?, #?\right\rbrack'>func</li>
```
3. Go to http://localhost:8080/examples/virtual_keyboard
4. Click on the edited button
5. Type RR or QQ or EE or any other shortcuts
and then you'll see

### Environment

**Operating System**
Windows 10

**Browser** 
Mozilla

**Comment by arnog** [comment]
Thanks for reporting this. This was an interesting issue. The problem would happen if you had smartFence on and were applying an inline shortcut inside a paren group that had been inserted as a pure fence (not a \left\right group). In that case, the parent would get (incorrectly) promoted to a \left\right group, causing the problem. The solution is to ignore the smartFence setting when inserting the shortcut. Fixed now.
