### ISSUE TITLE
Errors with MathJSON and \le \int \overline etc...

### ISSUE THREAD

**Issue by rmeniche** [arnog/mathlive#437]
## Prerequisites

-   [ 👍 ] Additional information to a known issue  
(linked to https://github.com/arnog/mathlive/issues/434)

## Description

As reported here : https://github.com/arnog/mathlive/issues/396

Some importants symbols or functions for us yield a problem with parsing. 
There is a known problem wih integral intervals, I'd like do say that it's the case for others symbols/functions which are important for us such as :
- \le ($\le$) is not working contrary to < > or $\ge$
![](https://i.imgur.com/i4cY7sH.png)

- \overline (also the case for vectors)
![](https://i.imgur.com/PVTk71C.png)

- \overrightarrow{ABC}
![](https://i.imgur.com/347jlez.png)

that it  also the case for \subseteq (⊆) \nsubset (⊄) \supseteq (⊇) \nsupset (⊅) which can be important too.

In the first time I said it was an error from the parser, but we think it's more an error in src/addons/Mathsjon.js

This is a key issue in our project, since we need to work on tree representation. 

## Steps to Reproduce

Just go mathlive.io, active the code view and type the latex command mentioned before.

### Environment

**Operating System**
Windows 10

**Browser** 
Firefox

**Comment by arnog** [comment]
I believe this has now been resolved.
