### ISSUE TITLE
MathLive breaks inside of ShadowDOM

### ISSUE THREAD

**Issue by bengolds** [arnog/mathlive#438]
## Description
If you try to create MathLive math fields inside of a Shadow DOM root node, a few things seem to break.

### Actual behavior

1. MathLive never thinks it's in focus, so selections are always gray.
2. Some keyboard shortcuts break (e.g. ctrl-a) and insert odd symbols.
3. Tab order on the page gets messed up.

### Expected Behavior

It'd be great for MathLive fields to behave normally inside of Shadow roots; I often use ShadowDOM + custom elements inside of Elm to encapsulate specific pieces of Javascript content.

## Steps to Reproduce

https://codepen.io/theotherben/pen/eYpErZo

The main issue seems to be the use of `document.activeElement` instead of `this.$el().getRootNode().activeElement`, for example [here](https://github.com/arnog/mathlive/blob/763d54e839a650e55e1b61c1598a0ac05c4a7a11/src/editor/editor-mathfield.js#L3683-L3685)

**Comment by arnog** [comment]
Good point. It should be fixed now.
