### ISSUE TITLE
Can't type symbol of lower frequency

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#44]
## Description
If I want to type a TeX command for a symbol which has lower frequency than another symbol, and that more frequent symbol has a longer length, I can't type the lower frequency symbol. For, example, if I want to type `\triangle`, the suggested symbol for completion is `triangleq` (see screen image).
![image](https://user-images.githubusercontent.com/1545836/33912662-a075770e-df4b-11e7-9691-43b04cc82311.png)

 If I type a space or 'enter' key at this point, I end up with `\triangleq`. I can't see that there is any way that I can get the triangle symbol by typing the `\triangle` command.

## Steps to Reproduce
1. Open mathlive.io, select the contents and type `\triangle`
2. Hit the enter key
3. You get `\triangleq` pictured below
![image](https://user-images.githubusercontent.com/1545836/33912800-1cda6f34-df4c-11e7-9294-a719aee958fa.png)

## Code to look at
It appears that the problem is either in `EditableMathlist.prototype.extractCommandStringAroundInsertionPoint` or in `EditableMathlist.prototype.commandOffsets`. In the former, perhaps it should return two values: the first is the (potential) command up to the point of the suggestion starting and the second is (as it currently stands) including the suggestion (siblings value has `suggestion: true`). That way the call `MathField.prototype.complete_`, which does the `matchSymbol` call can do a check for what is typed rather than the longer completion. In the later, perhaps a check could be made and both returned there. I think modifying `extractCommandStringAroundInsertionPoint` is likely better since it affects fewer calls.

**Comment by arnog** [comment]
Hmmm... There is a way, but perhaps it's not clear enough. Not sure what the right answer is. When the auto-completion suggests a longer symbol, if typing "space" or "return" overrode the auto-completion, well, that would defeat the purpose of the auto-completion.

The way you can access all the symbols, even when the first one suggested by auto-completion is longer than the one you're looking for is to use the up/down arrow keys to scroll through the available options. So, in your example, you would type "\tr", down-arrow, return. When pressing the "down-arrow" key, the auto-completion will change from "\triangleq" to "\triangle".

Let me know what you think...

**Comment by arnog** [comment]
One option could be to use different keys:
- return (and/or space?): insert a symbol based only on the characters typed so far
- tab: complete the symbol based on the auto-completion guess.
