### ISSUE TITLE
manipulating mathfield text from JS function ?

### ISSUE THREAD

**Issue by oliverstefanov** [arnog/mathlive#447]
Hi,

I would like to edit the latex content of a mathfield upon an external button click event that calls a JS function. That function must be inside `<script>` tags to be accessible to the handler (apparently). 

But then MathLive can't be imported since it has to be at the top of a `<script type="module">` tag. If i put my function inside that module, it is seen as undeclared.

I tried several things but i still don't see how to access the mathfield object (for example to do mf.$insert(...)) from outside the module script where the mathfield is created.

EDIT : clarity...

**Comment by arnog** [comment]
If you can share your code, I'd be happy to have a look.

This said, you can access the Mathfield from a HTMLElement like so:
```
const mathfield = document.getElementById('myMathfield').mathfield;
console.log(mathfield.$text());
```

If you have already imported the Mathfield module once, you don't need to import it again in a separate `<script>` tag, or in a `onclick` handler.

**Comment by oliverstefanov** [comment]
Ok great, it's exactly what I was looking for. It works now. Thank you!
