### ISSUE TITLE
Array editing commands are not operable in text mode

### ISSUE THREAD

**Issue by rmeniche** [arnog/mathlive#461]
## Prerequisites

-   [:+1:] New issue

## Description

Hello, this is really specific but, when the last column of a line is a text field and it's not the last line, it's hard to add a new line after it.

For example this :

`\begin{array}{lcl}a & b & \text{c} & a & b & c\end{array}`

Which create this in Mathlive

![](https://i.imgur.com/KJ116mu.png)

When we want to do escape with the curson after the 1st c, it just adds a space after this.

### Actual behavior

The effect is more obvious with MathML Markup

![](https://i.imgur.com/xFGvVxA.png)

### Expected Behavior

I expect it to work as normal when we add a new line.

## Steps to Reproduce

1/Go to mathlive.io
2/Copy and paste `\begin{array}{lcl}a & b & \text{c} & a & b & c\end{array}`
to the mathfield
3/Place your cursor after the first c at the same line
4/Try using escape

### Environment

**Operating System**
Windows10

**Browser** 
Mozilla

**Comment by arnog** [comment]
Fixed in master
