### ISSUE TITLE
MathLive npm package not Vue compatible

### ISSUE THREAD

**Issue by leontepe** [arnog/mathlive#463]
## Description

I don't know if I am using the MathLive npm package wrong, but like I described in #462 from yesterday, I can't use the arrow keys to move around / backspace to delete characters. Since I can now see it working on the example page online, I suppose it has something to do with me using and referencing the files from npm package. Is it maybe outdated?

In my local project, I am including the `mathlive.mjs` and `vue-mathlive.mjs` (+ css) files straight out of the `node_modules/mathlive` folder. Maybe my approach is wrong here?

### Environment

**Operating System**
Windows

**Browser**
Chrome/Firefox

**Comment by arnog** [comment]
Which version are you using?
Are there any messages in the JavaScript console.
There was a problem with the keyboard handling of the Vue wrapper, but it's fixed in 0.51.

**Comment by leontepe** [comment]
I was using 0.50.8, but now updated to 0.51 and now it works! Thanks :) didn't think I wasn't on the newest version since I more or less just installed it but whatever.
