### ISSUE TITLE
Backspace/Delete/Arrow Navigation not working on Ubuntu

### ISSUE THREAD

**Issue by johnhbenetech** [arnog/mathlive#469]
## Description

When visiting mathlive.io (as well as after pulling v52 to Benetech's Mathshare) several interactions no longer work for us on Ubuntu/Firefox.

For example we are unable to use backspace/delete to remove characters within the mathlive expression. The arrow keys also don't work to move within the expression

### Actual behavior

[What actually happened]
On Ubuntu/Firefox
During any entry of any kind there is a delay before the characters actually display. Each keystroke outputs the following in the JS Console:

main.js: ReferenceError: Can't Access Lexical declaration 'gPlottingDebounceTimer' before initialization
mathlive.mjs: TypeError: a is undefined

The above also occurs for any backspace/delete/arrow keystrokes and the expression/cursor remain unchanged.

### Expected Behavior

Ubuntu/Firefox combo worked in past versions (I don't have an exact version when it stopped unfortunately.

### Environment

**Operating System**
Ubuntu

**Browser**
Firefox

**Comment by arnog** [comment]
Can you try with Chrome on Ubuntu? (Trying to isolate if this is OS or browser specific)

**Comment by johnhbenetech** [comment]
@arnog also happens on Chrome/Ubuntu

**Comment by leerobert** [comment]
I'm seeing the same issue... here are the stacktraces

![Screenshot from 2020-05-26 15-52-07](https://user-images.githubusercontent.com/6231418/82944332-fdb2f380-9f68-11ea-9a81-fcd39f83a139.png)

**Comment by arnog** [comment]
Fixed with commit 6d28901

**Comment by johnhbenetech** [comment]
@arnog if it's not to much trouble, could we get a build for this?

**Comment by arnog** [comment]
Sure. I need to finish some work for a sponsor and I'll cut a build after that. Should be a couple of days.
