### ISSUE TITLE
renderMathInDocument/Element not working

### ISSUE THREAD

**Issue by leontepe** [arnog/mathlive#476]
It seems like MathLive.renderMathInElement() (and also [...]InDocument()) are not working.

JSFiddle:
https://jsfiddle.net/leontepe/35fq47t2/11/

Mathfield works as usual and the plain rendering doesn't.

Is my usage wrong or is it broken? It seems like there is no example on the [examples page](https://mathlive.io/examples/) that _just renders_ math.

**Comment by leontepe** [comment]
Nevermind.

**Comment by arnog** [comment]
Not sure what's going on. Some interaction with JSFiddle, I would guess?

BTW, you shouldn't call both `renderMathInDocument()` **and** `renderMathInElement()`
