### ISSUE TITLE
Font rendering looks weird on Firefox

### ISSUE THREAD

**Issue by leontepe** [arnog/mathlive#490]
I just tried MathLive out on Firefox Developer Edition (version 78.0b3, 64-Bit) and standard Firefox (version 75.0, 64-Bit) and both rendered the math in a weird way. It seems like they are not rendering the KaTeX fonts properly, they definitely look different... 🤔

I am running Windows 10 Pro (version 10.0.18363 Build 18363).

This is how it renders in both:
![image](https://user-images.githubusercontent.com/27787342/83967807-1b674d80-a8c5-11ea-8649-6e6e7cdd183c.png)

And for comparison, the normal LaTeX-style it renders in Chrome:
![image](https://user-images.githubusercontent.com/27787342/83967932-c415ad00-a8c5-11ea-8ad2-8c3c2d871ef5.png)

**Comment by arnog** [comment]
This is due to a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1252821

**Comment by arnog** [comment]
Implemented a workaround that always load fonts when in Firefox.
