### ISSUE TITLE
unpkg CSS URLs not working 

### ISSUE THREAD

**Issue by bengolds** [arnog/mathlive#502]
I believe the latest NPM release is missing the CSS files in `dist` -- these URLs don't work:

https://unpkg.com/mathlive/dist/mathlive.core.css
https://unpkg.com/mathlive/dist/mathlive.css

The npm package is also missing those URLs.

**Comment by arnog** [comment]
These files are no longer required. The stylesheet is injected dynamically as necessary. See https://github.com/arnog/mathlive/blob/master/CHANGELOG.md#0530-2020-05-31

**Comment by bengolds** [comment]
Hurrah! 🎺
