### ISSUE TITLE
Spacing is inconsistent between browsers

### ISSUE THREAD

**Issue by bengolds** [arnog/mathlive#505]
## Description

The spacing between variables and operators is quite large in Safari, and looks alright (albeit different) on Firefox and Chrome.

<img width="477" alt="ScreenCapture at Mon Jun 15 17:45:44 PDT 2020" src="https://user-images.githubusercontent.com/446007/84719431-3aeb1f80-af30-11ea-9597-7309cc9f2708.png">

### Environment

**Operating System**
macOS 10.15.5

**Browser**
Safari 13.1.1
Firefox 76.0.1
Chrome 83.0.4103.97

**Comment by arnog** [comment]
Looks like U+205F (Medium Mathematical Space) is not rendered correctly...

**Comment by arnog** [comment]
This is now fixed.
