### ISSUE TITLE
insertion point selection when deleting numerator

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#51]
## Description
I don't think the insertion point position when the numerator is deleted what it should be. Currently the code places the insertion point _after_ the denominator. But that's not where it would was when entering the fraction -- it would be in _before_ the denominator

## Steps to Reproduce
1. open mathlive.io
2. type a/b+1
3. delete the 'a' so the numerator is empty.
4. hit delete.

The insertion point is after the '1'. I believe it should be before the 'b' since you logically have '/b+1' and are you deleting the '/'.

The problem is at editor-editableMathlist.js:1491 (in ditableMathlist.prototype.delete_):
old: this.setSelection(this.anchorOffset() + denom.length - 1);
fix:  this.setSelection(this.anchorOffset() - 1);

Note1: the code seems unfinished around here because if you have an empty numerator, you can't use `backspace` to delete the numerator (and fraction). Similarly, you can't use `delete` to delete an empty denominator (and fraction).

Note2: there is also a bug with an empty numerator (or denominator) -- you can't click to place the cursor into the empty numerator or denominator. You can arrow your way there though.

**Comment by arnog** [comment]
Yes, fair point. (For clarification, "delete" = "forward delete").

Note 1 is valid as well in general, there are probably quite a few edge-y cases that are not handled satisfactorily. I don't quite follow the specific example you give, though. If you have an empty numerator and you press backspace, you would expect the fraction bar to be deleted? That is, same as if you had pressed forward delete? Shouldn't the character before the fraction be deleted instead?

Note 2: yes, good catch. This should probably be handled by inserting a placeholder value when exiting an empty numerator or denominator.

**Comment by NSoiffer** [comment]
The case of `backspace` (backward delete) in the numerator is interesting. There are two cases to consider. I think what happens could be different but the logic is related.
1. The numerator is not empty and the insertion point is at the start of the numerator. Deleting the fraction doesn't make sense because there is still content there. The current behavior is 'do nothing', which certainly can be justified if you think of the numerator as being a line and you are at the start of the line, then there is nothing to delete on the left.
2. The numerator is empty. In this case deleting the fraction is potentially sensible. Also again, 'do nothing' is sensible.

My feeling is that it took some action/keystroke to create the fraction, so `backspace` acts to delete that action in the case of the empty numerator. I could be biased because in many math editors, one creates a fraction with something like ctrl+f, so backspace to remove it sensible. For mathlive, the analogous case is typing `/` after a `=`. A fraction is created with an empty numerator. As a touch typist, it would be nice for `backspace` to get me back to where I was (i.e., type a character, delete a character and I'm back where I started).

I don't like the notion of deleting the character before the fraction because the insertion point is potentially not close to it. I would find that behavior really surprising.
