### ISSUE TITLE
[Question] Documentation for importing JSON Keyboard

### ISSUE THREAD

**Issue by rmeniche** [arnog/mathlive#518]
## Prerequisites

-   [ ] New issue

## Description
Hello,

I was wondering if you could tell me more about this feature that is in the README of examples/virtual_keyboard

Here is the part that get my interest : 
![Screenshot_2020-06-23 arnog mathlive](https://user-images.githubusercontent.com/60935654/85423587-2a155c00-b577-11ea-8c00-3ddb4a51162e.png)

In our project, we may try to select keyboards depending on many things, 
So I was wondering how we could, in makeMathField function, use a keyboard that is stored in a JSON file by calling it in the function (with a variable name for example)

So, how can we load a JSON keyboard with a JSON file that is in another directory ?

**Comment by arnog** [comment]
The layout of Virtual Keyboard can be specified either as HTML or as a JSON data structure. The JSON data structure doesn't have to be a separate file. In fact, it could be a regular JavaScript constant that you store in your code. In that case, you would set `customVirtualKeyboardLayers`, `customVirtualKeyboard` and `virtualKeyboards` to the appropriate values.

If you do want to store it in a JSON file, you can do so as well. Depending on your build environment and bundler, you can simply `import` the JSON file, or read it using a `fetch` call.

**Comment by rmeniche** [comment]
Oh ok I see, thanks for your answer !
