### ISSUE TITLE
Suggestion: improve how '/' works

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#52]
## Description
At the moment:
* if you type '/' after an operand such as `a` or `a^2`, you get a fraction with that operand in the numerator
* if you type '/' after anything else, you get a fraction fraction with an empty numerator. Eg., '/' after `=` gives '= \frac{}{placeholder}'

I think it makes more sense that whenever the thing to the right acts like an operand, it should be treated as an operand Here are two common cases to illustrate this:
1. `\sqrt{x}` -- this should become part of the numerator
2. `(x+y)` -- the grouping means that the subexpr is an operand and should be treated as such. In this case, it _might_ be a good idea to remove the parens when it goes into the numerator.

I'm not 100% sure removing the parens is a good idea, but if you consider a naive user, they are probably use to writing `(x+y)` vs writing `x+y` and then selecting the `x+y`.

FYI: Removing the parens is what ASCII math does for `(x+y)/2`.

**Comment by arnog** [comment]
I like that idea. You would need a definition for what gets considered a valid operand (numerator) for a fraction. Is it only the two examples you give, or are there others?
