### ISSUE TITLE
Problems with keystrokes

### ISSUE THREAD

**Issue by jalonsomartinez** [arnog/mathlive#522]
## Description

With a spanish keyboard
- The slash that is found with Shift-7 does not create a fraction, it writes a slash
- The '-' key creates a fraction when used alone. I guess it has the code for a slash in other keyboards
- However the '-' key creates a \pm if pressed after a '+' which is probably an expected behaviour, but inconsistens with previous.

### Environment

**Operating System**
Ubuntu 20.20

**Browser**
Chrome latest
Firefox latest

**URL**
https://mathlive.io/examples/basic/index.esm.html

**Comment by arnog** [comment]
FYI, I have a fix pending but the build is broken due to a third-party dependency and I'm waiting for a fix: https://github.com/facebook/jest/issues/10208

**Comment by G-Rath** [comment]
@arnog I've added a patch to my issue that you can use to unblock this in the meantime if you wish :)

**Comment by arnog** [comment]
Thanks! I'll wait a bit more to see in the hope to get an official fix...
