### ISSUE TITLE
Expression in brackets as numerator in fractions

### ISSUE THREAD

**Issue by nkipi** [arnog/mathlive#523]
## Prerequisites

-   [x] New issue
        [Searched by fractions and brackets.]

## Description

When you want to divide an expression in brackets by something, adding a fraction after the expression won't add the expression as numerator but will add a new fraction block after that.

![image](https://user-images.githubusercontent.com/28009381/86222588-bed71580-bb86-11ea-9a74-87817780e25a.png)

### Actual behavior

![mathlive-fraction](https://user-images.githubusercontent.com/28009381/86222664-d7dfc680-bb86-11ea-8276-22aeb6aa7dd4.gif)

### Expected Behavior

I would expect that the expression in brackets is automatically added as a numerator, same as when you select the expression as in the gif below:

![mathlive-fraction-selection](https://user-images.githubusercontent.com/28009381/86223007-4886e300-bb87-11ea-8091-2e1eb9af7d29.gif)

[Is this a regression: I think it was always like this]

## Steps to Reproduce

1. Go to https://mathlive.io/
2. Type an expression in brackets, e.g. `(a+b+c)`
3. Open keyboard and select `/` symbol.

### Environment

**Operating System** [Windows]

**Browser** [Chrome, Firefox]

**URL** [https://mathlive.io/]

**Comment by arnog** [comment]
Thanks for reporting this issue. It should be a simple fix in the definition of the "divide" key in the virtual keyboard.
FYI, you can get the desired behavior by pressing the "/" key on a physical keyboard.
