### ISSUE TITLE
npm test fails import

### ISSUE THREAD

**Issue by Caroch** [arnog/mathlive#533]
## Description

Right after cloning the repo, I ran ```npm ci``` and ```npm run build``` and the tests did not pass. 
The ```build.sh``` does not appear to create the ```mathlive.js``` file, but only the ```mathlive.mjs```... Can anyone tell me how this is possible ? 

### Actual behavior

```shell
$ npm test

> mathlive@0.54.1 test /home/caroline/STAGES/Stage2A-N7/mathlive
> bash ./scripts/test.sh


  ● Test suite failed to run

    test/math.test.ts:1:22 - error TS2307: Cannot find module '../dist/mathlive' or its corresponding type declarations.

    1 import MathLive from '../dist/mathlive';
                           ~~~~~~~~~~~~~~~~~~

npm ERR! Test failed.  See above for more details.
```

### Expected Behavior

The tests should run and pass.

## Steps to Reproduce

In the shell :

```shell 
$ git clone https://github.com/arnog/mathlive.git
```
```shell 
$ cd mathlive/
```
```shell 
$ npm ci
```
```shell 
$ npm run build
```
```shell 
$ npm test
```

### Environment

**Operating System**
Ubuntu 18

**npm version**
npm 6.14.5

**Comment by arnog** [comment]
The tests incorrectly assume that a production build is available. They should run on either the production or development builds.

**Comment by arnog** [comment]
This has now been fixed.
