### ISSUE TITLE
Subscripts do not seem to output MathML correctly

### ISSUE THREAD

**Issue by johnhbenetech** [arnog/mathlive#534]
## Description

When entering a subscript into mathlive or mathshare's implementation of mathlive (using something like 2_3 for instance) - the MathML generated in the sr-only span does not include the subscript.

### Actual behavior

Resulting MathML only includes the main entry and omits the subscript 

### Expected Behavior

Resulting MathML should include msub element and content in the appropriate location

**Comment by timtsm** [comment]
Subscripts _are_ reported in mathml if they are on letters. In addition to numbers, close parentheses and + signs, among others, don't report subscripts in mathml. Close parentheses, \imaginaryI, and \exponentialE (and + signs) also don't report superscripts, making (a+b)^2 the same as (a+b), i^2 the same as i, e^x just e (when i and e are the \imaginaryI and \exponentialE forms--regular letters i and e work), etc.

**Comment by timtsm** [comment]
Oh, and a_x^2 (or a^2_x) is reported in mathml as a^2 (a can be any other letter as far as I can see).
