### ISSUE TITLE
blur event before focus event

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#543]
## Description

When clicking on the edge of a mathfield, the mathfield gains focus. However, the focus and blur events that happen are funky.

I could submit a PR, but I'm not entirely sure what the best way of fixing this would be.

### Actual behavior

A blur event gets fired and then two focus events get fired. 

```
blur 
focus
focus
```

### Expected Behavior

Those events are in the wrong order. I expected a single `focus` event instead of 3 out of order events. 

## Steps to Reproduce

```html
<div tabindex="0" id="dummy" style="border: 1px solid;">f(x)=0</div>
```
```js
MathLive.makeMathField("dummy", { onFocus: _ => console.log("focus"), onBlur: _ => console.log("blur") })
```

1. After creating a mathfield, click on the region above or below the formula. 
2. This triggers the focus event handler on the `math-editor` https://github.com/arnog/mathlive/blob/2f80922adcb5d1403393558feb57ebed89eb2c69/src/editor/mathfield-class.ts#L491-L492
3. That event handler then focuses on the textarea. This ends up triggering the blur event handler of the `math-editor`...
![image](https://user-images.githubusercontent.com/10220080/87241860-67a72f80-c427-11ea-93a1-2127a425d88a.png)

### Environment

**Operating System** Windows 10

**Browser** Firefox

**Comment by stefnotch** [comment]
Since this can only happen when the mathfield has a tabindex, issue https://github.com/arnog/mathlive/issues/544 is somewhat relevant.

**Comment by arnog** [comment]
With `tabIndex="0"` the matfield frame (the enclosing div) is focusable and when that happens the focus will correctly switch to the invisible `<textarea>` element which is normally focused to receive keyboard events, but generates in the process an incorrect `blur` event (for the container losing focus) and an incorrect `focus` event (for the `<textarea>` gaining focus).

**Comment by stefnotch** [comment]
Would, with custom elements, a simpler solution be to
1. Set a `tabindex=0` on the custom element by default
2. Set a `tabindex=-1` on the text input element!
3. As soon as the custom element gets focused, emit an event and focus the text input element
(Note: Focusing the text input element should not emit an event. That way, the duplicate events can't possibly ever happen.)

**Comment by arnog** [comment]
Yes, this could work, but I don't know if it would be simpler. The current solution works both for the custom element and the non-custom element case. What you suggest would require to have two different implementations, and to detect if we're in the custom element case or not.

**Comment by stefnotch** [comment]
That's true. I guess once the non-custom elements approach gets deprecated and removed, the check could be simplified.

**Comment by arnog** [comment]
Hmmm... I think this would still be needed. Programatically changing the focus fires a 'focus' (and 'blur') events.

**Comment by stefnotch** [comment]
I haven't actually tested it, but according to this random article, the focus event won't get fired again if the shadow host already has focus. https://medium.com/dev-channel/focus-inside-shadow-dom-78e8a575b73

**Comment by arnog** [comment]
Well, yes, the web component remains focused (i.e. `document.activeElement` remains the web component), but sub-elements of the web component will trigger focus events (the shadow root has its own `activeElement`, so there can be multiple "levels" of focused elements). So the text area will trigger focus and blur events, even if the web component itself doesn't.
