### ISSUE TITLE
When using MathLive.latexToMarkup fonts are not loading.

### ISSUE THREAD

**Issue by bhujoshi** [arnog/mathlive#546]
## Description
Fonts not loading when using **MathLive.latexToMarkup** working correctly on MathLive.makemathField and 
**fontsDirectory** option also not supported for MathLive.latexToMarkup 

https://codesandbox.io/s/html5-74498?file=/index.html

![error-in-xrightarrow](https://user-images.githubusercontent.com/9627563/87768222-716ecf80-c839-11ea-91a5-e38f75d3eda6.png)

### Actual behavior
It is not Generating correct equation when using MathLive.latexToMarkup

### Expected Behavior

It should generate correct equation

**Comment by bhujoshi** [comment]
I am interested to work on this issue. If the issue really exists.

**Comment by Phero49** [comment]
for me this fixed it @import url('/node_modules/mathlive/dist/mathlive-static.css');
@import url('/node_modules/mathlive/dist/mathlive-fonts.css');
