### ISSUE TITLE
CJK characters are ignored until input valid keys.

### ISSUE THREAD

**Issue by Paosder** [arnog/mathlive#555]
## Prerequisites

-   [ X ] New issue

## Description

CJK characters are ignored in mathfield until input valid keys like alphabet or number.

### Actual behavior

![issue-1](https://user-images.githubusercontent.com/20926881/87891446-e8dc7300-ca74-11ea-98ae-bf6bc94d7bbe.gif)

CJK characters suddenly appears when user input other keys.

### Expected Behavior

input CJK characters with ime mode.

### Environment

**Operating System**
Windows 10

**Browser** 
Chrome

**Comment by arnog** [comment]
I'm curious about the use case. Is this to name variables, or to add text or something else?

**Comment by Paosder** [comment]
Both. I want to use name variables, function name, operator name using CJK characters, and also text.

The previous version of mathlive, 0.35 or older, char composition was ignored (maybe wrong op?) so I handled it manually using a bit hacky ways(concatenate CJK characters to an word, then move caret position via modifying `mathField.mathlist.path`).

![issue-2](https://user-images.githubusercontent.com/20926881/88000507-c0b64800-cb38-11ea-8296-388edd99139c.gif)

Then, the breaking changes, that transferred to new code with typescript(hola, typescript!), however I cannot use that mess tricky method anymore(and suffering again) so I decided to resolve composition related issue. 

> I found that CJK characters are not appear until input valid keys for call `handlers.typedText(text)` method,
(keyboard.ts, line 207)
and also CJK chars not concatenated since its math mode, make it to call blur event so eventually exit composition status(`compositionend`).
(keyboard.ts, line 214)

For now, I don't know what is the best way to handle this issue, but it would be important issue to end-user since they are using multi-language.

**Comment by stefnotch** [comment]
@Paosder Is there an easy way to reproduce this if you don't happen to have an IME keyboard installed? Does something similar happen with the emoji input? (`Windows`+`;`)

**Comment by arnog** [comment]
I don't think you can repro this without an IME. An IME sends additional events (which the emoji input doesn't because those characters are not "composed"). Those events are not correctly handled. And in addition, it looks like there's stricter filtering of the input than there used to be (another symptom is that some accented characters are filtered out, even when entered in Latex, as per #599)

**Comment by Paosder** [comment]
You can activate IME mode via installing one of CJK languages in Windows 10. However, as mentioned above, you can't reproduce this issue without IME.

**Comment by arnog** [comment]
An idea for how to handle this would be to start polling the hidden textarea when `compositionstart` event is received and display the content in the formula, with some special decoration (wavy line). This might need to work somewhat like the command mode but new input would replace the currently "open" editing session, until the `compositonend` event is received/comitted.

**Comment by arnog** [comment]
Some languages (Japanese/Chinese) have some fairly complex IME interactions including being able to have caret/subselections inside the composition window and a composition menu that needs to be displayed in the right location.
That said, I am working on it and I'm hopeful to have a solution soon.

**Comment by arnog** [comment]
OK, I've pushed to GitHub an implementation. It's not perfect, due to some limitations of the Web APIs. Specifically:
- for IME that support multiple clauses (e.g. Kotoeri for Japanese), the clauses are not displayed differently (i.e. typically they would be displayed with a think underline under each clause and the active clause with a thick underline). However, the candidate menu is positioned under the current clause, so hopefully that's clear enough.
- recomposition doesn't work

I have only tested it on macOS, and only with Japanese and Korean IME. Additional testing may unveil issues. Please let me know if you see anything wrong or if you have additional feedback.

**Comment by Paosder** [comment]
Thanks for your great work! I've checked new features in `master` branch and I found the word disappears when characters are concatenated to complete form and then type any character again. The only `enter` key prevents disappearing chars. This issue makes impossible to activate inline shortcut like `ㄱㄴ`.

![disappear](https://user-images.githubusercontent.com/20926881/95819060-36a90480-0d60-11eb-9187-2ff89768b185.gif)

**Comment by arnog** [comment]
OK, so the issue is that when using the Korean input method in a regular text field, typing ㄱ(R key) followed by ㄴ (S key) ends the composition for the ㄱ character as soon as the S key is pressed. In a mathfield, typing ㄴ (S key) after a ㄱ (R key) **replaces** the ㄱ with ㄴ instead of committing it.

I'll look into it.

**Comment by arnog** [comment]
OK, there was an issue in the event ordering in this case. And Chrome and Firefox disagree on what is the right sequence of events (Chrome follows the W3C spec, Firefox improvises). I have fixed that now.
Then there was another problem where the input from a composition was never eligible for inline shortcut. Fixed that too.
The `ㄱㄴ` shortcut works now. FYI, it's better to use `\\sqrt{#0}` as the definition than `\\sqrt`, this way it takes into account arguments.

**Comment by Paosder** [comment]
Now it works gracefully! 🎉  Thank you! 😊 🙏

**Comment by Paosder** [comment]
The bad news. I found some weird behaviors in different browsers/OS. 😢 

In the latest version Chrome(86.0)/Edge(86.0) on MacOS(10.15.7, Catalina), next composition does not active right after composition ends. 
For example, in Hangul, if we type `가` (you can type this word via `R` and `K` keys), it still in composition mode. And then we type another `ㄱ`(`R` key) to concatenate these characters(`ㄱ`, `ㅏ`, `ㄱ`) to `각` and it still in composition mode. From begin to current step, these behaviors are absolutely normal and work gracefully. However, when we type another characters to end previous composition mode(`각`) and begin another composition mode with typed characters like typing `ㄱ`, the second character(`ㄱ`) are not in composition mode. Therefore we cannot concatenate with other characters, and then we could met split word `ㄱ` `ㅏ` if we type `ㅏ` right after. 
![2020-10-14 13 13 31](https://user-images.githubusercontent.com/20926881/95942915-623ef400-0e1f-11eb-9be2-25fda1114a21.gif)

In above, we can easily check second word(`가`) created via typing `ㄱ` is not in composition mode.

In the latest version of Safari on MacOS seems not working(disappearing characters).
(I tested in `master` branch via running test page using `npm run start`)
![2020-10-14 13 35 10](https://user-images.githubusercontent.com/20926881/95944045-46891d00-0e22-11eb-82a6-7c13b0223a21.gif)

In the latest version of Chrome/Edge on Windows 10, word of each concatenated step is cloned.
For example, when we make `각` via typing `ㄱ`, `ㅏ`, and `ㄱ` sequentially, then it duplicated each step of composition, so it displays like `ㄱ가각`.
![duplicated](https://user-images.githubusercontent.com/20926881/95945001-86510400-0e24-11eb-881d-8e6c211d1314.gif)

**Comment by arnog** [comment]
The browser divergent implementations (and the interactions with the various IME) make this area a bit tricky, so thanks for testing and reporting these issues. I'll look into it and hopefully can find some workaround that can work on all browsers.

**Comment by arnog** [comment]
OK, I have made some improvements, I think. `K + R + K + R` should work now. It also seems to work in Safari. I have not been able to test on Windows, but I'm hopeful that this fix will take care of it.

Please have a look at it and don't hesitate to let me know if you see some problems.

**Comment by Paosder** [comment]
I've checked in several environments(Chrome, Edge, Safari in Mac, Win) and it seems works all fine to me! 🎉 I'll note in here if I find some other problems related with this.

**Comment by arnog** [comment]
That's wonderful news. Thanks for helping with this. If you do some problems, please open a new issue. Thanks!
