### ISSUE TITLE
How to clear the previous formula 

### ISSUE THREAD

**Issue by 2010hexi** [arnog/mathlive#563]
## Description
I  used the official example to integrated into my webpack project, but it CANNOT be import in the xxxx.Vue file, 

 

If i code like this:

```vue

# in the vue file
import mathlive from 'mathlive'

Vue.use(mathlive)
``` 

it will shows the error like this

![image](https://user-images.githubusercontent.com/43429845/88497104-e7b9c180-cff1-11ea-90bb-ee03cce65e82.png)

so it can only import it in the index.html file, using  script with type="module"

like this:

```
<script type="module">
  import MathLive from './static/mathlive/mathlive.mjs';
  // import MathLive from 'https://unpkg.com/mathlive/dist/mathlive.mjs';

  const mf = MathLive.makeMathField('mf', {
    smartMode: true,
    virtualKeyboardMode: 'manual',
    onContentDidChange: (mf) => {
      const latex = mf.$text();
      document.getElementById('latex').innerHTML = escapeHtml(
        latex
      );

      const mathJSON = MathLive.latexToAST(latex);
      document.getElementById('mathjson').innerHTML = escapeHtml(
        JSON.stringify(mathJSON)
      );
    },
  });

  function escapeHtml(string) {
    return String(string).replace(/[&<>"'`=/\u200b]/g, function (
      s
    ) {
      return (
        {
          '&': '&amp;',
          '<': '&lt;',
          '>': '&gt;',
          '"': '&quot;',
          "'": '&#39;',
          '/': '&#x2F;',
          '`': '&#x60;',
          '=': '&#x3D;',
          '\u200b': '&amp;#zws;',
        }[s] || s
      );
    });
  }

</script>
```

the problem is that if i can only import in the index.html file, it cannot be reused in the other vue file.

so i continue to use the above approach, and  code the ID  into one Vue file, 

```vue
# Test.vue file
<template>
  <div class="hello">
    <main>
      <div class="mathfield" id="mf" >
        $$\nexists \exists f(x)+\frac{3i}{y\cdot h}$$
        <!-- $$\frac{\text{a\textit{b\textbf{\textsf{c}d}}}}{\mathbf{e\mathit{f}\mathbb{G}}}$$ -->
      </div>
     
    </main>

  </div>
</template>
```

it works~ like this

![image](https://user-images.githubusercontent.com/43429845/88497414-dfae5180-cff2-11ea-8080-8100356c36f7.png)

But i want to clear the previous formula before next time to edit it new one again.

I tried to search the node related to the formula, to make it "empty" , but fail,

```
## fail cases: 
document.querySelector(".ML__sr-only").innerText = ""

document.querySelector(".ML__fieldcontainer__field").innerText = ""

document.querySelector(".ML__base").innerText = "123"
```
I use previous code in js to clear it ,  the input box is empty , but when i am going to input new things, the previous formula come up again... 

I DONT know how to clear the exist formula...   I search the document, there is one $clearSelection() , but i cannot import mathlive in Vue file, cannot call this object to call this method, so I dont know if the method works or not.

But i know your official example, you click  the button  "I feel lucky",  https://mathlive.io/  you can change the formula, i think it should be changed it by some approaches.

![image](https://user-images.githubusercontent.com/43429845/88497731-c659d500-cff3-11ea-9fe7-0f09e90c098d.png)

Can you tell me how do you do it ?

### Environment

**Operating System**
[Windows]

**Browser** [Chrome]

**MathLive** [0.54.1]

**Comment by arnog** [comment]
To clear the mathfield, call `mf.$insert("", {insertionMode: "replaceAll"})`

`mf` is the variable returned by the call to `MathLive.makeMathField()`. If you don't have access to this variable, you can recover it from the DOM element, i.e. `getElementById("your-element-id").mathfield.$insert("", {insertionMode: "replaceAll"})`

**Comment by 2010hexi** [comment]
> To clear the mathfield, call `mf.$insert("", {insertionMode: "replaceAll"})`
> 
> `mf` is the variable returned by the call to `MathLive.makeMathField()`. If you don't have access to this variable, you can recover it from the DOM element, i.e. `getElementById("your-element-id").mathfield.$insert("", {insertionMode: "replaceAll"})`

Thanks , it works well.
