### ISSUE TITLE
Add option to turn off wrapping at start/end of line

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#58]
## Description
Right arrow at the end of a line wraps to the start of the line. Similarly, left arrow at the start of a line wraps to the end of a line. People who use screen readers often try to move through things quickly and bang on the arrow keys repeatedly. They want to hit "walls". The start/end of lines are a natural wall.

Since wraparound is potentially something other users might like, adding an option to mathlive that controls the behavior at the start/end of an expr would be useful.

The two places to change are in editor-editableMathlist.js
```
  EditableMathlist.prototype.next: this.path[0].offset = 0;
  EditableMathlist.prototype.previous: this.path[0].offset = this.root.children.length - 1;
```
but (obviously) there are other places that need to change to deal with configuring it.

**Comment by arnog** [comment]
You can do this by providing a `onMoveOutOf` handler that returns false. Let me know if this is not sufficient.

**Comment by NSoiffer** [comment]
Thanks -- I missed that function. Works just as desired.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
