### ISSUE TITLE
How to input a Bmatrix

### ISSUE THREAD

**Issue by zwz** [arnog/mathlive#597]
After I input `{something}`, if I try to add a row/column, it turns into `\begin{cases}...\end{cases}`.
So comes my question.

**Comment by zwz** [comment]
Well, maybe for `{something}`, it should turns into `Bmatrix` if a row is added; 
while for `{something`, `cases` instead.

**Comment by arnog** [comment]
There isn't a good way to do this currently. The available options are:
- paste `\begin{bmatrix}\placeholder()\end{bmatrix}` in a mathfield
- add a custom virtual keyboard panel with a UI width to insert the same thing

**Comment by arnog** [comment]
Question has been answered, closing.
