### ISSUE TITLE
Suggestions on the virtual keyboard toggle button

### ISSUE THREAD

**Issue by zwz** [arnog/mathlive#610]
1. I cannot find the tooltip customization in the document. I don't know if it is supported yet. In fact the default tooltip "Toggle Virtual Keyboard" seems introduce an issue when the mathfield is in a modal.  A horizontal scrollbar shows on the modal by default. And If I shorten the tooltip content with the web dev tools, the scrollbar disappears. (BTW, I am using chrome v84). Besides, the customization is also needed for other languages.

2. Although it is obvious to get the toggle state from the virtual keyboard (shown or not), people would miss the clue of hiding the virtual keyboard by the toggle button since it is the same no matter "on" or "off". I think it would help to make it clear by changing the appearance of the button between different states, like changing the color from gray to blue, or the background color form transparent to blue.

**Comment by arnog** [comment]
You can localize the tooltip. See http://cortexjs.io/docs/mathlive/?q=localization. The key for for the label of the tooltip is `tooltip.toggle virtual keyboard`. Note that localizations are already provided for english, arabic, german, greek, spanish, farsi, french, italian, japanese, polish and russian. You're welcome to submit additional languages as well.

You can also customize the appearance of the toggle with the CSS class: `ML__virtual-keyboard-toggle`.

Furthemore, you can specify the glyph used for the virtual keyboard toggle button using the [`virtualKeyboardToggleGlyph`](http://cortexjs.io/docs/mathlive/?q=virtualKeyboardToggleGlyph) option.

**Comment by zwz** [comment]
Nice.
Thank you for your instructions.
