### ISSUE TITLE
[mathlive.io site] Using overflow: scroll doesn't look right on Windows

### ISSUE THREAD

**Issue by matthew-e-brown** [arnog/mathlive#613]
## Prerequisites

-   [x] New issue

[For more information, see the `CONTRIBUTING` guide.]

## Description

I can't find where the sourcecode for mathlive.io lives (if it is even public), so I figured I'd open this issue here. Basically, using `overflow: scroll` or `overflow-y: scroll` *forces* this big, ugly, white scroll-bar to appear for that container (If only Windows had those nice fading scrollbars that MacOS has 😪). It looks pretty rough when they border your whole site:

![nav shown, no-fix](https://user-images.githubusercontent.com/43387454/92310307-11fc8880-ef7b-11ea-922c-8cf147670349.png)

However, a quick tweak in DevTools takes care of this pretty easily:

```
nav#menu {
  /* old: */
  overflow-y: hidden;
  /* new: */
  overflow: hidden auto;
}

#content {
  /* old: */
  (this rule is also present in a media query for min-width: 1111px)
  overflow: hidden;
  /* new: */
  overflow: hidden auto;
}
```

Setting these values to `hidden auto` will let you keep all the same styles everywhere else without having to rework how the page is built, but also hide unnecessary scrollbars. It will only add a vertical one when necessary, but also then hide the horizontal one that appears once the vertical one does, since the vertical one increases the width of the container slightly on windows. See below:

![nav hidden, fix](https://user-images.githubusercontent.com/43387454/92310552-a23bcd00-ef7d-11ea-896d-e38d5389b362.png)
![nav shown, fix](https://user-images.githubusercontent.com/43387454/92310545-8f28fd00-ef7d-11ea-91e1-0f9690550023.png)

### Actual behavior

N/A

### Expected Behavior

N/A

## Steps to Reproduce

N/A

### Environment

**Operating System**
Windows

**Browser** Chrome, IE, Firefox

**URL** https://mathlive.io

**Comment by arnog** [comment]
Thanks for reporting this issue. 

>#content {
>  /* old: */
>  (this rule is also present in a media query for min-width: 1111px)
>  overflow: hidden;

I think this was `overflow: scroll`. 

What you're suggesting has a slightly different semantic, as that means the horizontal scrollbar will now not appear. I think `overflow: auto` should work better.

**Comment by matthew-e-brown** [comment]
Yes, true. I didn't think the horizontal scrolling was used anywhere, so I thought keeping it set to `hidden` would be closer to the current version. Otherwise, I agree, `overflow: auto;` would be more proper. 😄

**Comment by arnog** [comment]
OK, I think it's fixed now. Please re-open if it's still an issue on your end.
