### ISSUE TITLE
input many e letters cause error and the page be fake dead state  in side the \begin{equation}  \end{equation}

### ISSUE THREAD

**Issue by 2010hexi** [arnog/mathlive#628]
## Prerequisites

-   [ ] New issue
       

## Description

I need several line to present formula, so I add  

```
\begin{equation} 
 abc efg 
\end{equation}
```

so when I strike the ENTER key, it will start a new line for me to input formula, it is good for me, you can take a look at this image,

![image](https://user-images.githubusercontent.com/43429845/92671109-0547ae00-f348-11ea-95f2-0a6c7feca3ce.png)

but the strange things happen when you type  many eeeeeeeeee  and then ENTER ,  and then you want to continue input other thing on the next line , something wrong ,  you will see like this:

![image](https://user-images.githubusercontent.com/43429845/92671426-cd8d3600-f348-11ea-81a9-590a23cfbdfc.png)

Look at this gif, you will more clear.

![20200910_093308](https://user-images.githubusercontent.com/43429845/92671452-e4cc2380-f348-11ea-8471-bf49191ef114.gif)

it seems that it will automatically  copy again the \text{eeeeeeeeeeeeee} and  \end{equation} and then put them after the first \end{equation}

I have no idea how to deal with this issue, and I try to use   \​begin{multline}...\end{multline}  ,  but it doesn't work. 

![image](https://user-images.githubusercontent.com/43429845/92672597-94a29080-f34b-11ea-88e7-f5cc19373b81.png)

![image](https://user-images.githubusercontent.com/43429845/92672720-eea35600-f34b-11ea-9017-d6fae32ab864.png)

I want to know if any config can help stop it automatically  convert the  e to the \exponantialE command ?

or any other approaches to solve this problem?

### Environment

Windows

 Chrome

**Comment by arnog** [comment]
Thanks for reporting this and for the screencast, this was very helpful in understanding your report.

You can  remove the definition for the "ee" inline shortcut by setting the `overrideDefaultInlineShortcuts` options to true, and the `inlineShortcuts` option to the default value, minus the entry for 'ee'.
