### ISSUE TITLE
No fraction line rendered while 125% zoom in on Chrome.

### ISSUE THREAD

**Issue by arielkuzminski** [arnog/mathlive#637]
## Prerequisites

-   [x] New issue

## Description

In **Chrome** (85.0.4183.102) while page is zoomed in to **125%**, fraction line **does not** render.

[Screenshot](https://i.imgur.com/Vcy0eRx.png)

### Actual behavior

Fraction line does not render on 125% zoomed in Chrome while it should.

### Expected Behavior

Fraction line does render on 125% zoomed in Chrome.

## Steps to Reproduce

1. Zoom in Chrome to 125% (CTRL and +)
2. Check your fraction line

### Environment

**Windows 10 64-bit - 2004 version** 100% system zoom, native FULL HD resolution

**Chrome (85.0.4183.102)**

### Sugested workaround

```
.ML__mathlive .mfrac .frac-line::after {
    border-bottom-width: .05em;
}
```

Easily can do PR with fix however I'm not sure if it's suitable fix or just quick workaround so I just made a ticket.

Greetings.

**Comment by arnog** [comment]
That's probably a fine fix. This is something that every other version of Chrome breaks (often in different ways). Sigh.

**Comment by arielkuzminski** [comment]
I just found out that same problem exists with "sqrt-line": [Screenshot](https://i.imgur.com/2MQiRoE.png)
And fix (similar):
```
.ML__mathlive .mfrac .frac-line::after,
.ML__mathlive .sqrt .sqrt-line::before {
    border-bottom-width: .05em;
}
```
