### ISSUE TITLE
Are AtomIDs stable?

### ISSUE THREAD

**Issue by hubertlepicki** [arnog/mathlive#653]
I am implementing some functionality that relates to highlighting parts of the equation. I noticed I can do it by remembering the atom IDs (data-atom-id) of the rendered DOM HTML elements and highlighting the DOM nodes by adding appropriate class to them.

I also noticed that for the same equation, the atom IDs seem to be the same no mater where I render it and in which browser.

Is this correct and intended and I can rely on the atom IDs being stable this way, or you think it's a stupid idea that will backfire in the future?

**Comment by stefnotch** [comment]
Out of curiosity, what functionality are you implementing?

**Comment by hubertlepicki** [comment]
In short: it's a math quiz, where students have some equations to solve. After several seconds/minutes we display some hints. One of these types of hints is to highlight parts of the equation. For example if it's a quadratic equation like 4x^2 + 8x + 12 = 0, we may want to highlight 4, 8 and 12 and display a hint that 'all these digits can be divided by 4'.

**Comment by stefnotch** [comment]
I guess issue https://github.com/arnog/mathlive/issues/387 is relevant to your use-case then. 
@arnog Maybe it's worth labeling #387 as a `feature` request?

**Comment by arnog** [comment]
Yes, it sounds like #387 would be a more general solution to this.

That said, yes, the atom-id are stable for a given Latex equation: the atom-id are calculated from a hash of the latex of the equation.

**Comment by hubertlepicki** [comment]
Cool thank you. As for #387 I guess it may be viable solution but maybe not. For example, I may want to highlight just an "x" in equation, at given position, i.e. 2nd "x".

We have these steps where we'd highlight part of equation and expect user to enter transformed value and the highlight is a hint to the user what they have to do next. We were considering using latex fragments to highlight but if the same fragment appears multiple times in equation that brings in some complications. This is why we decided to go with remembering atom IDs.
