### ISSUE TITLE
Top line of a square root not showing up

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#655]
##  Description

The top line of a square root doesn't show up in Firefox with the default zoom level. If it's relevant, my Windows 10 is set to scale things by 125%.

### Actual behavior

![image](https://user-images.githubusercontent.com/10220080/94847581-12296000-0423-11eb-88c0-04b40113a169.png)

### Expected Behavior

This is a regression, possibly caused by a Firefox update.

## Steps to Reproduce

`\sqrt[]{333+4}`

### Environment

**Operating System**
Windows 10

**Browser** Firefox 81.0

**Comment by arnog** [comment]
What version of Mathlive are you seeing this with? I fixed a similar issue [here](https://github.com/arnog/mathlive/commit/17abfb674003c80d0c11d3bb8209a318fbb995a7).

**Comment by stefnotch** [comment]
Latest from master f5c284ea2736273e0307ab88c0f3bb2c917d6861

**Comment by arnog** [comment]
:( the fix I did for Chrome probably broke this, then. I'll have a look at it.

**Comment by stefnotch** [comment]
Alright, thank you!
(I'm really starting to see see why you would use SVGs if you were to rewrite the renderer.)

**Comment by arnog** [comment]
OK, I wasn't able to repro this on Firefox Mac. I have checked-in a potential fix, though. Give it a try and let me know. If this doesn't work, I'll have to install Windows :(

**Comment by stefnotch** [comment]
@arnog The top line of a square root now shows up, even if it's a bit wide. However, under some circumstances, the fraction-line disappears. 

![image](https://user-images.githubusercontent.com/10220080/95305767-b88fbe00-0886-11eb-8930-d704759a918a.png)

```
3+\frac{3}{3}-\sqrt[]{33333}+\frac{\sin \mleft(x\mright)}{\cos \mleft(x\mright)}
```

After playing around with it for a bit, it seems like reverting b3de7fd8eeaddfb22bb2c621390f38d7084101d1 and using `transform: translate(0,0)` to fix both issues should work.

**Comment by arnog** [comment]
OK, great, let's do that. There are two different code paths for hardware accelerated drawing and non-hardware accelerated drawing. It's usually the hardware-accelerated path that has issues, but it looks like that's the reverse on Firefox on Windows. Oh well...

**Comment by arnog** [comment]
I've pushed a changelist.
