### ISSUE TITLE
\begin{array}... external output has extra row

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#66]
## Description
When I enter a two row array, the generation of the LaTeX and MathML has an extra row.

## Steps to Reproduce
1. In mathlive.io paste `\begin{array}{r} 123 \\ 3\end{array}`. This displays correctly with two rows.
2. Observe that the TeX that is generated is `\begin{array}{r}123 \\ 3 \\ \end{array}` and the MathML is
```
<mtable columnalign="right ">
    <mtr>
        <mtd>
            <mn>123</mn>
        </mtd>
    </mtr>
    <mtr>
        <mtd>
            <mn>3</mn>
        </mtd>
    </mtr>
    <mtr>
        <mtd>
        </mtd>
    </mtr>
</mtable>
```

Both of these have three rows instead of two rows.

**Comment by arnog** [comment]
Great point. I don't know how I didn't notice that!
