### ISSUE TITLE
& in array env generates new row, not new column

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#67]
## Description
In an array environment, `&` should mark a new column and `\\` a new row. `\\` does the right thing, but `&` creates a new row also, not a new column.

## Steps to Reproduce
In mathlive.io, paste `\begin{array}{r}-13 & +13 \end{array}`. The display is
![image](https://user-images.githubusercontent.com/1545836/37552842-d749e896-2979-11e8-987a-0c859f26e655.png)

It should be
![image](https://user-images.githubusercontent.com/1545836/37552845-eae771e8-2979-11e8-82e8-9bb765c53114.png)

**Comment by arnog** [comment]
This is actually the correct behavior. At least it matches what TeX does. Try it with http://quicklatex.com/

The reason it behaves this way is that with the `array` environment, if you have specified that it should have a single column with `{r}`, any extra columns will be wrapped on the following line. If you want more than one column, specify it using `{rr}` for example.

**Comment by NSoiffer** [comment]
FYI: I checked a TeX expert. He said the input is an error and any behavior from rejection to what I thought should happen to what you implemented is okay. LaTeX auto corrects after issuing an error. This allows it to keep on going to report more errors. It's correction converts & to \\, so what you did agrees with the implementation, but it is not something one should count on. In other cases, he said the auto correct does things that are not useful, but in this case, it is reasonable.
