### ISSUE TITLE
Copy and paste of some expressions with square roots can change them to corrupt the resulting mathml

### ISSUE THREAD

**Issue by timtsm** [arnog/mathlive#677]
## Description

Certain expressions with square roots, when copied and pasted, produce a different result than you started with, which reports mathml which is invalid due to having an `mroot` element with only one child (rather than `msqrt` with that child).

My guess is the real underlying bug is that `\sqrt[]{x}` should be translated to `msqrt` rather than `mroot`. Note that `\sqrt[x]{}` is also translated to `mroot` with one child, so you can't tell which child is missing from the mathml alone.

## Steps to Reproduce

1. Make a new field.
2. Type `y=\sqrt{x}` _[enter]_
2a. The latex reported at this point from the api is `y=\sqrt{x}`
2b The mathml is `<mrow><mi>y</mi><mo>=</mo><msqrt><mi>x</mi></msqrt></mrow>`
3. Type _control-a_ _control-c_
3a. Paste the result somewhere and verify it is `$$y=\sqrt[]{x}$$`
4. Make a new mathfield and paste that result into it.
4a. The latex reported will be `y=\sqrt[]{x}`
4b. But the mathml is `<mrow><mi>y</mi><mo>=</mo><mroot><mi>x</mi></mroot></mrow>`, which is invalid.

Note that this does _not_ happen if you type just `\sqrt{x}` originally instead of `y=\sqrt{x}`. In that case, the copied text is `$$\sqrt[]{x}$$`, but the latex after pasting is `\sqrt{x}` and the mathml `<msqrt><mi>x</mi></msqrt>`.

### Actual Behavior

The mathml of the final result is `<mrow><mi>y</mi><mo>=</mo><mroot><mi>x</mi></mroot></mrow>`.

### Expected Behavior

The final mathml should be `<msqrt><mi>x</mi></msqrt>`.

### Environment

Chrome 85.0.4183.121 on Linux.
Chrome 85.0.4183.121 on Windows 10.

**Comment by arnog** [comment]
Probably related to #534

**Comment by arnog** [comment]
Fixed in mathlive@0.60.0
