### ISSUE TITLE
Event Listeners seems to not be released after component is destroyed

### ISSUE THREAD

**Issue by mciissee** [arnog/mathlive#685]
## Steps to Reproduce

1. Go to this link https://premierlangage.github.io/platon-front/components/forms/wc-math-live
2. Open the virtual keyboard of the math field component
3. Close it and go to another page (e.g matrix)
4. start editing any input field you will see an exception on the browser console

### Actual Behavior

[What happens when you follow the steps above]

The following exception is raised

```js
ERROR TypeError: can't access property "querySelectorAll", mathfield.virtualKeyboard is undefined
    unshiftKeyboardLayer mathlive.mjs:27711
    makeKeyboard mathlive.mjs:27680
    Angular 14
    makeKeyboard mathlive.mjs:27678
    toggleVirtualKeyboard mathlive.mjs:28012
    toggleVirtualKeyboard mathlive.mjs:28034
    perform mathlive.mjs:20882
    executeCommand mathlive.mjs:30880
    attachButtonHandlers mathlive.mjs:19235
    Angular 14
    on mathlive.mjs:18912
    attachButtonHandlers mathlive.mjs:19186
    MathfieldPrivate mathlive.mjs:30493
    connectedCallback mathlive.mjs:33569
    Angular 5
    ngOnInit math-live.component.ts:51
    __awaiter tslib.es6.js:74
    ZoneAwarePromise Angular
    __awaiter tslib.es6.js:70
    ngOnInit wc-math-live.js:34421
    ngOnInit web-components.ts:133
    __awaiter tslib.es6.js:74
    ZoneAwarePromise Angular
    __awaiter tslib.es6.js:70
    ngOnInit main.js:2244
```
### Expected Behavior

The listeners should be released when component is no more present on the DOM.

[Is this a regression: did it use to work in a previous version?] Yes

### Environment

**Operating System**
macOS Catalina

**Browser**
- Safari latest
- Firefox latest
- Chrome latest

**Comment by arnog** [comment]
OK, this is fixed now with the following caveat:
- you should either use the Mathfield element (i.e. the `<math-field>` tag or `new MathfieldElement()`) not the `makeMathField()` function)
- OR call the `dispose()` method on the mathfield before removing it from the DOM.
