### ISSUE TITLE
How to destroy a MathfieldElement

### ISSUE THREAD

**Issue by escobar5** [arnog/mathlive#687]
## Description

I'm removing a MathFieldElement from the DOM, and I'm getting this error:

> Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined

in this line:

```
function unshiftKeyboardLayer(mathfield) {
    const keycaps = mathfield.virtualKeyboard.querySelectorAll('div.keyboard-layer.is-visible .rows .keycap, div.keyboard-layer.is-visible .rows .action');
```

I was searching for a method to destroy the element before removing it from the DOM but cannot find it, I tried with the deprecated `revertToOriginalContent` but it doesn't work, I get:

> 
> Uncaught TypeError: (void 0) is not a function
>     at QS.destroy (mathinputview.js:56)

**Browser**

Chrome Latest

**Comment by arnog** [comment]
To remove an element, call the `remove()` DOM element method, for example:

```javascript
document.querySelector('math-field').remove();
```

There was a recent fix that should address the issue you've run into (in 5c5f13e). This is available in the main branch, but not yet in a published version.

**Comment by escobar5** [comment]
Yes, updating to main fixes the problem. Thank you!
