### ISSUE TITLE
Convert from AMD to JS modules

### ISSUE THREAD

**Issue by arnog** [arnog/mathlive#69]
MathLive currently uses requirejs to implment AMD-style modules. Native JavaScript modules are now supported by the major browsers and Node.

We should:
- convert all the import/export statements in the JS files to be JS modules
- modify the package.json file and webpack/babel configuration accordingly

**Comment by jboxman** [comment]
Hi. I think I can look at this.

**Comment by jboxman** [comment]
It doesn't look like I can close this.
