### ISSUE TITLE
Unable to run mathlive for VueJS with package from node_module 

### ISSUE THREAD

**Issue by BruhJerem** [arnog/mathlive#695]
## Description

I still have this problem when i reproduce the example for VueJs

in main.js

```
import MathLive from 'mathlive/dist/mathlive';
import Mathfield from 'mathlive/dist/vue-mathlive.mjs';
Vue.use(Mathfield, MathLive);
```

In my math component

```
<mathlive-mathfield id="mf" ref="mathfield" :config="{smartFence:false}" v-on:focus="ping"
            :on-keystroke="displayKeystroke" v-model="formula">f(x)=</mathlive-mathfield>
```

gives this error

`TypeError: Cannot read property '0' of undefined`

![Capture d’écran 2020-11-03 à 17 31 34](https://user-images.githubusercontent.com/25407613/98013261-71034000-1dfa-11eb-84ec-c20aef4ebbb1.png)

### Environment

**Operating System**
MacOS

**Browser** Chrome

**Comment by arnog** [comment]
The title is confusing me. Could you clarify: this is not happening when running the code in `examples/vue/index.html`, right? This is running your own code?

Do you have the code hosted somewhere so I could further debug this? It's hard to tell what's going on just from the info in the report. It seems like perhaps the DOM element that the mathfield is created from does not exist? What's at like 30481 of `mathlive.js`?

**Comment by BruhJerem** [comment]
Hello, yes, sorry, I changed the title.

This is what there is on the line of the error.

![Capture d’écran 2020-11-04 à 09 19 22](https://user-images.githubusercontent.com/25407613/98086341-e4e72c00-1e7e-11eb-8a1a-7eb81ed4a157.png)

It looks like, this line is doing the error

```
textarea = this.element.children[iChild++]
                .firstElementChild;
```

Maybe, the error is by my import at the beginning in my app.js.
I can't import from the url like in the example. I just tried from the example and it is working..

```
import Vue from 'vue'
import MathLive from "mathlive/dist/mathlive.mjs";
import MathfieldComponent from "mathlive/dist/vue-mathlive.mjs";
import { store } from './modules/store'
import router from './router'
import App from './App.vue'

Vue.use(MathfieldComponent, MathLive);

export function createApp () {
  const app = new Vue({
    // the root instance simply renders the App component.
    render: h => h(App),
    store,
    router
  })
  return { app, router, store }
}
```

**Comment by arnog** [comment]
There seems to be a configuration issue...

It appears that assigning to `innerHTML` (line 30596) does not produce the expected result (i.e. `this.element` should have some children).

Since I still can't reproduce this, could you inspect `this.element`, `this.element.innerHTML` and `this.element.children` to confirm this?

Do you have some Babel pre-processing that maybe is getting triggered by the template literal line 30590? Maybe something to support jsx? It might be best if there was *no* processing done on the `mathlive.mjs` file.

**Comment by BruhJerem** [comment]
Thank you for your response.
So, I made some console log, and this is what I got.

![Capture d’écran 2020-11-04 à 14 13 18](https://user-images.githubusercontent.com/25407613/98116000-f3960900-1ea7-11eb-8a0d-ec368ce7c485.png)

this.element

`<!--function (a, b, c, d) { return createElement(vm, a, b, c, d, true); }-->`

this.element.innerHTML

```
mathlive.mjs:30600 <span class="ML__textarea"><textarea class="ML__textarea__textarea" autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" aria-hidden="true" tabindex="0"></textarea></span><span class="ML__fieldcontainer"><span class="ML__fieldcontainer__field"></span><span ></span></span>
        <div class="ML__sr-only">
            <span aria-live="assertive" aria-atomic="true"></span>
            <span></span>
        </div>
```
 this.element.children

`mathlive.mjs:30601 undefined`

And here is the error.

I have some babel configuration, and that cause the issue it seems.

**Comment by arnog** [comment]
Hmmm... I think the warning at the top might be relevant: "You are using the runtime-only build of Vue...". It appears that the element that the Mathfield builds on (`this.element`) is not an HTMLElement but some comment node (!?) Try including the Vue runtime with its compiler.

**Comment by BruhJerem** [comment]
Sooo, i added this in app.js

`runtimeCompiler: true`

I got some other error now

![Capture d’écran 2020-11-04 à 15 09 08](https://user-images.githubusercontent.com/25407613/98121551-ba619700-1eaf-11eb-965e-f6f3f383448b.png)

The console logs are in this order:

this.element
this.element.innerHTML
this.element.children

**Comment by BruhJerem** [comment]
Ok, I just forgot to add a ++ in the condition for iChild...

I have still this error:

![Capture d’écran 2020-11-04 à 15 26 10](https://user-images.githubusercontent.com/25407613/98123391-162d1f80-1eb2-11eb-9f4f-fdc76f8bdf88.png)

But i got the ping function from the component. So it looks like it is all good :)

**Comment by BruhJerem** [comment]
So, i fixed this problem by adding the font folder to public (is there a better way ?)

**Comment by arnog** [comment]
Great! If everything is resolved, feel free to close this issue. I'll make sure to add a troubleshooting step in the documentation about `runtimeCompiler: true`

**Comment by BruhJerem** [comment]
Perfect, thank you 👍

**Comment by TCMAD** [comment]
> 
> 
> So, i fixed this problem by adding in config : `fontsDirectory : '/src/node_modules/mathlive/dist/fonts'`

Hello @BruhJerem , I have the same issue + some fonts errors.

![image](https://user-images.githubusercontent.com/40864981/98458215-8b3c7580-218e-11eb-8e85-8692418efb42.png)

Can you tell me where did you change the fonts directory ?

I tried this but nothing change:
```html
            <mathlive-mathfield
              :config="{smartFence:false, fontsDirectory:'/src/node_modules/mathlive/dist/fonts'}"
              v-model="question"
            ></mathlive-mathfield>
```

**Comment by BruhJerem** [comment]
Hello, did you run `npm install mathlive` ? And if so, is it in you node_modules ? 
Check if the path exists, maybe thats the error

**Comment by TCMAD** [comment]
Yes it's installed and i find it on my node_module : 

![image](https://user-images.githubusercontent.com/40864981/98461573-82a76780-21ad-11eb-8bb6-a2cbb3b8e9f3.png)

**Comment by BruhJerem** [comment]
So, apparently, the package doesn't care about the config of fonts directory. The default is './fonts' and it doesn't change. Idk why it worked for me last time. But now, I have the same problem as you.
I think you can open a Issue for this.

For now, you can fix it by changing the variables in the package in the function getDefault()..

**Comment by arnog** [comment]
@TCMAD based on the error messages you're getting in the console the issue you're encountering seems to be related to a server configuration issue. See https://github.com/FortAwesome/Font-Awesome/issues/8078

**Comment by arnog** [comment]
@BruhJerem if you have a reproducible case where the `fontsDirectory` option does not work I would be very interested in seeing it. Could you open an issue about that?

**Comment by BruhJerem** [comment]
@arnog, it's just that in the documentation it's telling to use `config` for fontsDirectory. But actually it's `option` ?

Also, I saw that the package is only taking from a folder that is public. So you can't get it from your local assets, or your node_modules.

**Comment by arnog** [comment]
Good catch regarding the documentation. The `options` used to be called `config` and the README file had not been updated. Done now.

I don't know what you mean regarding `from a folder that is public`. When setting the `fontsDirectory` option it can be either a relative path (which is relative to the location of the `mathlive.mjs` file) *or* a fully qualified URL (e.g. `http://myserver.com/assets/fonts`) or if you're executing locally, a local directory, i.e. `file://my-drive/my-projects/node_modules/myproject/fonts`.
