### ISSUE TITLE
\sqrt command produce wrong sequence

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#696]
## Description

`\sqrt` command produce wrong sequence, it place a root w/o placeholder and then navigation in editor are broken.

## Steps to Reproduce

Please check the following gif recording:
![060a5139-497f-4294-a568-715e5f03297b](https://user-images.githubusercontent.com/7888563/98395226-01e15200-206d-11eb-9ace-86cfadcbd03b.gif)
### Actual Behavior

Placeholder is not placed under the root and navigation are broken

### Expected Behavior

The same as a `sqrt` command

### Environment

**Operating System**
Windows

**Browser** Chrome, Opera (other is not tested), I think that is not depend on that

**Comment by arnog** [comment]
I have a pending fix for this.

**Comment by arnog** [comment]
Fixed with bcb807d

**Comment by alexprey** [comment]
That now works from virtual keyboard, but stil reproduced when I'm typing \sqrt

**Comment by arnog** [comment]
That's working as expected: when you're using the Latex/Command mode (i.e. typing latex directly), whatever you type is inserted directly. If you want the placeholder you would type `\sqrt{\placeholder{}}`. However, note that you can also use `sqrt` (without the "slash") in which case it's an inline shortcut, which is defined as including the placeholder.

**Comment by alexprey** [comment]
Ok, but why then I can't remove root after using the slash latex command?

1. Use `\sqrt` and enter
2. Press backslash
3. Cursor going out of root, but root steel in the editor

I'm test it a bit more and when I use `\sqrt{2}` or `\sqrt` it works better. But I found a new issue with sqrt and backspace key
![mathlive-sqrt-issue](https://user-images.githubusercontent.com/7888563/99145464-2b5b3880-2680-11eb-9743-ff49542dcbce.gif)

**Comment by arnog** [comment]
The version of mathlive on mathlive.io is a bit behind. Can you reproduce these problems with the version of mathlive in the main branch? This seems to work for me.
