### ISSUE TITLE
popover is not work with new math-field element

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#697]
## Description

Popover is not work with new math-field element. That placed at the end of document w/o any styling, etc. The same is work on demo site, but by sources it use a `makeMathField` method instead of new `math-field` HTML element.

[Include screenshots, screen recordings, code fragments or CodePen if applicable]

## Steps to Reproduce

1. Initialize MathLive editor with `math-field` HTML element on the page
2. Start to type any command

### Actual Behavior

Popover renders incorrect
![image](https://user-images.githubusercontent.com/7888563/98396330-a0ba7e00-206e-11eb-854f-1a8c28580c99.png)

### Expected Behavior

Popover should be renders under caret with proper styles
![image](https://user-images.githubusercontent.com/7888563/98396171-5d600f80-206e-11eb-8224-514cf376b917.png)

### Environment

**Operating System** Windows

**Browser** Chrome, Opera (other is not tested), I think that is not dependent from that

**Comment by alexprey** [comment]
I start to looking into that in the fork

**Comment by arnog** [comment]
Thanks for the fix!
