### ISSUE TITLE
getCaretPoint in popover.ts returns undefined

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#699]
## Description

`getCaretPoint` method in `popover.ts` returns undefined, so it leads to wrong positioning of popover in math-field

![image](https://user-images.githubusercontent.com/7888563/98398688-6c48c100-2072-11eb-9797-a61bbcfa6df9.png)

I'm check on previous version and everything works fine.

## Steps to Reproduce

1. Render `math-field` field
2. Start typing a command like a `\sqrt`

### Actual Behavior

Popover renders at the end of document

### Expected Behavior

Popover must be rendered under caret position in the editor.

### Environment

**Operating System**
Windows

**Browser** Chrome, Opera (other browsers is not tested)

**Comment by arnog** [comment]
I have a pending fix for this.

**Comment by alexprey** [comment]
I'm not sure which commit fix it, but I'm just test the latest build and now that works fine! Thanks you!
![formula-issue-fixed2](https://user-images.githubusercontent.com/7888563/98832168-8b1dcd80-244d-11eb-9db0-434e3be63c4e.gif)
