### ISSUE TITLE
Problems with \enclose rendering

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#7]
## Description

The new \\enclose command doesn't render properly. It should center the contents and add some padding. For maximum flexibility, the alignment and padding can be parameters, but the defaults should definitely be "center" for alignment and probably 0.4em horizontally and 0.5ex vertically (taken from the recommendations in the MathML spec).

As an example of the poor rendering,
    \\enclose{updiagonalstrike downdiagonalstrike}{\blacksquare}

displays as 
![image](https://user-images.githubusercontent.com/1545836/27555569-0054174e-5a67-11e7-93eb-a3d0c00b57e5.png)

(ignore the blue blob, that seems to be an artifact from the screen copy tool)

In the more complicated second case below, the centering and padding look good, but the linecap style on the lines can be improved (I think):
	\enclose{updiagonalstrike downdiagonalstrike}[2px solid red]{\frac{x^2+y^2}{\sqrt{x^2+y^2}}}

![image](https://user-images.githubusercontent.com/1545836/27555895-56d522f6-5a68-11e7-980d-5ac2fd387acf.png)

**Comment by arnog** [comment]
Multiple fixes to get there, but here's how it looks now:

<img width="289" alt="screen shot 2017-07-02 at 9 05 03 am" src="https://user-images.githubusercontent.com/760798/27772489-5a418f88-5f18-11e7-9ddc-f1a416cb5662.png">

<img width="289" alt="screen shot 2017-07-02 at 9 05 28 am" src="https://user-images.githubusercontent.com/760798/27772488-5a1b0b56-5f18-11e7-8add-990e5f8e2c0d.png">
