### ISSUE TITLE
Strange behaviour with integral and fractions

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#701]
## Description

[Description of the bug or feature.]

Fractions that placed after integral have strange behaviour. Not sure that this can be a bug, but looks weird for a user

## Steps to Reproduce

![mathlive-int-fraction-issue](https://user-images.githubusercontent.com/7888563/98415158-c99e3b80-208d-11eb-9014-31389c8ad2da.gif)

### Actual Behavior

See recording above

### Expected Behavior

I'm expect that after pracing at slash, formula inserts fractions into integral instead of wrapping them

![image](https://user-images.githubusercontent.com/7888563/98415341-31ed1d00-208e-11eb-8242-ad552ae269b0.png)

### Environment

**Operating System**
[macOS, Windows, iOS. Include the version if possible]

**Browser** [Safari, Chrome, IE, Firefox, etc...]

**Comment by arnog** [comment]
Agreed. It probably makes sense to exclude all extensible symbols (`\int`, `\sum`, etc...) from being eligible as an implicit numerator.

**Comment by arnog** [comment]
Fixed with bcb807d

**Comment by alexprey** [comment]
Thanks a lot! Works perfeclty!
