### ISSUE TITLE
Wrong sound naming

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#704]
In the code used `keypress-spacebar.wav` names of sounds by default, but in `/dist/sounds/` folders it named as `KaypressSpacebar.wav` so that leads to errors

**Comment by arnog** [comment]
Thanks for catching this and for submitting a PR. I see you have filed #707 about the `dist/` folder and it's worth considering, however in general you don't need to include dist in your PR, or if you do make sure to include a production `dist` folder built with `npm run dist` (i.e. the `DEVELOPMENT-BUILD` file should never be checked-in). I'm pushing a simplified PR that renames those files.
