### ISSUE TITLE
Remove dist folder from repo

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#707]
That is a good practice to not store any artifacts in the git repo.
It make to hard merge various kind of features from different branches, increases the repo size and makes hard the code review of pull requests.

**Comment by arnog** [comment]
I am leaning towards agreeing with this, however I'd like to keep this open a little while before acting on it to give a chance to anyone who might rely on the `dist` directory in the git repo to speak up.

**Comment by arnog** [comment]
OK, one week without dissent: I'm going to move forward and nuke `dist/`.
