### ISSUE TITLE
Feature request: add indication in virtual keyboard when it have additional options on hold

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#709]
## Description

Design required.
I think that it will be great if virtual keyboard buttons can have additional indication when have additional options which shown on key holding.

Something like that 
![image](https://user-images.githubusercontent.com/7888563/98834435-434c7580-2450-11eb-9313-ef87a74816d0.png)

**Comment by alexprey** [comment]
@arnog do you approve this feature request? If yes, so I can own it

**Comment by arnog** [comment]
Yes, let's give it a try. I'm a bit worried that it's going to be visually busy (there are a lot of keys for which this will apply) and virtual keyboards on iOS and Android have the same functionality without an indicator, so not entirely sure it's needed, but I can see why it might be useful. Worst case we can have a configuration option to display it or not.

**Comment by arnog** [comment]
I did prototype this. However, it turns out that most keycaps actually have an alternate key, so it ends up being very busy, and not very informative. Closing.
