### ISSUE TITLE
Start a command typing broke layout

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#710]
## Description

Start a command typing breaks layout

![formula-issue-3](https://user-images.githubusercontent.com/7888563/98837377-f10d5380-2453-11eb-9c22-32966048245c.gif)

## Steps to Reproduce

1. Use mathfield elements (no matter with custom or default styling)
2. Press `ESC` or `\` button in the mathfield element

### Actual Behavior

Layout of mathfield editor content are broken

### Expected Behavior

Layout must keept while use type a command

### Environment

**Operating System**
[macOS, Windows, iOS. Include the version if possible]

**Browser** [Safari, Chrome, IE, Firefox, etc...]

**Comment by alexprey** [comment]
Thanks for a fix! Now looks better, but still have some jumping
![mathlive-jumping-issue](https://user-images.githubusercontent.com/7888563/99061696-ff25b600-25b2-11eb-98a5-abbe16692c2e.gif)

Do you have any quick guide about architecture in order to I can join to fixes? Now I'm not completelly sure how rendering are works

**Comment by arnog** [comment]
The `tutorials/CONTRIBUTOR_GUIDE.md` has some information that you might find useful, including an architectural overview. Let me know if you have any questions or if you have any suggestions on how it could be improved.
