### ISSUE TITLE
Shift + ArrowRight key pressing leads to error

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#711]
## Description

`Shift` + `ArrowRight` key perssing leads to error

![image](https://user-images.githubusercontent.com/7888563/98839629-d2f52280-2456-11eb-8427-0a41c0cc5ed4.png)

## Steps to Reproduce

1. Use mathfield element with entered formula
2. Put caret before last symbol in editor
3. Hold `Shift` button on keyboard
4. Press `ArrowRight` button on keyboard multiple times

### Actual Behavior

After second pressing in the console client error appears

### Expected Behavior

Navigation with ArrowLeft works fine, so ArrowRight button must have the same behaviour

### Environment

**Operating System**
[macOS, Windows, iOS. Include the version if possible]

**Browser** [Safari, Chrome, IE, Firefox, etc...]

**Comment by arnog** [comment]
As per above commit, fixed.

**Comment by alexprey** [comment]
Thanks!
