### ISSUE TITLE
Inconsistent return type of latexToAST

### ISSUE THREAD

**Issue by mildlyincompetent** [arnog/mathlive#72]
## Description
The `latexToAST` function in `mathlive.js` is listed in the docs as returning a `string` (changed in #71), but returns an `Object` when the AST module is loaded and the latex is successfully parsed. However, if the AST module is not loaded, an empty string (`''`) is returned instead.

## Steps to Reproduce
Use `latexToAST` on some LaTeX, for example `1+2`.

### Actual behavior
The correct AST is produced, but with type `Object`, not `string` as expected.

### Expected Behavior 
Expected either a MASTON-style string to be returned, or a default return value of an empty object instead of empty string if the module is not loaded.

It looks like the intended behaviour here is to output the AST object as the function is currently doing, and for the default return value (if the AST module is not loaded) to be changed to `{}`, as the default return value appears to be present simply because the function was copied over from latexToMathML.

**Comment by arnog** [comment]
That's correct. It's a copy/paste error, the return type is supposed to always be an Object.
