### ISSUE TITLE
The native keyboard doesn't show up on some Apple devices (iPad mini)

### ISSUE THREAD

**Issue by snikitina** [arnog/mathlive#723]
Hi, thank you for your consistent work on the library!

## Description

The native keyboard doesn't show up when the math field is focused on iPad mini and iPhone.

Firstly, I am not sure if this is expected behaviour, however I can see the native keyboard on iPad Pro so I was wondering if there is a way to make it work on iPad mini as well.

## Steps to Reproduce

1. Open https://mathlive.io/examples/latex/index.html in Safari on iPad mini
2. Focus the math field

### Actual Behavior

The native keyboard doesn't show up.

I can see no error messages in Web Inspector.

### Expected Behavior

I would expect the native keyboard to appear, e.g. here is the screenshot of iPad Pro in Apple Simulator app (I was also able to reproduce the same behaviour on two actual devices). 

![image](https://user-images.githubusercontent.com/3908566/100047393-7c301580-2e66-11eb-9ca8-373a884bcc84.png)

### Environment

**Operating System**
Device: iPad mini (5 generation) iOS 14.2
Device: iPhone 7 iOS 14.2
Apple's Simulator app v11.3: iPad mini (4th generation) iOS 13.3
Apple's Simulator app v11.3: iPhone 11 Pro iOS 13.3

**Browser**
Safari 13 & 14

**Comment by snikitina** [comment]
On a similar note, is it possible to prevent the native keyboard from showing up when the input is focused so that the virtual keyboard alone is used for input?

**Comment by arnog** [comment]
It is the expected behavior. See "Controlling when the virtual keyboard panel is displayed" in [MathLive Guide: Virtual Keyboard](http://cortexjs.io/mathlive/guides/virtual-keyboards/).
You can prevent the virtual keyboard from showing by setting the `virtualKeyboardMode` option to `off`. However even in this case the native keyboard will not show up. 
I'm curious: what is your use case for wanting the native keyboard?

**Comment by snikitina** [comment]
We have built a custom mini toolbar with a subset of characters that we require and we were hoping that we can get away with it and a native keyboard. While it works well on iPads, the Android experience (Android 10 Galaxy Tab S4) is completely broken: there is a huge delay before the characters appear and then you can't delete them. So it does feel like a virtual keyboard is a way to go.

My initial confusion was also caused by not being aware of Desktop vs Mobile mode on touch devices hence I was getting different behaviour on iPad Pro (native keyboard) and iPad Mini (no native keyboard). Forcing the browsers on all touch devices (i.e. the users) to always require Mobile version of the website makes the experience consistent.

I'm going to close the issue, thank you for the explanation.

**Comment by oatymart** [comment]
@snikitina can you expand on how you've done this?

> Forcing the browsers on all touch devices (i.e. the users) to always require Mobile version of the website makes the experience consistent.
