### ISSUE TITLE
`\left[...\right]` should get promoted to `bmatrix` environment, not `matrix`

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#724]
## Description

When I'm use matrix bracets and then try to fill content of that, brecets are removed

![image](https://user-images.githubusercontent.com/7888563/100083143-1dfd3580-2e5a-11eb-85dc-4d95f62e85c8.png)

I'm use following editor instance https://mathlive.io/examples/basic/index.esm.html

## Steps to Reproduce

1. Place matrix bracets from keyboard
2. Enter the first value
3. Press `Ctrl + ,` and type new value (the same when I'm use Enter to place a new row in the matrix)

### Actual Behavior

Matrix bracets removed from editor

### Expected Behavior

Matrix bracets must be in place

### Environment

**Operating System**
[macOS, Windows, iOS. Include the version if possible]

**Browser** [Safari, Chrome, IE, Firefox, etc...]

**Comment by arnog** [comment]
I can't figure out how to reproduce this. Could you clarify exactly which keys on the keyboard you are pressing?

**Comment by Kydyralin** [comment]
According to the reference page of LaTeX operators ([wikibooks](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Matrices_and_arrays) and [mathlive](https://mathlive.io/reference.html)) for the `\begin{matrix}...\end{matrix}` syntax it's expected to brackets to be not rendered so I think it's not a bug.

**Comment by arnog** [comment]
Oh, OK... I think I understand this report now. @Kydyralin is correct: `\begin{matrix}...\end{matrix}` display its content in tabular form, but without fences. 

For square brackets use `\begin{bmatrix}...\end{bmatrix}` and for parentheses use `\begin{pmatrix}...\end{pmatrix}`

**Comment by alexprey** [comment]
Ok, sorry for late response. Initially braces was placed in mathlive by virtual keyboard, but when I add a new column or row - braces disappears from input. I'm record gif, please check it for details

![matrix-issue](https://user-images.githubusercontent.com/7888563/101020964-497dcf80-3580-11eb-8168-14fb8b83ef2a.gif)

**Comment by arnog** [comment]
Oh, OK, I really got it now. The problem is in the tabular promotion algorithm (when you add a column/row the existing expression gets "promoted" to a tabular environment). It seems like it's getting promoted to a `matrix`, while in his case it should get promoted to a `bmatrix`.

**Comment by ImGelu** [comment]
@arnog any updates on this? I was able to reproduce this bug differently (not sure if it's the same problem, but I thought that commenting here would be a better option than opening a new issue):

1. Insert a `pmatrix`: `\begin{pmatrix}1 & 2 \\ 3 & 4\end{pmatrix}`
![Screenshot from 2022-05-25 13-16-03](https://user-images.githubusercontent.com/24230481/170239687-f6da100c-a53e-4349-9ae6-ce3a5ef424d9.png)
3. Copy the matrix via `CTRL+C` or via keyboard shortcut
4. Press `=`
![Screenshot from 2022-05-25 13-16-52](https://user-images.githubusercontent.com/24230481/170239773-617b9f25-193e-41dc-9c6b-950eb9aefe4e.png)
6. Paste the previously copied `pmatrix`
7. So far, the bracets are still visibile
![Screenshot from 2022-05-25 13-17-11](https://user-images.githubusercontent.com/24230481/170239849-6af278a2-795e-4f4f-83ad-1bbd3e860301.png)
9. Insert another `=`. The bracets dissapear.
![Screenshot from 2022-05-25 13-17-50](https://user-images.githubusercontent.com/24230481/170239972-8ff28f18-bc7a-4511-b490-2c86594f3508.png)

Note: this happens only if the editor has been focused the whole time. If you click outside it (thus losing its focus) before step 9, the bracets are stil there.

**Comment by ImGelu** [comment]
> @ImGelu that's a different issue

Ah, apologies for the useless bump then. Thought this had the same cause.

**Comment by arnog** [comment]
This is now working correctly. Typing `[` `a` followed by `alt`+`Tab` will promote the parenthesis to a `bmatrix`
