### ISSUE TITLE
'x' symbol pressed several times leads to strange behavior  

### ISSUE THREAD

**Issue by stylebc** [arnog/mathlive#726]
## Description

When I'm typing 'x' 2 times it is replaced with a cross symbol. 
![image](https://user-images.githubusercontent.com/7346159/100220756-d85b6e00-2f28-11eb-93a3-7534542ab659.png). 
Then repeat it 3 times, `x` symbol appears in unexpected places (or expected, not sure here). 
Then remove all by a backspace and enter the `x` symbol again. It will insert not `x` symbol but several crosses
gif attached 

## Steps to Reproduce

1. Press `x` on keyboard 6 times
2. remove symbols by backspace
3. press `x` again

### Actual Behavior
several crosses appeared
![chrome-capture (3)](https://user-images.githubusercontent.com/7346159/100222532-49038a00-2f2b-11eb-8ded-cf62f38cc073.gif)

### Expected Behavior
one `x` symbol should be inserted

### Environment

**Browser** Chrome

**Comment by arnog** [comment]
By default, "xx" is an inline shortcut for the `\times` command (✖️). This inline-shortcut can be turned off using the [inlineShortcuts`](http://cortexjs.io/docs/mathlive/#(%22options%22%3Amodule).(InlineShortcutsOptions%3Atype)) option.
So, that behavior is expected.
However, there is something going on after backspace is pressed. Either a single "x" or a `\times` (✖️) character should be inserted, but a string of them can appear, which is not the correct behavior.

**Comment by alexprey** [comment]
Not sure that this flow is correct. What I expect when typing 4 x symbols

| typings | actual | expected |
| - | - | - |
| `x` | `x` | `x |
| `xx` | `✖️` | `✖️` |
| `xxx` | `x✖️` | `✖️x` |
| `xxxx` | `✖️✖️` | `✖️✖️` |
```

This are actual for all shortcuts.

I'm try to looking into this issue and found that you use keystroke buffer that handled to rendering items. Why it done by this way?
