### ISSUE TITLE
virtualKeyboard Height

### ISSUE THREAD

**Issue by shariful2011** [arnog/mathlive#730]
Is there a way to increase/decrease the height of the virtualKeyboard? I badly need it, please help.

**Comment by arnog** [comment]
Yes, there might be some ways. Could you let me know more about what you are trying to do? Are you using custom keyboards or the standard ones? Why do you need to adjust the height? And do you need to increase it or decrease it?

**Comment by shariful2011** [comment]
I am using it on Chromium Embed for a Windows Application(exe). The area of my CEF is not so big, that's why I need to decrease the height. I am using the standard one. Please see the image.

![image](https://user-images.githubusercontent.com/634779/100537241-d824e080-3250-11eb-8854-0023d1bd710b.png)

**Comment by arnog** [comment]
ok, I see.
Right now, you can control the height of the virtual keyboard by defining a CSS rule like this:

```css
.ML__keyboard { height: 200px; }
```

However, this is far from perfect as the keycap size will not adjust and some will get offscreen.

To address this, I've added some new CSS variables. To use them, define the following CSS variables on a parent container (the `body` of your document, for example):
```css
body {
   --keycap-height: 40px;
   --keycap-font-size: 16px;
}
```

Adjusting the keycap height will automatically reduce the height of the virtual keyboard.

**Comment by shariful2011** [comment]
I tried as per your suggestion by adding those variables in the body but not working. Please check my index.html on how to solve it.
[index.zip](https://github.com/arnog/mathlive/files/5612042/index.zip)

**Comment by arnog** [comment]
Did you make a build of MathLive with those changes? The changes are in the main branch, but they are not in a published version.

**Comment by shariful2011** [comment]
Yes, I did pull from the master branch and build it.

**Comment by arnog** [comment]
Sorry, you have to specify those variables on the `.ML__keyboard` selector, with sufficient specificity to override the default, so:
```css
body .ML__keyboard {
    --keycap-height: 20px;
    --keycap-font-size: 12px;
}
```
