### ISSUE TITLE
Unable to type Z on Dvorak layout

### ISSUE THREAD

**Issue by sorenbug** [arnog/mathlive#732]
## Description

Pressing the Z key on Dvorak acts like a / press on QWERTY.

## Steps to Reproduce

1. Set your keyboard layout to Dvorak
2. Try typing `z` on https://mathlive.io

### Actual Behavior

A fraction box is inserted, like expected from a / press.

### Expected Behavior

A `z` is inserted.

### Environment

Windows 10 Home, 20H2, 19042.630

Google Chrome `86.0.4240.198 (Official Build) (64-bit) (cohort: Stable)`

---

This is related to #216. Today is the first day I've used MathLive, so I don't have any info on whether this is a regression or not. I apologize.

**Comment by arnog** [comment]
Thanks for reporting this. This was indeed broken. Should work better now.
