### ISSUE TITLE
Matrix braces is not supported in MathML: In conversion to MathML, unknown type : mopen

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#737]
## Description

Usage of braces from virtual keyboard leads to errors of MathML converter, that says that `mopen` or `mclose` entries is not supported. But if I use physical keyboard with `[` the output is correct

![image](https://user-images.githubusercontent.com/7888563/100737958-f243f780-33e5-11eb-87f9-3d5e95527597.png)

## Steps to Reproduce

1. Use math-field element with MathML output
2. Place matrix braces from virtual keyboard

### Actual Behavior

Output is not genereted correctly, debug information in console:
```
In conversion to MathML, unknown type : mopen
```

### Expected Behavior

Correct MathML are generated w/o any errrors.
Matrix specification: https://www.w3.org/TR/MathML3/chapter3.html#presm.mtable

### Environment

**Operating System** Windows
**Browser** Opera

**Comment by arnog** [comment]
Fixed now.
