### ISSUE TITLE
Virtual keyboard doesn't show itself

### ISSUE THREAD

**Issue by okeoke85** [arnog/mathlive#741]
## Description

Virtual keyboard doesn't show itself and in console some warnings appearing maybe this would be helpful
![image](https://user-images.githubusercontent.com/15729538/100872413-d2c6d080-34b2-11eb-9b56-012d13059de7.png)
Mayba font warnings have something to do with this situation even though i set up font directory as below code;
![image](https://user-images.githubusercontent.com/15729538/100874918-559d5a80-34b6-11eb-83b3-7b84f0f19a97.png)

[Include screenshots, screen recordings, code fragments or CodePen if applicable]

## Steps to Reproduce
Code setup in .vue file;

```
<template>
  <div>
    <v-card>
      <v-card-text>
        <div id="container"></div>
      </v-card-text>
    </v-card>
  </div>
</template>
```
and 

```
  mounted() {
    const mfe = new MathfieldElement({ fontsDirectory: "http://localhost:5000/asset/mathlive-fonts", virtualKeyboardMode:"manual"});
    document.getElementById("container").appendChild(mfe);
  },
```
[Provide steps that are specific and repeatable, if possible]

1. [First Step]
2. [Second Step]
3. [and so on...]

### Actual Behavior

Toogle on keyboard button and nothing happens, warnings show up on console as in the screenshot above

### Expected Behavior

Virtualkeyboard show up

[Is this a regression: did it use to work in a previous version?]

I' wrok on latest version 0.59

### Environment

**Operating System**
Windows 10

**Browser**
Chrome

**Comment by okeoke85** [comment]
Hi, it appears this is an old beatiful z-index problem, i override the  .ML__keyboard's z-index as below maybe it helps, thank you for this beatiful component though, best.
```
.ML__keyboard{
                z-index: 10000 !important;
            }
```

**Comment by arnog** [comment]
@okeoke85 Thanks!

There is a CSS variable you can set for that as well:

```css
body {
   --keyboard-zindex: 10000;
}
```

**Comment by okeoke85** [comment]
Thank you, by the way about warnings, do you think will they be harmful, as i mentioned i set the fontsDirectory but still see the warnings as well; it gets the default location of component even i set fontsDirectory like;

fontsDirectory = localhost:5000/asset/mathlive-fonts/

Best.

![image](https://user-images.githubusercontent.com/15729538/100992086-cb5fff80-356http://localhost:5000/asset/mathlive-

**Comment by arnog** [comment]
You're seeing these warnings in Chrome?

AFAICT despite the warning the font does still get used. I'd love to get rid of them, but I'm not entirely sure what the font parser is complaining about...

**Comment by okeoke85** [comment]
Sorry for late answer,

Yes it is chrome, the main reason seems to be; even if you set the fonts directory, at some point parser tries to get fonts from the directory where component is in but in functionalty it seems to be everything works fine, i debug the code even console.logged the fontsDirectory if my settings is being reflected in matlive.js, i saw they are reflected. For now everythins is fine jsut saw warnings. Thank you to be so considered.

Best.
