### ISSUE TITLE
import in Jest test fails

### ISSUE THREAD

**Issue by grant-davidson** [arnog/mathlive#768]
## Description

Jest tests that import from "mathlive" fail with the message "Cannot read property 'get' of undefined"

## Steps to Reproduce

1. Create a jest test that renders a component via jsdom and imports mathlive
2. Run the test

### Actual Behavior

Jest displays an error message:

    TypeError: Cannot read property 'get' of undefined

      1 | import React, { useCallback, useEffect, useRef } from "react";
      2 | import styled, { createGlobalStyle } from "styled-components";
    > 3 | import { MathfieldElement } from "mathlive";
        | ^

The problem is that jsdom doesn't support custom web components and the following mathlive code assumes its running in a browser where window has a customElements property:

```
if (!window.customElements.get('math-field')) {
    window.MathfieldElement = MathfieldElement;
    window.customElements.define('math-field', MathfieldElement);
}
```

According to this [post](https://stackoverflow.com/questions/57478484/how-to-test-custom-web-component-with-jest), upgrading to the latest version of jsdom may resolve this problem.

### Expected Behavior
  Mathlive should import successfully

### Environment
React 16.12.0
CRA 3.1.2

**Operating System**
Windows 10

**Browser** 
jsdom 16.4.0

**Comment by arnog** [comment]
@grant-davidson thanks for reporting this.

jsdom claims to be supporting web components as of 16.2.0. But it would seem to still have some problems. There are alternatives to using jsdom, though, such as using Puppeteer or happydom.

However, since Mathlive doesn't use jsdom, I'm not entirely sure if you are suggesting that Mathlive should be doing something different than what it currently is doing?

**Comment by grant-davidson** [comment]
Thanks @arnog for your reply.

Yes, I realise this is not a bug in Mathlive but I was wondering if you could change the customElements related code to:

```
if (window.customElements !== undefined && !window.customElements.get('math-field')) {
    window.MathfieldElement = MathfieldElement;
    window.customElements.define('math-field', MathfieldElement);
}
```

**Comment by arnog** [comment]
OK, I see. Sure, this could be added, although of course that means you still wouldn't be able to use the `<math-field>` element (but I guess the `MathfieldElement` class might be OK)

**Comment by grant-davidson** [comment]
Thanks @arnog !
