### ISSUE TITLE
Bug: Keycap doesn't render latex labels correctly

### ISSUE THREAD

**Issue by pratyusharma** [arnog/mathlive#773]
## Description
In the custom keyboard I have added the following keys:

```typescript
const mfe = new MathfieldElement({
customVirtualKeyboardLayers: {
    'layer-1': {
        rows: [ ....
            [ ....
                {
                    class: 'fnbutton',
                    latex: '\\frac{#0}{#?}',
                },
            ]
        ]
    }
}
}
```

But the keycap label isn't rendered according to the latex defined for the keycap. Below is how the key is shown. The keycaps which don't have a vertical positioning (eg. infinity, pi etc.) seem to be rendered fine.

The button functions as expected when clicked and inserts the correct latex to the math-field.

<img width="1077" alt="Screenshot 2020-12-25 at 3 09 48 PM" src="https://user-images.githubusercontent.com/22957102/103131091-58f6c100-46c5-11eb-8346-ae4f4c3494c9.png">

_The buttons in red have images set as key labels._

### Environment
**Angular**
Angular CLI: 9.1.13
Node: 10.16.0
OS: darwin x64

**NPM Package**
"mathlive": "^0.59.0"

**Operating System**
macOS 10.14

**Browser** 
Safari 12.0

**Comment by arnog** [comment]
I believe this is fixed in mathlive@0.60.0. Please re-open if you still see a problem.
