### ISSUE TITLE
htmlData command

### ISSUE THREAD

**Issue by zoranpopovic** [arnog/mathlive#785]
Katex has a really handy latex command `\htmlData{foo=a, bar=b}{x}` that allows for storing data within expression components, which is crucial for keeping track of expression changes, and backend interpretation of the changed math content.  Would it be possible to add it to Mathlive?  I would imagine \\cssId and \\class could be implemented using htmlData...

**Comment by arnog** [comment]
Yes, that's certainly possible.

Note that `\cssId` and `\class` are already supported.

**Comment by arnog** [comment]
Fixed by #786.
