### ISSUE TITLE
virtual keyboard state

### ISSUE THREAD

**Issue by ShaMan123** [arnog/mathlive#788]
## Accessing the virtual keyboard state (visible or not)

Hi,
How can I access the virtual keyboard state?
Listening to `virtual-keyboard-toggle` isn't good enough because it fires a lot and doesn't provider the current state.
It could be useful for the event to contain the state.
Any advice will be appreciated.

**Comment by arnog** [comment]
It looks like this property is not currently exposed. That's an oversight.

**Comment by ShaMan123** [comment]
This is good.
Pointing out that sometimes the keyboard isn't removed from the dom after dismissal. So after toggling a few math field I have a few keyboards in different states. As a workaround I remove all keyboards after dismissing. Then this works.

**Comment by arnog** [comment]
The `virtualKeyboardState` property is now available.

Note also that the issue with the spurious keyboards remaining behind should be fixed.

**Comment by ShaMan123** [comment]
Great! Thanks!!
