### ISSUE TITLE
Need the ability to increase spacing

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#79]
## Description
[Description of the bug or feature.]
For dyslexia, some students need additional space between symbols to help them distinguish the symbols. 

I could add spacing, but then it is in the content and affects backspacing, etc. Ideally, it would be a multiplier for the basic 'em' width used, so that (for example) `horizontalSpacing: 2` would double the standard amount of whitespace used (1/16 em -> 2/16em, etc).

**Comment by arnog** [comment]
I have added the `horizontalSpacingScale` scale property. It could be further refined to provide even more control of the layout, but not clear if that should just be an expansion of where this scaling factor is used (vertical spacing between big ops and their arguments?) or additional scaling factors. I suggest trying this and collecting feedback from users to better understand what, if any, other layout adjustments would be desirable.
