### ISSUE TITLE
Mathlive Keyboard: Space not working and not able to use % symbol with number

### ISSUE THREAD

**Issue by golukumar21** [arnog/mathlive#793]
## Description
When pressing the space key on virtual keyboard as well as our keyboard, Space is not working. Also when we try to put % after any keyword it's not rendering.
[Description of the bug or feature.]
Space key and % symbol not rendering(intermittent).
[Include screenshots, screen recordings, code fragments or CodePen if applicable]

## Steps to Reproduce
1. Try entering 15 [space] + 6.
2. Try entering 15 followed by %.
[Provide steps that are specific and repeatable, if possible]

1. [First Step]
2. [Second Step]
3. [and so on...]

### Actual Behavior
% symbol not coming up.
space not working.
[What happens when you follow the steps above]

[If there are any error messages, include the exact text shown,
or upload a screenshot. Some error messages may be displayed in the Javascript console.]

### Expected Behavior
Space should come up. => 15 + 6
% should come up. => 15%
[What did you expect to happen insteead]

[Is this a regression: did it use to work in a previous version?]

### Environment

**Operating System**
[macOS, Windows, iOS. Include the version if possible]
Windows
**Browser** [Safari, Chrome, IE, Firefox, etc...]
Chrome

**Comment by oatymart** [comment]
Reproducible in Mathlive 0.59.0 - at least for `%` character (shift-5) on US Macbook Pro keyboard. `%` character also disappears if pasted in.

**Comment by physedo** [comment]
I have the same problem in Mathlive 0.59.0 it works in this version https://mathlive.io/: mathlive.js v0.59.0-93-g1b6a4ee-dirty

**Comment by physedo** [comment]
it works when you make custome keyboard:` "virtualKeyboardMode": "manual",
      "customVirtualKeyboardLayers": {
          "layer-name": {
              "styles": "",
              "rows": [
                  [
                      {
                          "class": "keycap",
                          "latex": "\\%"
                      }
                  ]
              ]
          }
      },
      "customVirtualKeyboards": {
          "keyboard-name": {
              "label": "Json",
              "tooltip": "Json keyboard",
              "layer": "layer-name"
          }
      },
      "virtualKeyboards": "keyboard-name"`

**Comment by physedo** [comment]
How to import all keys and percent key ? @arnog

**Comment by arnog** [comment]
In mathlive@0.60.0:
- the `\%` command is accessible via the alt panel for the "/" in the virtual keyboard.
- to specify what happens when the spacebar key is pressed, set the `mathModeSpace` option. For example, set it to `"\\;"` to insert a medium space.

In main:
- pressing the "%" key on the physical keyboard will insert the `/%` command (new default inline shortcut)
