### ISSUE TITLE
Slash "/" character on French keyboard - wrong command

### ISSUE THREAD

**Issue by oatymart** [arnog/mathlive#807]
mathlive 0.59.0

On a French AZERTY keyboard layout in Linux, typing the `/` character (to start a fraction) doesn't result in the correct command. Instead, pressing the key beside Shift R (marked below) executes the fraction command.

![image](https://user-images.githubusercontent.com/43652944/106264547-15dcc000-6226-11eb-8180-93eed874e574.png)

I was checking the code and noticed an inconsistency [here](https://github.com/arnog/mathlive/blob/v0.59.0/src/editor/keyboard-layout.ts#L895): the id says `french.linux` and platform `apple`. No idea if this is related to the above issue, though.

**Comment by arnog** [comment]
I *think* there's a very good chance that you've correctly identified the issue.  I don't have a Linux setup to test it with, though.
