### ISSUE TITLE
Command completion does not trigger onContentDidChange

### ISSUE THREAD

**Issue by dangcuuson** [arnog/mathlive#81]
## Description
In command mode, after pressing tab/space/enter to finish insertion, the `onContentDidChange` as well as `onContentWillChange` callbacks were not invoked

## Steps to Reproduce

1. The following code are created based on the [basic example](https://github.com/arnog/mathlive/tree/master/examples/basic)
```html
<html>
<header>
    <link rel="stylesheet" href="./mathlive/mathlive.core.css">
    <link rel="stylesheet" href="./mathlive/mathlive.css">
</header>

<body>
    <div>Input: </div>
    <div id="mf">
        f(x)=
    </div>

    <div>Output (onContentDidChange): </div>
    <div id="output"></div>

    <script src="./mathlive/mathlive.js"></script>
    <script>
        (function () {
            function updateOutput(mathfield) {
                document.getElementById('output').innerHTML = mathfield.latex();
            }
            const mf = MathLive.makeMathField('mf', {
                onContentDidChange: updateOutput
            });
        })()
    </script>
</body>

</html>
```
2. Type '\\' to enter command mode
3. Insert any command (e.g: sin)

### Actual behavior
The output element does not get updated with the new inserted command

### Expected Behavior 
The output element should be updated with the new inserted command

**Comment by arnog** [comment]
Fixed now.
