### ISSUE TITLE
Font directory error in FireFox

### ISSUE THREAD

**Issue by bryanllewis** [arnog/mathlive#815]
## Description

Using MathLive 0.59.0 via npm on a Vue.js 2 app.  I am loading the mathfield programatically in the mounted() function.  Chrome (87 & 88) and Edge (88.0.705.56) work perfectly.  

```
import MathLive from 'mathlive';
this.mf = MathLive.makeMathField('formula', {
    virtualKeyboardMode: 'onfocus',
    fontsDirectory: '../fonts'
});
```

FireFox 85 fails to load the MathField.  The console shows this error:

![image](https://user-images.githubusercontent.com/5273255/106394080-8b27cc80-63af-11eb-88ab-fbba086a5be3.png)

MathLive load fails.  Virtual keyboard displays but field is not active.  It is failing on line 11994 of mathlive.mjs:

`const fontsFolder = new URL(fontsDirectory !== null && fontsDirectory !== void 0 ? fontsDirectory : './fonts', gScriptUrl).toString();`

The call to "new URL()" throws the exception when I try passing "../fonts" or the default of "./fonts".  If I comment out that line and change it to:

`const fontsFolder = fontsDirectory;`

And pass in a fully qualified URL via the options (e.g.  fontsDirectory: 'https://localhost:8081/fonts') then it works (and it still works on all other browsers too).

### Environment
**Operating System**
Windows 10

FireFox 85.0

**Comment by arnog** [comment]
I was not able to reproduce this.

There is something odd going on, though. Note that the error message you get is "URL constructor:  is not a valid URL". After the ":" there should be the URL that was passed in, in your case "../fonts". The fact that it appears to be blank is odd. A blank URL is indeed invalid. Also, can you verify that `gScriptUrl` is valid? It should be the URL of the script, i.e. something like 'http://example.com/mathlive/dist/mathlive.mjs'.

Do you have a code sample somewhere that I could use to try to debug this?

**Comment by bryanllewis** [comment]
On Chrome and Edge, the value of gScriptUrl is the name of the Vue script (https://localhost:8081/js/task.js), where as on FireFox, the value is an empty string.  So that's weird. and perhaps that is the real underlying problem.  I can't share this existing code directly on a public URL.  But I am going to strip down just this portion into a new Vue project and see if it still does it.  If it does, I will share that URL within the next day or two.  Thanks.

**Comment by arnog** [comment]
The fact that `gScriptUrl` is empty is definitely the problem: it prevents relative URL (such as `../fonts`) from being interpreted correctly. 

I'm interested to know why it happens, though. It has to be related to the way the script is loaded, perhaps because it is asynchronously loaded, or deferred loaded, or ...?

I also noticed that there was a fallback mechanism in place in case the script URL could not be obtained, but this fallback mechanism failed to trigger if the return script was an empty string (it only expected a null or undefined value). I've fixed that in the main branch.

**Comment by bryanllewis** [comment]
By creating a simple example, with only the MathLive stuff on the page, FireFox is now working.  So some other component or piece of code on my original page must be conflicting and causing this problem.  I will investigate further, but it's clearly not a bug.  Thanks.
