### ISSUE TITLE
Cannot input backslash on Mac with de-CH or fr-CH keyboard

### ISSUE THREAD

**Issue by PhilippImhof** [arnog/mathlive#816]
## Description

Using the [example page](https://mathlive.io/examples/basic/index.esm.html), when I press `shift+alt+7` on the keyboard, I only get a forward slash instead of a backslash:

![image](https://user-images.githubusercontent.com/52650214/106626917-7ea2a000-6578-11eb-8daf-762af2cb289a.png)

Switching to en-US, I can enter the backslash with a direct key press ($ on the QWERTZ keyboard) and get:

![image](https://user-images.githubusercontent.com/52650214/106627037-a6920380-6578-11eb-86db-46298de76cc1.png)

The behaviour is consistent with what happens on a Windows when I press `alt gr + <` (i.e. the normal way of entering a backslash on a de-CH keyboard). However, after having read [the list of keyboard shortcuts](http://mathlive.io/reference_shortcuts.html), I believe that entering a backslash should switch to command mode. 

### Environment

**Operating System**

Mac OS X Catalina and Windows 8.1

**Browser** 

Chrome 88.0.4324.96 (Mac) / 88.0.4324.104 (Win)

**Comment by Zahara-Nour** [comment]
Same problem with a Fr-Fr keyboard on Imac

**Comment by Zahara-Nour** [comment]
When cloning the repo and playing with the Mathlive Testing Playground, it 's working.
<img width="1052" alt="Capture d’écran 2021-02-18 à 2 46 12 PM" src="https://user-images.githubusercontent.com/32236491/108353106-cc660c00-71f8-11eb-9ed6-cc58278a5c3c.png">

**Comment by arnog** [comment]
Yes, this was fixed with 1310983
