### ISSUE TITLE
Native keyboard pushes virtual keyboard away on iPadOS >= 14.3

### ISSUE THREAD

**Issue by roed** [arnog/mathlive#818]
## Description

On an ipad with iOS 14.3, sometimes the native keyboard overrides the virtual keyboard.

## Steps to Reproduce

1. Visit http://mathlive.io/examples/basic/index.esm.html
2. Tap on the virtual keyboard button
3. Tap on the x^2 button

### Actual Behavior

See that the virtual keyboard is gone and the native keyboard is opened.

### Expected Behavior

The native keyboard stays hidden and the virtual keyboard is still visible.

### Environment

**Operating System**
iOS 14.3 and later (also reproducable in the simulator)

**Browser**
Safari

**Comment by arnog** [comment]
I can't seem to be able to reproduce this. There must be some extra steps needed. Let me know if you can find something more consistently reproducible.

**Comment by oatymart** [comment]
I'm able to reproduce this one. I'm running Mathlive 0.59.0, my Mathfield is using `virtualKeyboardMode: "onfocus"`.

Browserstack results from my QA person
- iPad Air 2 with Safari 14.3, the device keyboard opens over Mathlive's
- iPad Pro 12.9 2020 with Safari 13.4 and 14, the device keyboard opens over Mathlive's
- iPad Mini with Safari 13.4, not reproduced

Real device
- iPad 4th Gen with Safari 14.3, the device keyboard opens over Mathlive's

Note: the iPad keyboard can then be minimised by the user, revealing the ML keyboard, but only if the user discovers this.

If you have any ideas, it would be appreciated. I'm not sure how it's implemented and whether it's a question of input attributes, timing, etc.

**Comment by arnog** [comment]
OK, I've figured out what's going on.

With iPad OS 14 and later, Apple has changed the information returned by WebKit. It pretends to be a Mac. That interferes with the handling of the virtual keyboard.

This happens only on iPad OS (not on iOS), and when "Desktop Mode" is turned on (which I think it is by default).
