### ISSUE TITLE
On MathLive reference page, "details" options don't display

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#82]
## Prerequisites

* [ ] Did you check the [issue tracker](https://github.com/arnog/mathlive/issues) to see if this issue has already been reported?

For more information, see the `CONTRIBUTING` guide.

## Description
If you go to the [mathlive reference page](http://mathlive.io/0.24f/reference.html) and click on one of the links under "details", nothing happens. For example, clicking on ["top 60"](http://mathlive.io/0.24f/reference.html?frequency=4000), results in nothing (see screen shot below):
![image](https://user-images.githubusercontent.com/1545836/41483593-822a13ac-708e-11e8-9921-1416c922167e.png)

The compact format links work fine.

**Comment by arnog** [comment]
I have a fix for this. I just need to updated mathlive.io with it.

**Comment by arnog** [comment]
Updated now.
