### ISSUE TITLE
Environments are incorrectly described on reference page

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#83]
## Description
This is a minor quibble.  The references pages (e.g, [top 40 compact](http://mathlive.io/0.24f/reference.html?format=compact&frequency=4000)) lists the environments as shown below:
![image](https://user-images.githubusercontent.com/1545836/41483743-38660f9a-708f-11e8-9354-0898f3eb49ce.png)
(and so on)

The environments are really `\begin{name}....\end{name}`. Although I like the idea that one could write `\matrix{ 1 & 2 \\ 3 & 4}`, that's not TeX and not what mathlive accepts.

The page should be more explicit/correct about evironments.

**Comment by arnog** [comment]
Fixed.
