### ISSUE TITLE
<math-field> component and custom virtual keyboard

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#833]
Is it possible to use a custom virtual keyboard with a <math-field> component? I don't see any attribute allowing this in the docs.

**Comment by arnog** [comment]
Yes, you can customize the virtual keyboard using the `customVirtualKeyboardLayers`, `customVirtualKeyboards`, `virtualKeyboards` properties. You can change those properties using the `setOptions()` method on the mathfield.

For more info see http://cortexjs.io/mathlive/guides/virtual-keyboards/

**Comment by Zahara-Nour** [comment]
I managed to create a custom virtual keyboard
<img width="416" alt="Capture d’écran 2021-02-26 à 6 57 30 PM" src="https://user-images.githubusercontent.com/32236491/109323459-89dda880-7864-11eb-8c7b-414fde38b57d.png">

I'm facing two issues

1. I created a key to display a fraction but the key content isn't formated correctly (in the image , it's the key with 'xy')
```
{
            class: 'keycap',
            latex:'\\frac{x}{y}'
          },
```

2. The key to delete backward throw an error (whereas the keys to move left and right work)
```
{
    class: 'action font-glyph bottom right',
     command: ['performWithFeedback', 'deleteBackward'],
     label: '&#x232b;',
}
``` 
error thrown
```
mathlive.min.js:2 Uncaught Error: Unknown command "deleteBackward"
    at mathlive.min.js:2
    at vr.executeCommand (mathlive.min.js:2)
    at mathlive.min.js:2
    at Object.performWithFeedback [as fn] (mathlive.min.js:2)
    at mathlive.min.js:2
    at vr.executeCommand (mathlive.min.js:2)
    at HTMLLIElement.<anonymous> (mathlive.min.js:2)
```

**Comment by arnog** [comment]
Hmmm... I don't see anything obvious regarding what might be wrong. The example in `examples/virtual_keyboard/index.html` in fact uses '\frac{x}{y}` and it does display correctly.

And I've tried a key with the `deleteBackward` command and it works fine for me.

You wouldn't have a place where I could have a look at your code?

**Comment by Zahara-Nour** [comment]
Tried to use dirty mathlive version, but now my custom virtual doesn't appear anymore, only the original keyboard is displayed.

**Comment by Zahara-Nour** [comment]
I made a codesandbox so you can see the bug reproduced. In this sandbox, I created a simple math-field element with a custom keyboard. The same problems appear :
 - fraction key doesn't display correctly
 - exception is thrown  with the delete backward key

[The sandbox](https://codesandbox.io/s/mathlive-custom-keaboard-ru9qo?file=/index.html)


to see the console errors (embedded preview doesn't work correctly to display them) use this link with the browser developpment tools

[preview](https://ru9qo.csb.app/)

**Comment by Zahara-Nour** [comment]
Found it !

**Comment by Zahara-Nour** [comment]
To delete backward I used the command deleteBackward but it seems to be deletePreviousChar. I can't even find any reference to deleteBackward in your code (don't understand why I use it, my bad !)

**Comment by arnog** [comment]
OK, that solves some of the problem. To be honest, it may have been `deleteBackward` in a previous version.

**Comment by arnog** [comment]
Actually... the command does seem to be `deleteBackward` (in main). Maybe it **was** `deletePreviousChar` in a previous version...

**Comment by Zahara-Nour** [comment]
Ok I understand now. I use the latest tagged version (v0.59) in production which uses deletePreviousChar. In dirty, this is deleteBackward and I took my inspiration from it.  USAGE_GUIDE is not up-to-date because it still references deletePreviousChar.

I will use dirty version now, but as I said, custom keyboard doesn't display anymore. I will investigate.

**Comment by Zahara-Nour** [comment]
I found a solution for the custom virtual keyboard not displaying.  setOptions didn't update virtualKeyboard field of the Mathfield with the new options.
I will submit a PR.

**Comment by Zahara-Nour** [comment]
The good news is that fractions seem to display correctly now with the dirty build.

**Comment by arnog** [comment]
Great. Thanks for the PR.

**Comment by coprocoder** [comment]
Type checking for customVirtualKeyboardLayers still doesn't work.
There is a way out with @ts-nocheck
Without the deleteBackward button, all typescript checks pass perfectly.

**Comment by arnog** [comment]
Fixed in main branch
