### ISSUE TITLE
Keyboard not responding

### ISSUE THREAD

**Issue by faliagas** [arnog/mathlive#834]
## Description

I try to write a math formula (e.g. \frac{y}{x}) but when I press "\" it does not display.

## Steps to Reproduce

1. Press Math
2. Press \
3. Nothing happens

### Expected Behavior

Formula expected to appear

### Environment

**Operating System**
Linux Ubuntu 20.04

**Browser** [Safari, Chrome, IE, Firefox, etc...]
Chrome latest version

**Comment by arnog** [comment]
1/ Which version of Mathlive are you using?
2/ What is the layout of your physical keyboard?

**Comment by faliagas** [comment]
1) mathlive.js v0.59.0-93-g1b6a4ee-dirty
2) Keyboard layout: US english (Dell laptop)

**Comment by arnog** [comment]
Fixed in mathlive@0.60.0
