### ISSUE TITLE
Typing opening parenthesis in a pair of vertical bars doesn't generate closing parenthesis

### ISSUE THREAD

**Issue by jambonmcyeah** [arnog/mathlive#843]
## Description
Typing opening parenthesis  in a pair of vertical bars doesn't generate closing parenthesis

https://user-images.githubusercontent.com/21069675/109434047-52483b00-79e1-11eb-84a4-5fdf8b9525dd.mp4

## Steps to Reproduce

1. Type `|(`

### Actual Behavior
Closing fence `|` is generated

### Expected Behavior

Closing fence  `)|` is generated

### Environment

**Operating System**
Windows, Linux

**Browser**
Chrome, Firefox

**Comment by arnog** [comment]
Fixed with 5a06ffd33442f70248f2473cb4cf58bbce2bef3d
