### ISSUE TITLE
When I link in html with local script file and css file, the symbols are broken.

### ISSUE THREAD

**Issue by reach1dev** [arnog/mathlive#844]
## Description

When I link in HTML with the makelive.min.js file locally, the symbols are broken.

![image](https://user-images.githubusercontent.com/78322772/109480938-369a6e80-7a8d-11eb-821a-d284a2849367.png)

## Steps to Reproduce

1. create test.html with the following code.
```
<!DOCTYPE html>
<html lang="en-US">
    <body>
        <math-field>f(x)=</math-field>
        <script src="mathlive.min.js"></script>
    </body>
</html>
```
2. copy mathlive.min.js in the same folder and fonts folder as well.
3. Open test.html in browser.

### Actual Behavior

The math special symbols are broken like the image I upload.

### Expected Behavior

I think it should work like we link the js file on the server.

### Environment

Windows, Chrome

**Comment by arnog** [comment]
I can't reproduce this.

Make sure the `mathlive.min.js` file and the `fonts` directory are in the same folder as the `.html` file.

There could be another thing. Some browsers, sometimes, decide that the encoding of a page is not UTF-8, which can cause some problems displaying the fonts. Try to add:

```html
<head>
    <meta charset="utf-8">
</head>
```

before the `<body>` tag.

**Comment by reach1dev** [comment]
@arnog Thanks, meta tag with "utf-8" solved this issue.
