### ISSUE TITLE
Virtual keyboard get closed if any html element value get changed

### ISSUE THREAD

**Issue by moh1434** [arnog/mathlive#845]
## Description
When i set Virtual keyboard mode to **'onfoucs'**, the keyboard will close if any html element value get changed.

## Steps to Reproduce

1-In html:
`      <mathlive-mathfield
:options="{
smartFence: false,
 virtualKeyboardMode: 'onfocus',
 }"
        v-model="formula"
      ></mathlive-mathfield>`
     ` <h1>{{ counter }}</h1>`
2-vueJs data:
`      formula: "",
      counter: 0,`
3-vueJs methods:
`    increase_every_4s() {
      this.counter++;
      setTimeout(this.increace_every_4s, 4000);
    },`
and in created hook:
`  created() {
    this.increase_every_4s();
  },`

### Actual Behavior
Now the counter will increase every 4 seconds and every time the counter value get increased, the virtual keyboard will close even if i'm using it

### Expected Behavior

I expected the virtual keyboard will not close unless i click on other html element

### Environment

**Operating System**
Linux mint

**Browser** [Firefox, Chrome]

**Comment by leerobert** [comment]
I can also confirm this behavior. Virtual keyboard doesn't even open for me on both Windows / Mac on browsers (Firefox, Chrome, Safari). In fact when I change `virtualKeyboardMode: 'manual'` I do not even see the button with the vue component. 

To test this locally @arnog , you can use https://github.com/leerobert/nuxt-mathlive as a template. I'm going to try to source the issue as my older component using mathlive 0.53.0 and nuxt 2.12 was working fine with the keyboard.

**Comment by leerobert** [comment]
Actually scratch that. Even downgrading to `0.55` seems to have issues if you dig deeply enough. 

Here is a codepen that I'm currently using to try to debug issues:

https://codesandbox.io/s/compassionate-silence-n5wb1

**Comment by leerobert** [comment]
Ok I'm starting to see whats happening here I think... the `blur` event is being triggered after a single character change in the mathfield. This of course causes `onfocus` and `auto` mode to close the keyboard. Now i need to figure out why the `blur` event seems to get triggered.

**Comment by arnog** [comment]
This is working now with mathlive@0.62.0.

Note that the `:config` attribute is now `:options`.
