### ISSUE TITLE
`ignoreSpacebarInMathMode` option not working

### ISSUE THREAD

**Issue by ShaMan123** [arnog/mathlive#859]
## Description

`ignoreSpacebarInMathMode` option doesn't seem to work in `math` mode.

## Steps to Reproduce

1. Render Mathlive in `math` mode with options: `{ ignoreSpacebarInMathMode: false }`
2. Hit the spacebar

### Actual Behavior

Nothing happens

### Expected Behavior

Should render a space, switching to `text` mode is my current workaround.

### Environment

**Operating System** Windows10

**Browser** Chrome

**Version** 0.59

**Comment by evyatarbh** [comment]
It's not just that. I found a [very extensive post](https://tex.stackexchange.com/questions/74353/what-commands-are-there-for-horizontal-spacing) about adding spaces in LaTeX. Some of them work in MathLive (when injected using the insert method), but parts of the math expressions are no longer displayed properly when those spaces are included. In my case, it's mainly fractions that should display vertically like (1)/(2), which are being displayed as text like here.

**Comment by arnog** [comment]
@evyatarbh: That sounds like a different problem. The original report is specifically about the **input** option to ignore the spacebar when in math mode. This is the default behavior in TeX, where spaces (U+0020 unicode characters) are ignored when doing the layout of a formula. The `ignoreSpacebarInMathMode` motion, when set to false, should insert a text mode space when the spacebar is pressed. It apparently doesn't work right now, but should.

What you are describing appears to be some Latex command that may not render at all or that may not render correctly. Mathlive does support some of those commands such as `\quad`, `\;`, `\hspace`, etc... Actually, I think all the commands mentioned in this post should be supported. If you are experiencing some difficulties, it would be helpful if you could file a separate issue, indicating in more details what you are inputting, what output you expect to get, and what you actually get.

**Comment by arnog** [comment]
The `ignoreSpacebarInMathMode` option was inadvertently not hooked up.

However, this option is problematic as an element attribute (it defaults to true, but element attributes default to false). 

The option has been replaced with `mathModeSpace` which is more flexible (you can specify which space to use) and doesn't have the issue of the default boolean value.

(The issued discussed by @evyatarbh was resolved in #886)

**Comment by ShaMan123** [comment]
Fantastic!
Thanks

בתאריך יום ו׳, 9 באפר׳ 2021, 13:19, מאת Arno Gourdol ‏<
***@***.***>:
