### ISSUE TITLE
For math to speech, ids are not being set correctly in <mark>

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#86]
## Description
For this expression: `\frac {b}{9}-34\leq  -36`, the following SSML was generated for built-in speech:
```
<?xml version="1.0"?>
<speak xmlns="http://www.w3.org/2001/10/synthesis" version="1.1" xml:lang="en-US">
<auto-breaths>
    <p>
        <s>
            <mark name="adfhy5"/>
            <mark name="adfhy3"/>
            <say-as interpret-as="character">b</say-as> over
            <mark name="adfhy4"/>9<mark name="adfhy6"/>
            <break time="150ms"/>  minus <break time="150ms"/>
            <mark name="adfhy7"/>3
            <mark name="adfhy7"/>4
            <mark name="adfhy8"/>  is less than or equal to
            <mark name="adfhy9"/>  minus
            <mark name="adfhya"/>3
            <mark name="adfhya"/>6</s>
        </p>
    </auto-breaths>
</speak>
```

And this is the element tree as shown by the debugger:
![image](https://user-images.githubusercontent.com/1545836/41568164-f7b4183e-7318-11e8-96fc-672e508e8751.png)

Notice that the counting/marks/ids fall apart when multi-digit numbers are involved. For example, both '3' and '4' are marked with `name="adfhy7"` which is probably ok, but the `≤` is marked with `name="adfhy8"` which is _not_ correct; it should be 'adfhy9'.

Sync highlighting is currently not working properly, but once it does, this will be a problem.

**Comment by arnog** [comment]
There's two numbering algorithms for the atom IDs: a regular one, used when editing an expression, and one used when sync highlighting the expression (there's a flag that can be passed to render( ) to select which algorithm to use). When the sync highlighting variant is used, the atom-IDs are allocated differently, for example the consecutive digits of a number will all be allocated the same ID so they can all be highlighted at the same time.
I think the render tree and the atom IDs you have reflect the display mode, while the atom-IDs used in the SSML reflect the sync highlight mode. As such, they are going to be out of sync (slightly).
That said, there is something wrong in the SSML: the mark should only be generated for the first digit of a multi-digit positive number, or for the negative sign for a multi-digit negative number. But that sounds like issue #85.

**Comment by arnog** [comment]
I think this issue is now fixed.
