### ISSUE TITLE
Mathlive outputs missing space after \\lbracket

### ISSUE THREAD

**Issue by iboyperson** [arnog/mathlive#860]
## Description

**Precursor**: I wasn't exactly sure what to title this issue so if I can name it better please tell me.

The issue is that mathlive does not always include a space after `\lbrace` (it is possible there are others but I found this with `\lbrace`). Below I have included a Codesandbox to demonstrate this. It should be noted that the output format here is `latex-extended`.

https://codesandbox.io/s/suspicious-platform-v8roo?file=/src/App.js

Outside the sandbox here is the file in my actual project that I am seeing this in: https://github.com/iboyperson/discrete-calculator/blob/sets/src/pages/Sets.tsx

## Steps to Reproduce
1. Enter provided  Codesandbox
2. Select the mathfield
3. Press Enter
4. You should now see the value has become `A=\lbracea,a,a\rbrace` instead of `A=\lbrace a,a,a\rbrace`

Alternatively, manually inputting `A={a,a,a}` (via keyboard input) and pressing Enter produces output with the expected space

### Actual Behavior

Mathlive outputs `A=\lbracea,a,a\rbrace` (space missing after `\lbrace`)

### Expected Behavior

Mathlive outputs `A=\lbrace a,a,a\rbrace` (with space present after `\lbrace`)

[Is this a regression: did it use to work in a previous version?]
I am unsure whether this is a regression or not. I only recently began working with this library.

### Environment

**Operating System**
Linux (Arch Linux): Version is rolling release.

**Browser** [Safari, Chrome, IE, Firefox, etc...]
Firefox

**Comment by arnog** [comment]
I believe this is fixed in master.

**Comment by iboyperson** [comment]
Cool! Thanks for the great project! I eagerly await the next release.

**Comment by arnog** [comment]
Fixed in mathlive@0.60.0
