### ISSUE TITLE
IOS11 whether there will be a script error, whether there are compatibility issues

### ISSUE THREAD

**Issue by xiaozo** [arnog/mathlive#863]
## Description

[Description of the bug or feature.]

IOS11 whether there will be a script error, whether there are compatibility issues

**Comment by arnog** [comment]
I'm sorry, I don't understand what you mean.

If you are asking if iOS 11 is supported, Mathlive supports the last two versions of evergreen browsers. 

So, for Safari on iOS that would be Safari 14 and Safari 13. That said, it is entirely possible that Mathlive works on iOS 11 as well, but I haven't tested it.

**Comment by xiaozo** [comment]
[https://zykj-resource-repository-dev.oss-cn-hangzhou.aliyuncs.com/temp/pre/2021/03/18/125D0FBC-E4F1-4FA9-9CBB-3DA45C60A361.png](url)

**Comment by xiaozo** [comment]
[https://zykj-resource-repository-dev.oss-cn-hangzhou.aliyuncs.com/temp/pre/2021/03/18/125D0FBC-E4F1-4FA9-9CBB-3DA45C60A361.png](url)

**Comment by xiaozo** [comment]
[https://zykj-resource-repository-dev.oss-cn-hangzhou.aliyuncs.com/temp/pre/2021/03/18/125D0FBC-E4F1-4FA9-9CBB-3DA45C60A361.png](url)   I was running my MathLive project on an iOS 11.1 emulator and had the problem shown above. I had the same problem with iOS 11 on the real machine. It should be the compatibility problem of MathLive that caused the page error. I hope you can solve this problem. Thank you!

**Comment by xiaozo** [comment]
[https://zykj-resource-repository-dev.oss-cn-hangzhou.aliyuncs.com/temp/pre/2021/03/18/125D0FBC-E4F1-4FA9-9CBB-3DA45C60A361.png](url)   I was running my MathLive project on an iOS 11.1 emulator and had the problem shown above. I had the same problem with iOS 11 on the real machine. It should be the compatibility problem of MathLive that caused the page error.  Thank you!

**Comment by arnog** [comment]
Unfortunately, this screenshot does not allow me to debug what the problem might be. It looks like Mathlive is not loaded? And as I mentioned earlier iOS 11 is not supported. Have you tried with other versions of iOS? Which ones work? Which ones don't? What error message is displayed in the Javascript console, if any?

If there is a problem specific to iOS 11 and if you create a pull request with a fix for it I'd be happy review it and consider merging it.
