### ISSUE TITLE
convertLatexToMarkup not working as expected for certain latex such as matrix and trigonometry functions

### ISSUE THREAD

**Issue by melvinotieno** [arnog/mathlive#879]
## Description

I am using MathfieldElement to input math equations. In the same page, I am displaying the equations to make sure what is entered is correct using convertLatexToMarkup function but some latex are not converted. Below is an example screenshot

![Screenshot from 2021-03-30 16-20-36](https://user-images.githubusercontent.com/46104684/112996386-cc9ce400-9174-11eb-8689-af7d25409a82.png)

The image above is the correct display in a mathfield element

![Screenshot from 2021-03-30 16-20-59](https://user-images.githubusercontent.com/46104684/112996515-e6d6c200-9174-11eb-8b42-6f8645fcb85d.png)

The above image is for the function convertLatexToMarkup. As you can see, it is not fully converted

**Comment by arnog** [comment]
Thank you for writing up this report. A few question to help track down the problem:
- Which version of Mathlive did you use?
- Do you have some sample code showing what the problem is? In a github repo, or a coding sandbox (https://jsfiddle.net/)?
- The function `convertLatexToMarkup()` should output some HTML markup corresponding to the Latex  provided as an argument. Are you saying that it outputs instead the Latex you input or is the screenshot you included the result of rendering the result of `convertLatexToMarkup()`? And if so, what was the Latex you input?

**Comment by melvinotieno** [comment]
- I am using the latest mathlive, version 0.59.0
- I am working on a client's project but I can try to reproduce the code for you. I am using react
- The screenshot is the result of rendering the result of convertLatexToMarkup(), the latex input is the exact latex gotten from the MathfieldElement

**Comment by arnog** [comment]
`the latex input is the exact latex gotten from the MathfieldElement`: and what is that?

**Comment by melvinotieno** [comment]
math-field input element

**Comment by arnog** [comment]
I mean: what is the value of the Latex string in input to `convertLatexToMarkup()`. I'm trying to figure out if the problem is that you are not getting the correct Latex from the Mathfield element or that `convertLatexToMarkup` is not correctly rendering the Latex.

Also, could you try with the version in the main branch?

**Comment by arnog** [comment]
Uh... Can you check that again.

**Comment by arnog** [comment]
And the output you get from `convertLatexToMarkup()` is `cos\mleft(\frac{\pi}{100}\mright)`?

**Comment by melvinotieno** [comment]
Seems like github is automatically stripping \

**Comment by melvinotieno** [comment]
> And the output you get from `convertLatexToMarkup()` is `cos\mleft(\frac{\pi}{100}\mright)`?

yes exactly

**Comment by arnog** [comment]
OK, I don't see how that's possible. If you input a matrix, `convertLatexToMarkup()` is not going to transform it into a trig function. There must be something else going on with your code, but I can't do much about it without looking at it.

**Comment by melvinotieno** [comment]
For matrix

this is the input in math-field element

![Screenshot from 2021-03-30 18-54-16](https://user-images.githubusercontent.com/46104684/113018636-6b334000-9189-11eb-850a-3a90bafecda2.png)

however, using convertLatexToMarkup() gives

![Screenshot from 2021-03-30 18-54-25](https://user-images.githubusercontent.com/46104684/113018732-83a35a80-9189-11eb-8292-74d7fc159458.png)

**Comment by melvinotieno** [comment]
> OK, I don't see how that's possible. If you input a matrix, `convertLatexToMarkup()` is not going to transform it into a trig function. There must be something else going on with your code, but I can't do much about it without looking at it.

No, what I am trying to mean is the problem appears when using trig and when using matrix

**Comment by arnog** [comment]
OK, got it. So you pass `\begin{matrix}2 & 3 \ 3 & 4 \ 4 & 5\end{matrix} ` to `convertLatexToMarkup()` and you get the output `2 & 4 \\ 3 & 4 \end{matrix}`.

**Comment by melvinotieno** [comment]
> OK, got it. So you pass `\begin{matrix}2 & 3 \ 3 & 4 \ 4 & 5\end{matrix} ` to `convertLatexToMarkup()` and you get the output `2 & 4 \\ 3 & 4 \end{matrix}`.

yes exactly

**Comment by melvinotieno** [comment]
And when I pass `\cos \mleft(\frac{\pi t}{100}\mright)` to convertLatexToMarkup() I get `cos  \mleft(\frac{\pi t}{100}\mright)`

**Comment by melvinotieno** [comment]
Another one that I just noticed is `\muA`, it returns `\muA`, therefore it doesn't get converted

**Comment by melvinotieno** [comment]
I believe I figured it out. Using the math field keyboard sometimes outputs the latex with spaces and some with missing curly braces {} therefore the convertLatexToMarkup won't work once I get the latex from the math-field

**Comment by arnog** [comment]
Could you check with mathlive@0.0.60 and let me know if this still happens?
