### ISSUE TITLE
[Firefox] Uncaught ReferenceError: TouchEvent is not defined

### ISSUE THREAD

**Issue by iboyperson** [arnog/mathlive#896]
## Description

On Firefox clicking into the Mathlive input box throws the following error:
```
Uncaught ReferenceError: TouchEvent is not defined
    handleEvent https://unpkg.com/mathlive/dist/mathlive.min.js:2
    handleEvent https://unpkg.com/mathlive/dist/mathlive.min.js:2
mathlive.min.js:2:552212
```

I have tested this on Chrome and Edge and the same error does not occur.

## Steps to Reproduce

Steps to reproduce can be done at https://cortexjs.io/mathlive/

1. Navigate to https://cortexjs.io/mathlive/
2. Click the Mathlive input box
3. Observe the console

### Actual Behavior

The following error is thrown:
```
Uncaught ReferenceError: TouchEvent is not defined
    handleEvent https://unpkg.com/mathlive/dist/mathlive.min.js:2
    handleEvent https://unpkg.com/mathlive/dist/mathlive.min.js:2
mathlive.min.js:2:552212
```

### Expected Behavior

The error is not thrown (I'm sorry if this sounds snarky. I wasn't exactly sure what to put here)

### Environment

**Operating System**
Windows 10 Version 10.0.19042 Build 19042

**Browser** [Safari, Chrome, IE, Firefox, etc...]
Firefox 87.0

**Comment by arnog** [comment]
Thanks for reporting this! Fixed now.
