### ISSUE TITLE
Keyboard sounds - option to disable?

### ISSUE THREAD

**Issue by oatymart** [arnog/mathlive#898]
I noticed that in the latest version 0.60.0, the Mathfield tries to load some wav files:
```
GET http://localhost:6006/sounds/plonk.wav 404 (Not Found)
GET http://localhost:6006/sounds/keypress-standard.wav 404 (Not Found)
GET http://localhost:6006/sounds/keypress-delete.wav 404 (Not Found)
GET http://localhost:6006/sounds/keypress-return.wav 404 (Not Found)
GET http://localhost:6006/sounds/keypress-spacebar.wav net::ERR_ABORTED 404 (Not Found)
```
(I didn't copy any files from `dist/sounds` to my served folder yet, which is why I got 404s)

My question is how I would go about configuring it if I don't wish to play any sounds, nor have console errors.

By inspecting the code it seems that I can specify some MathfieldOptions (I tried `plonkSound: null`) but that doesn't prevent errors. Would you recommend that I host a `empty.wav` file and assign that to each sound key, or would creating a hidden `HTMLAudioElement` be a better solution? Will there be an option to disable sounds in a future version?

Thanks for the latest release, by the way. The fixes are much appreciated.

**Comment by arnog** [comment]
Ooops.
Assigned a `new Audio()` object should silence them. However, that's a bit clunky.
I'll add an option to silence them when set to `null`.
