### ISSUE TITLE
Feature: Add divide symbol

### ISSUE THREAD

**Issue by yaki4** [arnog/mathlive#899]
Right now if i click on division symbol
<img width="55" alt="Capture d’écran, le 2021-04-13 à 14 22 29" src="https://user-images.githubusercontent.com/1856630/114601706-d12cc680-9c63-11eb-874b-7320e5134e40.png">

 a \frac is generated in Latex format which result to show the operation like this
<img width="77" alt="Capture d’écran, le 2021-04-13 à 14 22 22" src="https://user-images.githubusercontent.com/1856630/114601683-cb36e580-9c63-11eb-8321-1ccb7e18579d.png">

But in an educative context, we need to differentiate fraction and division. 
So instead of generating a \frac by default it should write a \div like so
6 \div 3 = 2 
<img width="129" alt="Capture d’écran, le 2021-04-13 à 14 27 02" src="https://user-images.githubusercontent.com/1856630/114602196-51ebc280-9c64-11eb-8966-c1a1a888f60a.png">

Also if right know i use this latex notation in the mathlive website i can see that the symbol is here but the package doesn't detect that i use a division.
<img width="823" alt="Capture d’écran, le 2021-04-13 à 14 31 22" src="https://user-images.githubusercontent.com/1856630/114602859-169dc380-9c65-11eb-8689-0eb1f17e11f3.png">

**Comment by arnog** [comment]
If you press and hold on the "division symbol" key, some alternate options will be displayed, including one for `\div`.
You can also create your own custom virtual keyboards if you'd like: https://cortexjs.io/mathlive/guides/virtual-keyboards/

**Comment by yaki4** [comment]
Always read the documentation. I should know that. 
Thank you for your quick and kind response.

**Comment by arnog** [comment]
No worries. Thanks for filing this issue!
