### ISSUE TITLE
Some ASCII math sequences can not be entered

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#90]
## Description
I'm not sure if this is a bug or by design. The following char sequences cannot be typed because there is a shorter sequence that takes precedence (ASCIIMath is converted as soon as it is recognized):

AsciiMath | Shorter character seq | characters shown
------------ | -------------|----------
delta          |  del |  \partial
epsilon | epsi  | e \psi
Epsilon | Epsi | E \psi
varepsilon | varepsi | vare \psi
upsilon | upsi | u\psi 

These sequences are in the code, so potentially they should be typeable.

If the `psi` shortcut is dropped, four sequences become typeable. I'm not saying to do this, just pointing it out.

**Comment by arnog** [comment]
Fixed with f39c2abf0a0ecf6b154567f98abfcc3a5f0db450
