### ISSUE TITLE
\textcolor not properly typeset in static mode

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#907]
## Description

When using static typeset with $$..$$ syntax, color is not always applied :

`$$\textcolor{green}{\text{négatif}}$$` works whereas `$$\text{Le résultat de }37+(-56)\text{ est } \textcolor{green}{\text{négatif}}$$` no

I gonna use the mathlive-bug-issue-templates repo to reproduce this issue.

### Environment

**MathLive version** master

**Operating System** macOS Big Sur

**Browser** Chrome

**Comment by Zahara-Nour** [comment]
did the repo :

```
git clone git@github.com:Zahara-Nour/mathlive-907-issue.git
cd mathlive-907-issue
yarn
yarn dev
```

**Comment by arnog** [comment]
Thank you for the repo, it was very useful as the bug actually only happens when using `renderMathInDocument()`.
