### ISSUE TITLE
Typing '~' results in no display

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#91]
## Description
If I type `~`, it is not displayed although some character is seems present as a backspace is needed to remove it.

Two related(?) problems:
-  `~~` is supposed to be the same as `\approx`, but that doesn't work, perhaps because `~` is mapped to something else.
- `~=` is supposed to be the same as `\cong`

**Comment by arnog** [comment]
Ah, yes. In TeX, ~ is a non-breaking space. I'll change the keyboard mapping to map the '~' key to a new '\~' command (an operator), and change the shortcut handling routine to detect shortcuts made of commands to deal with '\~' + '='.
