### ISSUE TITLE
Shortcuts that start with '(' don't work

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#92]
## Description
The code contains the following shortcuts:

Shortcut | TeX equiv
----------|-----------
(: | \langle
(.) | \odot
(+) | \oplus
(*) | \otimes
(-) | \ominus

None of these expand to anything. E.g., `(:` displays as
![image](https://user-images.githubusercontent.com/1545836/41878732-28efb8dc-788b-11e8-8f96-27e039acdd91.png)
Perhaps the auto paren matching is messing this up?

 `:)` does turn into `\rangle`, so with `(:` broken, there's a weird asymmetry now.

**Comment by NSoiffer** [comment]
I think the same issue afflicts `||` which should turn into `\Vert`. It looks like mathlive is trying to "close" the first `|`:
![image](https://user-images.githubusercontent.com/1545836/41881156-d7752544-7896-11e8-9580-6dc3ae80e180.png)

**Comment by NSoiffer** [comment]
I looked into this a little. The problem appears to be that `(` starts a "body" on "path". This means that `(`  is _not_ part of the string match when looking for a shortcut for any character that follows `(` because `(`  is not in the same part of "path" as the character that follows it . See editor-mathfields.js starting around line 982. 

This also the problem with `|` and all other opening fences.

**Comment by arnog** [comment]
Fixed with f39c2abf0a0ecf6b154567f98abfcc3a5f0db450
