### ISSUE TITLE
Backets not coloured

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#925]
## Description

Brackets are not colored when using \textcolor

exemple with `\textcolor{green}{\left(3+4\right)}`

<img width="799" alt="Capture d’écran 2021-05-07 à 07 09 12" src="https://user-images.githubusercontent.com/32236491/117396729-41e19e80-af03-11eb-955f-e6bca6312faf.png">

### Environment
Master
MacOS
Chrome

**Comment by arnog** [comment]
I have a pending fix for this.

**Comment by arnog** [comment]
Fixed in mathlive 0.64
