### ISSUE TITLE
lack an appropriate loader to handle this file type when use mathlive in vue-cli2

### ISSUE THREAD

**Issue by aoxiangsky** [arnog/mathlive#938]
## Description

lack an appropriate loader to handle this file type when use mathlive in vue-cli2

## Steps to Reproduce

import { renderMathInElement } from 'mathlive' in vue-cli2

Below is my webapck configuration and page error message

[![gwk8c8.png](https://z3.ax1x.com/2021/05/12/gwk8c8.png)](https://imgtu.com/i/gwk8c8)
[![gwk31f.png](https://z3.ax1x.com/2021/05/12/gwk31f.png)](https://imgtu.com/i/gwk31f)

**Comment by aoxiangsky** [comment]
node version: v12.16.3
webpack version: v3.6

**Comment by arnog** [comment]
It's the `.mjs` file extension which is confusing WebPack. You can either modify your WebPack configuration to map the `.mjs` extension to Javascript, or use the `mathlive.min.js` file instead of `mathlive.min.mjs`.

**Comment by arnog** [comment]
It's the `.mjs` file extension which is confusing WebPack. You can either modify your WebPack configuration to map the `.mjs` extension to Javascript, or use the `mathlive.min.js` file instead of `mathlive.min.mjs`.

**Comment by aoxiangsky** [comment]
` import { renderMathInElement } from 'mathlive/dist/mathlive.min.js' `

I tried it but it didn't work

[![gwaYWt.md.png](https://z3.ax1x.com/2021/05/12/gwaYWt.md.png)](https://imgtu.com/i/gwaYWt)

**Comment by aoxiangsky** [comment]
> It's the `.mjs` file extension which is confusing WebPack. You can either modify your WebPack configuration to map the `.mjs` extension to Javascript, or use the `mathlive.min.js` file instead of `mathlive.min.mjs`.

` import { renderMathInElement } from 'mathlive/dist/mathlive.min.js' `

I tried it but it didn't work

[![gwaYWt.md.png](https://z3.ax1x.com/2021/05/12/gwaYWt.md.png)](https://imgtu.com/i/gwaYWt)

**Comment by arnog** [comment]
Unfortunately I don’t have enough information to debug this. There is something in your WebPack configuration that prevents it from parsing the library file. It could be something to do with the version of JS you target, and you may need to use Babel to transpile the library.

Alternatively, I would suggest using the CDN version of mathlive:

```js
  import { renderMathInElement } from "https://unpkg.com/mathlive/dist/mathlive.min.js"
```

**Comment by arnog** [comment]
Two weeks since last activity. Closing.
