### ISSUE TITLE
[FEATURE] Add access to stretchable over/under symbols to the virtual keyboard

### ISSUE THREAD

**Issue by SushantGautam** [arnog/mathlive#939]
The bar is only for a single word in LATEX. What if we replace it with Overline? We could ever use it for multiple words.
![image](https://user-images.githubusercontent.com/16721983/118001187-35779e80-b366-11eb-9dec-f06d30941f3c.png)

**Comment by arnog** [comment]
In LaTeX the `\bar` command is indeed considered a non-stretchable accent, while the `\overline` command is an extensible symbol.  See the **Extensible Symbols** section in the [Supported Commands](https://cortexjs.io/mathlive/reference/commands/).

MathLive tries to follow how LaTeX behaves (try it in https://www.codecogs.com/latex/eqneditor.php for example), so I think this is correct behavior.

Also note that if you'd like to put a bar over multiple words you can use the`\text` command: `\overline{\text{This Is A Formula}}`

**Comment by SushantGautam** [comment]
Thanks for replying, I was trying to use your playground at https://mathlive.io/. I couldn't /overline over a text. There was an option on the keyboard but that was a /bar.  So what if we use overline instead of a bar there on the virtual keyboard?
I don't think a user would need a non-stretchable style of bar, but \overline would be useful to be used with multiple use-cases.
![image](https://user-images.githubusercontent.com/16721983/118076699-71484d80-b3d2-11eb-9f48-ec0b66b62577.png)

**Comment by arnog** [comment]
Yes, that's a good idea. Currently all these options in the virtual keyboard are for accents, but it would be useful to have access to `\overline` and other stretchable symbols. Updating the issue title to reflect this as a feature request.

**Comment by arnog** [comment]
I've replaced `\bar` with `\overline` in the virtual keyboard. Also added `\underline`, `\xleftarrow` and `\xrightarrow`. 
`\bar` is still accessible as the alt-panel for `\vec`.

**Comment by SushantGautam** [comment]
Great! Thanks for considering and so quick!
Hope that would be helpful to all the users.
What about the release cycles? Do you have any schedules?
When can I expect it to be reflected live on the Playground?

**Comment by arnog** [comment]
It is live in mathlive 0.65 which I've just pushed to npm.

You can try it out at https://cortexjs.io/mathlive/

**Comment by SushantGautam** [comment]
Great! It's live there.
How can I encode in the custom keyboard?
For eg:

```
{
                    class: "tex small",
                    label: "",
                    insert:
                 `
$$\\begin{matrix}
{#0} \\
{#0} 
\\end{matrix}

$$`
},
```
But that doesn't seem to work because of "\\" in row seperator. 
Do you have any idea how can I do that?
I was trying to make a key for siumulatenous equation like:
`f(n) = \begin{cases} n/2, & \mbox{if } n\mbox{ is even} \\ 3n+1, & \mbox{if } n\mbox{ is odd} \end{cases}
`
But this is also not possible since I couldn't find a way to encode \\ in your insert field. 
Is there any way to put such template to the virtual keyboard field?

**Comment by SushantGautam** [comment]
> Great! It's live there.
> How can I encode newline in the custom keyboard?
> For eg:
> 
> ```
> {
>                     class: "tex small",
>                     label: "",
>                     insert:
>                  `
> $$\\begin{matrix}
> {#0} \\
> {#0} 
> \\end{matrix}
> 
> $$`
> },
> ```
> 
> But that doesn't seem to work because of `\\` in row seperator.
> Do you have any idea how can I do that?
> I was trying to make a key for siumulatenous equation like:
> `f(n) = \begin{cases} n/2, & \mbox{if } n\mbox{ is even} \\ 3n+1, & \mbox{if } n\mbox{ is odd} \end{cases} `
> But this is also not possible since I couldn't find a way to encode `\\` in your insert field.
> Is there any way to put such template to the virtual keyboard field?

![image](https://user-images.githubusercontent.com/16721983/118270619-07b66500-b4e0-11eb-8309-6dd3a1f511f8.png)
I managed to do it with four slashes `\\\\` and it worked.

**Comment by arnog** [comment]
Yes, you have to use `\\\\` since LaTeX except two slashes, but to get a single slash you need to escape it in Javascript, so one slash is `\\` and two slashes is `\\\\`. You can also use `\cr` as a synonym for `\\` (so `\\cr` in Javascript).

**Comment by chenjiayu119** [comment]
> 在 LaTeX 中，该`\bar`命令确实被视为不可拉伸的重音符号，而该`\overline`命令是可扩展的符号。请参阅[支持的命令](https://cortexjs.io/mathlive/reference/commands/)中的**可扩展符号**部分。[](https://cortexjs.io/mathlive/reference/commands/)
> 
> MathLive 尝试遵循 LaTeX 的行为方式（例如，在https://www.codecogs.com/latex/eqneditor.php中尝试），所以我认为这是正确的行为。
> 
> 另请注意，如果您想在多个单词上加一条横线，可以使用以下`\text`命令：`\overline{\text{This Is A Formula}}`

import { convertLatexToMathMl } from "mathlive";
convertLatexToMathMl('\overline{}')

There will be issues with converting LaTeX to MathML for all overflow related topics
