### ISSUE TITLE
No way to enter '/'

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#94]
## Description
If `/` is typed, a 2D fraction is immediately created. Looking through the source code tables and the mathlive documentation, I couldn't find a way to enter `/`. There are occasions when you want to use the linear form of division, so this seems like an oversight.

Note: the ASCIIMath name for `/` is `//`, that can't be used because typing the first `/` immediately creates a 2D fraction.

**Comment by dangcuuson** [comment]
I think you can combine `onKeystroke` with `typedText` to achieve that:

```javascript

mathlive.makeMathFied('mf', {
  onKeystroke: (key, mf) => {
    if (key === 'Slash') {
       mf.typedText('/'); // simulate typing '/'
       return false;
    }
    return true;
  }
})

```

**Comment by arnog** [comment]
Added a built-in shortcut that will produce "\/": alt-shift-"/" (or option-shift-"/").
