### ISSUE TITLE
undefined in tooltip of custom virtual keyboard layer

### ISSUE THREAD

**Issue by SushantGautam** [arnog/mathlive#943]
![image](https://user-images.githubusercontent.com/16721983/118302222-ab653c80-b503-11eb-87af-2eb9518b5a6a.png)
Used:
https://unpkg.com/mathlive@0.65.0/dist/mathlive.min.js

**Comment by arnog** [comment]
Ah, thanks! The tooltip was expected a localized string, and displayed "undefined" if one was not available. It is fixed now so that it displayed the string if a localized one is not available.
