### ISSUE TITLE
Extra space in latex output

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#945]
After an input of `123\,456` in a mathfield element, I get back `123\, 456` in the latex output, i.e. with an extra space after `\,`

<img width="718" alt="Capture d’écran 2021-05-15 à 18 32 58" src="https://user-images.githubusercontent.com/32236491/118369661-e40d2080-b5ac-11eb-8ced-77f6f0f3afd6.png">

**MathLive version**
Master

**Operating System** 
macOS

**Browser**  Chrome

**Comment by arnog** [comment]
Thank for the report! Fixed in the main branch.
