### ISSUE TITLE
Entering a long expression with the virutal keyboard and the focus is hidden

### ISSUE THREAD

**Issue by krampstudio** [arnog/mathlive#947]
## Description

If you enter an expression using the virtual keyboard only (without the focus on the field), and that expression is longer than the input field, the end of the expression is hidden and the newly added characters are hidden too.

![image](https://user-images.githubusercontent.com/468620/118957377-c3ecb100-b960-11eb-889b-30ac4a95c609.png)

## Steps to Reproduce

[Provide steps that are specific and repeatable, if possible]

1. Any mathlive with virtual keyboard with a reduced input field width
2. Open the virtual keyboard 
3. Remove the focus from the field if it was focussed 
4. Enter a long expression (can be just numbers)

### Actual Behavior

The last entered characters are hidden

### Expected Behavior
The focus follows the entered characters so we can see what we're entering.

### Environment

**MathLive version**: latest

**Operating System**: all

**Browser** : all

**Comment by arnog** [comment]
I cannot reproduce this with the current version of mathlive. I noticed the screenshot is from mathlive.io, which is using a much older version of mathlive. Can you confirm the version of mathlive you are seeing this with?

**Comment by arnog** [comment]
In the current version of Mathlive removing the focus on the field will also close the virtual keyboard, so the steps in the report  cannot be followed exactly.

**Comment by krampstudio** [comment]
Thanks for your reply. I've the issue with version `0.60.0`.
I'll try with the last version and close the issue if it doesn't occur anymore.

**Comment by krampstudio** [comment]
closing since I'm not using the given version anymore
