### ISSUE TITLE
how to define altKeys in a custom virtual keyboard layer.

### ISSUE THREAD

**Issue by faxinwang** [arnog/mathlive#952]
## Description

I have read the virtual keyboard guide (https://cortexjs.io/mathlive/guides/virtual-keyboards/) and the source codes but didn't find any information about how to define altKeys in a custom virtual keyboard layer. could you please show me how to do that, thank you!!!

**Comment by arnog** [comment]
That is a great question.

There is currently no API to do this, but it would absolutely make sense to have one.

**Comment by faxinwang** [comment]
Ok, fine, waiting for this feature and thank you for your effort.

**Comment by arnog** [comment]
Fixed in the main branch, will be available in the next npm release.
