### ISSUE TITLE
Why does losing the cursor on Apple's keyboard not disappear

### ISSUE THREAD

**Issue by li741938507** [arnog/mathlive#954]
Why does losing the cursor on Apple's keyboard not disappear

**Comment by li741938507** [comment]
v0.60.1

**Comment by arnog** [comment]
I'm sorry, I don't understand what you mean.
Could you follow the template for the issue report and provide steps to follow to reproduce the problem, and screenshots if necessary?

**Comment by arnog** [comment]
Two weeks without activity. Closing.
