### ISSUE TITLE
Exponent with shortcut not working or broken e to the pie 

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#960]
## Description

`e^pi` doesn't produce the expected result

## Steps to Reproduce

[Provide steps that are specific and repeatable, if possible]

1. Go to https://cortexjs.io/mathlive/
2. Type in `e^pi`

### Actual Behavior

![image](https://user-images.githubusercontent.com/10220080/120079520-856b9a80-c0b4-11eb-80f2-be227df079b3.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/10220080/120079511-7e448c80-c0b4-11eb-89ff-44c7aa638f8f.png)

### Environment

**MathLive version**

**Operating System** Windows 10

**Browser** Firefox 88 and Microsoft Edge

**Comment by arnog** [comment]
Wow! That's a good one.

**Comment by arnog** [comment]
That was a very good one. The symptom were simple in appearance, but the problem (and the fix) was non-trivial. Thanks!

**Comment by stefnotch** [comment]
Awesome, glad that you managed to fix another sneaky little bug. Also glad that it was an interesting one 😄 
I might end up reporting a few more bugs in the next few months, since I'm attempting to use mathlive for my mathematics homework. And that involves a fair amount of typing and testing :)

**Comment by arnog** [comment]
Wonderful, that's always welcome!
