### ISSUE TITLE
Macbook NO/SV keyboard ']' key turns into '('

### ISSUE THREAD

**Issue by MariusSK** [arnog/mathlive#962]
## Description

It is not possible to enter the character ']' using Norwegian or Swedish keyboard setup on my Macbook. Attempting to do so will put the symbol '(' into the input field. 

## Steps to Reproduce

1. Using a macbook, set keyboard languge to either Norwegian or Swedish.
2. Open http://mathlive.io/
3. Put the cursor in the input field. 
4. Hit [option] + [9]

### Actual Behavior

The symbol that shows up in the input field is '('

### Expected Behavior

I expected the symbol ']'

### Environment

**MathLive version**
The current version on http://mathlive.io/
(Built with mathlive.js v0.59.0-93-g1b6a4ee-dirty)

**Operating System** [macOS, Windows, iOS. Include the version if possible]
Macbook, MacOS Big Sur 11.3

**Browser** [Safari, Chrome, IE, Firefox, etc...]
Google Chrome, Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by arnog** [comment]
Keybindings that are specific to the US keyboard layout (such as alt+9) no longer apply to non-US keyboard layout.

**Comment by MariusSK** [comment]
When testing today, the bug is back again. Exactly the same as last time. I believe it worked for a while before that.

**Comment by MariusSK** [comment]
Maybe related, maybe not: It is also not possible to add backslash ("\"). Normally, this would be <option> + <shift> + 7. The output is just slash ("/"). This is not the same as <shift> + 7 (normally "/" on the keyboard), which instead starts a fraction. 

I can make this a separate issue if you think the two are not related.

**Comment by arnog** [comment]
The issues probably are related. However, unfortunately I am unable to reproduce them. When I switch my keyboard to Norwegian Bokmål option + shift + 8 gives me `[`, and options + shift + 7 gives me `\`...

There must be something else in the configuration that's causing this problem.

Can you confirm which version of MathLive you're using? (you can print the version by importing the `version` symbol  from the MathLive library, or in the browser by typing `console.log(MathLive.version)`.

**Comment by MariusSK** [comment]
I'm using http://mathlive.io/. From the page; "Built with mathlive.js v0.59.0-93-g1b6a4ee-dirty".  
I open the console, type "console.log(MathLive.version)" and get "{{SDK_VERSION}}" and then "undefined". Not sure what this means. 

Also tested with FireFox 89.0.2 (64-bit), same problem.

**Comment by arnog** [comment]
Ah, OK. The version on Mathlive.io is very out of date. Try it here: https://cortexjs.io/mathlive/

**Comment by MariusSK** [comment]
That version works like a charm. Excellent, thank you.
