### ISSUE TITLE
Arrow key navigation gets stuck

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#968]
## Description

I typed something and then pressed the right arrow key. To my surprise, it didn't work. Instead, I only heard the "plonk" sound.
![image](https://user-images.githubusercontent.com/10220080/120344115-95c08700-c2f9-11eb-936d-e3a177543646.png)

## Steps to Reproduce

1. Go to https://cortexjs.io/mathlive/
2. Paste in `\begin{equation*} x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}\R \end{equation*}`
3. Place the at the beginning and repeatedly press the right arrow key, until you get stuck just in front of the `\R`

### Actual Behavior

Caret gets stuck. I believe this happens with any instance of `\R` or `\Z` or `\N`. Funnily enough, it does not happen with `\C`

### Expected Behavior

I expected the caret to move to after the `\R`

### Environment

**MathLive version** 0.68.0

**Operating System** Windows 10

**Browser** Firefox 88, Microsoft Edge

**Comment by arnog** [comment]
This problem occurred when navigating "through" a macro (the `\R` command) at the end of an equation. It would try to go "too far" and would thus "plonk". Should be fixed now.
