### ISSUE TITLE
Branch doesn't build since commit   "chore: integrate MathJSON, fix null safery "

### ISSUE THREAD

**Issue by Zahara-Nour** [arnog/mathlive#969]
After exploring all comits, I found that I couldn't build master since commit cff2fccb01964c115592f21fc67b9847c7990c48 .
<img width="913" alt="Capture d’écran 2021-06-01 à 21 03 21" src="https://user-images.githubusercontent.com/32236491/120370082-cebe2300-c31c-11eb-82dd-9056a3bbd61f.png">

**Comment by arnog** [comment]
This is due to the integration of MathJSON as a github submodule. It turns out that submodules are not a good choice for various build environment. I'll change over to use a regular npm dependency. That change should land within 24h.

**Comment by arnog** [comment]
OK, I've published 0.68.1 on npm that attempts to address this. Thank you for your patience and please do let me know if you encounter a problem.

**Comment by Zahara-Nour** [comment]
I was able to use the last published version (0.68.1) but master branch still
 doesn't build after your fix.
<img width="809" alt="Capture d’écran 2021-06-04 à 10 40 55" src="https://user-images.githubusercontent.com/32236491/120764940-5a080600-c521-11eb-8d63-f961a04471af.png">

**Comment by arnog** [comment]
You may need to do `npm install` first.

**Comment by Zahara-Nour** [comment]
I cleaned everything,  reinstalled and it worked, thank you !
