### ISSUE TITLE
[FEATURE] Support vertical scrolling 

### ISSUE THREAD

**Issue by ankushClassplus** [arnog/mathlive#970]
I have created a mathfield input with height 180px and overflow auto so when I am scrolling the content in horizontally its working but when i am trying vertical scroll so its not working .

**// ref element** 

`< div className={styles.input}
    ref={this.editorRef} >
     {this.state.initialLatex || "#?"}
 </ div >`

**//initialisation** 

`componentDidMount() {
		document.body.append(this.container);
		this.editor = window.MathLive.makeMathField(this.editorRef.current, {
			onKeystroke: (e, keyCode) => {
				if (keyCode == "[Space]") {
					this.insertLatex("\\,");
				}
			}
		})
	}	`

**//styles**
`.input{
    padding: 5px;
    overflow: auto;
    height:18rem;
    width: 100%; 
    margin-right: 2rem;
    border: 1px solid #CCCCCC;
    /* border: 1px solid #000; */
}`

<img width="626" alt="Screenshot 2021-06-02 at 5 48 14 PM" src="https://user-images.githubusercontent.com/50407809/120478995-0f747580-c3cb-11eb-8f50-551ee0f45418.png">

See in the image there is some content below .

**Comment by arnog** [comment]
@ankushClassplus thank you for reporting this issue.

Vertical scrolling is indeed not currently supported, but this could be an interesting future feature. For now, you can either adjust the size of the mathfield container as necessary, or change its scroll properties as needed.

Note also that `makeMathField` is a deprecated call that will be removed shortly. You should instead use `new MathfieldElement()` or the `<math-field>` tag.
