### ISSUE TITLE
Selection depth no longer exposed

### ISSUE THREAD

**Issue by baldoalessandro** [arnog/mathlive#973]
## Description
I was using the suggested method (as per 0.57.0) to access the selection depth `mf.selection[0].depth`, now with the new Selection API based on Ranges introduced in 0.6.0 it seems that the depth information is no longer available.

## Steps to Reproduce
Try to access `mf.selection[0].depth` using mathalive 0.68.1

### Actual Behavior

Selection doesn't expose the `depth` property anymore.
Is there a way I can still access this information?
Thank you!

### Environment

**MathLive version**: 0.68.1

**Operating System**: macOS 10.15

**Browser**: Chrome, Firefox

**Comment by arnog** [comment]
It looks like I dropped this property. I will reintroduce it, probably with something like `getOffsetDepth(offset)`.

**Comment by baldoalessandro** [comment]
Thank you!

**Comment by arnog** [comment]
OK, it's `getOffsetDepth()`...
