### ISSUE TITLE
Fraction tex doesn't appear anymore with keyboard input

### ISSUE THREAD

**Issue by e1MasterAccount** [arnog/mathlive#974]
I've been using for 2 months now. But for the last 3 days, when in inputting a fraction with "/" symbol in a mathfield (using a keyboard not the UI keyboard) the tex displayed by the math-field element is "/" and not "\frac{\placeholder{⬚}}{\placeholder{⬚}}" like before.

I temporarily corrected this issue by adding this code when requesting mathfields value :
"
ev.target.value = ev.target.value.replaceAll("/","\\frac{\\placeholder{⬚}}{\\placeholder{⬚}}");
ev.target.value = ev.target.value.replaceAll("\\frac{}{}","")
"

Problem seems simple but is odd.

![Action 03-06-2021 22-35-16](https://user-images.githubusercontent.com/59661951/120708777-4bd3ce80-c4bc-11eb-81a6-3fe579ec6f4f.gif)

**Comment by arnog** [comment]
What kind of keyboard layout are you using (AZERTY, QWERTY, etc...)?

**Comment by e1MasterAccount** [comment]
I'm using a French AZERTY keyboard but the issue remains when switching keyboard to QWERTY on windows.

However, I observed that even though "/" is not correctly drawn in the math field, the ascii-math value it returns is correct.

**Comment by Chrisb0606** [comment]
Hello,
I also face exactly the same issue but this time with a French Mac Keyboard.
When I use the "/" with the numeric keypad it behaves as a fraction but when I use the "/" in the "latin" layout it displays a "/" as a text (not a fraction).
I use an AZERTY French Mac Keyboard. I've tested with the Mac US Keyboard setting it works well.
I ve figured out that the keycodes are different in FR or US MacKeyboard.
On the US Mac Keyboard :
- 111 for the "/" on numeric pad (works  as a Fraction as expected)
- 191 for the "/" on latin layout  (works  as a Fraction as expected)
On the French Mac Keyboard :
- 111 for the "/" on numeric pad (works  as a Fraction as expected)
- 58 for the "/" on standard keyboard (doesn't work as a Fraction but as a "/"  text )

Thanks for your help,
Chris

**Comment by nnnawi** [comment]
Hi, I do not know how to solve the issue but I think you can use the temporary fix I showed in my first comment.

**Comment by Chrisb0606** [comment]
Hi,
Thanks for the workaround, I've tried to implement it, but it seems that the denominator can only accept one character with this method : once the first char in denominator is filled, the cursor automaticaly moves to the middle line.
Thanks
Chris
