### ISSUE TITLE
Provide a Command for `clearSelection`

### ISSUE THREAD

**Issue by strickinato** [arnog/mathlive#975]
## Description

I may be wrong, but based on the header files, I expected there to be a command within the MathField to clear the selection.

**There was a deprecated command `clearSelection`:**
https://github.com/arnog/mathlive/blob/aa079aeda566c74508ed031c0a38543ddc1599cc/src/public/mathfield.ts#L280-L283

**However, in the actual list of commands, this command doesn't seem to exist, though it would surely be useful:**

Note also, that this is still listed as an available command in the documentation here:
https://github.com/arnog/mathlive/blob/30deb20fc5d0879867988fbadc150ae89686104a/examples/vue/README.md#methods

## Steps to Reproduce

This is not a bug persé, so I can't reproduce it, 

### Actual Behavior

As of right now, there's no way I can think of to clear the selection in the mathfield then the following brittle hack:

```ts
   $mathField.selection = [{ start = 0 }]
```

### Expected Behavior

I would expect to be able to write:

```ts
   $mathField.clearSelection()
```

### Environment

**MathLive version**
My system: 0.59
But still appears to be true currently:  0.68.1

**Operating System** [macOS, Windows, iOS. Include the version if possible]
All systems

**Browser** [Safari, Chrome, IE, Firefox, etc...]
All browsers

## Additional note:

I'd be happy to take the time to make a PR - but figured it wise to check in first to see if I was missing something or if there is a reason for the change.

Thanks so much for your work!

**Comment by arnog** [comment]
The `clearSelection` method got dropped in part because of its ambiguity. Does it mean "set the selection to be empty" or "delete what is selected". The deprecated version meant the latter. It looks  like you want to do the former.

To set the selection to "nothing" (without deleting anything), you can simply do `mf.position = 0`. This will set the position of the insertion point to the first element in the formula. You can also do `mf.selection = { ranges: [0, 0] }` which means the same thing.

To "clear" (i.e. delete) the selection, you would use `mf.executeCommand('delete-backward')`.

Let me know what you think.

**Comment by strickinato** [comment]
Ah! That makes sense. 


And the ambiguity is clear. I didn't see it before, but now I can't unsee the other interpretation. (funny how a brain works)

That said, I still feel a bit uncomfortable circumventing the `executeCommand` interface in order to "deselect" input, so I wonder if it's worth including

`executeCommand('deselect')`

With this terminology, I think it's clear nothing would be deleted.

However, I do see a new ambiguity in that it's not totally clear what the cursor's behavior would be. The new position (as far as I understand the model)  could be at one of four places:

* Beginning of input
* Start selection
* End of active selection
* End of input

It seems sensible to me have either "start of input" or "end of input" be a default, but also I'm sort of stuck thinking about my own use case.

I definitely trust your judgement here, but would want to put a vote in for exposing this behavior somehow.


(And so it doesn't get lost in the fray, a reminder that it's probably worthwhile removing `clearSelection` from the Vue example)

**Comment by arnog** [comment]
Hmm... It's interesting that you think of using the methods on MathLiveElement as "circumventing" `executeCommand()`... I can assure you that all the methods of MathLiveElement are public APIs that are meant to be used directly. All the private APIs of MathLive are actually hidden and not accessible from the MathLiveElement, so you can't do something you're not supposed to accidentally.

As such, you are supposed to manipulate the selection using the `position` and `selection` getters/setters of the MathLiveElement, just like you are supposed to read/write the value using the `value` getter/setter.

And as you note, a `deselect` selector, would be ambiguous in its behavior, or need additional parameters to specify how you want to handle the "deselection". By that point, doing a simple `mf.position = 0` (to set the selection at the beginning of the field) or `mf.position = -1` or `mf.position = mf.lastOffset` (to set it at the end) or `mf.position = mf.selection.ranges[0][0]` (to set it at before the current selection) or `mf.position = mf.selection.ranges[0][1]` (to set it after the current selection), seems both more explicit and just as simple.

(I've updated the Vue example and a few other places that had a reference to `clearSelection()`)

**Comment by strickinato** [comment]
Thank you for your responses and updating the examples!!


To this point:

> Hmm... It's interesting that you think of using the methods on MathLiveElement as "circumventing" executeCommand()... I can assure you that all the methods of MathLiveElement are public APIs that are meant to be used directly.

It's really that I got in my head: "there should be a command for this", and everything else felt out of place.

I agree, manipulating position directly is great.

Thanks again - I'll close the issue
