### ISSUE TITLE
Postinstall hook fails on Windows

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#980]
## Description

I hope this is not an irritating issue to sort out, but currently the postinstall hook causes an issue on Windows

The following log was collected from inside Visual Studio Code using the Powershell. I also tested it with other command lines like the Git Bash and it still resulted in the same error
```
PS C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-mathlive> npm i
npm ERR! code 1
npm ERR! path C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-mathlive\node_modules\mathlive
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c if git rev-parse --git-dir > /dev/null 2>&1; then git config core.hooksPath ./git-hooks; fi
npm ERR! rev-parse was unexpected at this time.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Stefnotch\AppData\Local\npm-cache\_logs\2021-06-04T18_34_43_138Z-debug.log
```

https://github.com/arnog/mathlive/blob/de67e93280d765acbc54aa9e8ba682df1a196cbb/package.json#L19

Weirdly enough, I was able to install mathlive 0.68.0 previously.

## Steps to Reproduce

1. `mkdir test123`
2. `cd test123`
3. `npm init`
4. `npm i mathlive@0.68.1`

### Actual Behavior

 
[2021-06-04T18_34_43_138Z-debug.log](https://github.com/arnog/mathlive/files/6600612/2021-06-04T18_34_43_138Z-debug.log)

### Expected Behavior

I expected to be able to install Mathlive

### Environment

**MathLive version** Mathlive 0.68.1

**Operating System** Windows 10

**Browser** n/a

**Comment by arnog** [comment]
Oh boy... I'll try something, but I don't have a Windows machine to test it with, so please be patient if this doesn't work...

**Comment by arnog** [comment]
OK, I've checked-in a tentative fix... Hope it works!

**Comment by stefnotch** [comment]
I tried it out by downloading mathlive and running `npm install`. 

When doing it in a command prompt window, a different error pops up. That's progress, I guess

```
C:\Users\Stefnotch\Downloads\mathlive-master>npm i

> mathlive@0.68.0 postinstall
> bash ./scripts/postinstall.sh

Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
npm ERR! code 4294967295
npm ERR! path C:\Users\Stefnotch\Downloads\mathlive-master
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c bash ./scripts/postinstall.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Stefnotch\AppData\Local\npm-cache\_logs\2021-06-04T19_26_39_524Z-debug.log
```

When running it with the git bash, it actually works. 
```
Stefnotch@STEFNOTCH-PC MINGW64 ~/Downloads
$ cd mathlive-master/

Stefnotch@STEFNOTCH-PC MINGW64 ~/Downloads/mathlive-master
$ npm i

> mathlive@0.68.0 postinstall
> bash ./scripts/postinstall.sh


> mathlive@0.68.0 prepare
> bash ./scripts/build.sh production

 ✔  Output directories cleaned out
 ✔  Static assets copied
 ✔  Static CSS built
 ✔  CSS Optimized
 ✔  Declaration files built
 ●  Making a production build(node:6228) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\Stefnotch\Downloads\mathlive-master\node_modules\rollup-plugin-typescript2\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
src/mathlive.ts
src/core-definitions/definitions.ts
src/core/atom-class.ts
src/core/context.ts
src/core/parser.ts
...
```

**Comment by arnog** [comment]
Hmm... `bash` has been required  to build mathlive for a loooong time. I don't know if I can make this work any better. You either need to install the Linux subsystem for Windows (see https://docs.microsoft.com/en-us/windows/wsl/install-win10) or use `git-bash`. Or do you have any suggestion for how to handle this?

**Comment by stefnotch** [comment]
Not really, I personally write my scripts using Node.js. That replaces the bash dependency with a Node.js dependency, not sure if that's preferable in any way.

Another alternative is trying to figure out a way to do without a postinstall hook. After all, it should be possible to `npm install mathlive` into any project without any issues. 

And finally, as long as it works with git bash, it's alright for me.

**Comment by arnog** [comment]
OK, I've removed the `postinstall` hook. It should work now, but please reopen if there's still a problem.
