### ISSUE TITLE
The alternate keys do not display in the right place when `virtualKeyboardContainer` is provided.

### ISSUE THREAD

**Issue by faxinwang** [arnog/mathlive#994]
I have a custom vritual keyboard layer with my own `virtualKeyboardContainer`,  when I click+hold to trigger alternate keys, the alternate keys display in the top left corner of html body element, far away from the clicked keycap. Then I remove my custom layers and using the default keyboard layers but keep the `virtualKeyboardContainer` points to a custom place, the problem still exist.  I think this may be a bug.

And also I want to report another small bug. In the official site https://cortexjs.io/mathlive/guides/virtual-keyboards/, the alternate keys get blank on mouse hover, which is not the case in previous versions.

**Comment by arnog** [comment]
I tried to reproduce this problem but I was not able to.
1/ Which version of Mathlive are you using?
2/ Do you have some code illustrating this problem you could share?

**Comment by faxinwang** [comment]
I'm using the latest version(0.68.1), I have just made a codepen to show you the bug. you can see it here. https://codepen.io/faxin/pen/XWMYpma

**Comment by arnog** [comment]
I have pushed a fix. For this to work, you no longer need to define rules for `.ML__keyboard`, you just need to make sure that the container has a `position` of `relative`.
