### ISSUE TITLE
Horizontal strikethrough symbol support 

### ISSUE THREAD

**Issue by ankushClassplus** [arnog/mathlive#995]
Horizontal strikethrough symbol is not supported could you guys help me to solve this issue ?

<img width="419" alt="Screenshot 2021-06-07 at 3 31 44 PM" src="https://user-images.githubusercontent.com/50407809/120998616-e0347e80-c7a5-11eb-9ba9-64357e1cfe4b.png">

**Comment by ankit0812** [comment]
I am also facing this issue. Any help?

**Comment by apoorvclp** [comment]
This issue is the last missing piece of my editor, please help!

**Comment by arnog** [comment]
Which Latex command are you expecting? (and are you all working on the same project 😀 ?)
That said, the answer is `$\enclose{horizontalstrike}{addadadadadadadada}$`.

**Comment by arnog** [comment]
Hello?

**Comment by arnog** [comment]
This seemed really urgent at the time, but the submitters have gone silent now, so I guess they must be really busy with something else. Closing.
